# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/modules/MosaicEditor/MosaicEditorTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(427, 123)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.atlasCombo = QtWidgets.QComboBox(self.frame_3)
        self.atlasCombo.setObjectName("atlasCombo")
        self.atlasCombo.addItem("")
        self.gridLayout_2.addWidget(self.atlasCombo, 0, 0, 1, 1)
        self.atlasLayout = QtWidgets.QGridLayout()
        self.atlasLayout.setSpacing(0)
        self.atlasLayout.setObjectName("atlasLayout")
        self.gridLayout_2.addLayout(self.atlasLayout, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_3)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.normalizeBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.normalizeBtn.setObjectName("normalizeBtn")
        self.verticalLayout.addWidget(self.normalizeBtn)
        self.blendBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.blendBtn.setObjectName("blendBtn")
        self.verticalLayout.addWidget(self.blendBtn)
        self.autoRangeBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.autoRangeBtn.setObjectName("autoRangeBtn")
        self.verticalLayout.addWidget(self.autoRangeBtn)
        self.tileShadingBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.tileShadingBtn.setObjectName("tileShadingBtn")
        self.verticalLayout.addWidget(self.tileShadingBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.mosaicDisplayMin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.mosaicDisplayMin.setMinimum(-1.0)
        self.mosaicDisplayMin.setMaximum(65000.0)
        self.mosaicDisplayMin.setSingleStep(0.25)
        self.mosaicDisplayMin.setObjectName("mosaicDisplayMin")
        self.gridLayout.addWidget(self.mosaicDisplayMin, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.mosaicDisplayMax = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.mosaicDisplayMax.setMaximum(65536.0)
        self.mosaicDisplayMax.setSingleStep(0.25)
        self.mosaicDisplayMax.setProperty("value", 2.0)
        self.mosaicDisplayMax.setObjectName("mosaicDisplayMax")
        self.gridLayout.addWidget(self.mosaicDisplayMax, 1, 1, 1, 1)
        self.mosaicApplyScaleBtn = QtWidgets.QPushButton(self.groupBox)
        self.mosaicApplyScaleBtn.setObjectName("mosaicApplyScaleBtn")
        self.gridLayout.addWidget(self.mosaicApplyScaleBtn, 2, 0, 1, 2)
        self.mosaicFlipUDBtn = QtWidgets.QPushButton(self.groupBox)
        self.mosaicFlipUDBtn.setObjectName("mosaicFlipUDBtn")
        self.gridLayout.addWidget(self.mosaicFlipUDBtn, 3, 1, 1, 1)
        self.mosaicFlipLRBtn = QtWidgets.QPushButton(self.groupBox)
        self.mosaicFlipLRBtn.setObjectName("mosaicFlipLRBtn")
        self.gridLayout.addWidget(self.mosaicFlipLRBtn, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.atlasCombo.setItemText(0, _translate("Form", "Select Atlas..."))
        self.groupBox_2.setTitle(_translate("Form", "Image Correction"))
        self.normalizeBtn.setText(_translate("Form", "Normalize"))
        self.blendBtn.setText(_translate("Form", "Blend"))
        self.autoRangeBtn.setText(_translate("Form", "Auto Range"))
        self.tileShadingBtn.setText(_translate("Form", "Tile Shading"))
        self.groupBox.setTitle(_translate("Form", "Tile Operations"))
        self.label_2.setText(_translate("Form", "Min"))
        self.label.setText(_translate("Form", "Max"))
        self.mosaicApplyScaleBtn.setText(_translate("Form", "Apply Tile Scale"))
        self.mosaicFlipUDBtn.setText(_translate("Form", "FlipUD"))
        self.mosaicFlipLRBtn.setText(_translate("Form", "FlipLR"))

