# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/modules/Manager/ManagerTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(270, 940)
        MainWindow.setStyleSheet("")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.configList = QtWidgets.QListWidget(self.groupBox)
        self.configList.setObjectName("configList")
        self.verticalLayout_3.addWidget(self.configList)
        self.loadConfigBtn = QtWidgets.QPushButton(self.groupBox)
        self.loadConfigBtn.setObjectName("loadConfigBtn")
        self.verticalLayout_3.addWidget(self.loadConfigBtn)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.moduleList = QtWidgets.QTreeWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moduleList.sizePolicy().hasHeightForWidth())
        self.moduleList.setSizePolicy(sizePolicy)
        self.moduleList.setHeaderHidden(True)
        self.moduleList.setObjectName("moduleList")
        self.moduleList.headerItem().setText(0, "1")
        self.verticalLayout_4.addWidget(self.moduleList)
        self.loadModuleBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.loadModuleBtn.setObjectName("loadModuleBtn")
        self.verticalLayout_4.addWidget(self.loadModuleBtn)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.logBtn = LogButton(self.centralwidget)
        self.logBtn.setObjectName("logBtn")
        self.verticalLayout.addWidget(self.logBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.reloadModuleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.reloadModuleBtn.setObjectName("reloadModuleBtn")
        self.verticalLayout.addWidget(self.reloadModuleBtn)
        self.quitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.quitBtn.setObjectName("quitBtn")
        self.verticalLayout.addWidget(self.quitBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        Qt.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = Qt.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ACQ4 Manager"))
        self.groupBox.setTitle(_translate("MainWindow", "Configuration"))
        self.loadConfigBtn.setText(_translate("MainWindow", "Load Configuration"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Modules"))
        self.loadModuleBtn.setText(_translate("MainWindow", "Load Module"))
        self.logBtn.setText(_translate("MainWindow", "Log"))
        self.reloadModuleBtn.setText(_translate("MainWindow", "Reload Libraries"))
        self.quitBtn.setText(_translate("MainWindow", "Quit ACQ4"))

from acq4.LogWindow import LogButton
