# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/modules/Camera/sequencerTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(342, 103)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pauseBtn = QtWidgets.QPushButton(Form)
        self.pauseBtn.setCheckable(True)
        self.pauseBtn.setObjectName("pauseBtn")
        self.gridLayout_3.addWidget(self.pauseBtn, 1, 0, 1, 1)
        self.deviceCombo = ComboBox(Form)
        self.deviceCombo.setObjectName("deviceCombo")
        self.gridLayout_3.addWidget(self.deviceCombo, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 1, 1, 1)
        self.statusLabel = QtWidgets.QLabel(Form)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout_3.addWidget(self.statusLabel, 3, 0, 1, 3)
        self.startBtn = QtWidgets.QPushButton(Form)
        self.startBtn.setCheckable(True)
        self.startBtn.setObjectName("startBtn")
        self.gridLayout_3.addWidget(self.startBtn, 0, 0, 1, 1)
        self.timelapseGroup = QtWidgets.QGroupBox(Form)
        self.timelapseGroup.setCheckable(True)
        self.timelapseGroup.setChecked(False)
        self.timelapseGroup.setObjectName("timelapseGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.timelapseGroup)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.intervalSpin = SpinBox(self.timelapseGroup)
        self.intervalSpin.setMinimumSize(Qt.QSize(75, 0))
        self.intervalSpin.setObjectName("intervalSpin")
        self.gridLayout_2.addWidget(self.intervalSpin, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.timelapseGroup)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.timelapseGroup)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.iterationsSpin = QtWidgets.QSpinBox(self.timelapseGroup)
        self.iterationsSpin.setObjectName("iterationsSpin")
        self.gridLayout_2.addWidget(self.iterationsSpin, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.timelapseGroup, 0, 1, 3, 1)
        self.zStackGroup = QtWidgets.QGroupBox(Form)
        self.zStackGroup.setCheckable(True)
        self.zStackGroup.setChecked(False)
        self.zStackGroup.setObjectName("zStackGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.zStackGroup)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.zSpacingSpin = SpinBox(self.zStackGroup)
        self.zSpacingSpin.setObjectName("zSpacingSpin")
        self.gridLayout.addWidget(self.zSpacingSpin, 3, 2, 1, 1)
        self.zStartSpin = SpinBox(self.zStackGroup)
        self.zStartSpin.setMinimumSize(Qt.QSize(75, 0))
        self.zStartSpin.setObjectName("zStartSpin")
        self.gridLayout.addWidget(self.zStartSpin, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.zStackGroup)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 2)
        self.zEndSpin = SpinBox(self.zStackGroup)
        self.zEndSpin.setObjectName("zEndSpin")
        self.gridLayout.addWidget(self.zEndSpin, 1, 2, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.zStackGroup)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.zStackGroup)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 2, 1)
        self.setStartBtn = QtWidgets.QPushButton(self.zStackGroup)
        self.setStartBtn.setMaximumSize(Qt.QSize(15, 20))
        self.setStartBtn.setObjectName("setStartBtn")
        self.gridLayout.addWidget(self.setStartBtn, 0, 1, 1, 1)
        self.setEndBtn = QtWidgets.QPushButton(self.zStackGroup)
        self.setEndBtn.setMaximumSize(Qt.QSize(15, 20))
        self.setEndBtn.setObjectName("setEndBtn")
        self.gridLayout.addWidget(self.setEndBtn, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.zStackGroup, 0, 2, 3, 1)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pauseBtn.setToolTip(_translate("Form", "<html><head/><body><p>Pause the sequence acquisition.</p><p>Click again to resume.</p></body></html>"))
        self.pauseBtn.setText(_translate("Form", "Pause"))
        self.deviceCombo.setToolTip(_translate("Form", "<html><head/><body><p>The imaging device to use during the sequence acquisition.</p></body></html>"))
        self.startBtn.setToolTip(_translate("Form", "<html><head/><body><p>Begin acquiring a sequence of images (timelapse, z-stack, or both).</p><p>Click again to interrupt a running sequence.</p></body></html>"))
        self.startBtn.setText(_translate("Form", "Start"))
        self.timelapseGroup.setToolTip(_translate("Form", "<html><head/><body><p>Enable/disable acquiring a timelapse series of images or z-stacks.</p></body></html>"))
        self.timelapseGroup.setTitle(_translate("Form", "Timelapse"))
        self.intervalSpin.setToolTip(_translate("Form", "<html><head/><body><p>The minimum time interval to wait between the start of subsequent acquisitions.</p><p>The actual interval may be longer if the image or z-stack acquisition is slow.</p></body></html>"))
        self.label_4.setText(_translate("Form", "Interval"))
        self.label_5.setText(_translate("Form", "Iterations"))
        self.iterationsSpin.setToolTip(_translate("Form", "<html><head/><body><p>The number of images or (z-stacks, if enabled) to acquire in the timelapse series.</p><p>If the values is &quot;inf&quot;, then the acquisition will continue until the user clicks Stop.</p></body></html>"))
        self.iterationsSpin.setSpecialValueText(_translate("Form", "inf"))
        self.zStackGroup.setToolTip(_translate("Form", "<html><head/><body><p>Enable or disable acquiring a stack of images along a range of focus depths.</p><p>The entire stack is acquired once per timelapse iteration.</p></body></html>"))
        self.zStackGroup.setTitle(_translate("Form", "Z Stack"))
        self.zSpacingSpin.setToolTip(_translate("Form", "<html><head/><body><p>Spacing petween frames in the z-stack.</p></body></html>"))
        self.zStartSpin.setToolTip(_translate("Form", "<html><head/><body><p>The focus depth at the beginning of the z-stack.</p></body></html>"))
        self.label.setText(_translate("Form", "Spacing"))
        self.zEndSpin.setToolTip(_translate("Form", "<html><head/><body><p>The approximate focus depth at the end of the z-stack.</p><p>(The exact end point is the start point plus a multiple of the spacing)</p></body></html>"))
        self.label_3.setText(_translate("Form", "End"))
        self.label_2.setText(_translate("Form", "Start"))
        self.setStartBtn.setToolTip(_translate("Form", "<html><head/><body><p>Use the current focus depth as the z-stack start point.</p></body></html>"))
        self.setStartBtn.setText(_translate("Form", ">"))
        self.setEndBtn.setToolTip(_translate("Form", "<html><head/><body><p>Use the current focus depth as the z-stack endpoint.</p></body></html>"))
        self.setEndBtn.setText(_translate("Form", ">"))

from acq4.pyqtgraph import ComboBox, SpinBox
