# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/modules/PSPReversal/ctrlTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 468)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        palette = Qt.QPalette()
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.WindowText, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Button, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Light, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Midlight, brush)
        brush = Qt.QBrush(Qt.QColor(127, 127, 127))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Dark, brush)
        brush = Qt.QBrush(Qt.QColor(170, 170, 170))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Mid, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Text, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.BrightText, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.ButtonText, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(50, 50, 50))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Window, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Shadow, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.AlternateBase, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 220))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.ToolTipBase, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.ToolTipText, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.WindowText, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Button, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Light, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Midlight, brush)
        brush = Qt.QBrush(Qt.QColor(127, 127, 127))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Dark, brush)
        brush = Qt.QBrush(Qt.QColor(170, 170, 170))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Mid, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Text, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.BrightText, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.ButtonText, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(50, 50, 50))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Window, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Shadow, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.AlternateBase, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 220))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.ToolTipBase, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.ToolTipText, brush)
        brush = Qt.QBrush(Qt.QColor(127, 127, 127))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.WindowText, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Button, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Light, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Midlight, brush)
        brush = Qt.QBrush(Qt.QColor(127, 127, 127))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Dark, brush)
        brush = Qt.QBrush(Qt.QColor(170, 170, 170))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Mid, brush)
        brush = Qt.QBrush(Qt.QColor(127, 127, 127))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Text, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.BrightText, brush)
        brush = Qt.QBrush(Qt.QColor(127, 127, 127))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.ButtonText, brush)
        brush = Qt.QBrush(Qt.QColor(50, 50, 50))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(50, 50, 50))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Window, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Shadow, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.AlternateBase, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 220))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.ToolTipBase, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.ToolTipText, brush)
        Form.setPalette(palette)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        palette = Qt.QPalette()
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Window, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Window, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Window, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setAlignment(Qt.Qt.AlignLeading|Qt.Qt.AlignLeft|Qt.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(Qt.QRect(15, 318, 46, 16))
        self.label_10.setObjectName("label_10")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(Qt.QRect(8, 307, 325, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(Qt.QRect(90, 340, 251, 56))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.PSP_Reversal_vrmp = QtWidgets.QLineEdit(self.layoutWidget)
        self.PSP_Reversal_vrmp.setObjectName("PSP_Reversal_vrmp")
        self.gridLayout_3.addWidget(self.PSP_Reversal_vrmp, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.PSPReversal_Tau = QtWidgets.QLineEdit(self.layoutWidget)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_Tau.setFont(font)
        self.PSPReversal_Tau.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_Tau.setObjectName("PSPReversal_Tau")
        self.gridLayout_3.addWidget(self.PSPReversal_Tau, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.PSPReversal_Rin = QtWidgets.QLineEdit(self.layoutWidget)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_Rin.setFont(font)
        self.PSPReversal_Rin.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_Rin.setObjectName("PSPReversal_Rin")
        self.gridLayout_3.addWidget(self.PSPReversal_Rin, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 2, 1, 1)
        self.PSPReversal_Tauh = QtWidgets.QLineEdit(self.layoutWidget)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_Tauh.setFont(font)
        self.PSPReversal_Tauh.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_Tauh.setObjectName("PSPReversal_Tauh")
        self.gridLayout_3.addWidget(self.PSPReversal_Tauh, 1, 3, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(Qt.QRect(10, 340, 77, 73))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.PSPReversal_KeepAnalysis = QtWidgets.QCheckBox(self.layoutWidget1)
        self.PSPReversal_KeepAnalysis.setLayoutDirection(Qt.Qt.LeftToRight)
        self.PSPReversal_KeepAnalysis.setObjectName("PSPReversal_KeepAnalysis")
        self.verticalLayout_4.addWidget(self.PSPReversal_KeepAnalysis)
        self.PSPReversal_KeepT = QtWidgets.QCheckBox(self.layoutWidget1)
        self.PSPReversal_KeepT.setLayoutDirection(Qt.Qt.LeftToRight)
        self.PSPReversal_KeepT.setObjectName("PSPReversal_KeepT")
        self.verticalLayout_4.addWidget(self.PSPReversal_KeepT)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(Qt.QRect(5, 20, 357, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.PSPReversal_IVLimits = QtWidgets.QCheckBox(self.layoutWidget2)
        font = Qt.QFont()
        font.setPointSize(11)
        self.PSPReversal_IVLimits.setFont(font)
        self.PSPReversal_IVLimits.setLayoutDirection(Qt.Qt.LeftToRight)
        self.PSPReversal_IVLimits.setObjectName("PSPReversal_IVLimits")
        self.horizontalLayout_6.addWidget(self.PSPReversal_IVLimits)
        self.PSPReversal_IVLimitMin = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.PSPReversal_IVLimitMin.setDecimals(1)
        self.PSPReversal_IVLimitMin.setMinimum(-2000.0)
        self.PSPReversal_IVLimitMin.setMaximum(2000.0)
        self.PSPReversal_IVLimitMin.setSingleStep(5.0)
        self.PSPReversal_IVLimitMin.setProperty("value", -160.0)
        self.PSPReversal_IVLimitMin.setObjectName("PSPReversal_IVLimitMin")
        self.horizontalLayout_6.addWidget(self.PSPReversal_IVLimitMin)
        self.PSPReversal_IVLimitMax = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.PSPReversal_IVLimitMax.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_IVLimitMax.setDecimals(1)
        self.PSPReversal_IVLimitMax.setMinimum(-2000.0)
        self.PSPReversal_IVLimitMax.setMaximum(2000.0)
        self.PSPReversal_IVLimitMax.setSingleStep(5.0)
        self.PSPReversal_IVLimitMax.setProperty("value", 100.0)
        self.PSPReversal_IVLimitMax.setObjectName("PSPReversal_IVLimitMax")
        self.horizontalLayout_6.addWidget(self.PSPReversal_IVLimitMax)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(Qt.QRect(5, 50, 341, 28))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_14.setMaximumSize(Qt.QSize(30, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.PSPReversal_Sequence1 = QtWidgets.QComboBox(self.layoutWidget3)
        self.PSPReversal_Sequence1.setMaximumSize(Qt.QSize(75, 16777215))
        font = Qt.QFont()
        font.setPointSize(11)
        self.PSPReversal_Sequence1.setFont(font)
        self.PSPReversal_Sequence1.setObjectName("PSPReversal_Sequence1")
        self.PSPReversal_Sequence1.addItem("")
        self.PSPReversal_Sequence1.addItem("")
        self.PSPReversal_Sequence1.addItem("")
        self.PSPReversal_Sequence1.addItem("")
        self.PSPReversal_Sequence1.addItem("")
        self.horizontalLayout_3.addWidget(self.PSPReversal_Sequence1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_19.setMaximumSize(Qt.QSize(30, 16777215))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.PSPReversal_Sequence2 = QtWidgets.QComboBox(self.layoutWidget3)
        self.PSPReversal_Sequence2.setMaximumSize(Qt.QSize(75, 16777215))
        font = Qt.QFont()
        font.setPointSize(11)
        self.PSPReversal_Sequence2.setFont(font)
        self.PSPReversal_Sequence2.setObjectName("PSPReversal_Sequence2")
        self.PSPReversal_Sequence2.addItem("")
        self.horizontalLayout_4.addWidget(self.PSPReversal_Sequence2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_16.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.PSPReversal_tauh_Commands = QtWidgets.QComboBox(self.layoutWidget3)
        font = Qt.QFont()
        font.setPointSize(11)
        self.PSPReversal_tauh_Commands.setFont(font)
        self.PSPReversal_tauh_Commands.setObjectName("PSPReversal_tauh_Commands")
        self.PSPReversal_tauh_Commands.addItem("")
        self.horizontalLayout_5.addWidget(self.PSPReversal_tauh_Commands)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(Qt.QRect(10, 425, 332, 32))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PSPReversal_Update = QtWidgets.QPushButton(self.layoutWidget4)
        self.PSPReversal_Update.setObjectName("PSPReversal_Update")
        self.horizontalLayout.addWidget(self.PSPReversal_Update)
        self.dbStoreBtn = QtWidgets.QPushButton(self.layoutWidget4)
        font = Qt.QFont()
        font.setPointSize(12)
        self.dbStoreBtn.setFont(font)
        self.dbStoreBtn.setObjectName("dbStoreBtn")
        self.horizontalLayout.addWidget(self.dbStoreBtn)
        self.PSPReversal_rePlotData = QtWidgets.QPushButton(self.layoutWidget4)
        self.PSPReversal_rePlotData.setObjectName("PSPReversal_rePlotData")
        self.horizontalLayout.addWidget(self.PSPReversal_rePlotData)
        self.PSPReversal_PrintResults = QtWidgets.QPushButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PSPReversal_PrintResults.sizePolicy().hasHeightForWidth())
        self.PSPReversal_PrintResults.setSizePolicy(sizePolicy)
        self.PSPReversal_PrintResults.setObjectName("PSPReversal_PrintResults")
        self.horizontalLayout.addWidget(self.PSPReversal_PrintResults)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget5.setGeometry(Qt.QRect(5, 110, 341, 171))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setVerticalSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget5)
        self.label.setAlignment(Qt.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.PSPReversal_rmpTStop = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_rmpTStop.setFont(font)
        self.PSPReversal_rmpTStop.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_rmpTStop.setMaximum(10000.0)
        self.PSPReversal_rmpTStop.setProperty("value", 10.0)
        self.PSPReversal_rmpTStop.setObjectName("PSPReversal_rmpTStop")
        self.gridLayout_4.addWidget(self.PSPReversal_rmpTStop, 1, 2, 1, 1)
        self.PSPReversal_win1TStart = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_win1TStart.setFont(font)
        self.PSPReversal_win1TStart.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_win1TStart.setMinimum(-5000.0)
        self.PSPReversal_win1TStart.setMaximum(50000.0)
        self.PSPReversal_win1TStart.setObjectName("PSPReversal_win1TStart")
        self.gridLayout_4.addWidget(self.PSPReversal_win1TStart, 2, 1, 1, 1)
        self.PSPReversal_win1TStop = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_win1TStop.setFont(font)
        self.PSPReversal_win1TStop.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_win1TStop.setMinimum(-5000.0)
        self.PSPReversal_win1TStop.setMaximum(50000.0)
        self.PSPReversal_win1TStop.setObjectName("PSPReversal_win1TStop")
        self.gridLayout_4.addWidget(self.PSPReversal_win1TStop, 2, 2, 1, 1)
        self.PSPReversal_win1mode = QtWidgets.QComboBox(self.layoutWidget5)
        self.PSPReversal_win1mode.setObjectName("PSPReversal_win1mode")
        self.PSPReversal_win1mode.addItem("")
        self.PSPReversal_win1mode.addItem("")
        self.PSPReversal_win1mode.addItem("")
        self.PSPReversal_win1mode.addItem("")
        self.PSPReversal_win1mode.addItem("")
        self.PSPReversal_win1mode.addItem("")
        self.PSPReversal_win1mode.addItem("")
        self.gridLayout_4.addWidget(self.PSPReversal_win1mode, 2, 3, 1, 1)
        self.PSPReversal_win2TStart = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_win2TStart.setFont(font)
        self.PSPReversal_win2TStart.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_win2TStart.setMinimum(0.0)
        self.PSPReversal_win2TStart.setMaximum(50000.0)
        self.PSPReversal_win2TStart.setObjectName("PSPReversal_win2TStart")
        self.gridLayout_4.addWidget(self.PSPReversal_win2TStart, 3, 1, 1, 1)
        self.PSPReversal_win2TStop = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_win2TStop.setFont(font)
        self.PSPReversal_win2TStop.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_win2TStop.setMinimum(0.0)
        self.PSPReversal_win2TStop.setMaximum(50000.0)
        self.PSPReversal_win2TStop.setObjectName("PSPReversal_win2TStop")
        self.gridLayout_4.addWidget(self.PSPReversal_win2TStop, 3, 2, 1, 1)
        self.PSPReversal_win2mode = QtWidgets.QComboBox(self.layoutWidget5)
        self.PSPReversal_win2mode.setObjectName("PSPReversal_win2mode")
        self.PSPReversal_win2mode.addItem("")
        self.PSPReversal_win2mode.addItem("")
        self.PSPReversal_win2mode.addItem("")
        self.PSPReversal_win2mode.addItem("")
        self.PSPReversal_win2mode.addItem("")
        self.PSPReversal_win2mode.addItem("")
        self.PSPReversal_win2mode.addItem("")
        self.PSPReversal_win2mode.addItem("")
        self.PSPReversal_win2mode.addItem("")
        self.gridLayout_4.addWidget(self.PSPReversal_win2mode, 3, 3, 1, 1)
        self.PSPReversal_showHide_lrwin0 = QtWidgets.QCheckBox(self.layoutWidget5)
        palette = Qt.QPalette()
        brush = Qt.QBrush(Qt.QColor(253, 218, 40))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.WindowText, brush)
        brush = Qt.QBrush(Qt.QColor(253, 218, 40))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.WindowText, brush)
        brush = Qt.QBrush(Qt.QColor(69, 69, 69))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.WindowText, brush)
        self.PSPReversal_showHide_lrwin0.setPalette(palette)
        font = Qt.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PSPReversal_showHide_lrwin0.setFont(font)
        self.PSPReversal_showHide_lrwin0.setLayoutDirection(Qt.Qt.RightToLeft)
        self.PSPReversal_showHide_lrwin0.setObjectName("PSPReversal_showHide_lrwin0")
        self.gridLayout_4.addWidget(self.PSPReversal_showHide_lrwin0, 4, 0, 1, 1)
        self.PSPReversal_win0TStart = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_win0TStart.setFont(font)
        self.PSPReversal_win0TStart.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_win0TStart.setDecimals(1)
        self.PSPReversal_win0TStart.setMinimum(0.0)
        self.PSPReversal_win0TStart.setMaximum(10000.0)
        self.PSPReversal_win0TStart.setProperty("value", 0.0)
        self.PSPReversal_win0TStart.setObjectName("PSPReversal_win0TStart")
        self.gridLayout_4.addWidget(self.PSPReversal_win0TStart, 4, 1, 1, 1)
        self.PSPReversal_win0TStop = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_win0TStop.setFont(font)
        self.PSPReversal_win0TStop.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_win0TStop.setDecimals(1)
        self.PSPReversal_win0TStop.setMinimum(0.0)
        self.PSPReversal_win0TStop.setMaximum(10000.0)
        self.PSPReversal_win0TStop.setProperty("value", 5.0)
        self.PSPReversal_win0TStop.setObjectName("PSPReversal_win0TStop")
        self.gridLayout_4.addWidget(self.PSPReversal_win0TStop, 4, 2, 1, 1)
        self.PSPReversal_R_unCompensated = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_R_unCompensated.setFont(font)
        self.PSPReversal_R_unCompensated.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_R_unCompensated.setSuffix("")
        self.PSPReversal_R_unCompensated.setDecimals(1)
        self.PSPReversal_R_unCompensated.setMinimum(-100.0)
        self.PSPReversal_R_unCompensated.setObjectName("PSPReversal_R_unCompensated")
        self.gridLayout_4.addWidget(self.PSPReversal_R_unCompensated, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_3.setAlignment(Qt.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 2, 1, 1)
        self.PSPReversal_showHide_lrrmp = QtWidgets.QCheckBox(self.layoutWidget5)
        palette = Qt.QPalette()
        brush = Qt.QBrush(Qt.QColor(232, 73, 61))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.WindowText, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Text, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Window, brush)
        brush = Qt.QBrush(Qt.QColor(232, 73, 61))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.WindowText, brush)
        brush = Qt.QBrush(Qt.QColor(0, 0, 0))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Text, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Window, brush)
        brush = Qt.QBrush(Qt.QColor(69, 69, 69))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.WindowText, brush)
        brush = Qt.QBrush(Qt.QColor(69, 69, 69))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Text, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Window, brush)
        self.PSPReversal_showHide_lrrmp.setPalette(palette)
        font = Qt.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PSPReversal_showHide_lrrmp.setFont(font)
        self.PSPReversal_showHide_lrrmp.setToolTip("")
        self.PSPReversal_showHide_lrrmp.setLayoutDirection(Qt.Qt.RightToLeft)
        self.PSPReversal_showHide_lrrmp.setObjectName("PSPReversal_showHide_lrrmp")
        self.gridLayout_4.addWidget(self.PSPReversal_showHide_lrrmp, 1, 0, 1, 1)
        self.PSPReversal_rmpTStart = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        palette = Qt.QPalette()
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(212, 208, 200))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Base, brush)
        self.PSPReversal_rmpTStart.setPalette(palette)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_rmpTStart.setFont(font)
        self.PSPReversal_rmpTStart.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_rmpTStart.setDecimals(2)
        self.PSPReversal_rmpTStart.setMaximum(10000.0)
        self.PSPReversal_rmpTStart.setObjectName("PSPReversal_rmpTStart")
        self.gridLayout_4.addWidget(self.PSPReversal_rmpTStart, 1, 1, 1, 1)
        self.PSPReversal_showHide_lrwin1 = QtWidgets.QCheckBox(self.layoutWidget5)
        palette = Qt.QPalette()
        brush = Qt.QBrush(Qt.QColor(97, 225, 17))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.WindowText, brush)
        brush = Qt.QBrush(Qt.QColor(97, 225, 17))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.WindowText, brush)
        brush = Qt.QBrush(Qt.QColor(69, 69, 69))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.WindowText, brush)
        self.PSPReversal_showHide_lrwin1.setPalette(palette)
        font = Qt.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PSPReversal_showHide_lrwin1.setFont(font)
        self.PSPReversal_showHide_lrwin1.setToolTip("")
        self.PSPReversal_showHide_lrwin1.setLayoutDirection(Qt.Qt.RightToLeft)
        self.PSPReversal_showHide_lrwin1.setChecked(True)
        self.PSPReversal_showHide_lrwin1.setObjectName("PSPReversal_showHide_lrwin1")
        self.gridLayout_4.addWidget(self.PSPReversal_showHide_lrwin1, 2, 0, 1, 1)
        self.PSPReversal_showHide_lrwin2 = QtWidgets.QCheckBox(self.layoutWidget5)
        palette = Qt.QPalette()
        brush = Qt.QBrush(Qt.QColor(32, 127, 250))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.WindowText, brush)
        brush = Qt.QBrush(Qt.QColor(32, 127, 250))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.WindowText, brush)
        brush = Qt.QBrush(Qt.QColor(69, 69, 69))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.WindowText, brush)
        self.PSPReversal_showHide_lrwin2.setPalette(palette)
        font = Qt.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PSPReversal_showHide_lrwin2.setFont(font)
        self.PSPReversal_showHide_lrwin2.setToolTip("")
        self.PSPReversal_showHide_lrwin2.setLayoutDirection(Qt.Qt.RightToLeft)
        self.PSPReversal_showHide_lrwin2.setChecked(True)
        self.PSPReversal_showHide_lrwin2.setObjectName("PSPReversal_showHide_lrwin2")
        self.gridLayout_4.addWidget(self.PSPReversal_showHide_lrwin2, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_4.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 5, 0, 1, 1)
        self.PSPReversal_RsCorr = QtWidgets.QCheckBox(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PSPReversal_RsCorr.sizePolicy().hasHeightForWidth())
        self.PSPReversal_RsCorr.setSizePolicy(sizePolicy)
        self.PSPReversal_RsCorr.setObjectName("PSPReversal_RsCorr")
        self.gridLayout_4.addWidget(self.PSPReversal_RsCorr, 5, 2, 1, 1)
        self.PSPReversal_SubBaseline = QtWidgets.QCheckBox(self.layoutWidget5)
        self.PSPReversal_SubBaseline.setText("Sub Baseline")
        self.PSPReversal_SubBaseline.setObjectName("PSPReversal_SubBaseline")
        self.gridLayout_4.addWidget(self.PSPReversal_SubBaseline, 1, 3, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.PSPReversal_dataMode = QtWidgets.QLabel(self.layoutWidget5)
        self.PSPReversal_dataMode.setObjectName("PSPReversal_dataMode")
        self.horizontalLayout_8.addWidget(self.PSPReversal_dataMode)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget6.setGeometry(Qt.QRect(5, 80, 341, 25))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.PSPReversal_Alternation = QtWidgets.QCheckBox(self.layoutWidget6)
        self.PSPReversal_Alternation.setObjectName("PSPReversal_Alternation")
        self.horizontalLayout_9.addWidget(self.PSPReversal_Alternation)
        self.PSPReversal_EvenOdd = QtWidgets.QCheckBox(self.layoutWidget6)
        self.PSPReversal_EvenOdd.setObjectName("PSPReversal_EvenOdd")
        self.horizontalLayout_9.addWidget(self.PSPReversal_EvenOdd)
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget7.setGeometry(Qt.QRect(5, 285, 373, 29))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.PSPReversal_RMPMode = QtWidgets.QComboBox(self.layoutWidget7)
        font = Qt.QFont()
        font.setPointSize(12)
        self.PSPReversal_RMPMode.setFont(font)
        self.PSPReversal_RMPMode.setObjectName("PSPReversal_RMPMode")
        self.PSPReversal_RMPMode.addItem("")
        self.PSPReversal_RMPMode.addItem("")
        self.PSPReversal_RMPMode.addItem("")
        self.horizontalLayout_2.addWidget(self.PSPReversal_RMPMode)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.PSPReversal_Holding = QtWidgets.QLabel(self.layoutWidget7)
        palette = Qt.QPalette()
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Window, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Window, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Base, brush)
        brush = Qt.QBrush(Qt.QColor(255, 255, 255))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Window, brush)
        self.PSPReversal_Holding.setPalette(palette)
        self.PSPReversal_Holding.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.PSPReversal_Holding.setFrameShadow(QtWidgets.QFrame.Plain)
        self.PSPReversal_Holding.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_Holding.setObjectName("PSPReversal_Holding")
        self.horizontalLayout_10.addWidget(self.PSPReversal_Holding)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.PSPReversal_Junction = QtWidgets.QDoubleSpinBox(self.layoutWidget7)
        self.PSPReversal_Junction.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.PSPReversal_Junction.setDecimals(1)
        self.PSPReversal_Junction.setMinimum(-50.0)
        self.PSPReversal_Junction.setMaximum(50.0)
        self.PSPReversal_Junction.setSingleStep(0.5)
        self.PSPReversal_Junction.setObjectName("PSPReversal_Junction")
        self.horizontalLayout_11.addWidget(self.PSPReversal_Junction)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.PSPReversal_AveragePlot = QtWidgets.QCheckBox(self.groupBox)
        self.PSPReversal_AveragePlot.setGeometry(Qt.QRect(100, 400, 87, 20))
        self.PSPReversal_AveragePlot.setObjectName("PSPReversal_AveragePlot")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.PSPReversal_IVLimits, self.PSPReversal_IVLimitMin)
        Form.setTabOrder(self.PSPReversal_IVLimitMin, self.PSPReversal_IVLimitMax)
        Form.setTabOrder(self.PSPReversal_IVLimitMax, self.PSPReversal_Sequence1)
        Form.setTabOrder(self.PSPReversal_Sequence1, self.PSPReversal_Sequence2)
        Form.setTabOrder(self.PSPReversal_Sequence2, self.PSPReversal_tauh_Commands)
        Form.setTabOrder(self.PSPReversal_tauh_Commands, self.PSPReversal_Alternation)
        Form.setTabOrder(self.PSPReversal_Alternation, self.PSPReversal_showHide_lrrmp)
        Form.setTabOrder(self.PSPReversal_showHide_lrrmp, self.PSPReversal_rmpTStart)
        Form.setTabOrder(self.PSPReversal_rmpTStart, self.PSPReversal_rmpTStop)
        Form.setTabOrder(self.PSPReversal_rmpTStop, self.PSPReversal_showHide_lrwin1)
        Form.setTabOrder(self.PSPReversal_showHide_lrwin1, self.PSPReversal_win1TStart)
        Form.setTabOrder(self.PSPReversal_win1TStart, self.PSPReversal_win1TStop)
        Form.setTabOrder(self.PSPReversal_win1TStop, self.PSPReversal_win1mode)
        Form.setTabOrder(self.PSPReversal_win1mode, self.PSPReversal_showHide_lrwin2)
        Form.setTabOrder(self.PSPReversal_showHide_lrwin2, self.PSPReversal_win2TStart)
        Form.setTabOrder(self.PSPReversal_win2TStart, self.PSPReversal_win2TStop)
        Form.setTabOrder(self.PSPReversal_win2TStop, self.PSPReversal_win2mode)
        Form.setTabOrder(self.PSPReversal_win2mode, self.PSPReversal_showHide_lrwin0)
        Form.setTabOrder(self.PSPReversal_showHide_lrwin0, self.PSPReversal_win0TStart)
        Form.setTabOrder(self.PSPReversal_win0TStart, self.PSPReversal_win0TStop)
        Form.setTabOrder(self.PSPReversal_win0TStop, self.PSPReversal_R_unCompensated)
        Form.setTabOrder(self.PSPReversal_R_unCompensated, self.PSPReversal_RMPMode)
        Form.setTabOrder(self.PSPReversal_RMPMode, self.PSPReversal_Junction)
        Form.setTabOrder(self.PSPReversal_Junction, self.PSPReversal_KeepAnalysis)
        Form.setTabOrder(self.PSPReversal_KeepAnalysis, self.PSPReversal_KeepT)
        Form.setTabOrder(self.PSPReversal_KeepT, self.PSP_Reversal_vrmp)
        Form.setTabOrder(self.PSP_Reversal_vrmp, self.PSPReversal_Tau)
        Form.setTabOrder(self.PSPReversal_Tau, self.PSPReversal_Rin)
        Form.setTabOrder(self.PSPReversal_Rin, self.PSPReversal_Tauh)
        Form.setTabOrder(self.PSPReversal_Tauh, self.PSPReversal_Update)
        Form.setTabOrder(self.PSPReversal_Update, self.dbStoreBtn)
        Form.setTabOrder(self.dbStoreBtn, self.PSPReversal_rePlotData)
        Form.setTabOrder(self.PSPReversal_rePlotData, self.PSPReversal_PrintResults)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "PSP Reversal V1.1"))
        self.label_10.setText(_translate("Form", "Results"))
        self.label_7.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">I<span style=\" vertical-align:sub;\">0</span>/Vr</p></body></html>"))
        self.label_9.setText(_translate("Form", "&tau;<sub>m</sub> (ms)"))
        self.label_2.setText(_translate("Form", "R<sub>in</sub>"))
        self.label_15.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&tau;<span style=\" vertical-align:sub;\">h</span> (ms)</p></body></html>"))
        self.PSPReversal_KeepAnalysis.setText(_translate("Form", "Keep \n"
"Analysis"))
        self.PSPReversal_KeepT.setText(_translate("Form", "Keep\n"
"Times"))
        self.label_13.setText(_translate("Form", "IV Cmd Limits"))
        self.PSPReversal_IVLimits.setText(_translate("Form", "Use Limits"))
        self.label_14.setText(_translate("Form", "Seq1"))
        self.PSPReversal_Sequence1.setItemText(0, _translate("Form", "None"))
        self.PSPReversal_Sequence1.setItemText(1, _translate("Form", "001"))
        self.PSPReversal_Sequence1.setItemText(2, _translate("Form", "002"))
        self.PSPReversal_Sequence1.setItemText(3, _translate("Form", "003"))
        self.PSPReversal_Sequence1.setItemText(4, _translate("Form", "004"))
        self.label_19.setText(_translate("Form", "Seq2"))
        self.PSPReversal_Sequence2.setItemText(0, _translate("Form", "None"))
        self.label_16.setText(_translate("Form", "Cmd"))
        self.PSPReversal_tauh_Commands.setItemText(0, _translate("Form", "0.0"))
        self.PSPReversal_Update.setText(_translate("Form", "Update"))
        self.dbStoreBtn.setText(_translate("Form", "-> db"))
        self.PSPReversal_rePlotData.setText(_translate("Form", "RePlot"))
        self.PSPReversal_PrintResults.setText(_translate("Form", "Print"))
        self.label.setText(_translate("Form", "T Start"))
        self.PSPReversal_win1mode.setItemText(0, _translate("Form", "Mean"))
        self.PSPReversal_win1mode.setItemText(1, _translate("Form", "Linear"))
        self.PSPReversal_win1mode.setItemText(2, _translate("Form", "Poly2"))
        self.PSPReversal_win1mode.setItemText(3, _translate("Form", "Min"))
        self.PSPReversal_win1mode.setItemText(4, _translate("Form", "Max"))
        self.PSPReversal_win1mode.setItemText(5, _translate("Form", "Abs"))
        self.PSPReversal_win1mode.setItemText(6, _translate("Form", "Sum"))
        self.PSPReversal_win2mode.setItemText(0, _translate("Form", "Mean"))
        self.PSPReversal_win2mode.setItemText(1, _translate("Form", "Mean-Win1"))
        self.PSPReversal_win2mode.setItemText(2, _translate("Form", "Mean-Linear"))
        self.PSPReversal_win2mode.setItemText(3, _translate("Form", "Mean-Poly2"))
        self.PSPReversal_win2mode.setItemText(4, _translate("Form", "Sum"))
        self.PSPReversal_win2mode.setItemText(5, _translate("Form", "Sum-Win1"))
        self.PSPReversal_win2mode.setItemText(6, _translate("Form", "Min"))
        self.PSPReversal_win2mode.setItemText(7, _translate("Form", "Max"))
        self.PSPReversal_win2mode.setItemText(8, _translate("Form", "Abs"))
        self.PSPReversal_showHide_lrwin0.setText(_translate("Form", "Exclude"))
        self.label_3.setText(_translate("Form", "T Stop"))
        self.PSPReversal_showHide_lrrmp.setText(_translate("Form", "I0/Vr"))
        self.PSPReversal_showHide_lrwin1.setText(_translate("Form", "Win1 (ms)"))
        self.PSPReversal_showHide_lrwin2.setText(_translate("Form", "Win2 (ms)"))
        self.label_4.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">R<span style=\" vertical-align:sub;\">uncomp</span></p></body></html>"))
        self.PSPReversal_RsCorr.setText(_translate("Form", "Ru Corr"))
        self.label_6.setText(_translate("Form", "Mode:"))
        self.PSPReversal_dataMode.setText(_translate("Form", "IC"))
        self.PSPReversal_Alternation.setText(_translate("Form", "Alternation"))
        self.PSPReversal_EvenOdd.setText(_translate("Form", "Even [odd]"))
        self.label_18.setText(_translate("Form", "Abcissa"))
        self.PSPReversal_RMPMode.setItemText(0, _translate("Form", "T (s)"))
        self.PSPReversal_RMPMode.setItemText(1, _translate("Form", "I (pA)"))
        self.PSPReversal_RMPMode.setItemText(2, _translate("Form", "Sp (#/s)"))
        self.label_5.setText(_translate("Form", "Hold"))
        self.PSPReversal_Holding.setText(_translate("Form", "     mV"))
        self.label_11.setText(_translate("Form", "JP"))
        self.PSPReversal_Junction.setSuffix(_translate("Form", " mV"))
        self.PSPReversal_AveragePlot.setText(_translate("Form", "PlotAverages"))

