# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './acq4/analysis/modules/PSPReversal/ctrlTemplate.ui'
#
# Created: Sat Jun 21 12:26:06 2014
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(350, 468)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Form.setPalette(palette)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(15, 318, 46, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(8, 307, 325, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 340, 251, 56))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.PSP_Reversal_vrmp = QtGui.QLineEdit(self.layoutWidget)
        self.PSP_Reversal_vrmp.setObjectName(_fromUtf8("PSP_Reversal_vrmp"))
        self.gridLayout_3.addWidget(self.PSP_Reversal_vrmp, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.PSPReversal_Tau = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_Tau.setFont(font)
        self.PSPReversal_Tau.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_Tau.setObjectName(_fromUtf8("PSPReversal_Tau"))
        self.gridLayout_3.addWidget(self.PSPReversal_Tau, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.PSPReversal_Rin = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_Rin.setFont(font)
        self.PSPReversal_Rin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_Rin.setObjectName(_fromUtf8("PSPReversal_Rin"))
        self.gridLayout_3.addWidget(self.PSPReversal_Rin, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 1, 2, 1, 1)
        self.PSPReversal_Tauh = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_Tauh.setFont(font)
        self.PSPReversal_Tauh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_Tauh.setObjectName(_fromUtf8("PSPReversal_Tauh"))
        self.gridLayout_3.addWidget(self.PSPReversal_Tauh, 1, 3, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 340, 77, 73))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.PSPReversal_KeepAnalysis = QtGui.QCheckBox(self.layoutWidget1)
        self.PSPReversal_KeepAnalysis.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PSPReversal_KeepAnalysis.setObjectName(_fromUtf8("PSPReversal_KeepAnalysis"))
        self.verticalLayout_4.addWidget(self.PSPReversal_KeepAnalysis)
        self.PSPReversal_KeepT = QtGui.QCheckBox(self.layoutWidget1)
        self.PSPReversal_KeepT.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PSPReversal_KeepT.setObjectName(_fromUtf8("PSPReversal_KeepT"))
        self.verticalLayout_4.addWidget(self.PSPReversal_KeepT)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(5, 20, 357, 32))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_13 = QtGui.QLabel(self.layoutWidget2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_6.addWidget(self.label_13)
        self.PSPReversal_IVLimits = QtGui.QCheckBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PSPReversal_IVLimits.setFont(font)
        self.PSPReversal_IVLimits.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PSPReversal_IVLimits.setObjectName(_fromUtf8("PSPReversal_IVLimits"))
        self.horizontalLayout_6.addWidget(self.PSPReversal_IVLimits)
        self.PSPReversal_IVLimitMin = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.PSPReversal_IVLimitMin.setDecimals(1)
        self.PSPReversal_IVLimitMin.setMinimum(-2000.0)
        self.PSPReversal_IVLimitMin.setMaximum(2000.0)
        self.PSPReversal_IVLimitMin.setSingleStep(5.0)
        self.PSPReversal_IVLimitMin.setProperty("value", -160.0)
        self.PSPReversal_IVLimitMin.setObjectName(_fromUtf8("PSPReversal_IVLimitMin"))
        self.horizontalLayout_6.addWidget(self.PSPReversal_IVLimitMin)
        self.PSPReversal_IVLimitMax = QtGui.QDoubleSpinBox(self.layoutWidget2)
        self.PSPReversal_IVLimitMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_IVLimitMax.setDecimals(1)
        self.PSPReversal_IVLimitMax.setMinimum(-2000.0)
        self.PSPReversal_IVLimitMax.setMaximum(2000.0)
        self.PSPReversal_IVLimitMax.setSingleStep(5.0)
        self.PSPReversal_IVLimitMax.setProperty("value", 100.0)
        self.PSPReversal_IVLimitMax.setObjectName(_fromUtf8("PSPReversal_IVLimitMax"))
        self.horizontalLayout_6.addWidget(self.PSPReversal_IVLimitMax)
        self.layoutWidget3 = QtGui.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(5, 50, 341, 28))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_14 = QtGui.QLabel(self.layoutWidget3)
        self.label_14.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_3.addWidget(self.label_14)
        self.PSPReversal_Sequence1 = QtGui.QComboBox(self.layoutWidget3)
        self.PSPReversal_Sequence1.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PSPReversal_Sequence1.setFont(font)
        self.PSPReversal_Sequence1.setObjectName(_fromUtf8("PSPReversal_Sequence1"))
        self.PSPReversal_Sequence1.addItem(_fromUtf8(""))
        self.PSPReversal_Sequence1.addItem(_fromUtf8(""))
        self.PSPReversal_Sequence1.addItem(_fromUtf8(""))
        self.PSPReversal_Sequence1.addItem(_fromUtf8(""))
        self.PSPReversal_Sequence1.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.PSPReversal_Sequence1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_19 = QtGui.QLabel(self.layoutWidget3)
        self.label_19.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_4.addWidget(self.label_19)
        self.PSPReversal_Sequence2 = QtGui.QComboBox(self.layoutWidget3)
        self.PSPReversal_Sequence2.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PSPReversal_Sequence2.setFont(font)
        self.PSPReversal_Sequence2.setObjectName(_fromUtf8("PSPReversal_Sequence2"))
        self.PSPReversal_Sequence2.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.PSPReversal_Sequence2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_16 = QtGui.QLabel(self.layoutWidget3)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_5.addWidget(self.label_16)
        self.PSPReversal_tauh_Commands = QtGui.QComboBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PSPReversal_tauh_Commands.setFont(font)
        self.PSPReversal_tauh_Commands.setObjectName(_fromUtf8("PSPReversal_tauh_Commands"))
        self.PSPReversal_tauh_Commands.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.PSPReversal_tauh_Commands)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.layoutWidget4 = QtGui.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 425, 332, 32))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.PSPReversal_Update = QtGui.QPushButton(self.layoutWidget4)
        self.PSPReversal_Update.setObjectName(_fromUtf8("PSPReversal_Update"))
        self.horizontalLayout.addWidget(self.PSPReversal_Update)
        self.dbStoreBtn = QtGui.QPushButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dbStoreBtn.setFont(font)
        self.dbStoreBtn.setObjectName(_fromUtf8("dbStoreBtn"))
        self.horizontalLayout.addWidget(self.dbStoreBtn)
        self.PSPReversal_rePlotData = QtGui.QPushButton(self.layoutWidget4)
        self.PSPReversal_rePlotData.setObjectName(_fromUtf8("PSPReversal_rePlotData"))
        self.horizontalLayout.addWidget(self.PSPReversal_rePlotData)
        self.PSPReversal_PrintResults = QtGui.QPushButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PSPReversal_PrintResults.sizePolicy().hasHeightForWidth())
        self.PSPReversal_PrintResults.setSizePolicy(sizePolicy)
        self.PSPReversal_PrintResults.setObjectName(_fromUtf8("PSPReversal_PrintResults"))
        self.horizontalLayout.addWidget(self.PSPReversal_PrintResults)
        self.layoutWidget5 = QtGui.QWidget(self.groupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(5, 110, 341, 171))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setVerticalSpacing(5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(self.layoutWidget5)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.PSPReversal_rmpTStop = QtGui.QDoubleSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_rmpTStop.setFont(font)
        self.PSPReversal_rmpTStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_rmpTStop.setMaximum(10000.0)
        self.PSPReversal_rmpTStop.setProperty("value", 10.0)
        self.PSPReversal_rmpTStop.setObjectName(_fromUtf8("PSPReversal_rmpTStop"))
        self.gridLayout_4.addWidget(self.PSPReversal_rmpTStop, 1, 2, 1, 1)
        self.PSPReversal_win1TStart = QtGui.QDoubleSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_win1TStart.setFont(font)
        self.PSPReversal_win1TStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_win1TStart.setMinimum(-5000.0)
        self.PSPReversal_win1TStart.setMaximum(50000.0)
        self.PSPReversal_win1TStart.setObjectName(_fromUtf8("PSPReversal_win1TStart"))
        self.gridLayout_4.addWidget(self.PSPReversal_win1TStart, 2, 1, 1, 1)
        self.PSPReversal_win1TStop = QtGui.QDoubleSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_win1TStop.setFont(font)
        self.PSPReversal_win1TStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_win1TStop.setMinimum(-5000.0)
        self.PSPReversal_win1TStop.setMaximum(50000.0)
        self.PSPReversal_win1TStop.setObjectName(_fromUtf8("PSPReversal_win1TStop"))
        self.gridLayout_4.addWidget(self.PSPReversal_win1TStop, 2, 2, 1, 1)
        self.PSPReversal_win1mode = QtGui.QComboBox(self.layoutWidget5)
        self.PSPReversal_win1mode.setObjectName(_fromUtf8("PSPReversal_win1mode"))
        self.PSPReversal_win1mode.addItem(_fromUtf8(""))
        self.PSPReversal_win1mode.addItem(_fromUtf8(""))
        self.PSPReversal_win1mode.addItem(_fromUtf8(""))
        self.PSPReversal_win1mode.addItem(_fromUtf8(""))
        self.PSPReversal_win1mode.addItem(_fromUtf8(""))
        self.PSPReversal_win1mode.addItem(_fromUtf8(""))
        self.PSPReversal_win1mode.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.PSPReversal_win1mode, 2, 3, 1, 1)
        self.PSPReversal_win2TStart = QtGui.QDoubleSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_win2TStart.setFont(font)
        self.PSPReversal_win2TStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_win2TStart.setMinimum(0.0)
        self.PSPReversal_win2TStart.setMaximum(50000.0)
        self.PSPReversal_win2TStart.setObjectName(_fromUtf8("PSPReversal_win2TStart"))
        self.gridLayout_4.addWidget(self.PSPReversal_win2TStart, 3, 1, 1, 1)
        self.PSPReversal_win2TStop = QtGui.QDoubleSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_win2TStop.setFont(font)
        self.PSPReversal_win2TStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_win2TStop.setMinimum(0.0)
        self.PSPReversal_win2TStop.setMaximum(50000.0)
        self.PSPReversal_win2TStop.setObjectName(_fromUtf8("PSPReversal_win2TStop"))
        self.gridLayout_4.addWidget(self.PSPReversal_win2TStop, 3, 2, 1, 1)
        self.PSPReversal_win2mode = QtGui.QComboBox(self.layoutWidget5)
        self.PSPReversal_win2mode.setObjectName(_fromUtf8("PSPReversal_win2mode"))
        self.PSPReversal_win2mode.addItem(_fromUtf8(""))
        self.PSPReversal_win2mode.addItem(_fromUtf8(""))
        self.PSPReversal_win2mode.addItem(_fromUtf8(""))
        self.PSPReversal_win2mode.addItem(_fromUtf8(""))
        self.PSPReversal_win2mode.addItem(_fromUtf8(""))
        self.PSPReversal_win2mode.addItem(_fromUtf8(""))
        self.PSPReversal_win2mode.addItem(_fromUtf8(""))
        self.PSPReversal_win2mode.addItem(_fromUtf8(""))
        self.PSPReversal_win2mode.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.PSPReversal_win2mode, 3, 3, 1, 1)
        self.PSPReversal_showHide_lrwin0 = QtGui.QCheckBox(self.layoutWidget5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(253, 218, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 218, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.PSPReversal_showHide_lrwin0.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PSPReversal_showHide_lrwin0.setFont(font)
        self.PSPReversal_showHide_lrwin0.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.PSPReversal_showHide_lrwin0.setObjectName(_fromUtf8("PSPReversal_showHide_lrwin0"))
        self.gridLayout_4.addWidget(self.PSPReversal_showHide_lrwin0, 4, 0, 1, 1)
        self.PSPReversal_win0TStart = QtGui.QDoubleSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_win0TStart.setFont(font)
        self.PSPReversal_win0TStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_win0TStart.setDecimals(1)
        self.PSPReversal_win0TStart.setMinimum(0.0)
        self.PSPReversal_win0TStart.setMaximum(10000.0)
        self.PSPReversal_win0TStart.setProperty("value", 0.0)
        self.PSPReversal_win0TStart.setObjectName(_fromUtf8("PSPReversal_win0TStart"))
        self.gridLayout_4.addWidget(self.PSPReversal_win0TStart, 4, 1, 1, 1)
        self.PSPReversal_win0TStop = QtGui.QDoubleSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_win0TStop.setFont(font)
        self.PSPReversal_win0TStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_win0TStop.setDecimals(1)
        self.PSPReversal_win0TStop.setMinimum(0.0)
        self.PSPReversal_win0TStop.setMaximum(10000.0)
        self.PSPReversal_win0TStop.setProperty("value", 5.0)
        self.PSPReversal_win0TStop.setObjectName(_fromUtf8("PSPReversal_win0TStop"))
        self.gridLayout_4.addWidget(self.PSPReversal_win0TStop, 4, 2, 1, 1)
        self.PSPReversal_R_unCompensated = QtGui.QDoubleSpinBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_R_unCompensated.setFont(font)
        self.PSPReversal_R_unCompensated.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_R_unCompensated.setSuffix(_fromUtf8(""))
        self.PSPReversal_R_unCompensated.setDecimals(1)
        self.PSPReversal_R_unCompensated.setMinimum(-100.0)
        self.PSPReversal_R_unCompensated.setObjectName(_fromUtf8("PSPReversal_R_unCompensated"))
        self.gridLayout_4.addWidget(self.PSPReversal_R_unCompensated, 5, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget5)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 2, 1, 1)
        self.PSPReversal_showHide_lrrmp = QtGui.QCheckBox(self.layoutWidget5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(232, 73, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 73, 61))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.PSPReversal_showHide_lrrmp.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PSPReversal_showHide_lrrmp.setFont(font)
        self.PSPReversal_showHide_lrrmp.setToolTip(_fromUtf8(""))
        self.PSPReversal_showHide_lrrmp.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.PSPReversal_showHide_lrrmp.setObjectName(_fromUtf8("PSPReversal_showHide_lrrmp"))
        self.gridLayout_4.addWidget(self.PSPReversal_showHide_lrrmp, 1, 0, 1, 1)
        self.PSPReversal_rmpTStart = QtGui.QDoubleSpinBox(self.layoutWidget5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.PSPReversal_rmpTStart.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_rmpTStart.setFont(font)
        self.PSPReversal_rmpTStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_rmpTStart.setDecimals(2)
        self.PSPReversal_rmpTStart.setMaximum(10000.0)
        self.PSPReversal_rmpTStart.setObjectName(_fromUtf8("PSPReversal_rmpTStart"))
        self.gridLayout_4.addWidget(self.PSPReversal_rmpTStart, 1, 1, 1, 1)
        self.PSPReversal_showHide_lrwin1 = QtGui.QCheckBox(self.layoutWidget5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(97, 225, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 225, 17))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.PSPReversal_showHide_lrwin1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PSPReversal_showHide_lrwin1.setFont(font)
        self.PSPReversal_showHide_lrwin1.setToolTip(_fromUtf8(""))
        self.PSPReversal_showHide_lrwin1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.PSPReversal_showHide_lrwin1.setChecked(True)
        self.PSPReversal_showHide_lrwin1.setObjectName(_fromUtf8("PSPReversal_showHide_lrwin1"))
        self.gridLayout_4.addWidget(self.PSPReversal_showHide_lrwin1, 2, 0, 1, 1)
        self.PSPReversal_showHide_lrwin2 = QtGui.QCheckBox(self.layoutWidget5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(32, 127, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 127, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 69, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.PSPReversal_showHide_lrwin2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PSPReversal_showHide_lrwin2.setFont(font)
        self.PSPReversal_showHide_lrwin2.setToolTip(_fromUtf8(""))
        self.PSPReversal_showHide_lrwin2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.PSPReversal_showHide_lrwin2.setChecked(True)
        self.PSPReversal_showHide_lrwin2.setObjectName(_fromUtf8("PSPReversal_showHide_lrwin2"))
        self.gridLayout_4.addWidget(self.PSPReversal_showHide_lrwin2, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget5)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 5, 0, 1, 1)
        self.PSPReversal_RsCorr = QtGui.QCheckBox(self.layoutWidget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PSPReversal_RsCorr.sizePolicy().hasHeightForWidth())
        self.PSPReversal_RsCorr.setSizePolicy(sizePolicy)
        self.PSPReversal_RsCorr.setObjectName(_fromUtf8("PSPReversal_RsCorr"))
        self.gridLayout_4.addWidget(self.PSPReversal_RsCorr, 5, 2, 1, 1)
        self.PSPReversal_SubBaseline = QtGui.QCheckBox(self.layoutWidget5)
        self.PSPReversal_SubBaseline.setText(_fromUtf8("Sub Baseline"))
        self.PSPReversal_SubBaseline.setObjectName(_fromUtf8("PSPReversal_SubBaseline"))
        self.gridLayout_4.addWidget(self.PSPReversal_SubBaseline, 1, 3, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.layoutWidget5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.PSPReversal_dataMode = QtGui.QLabel(self.layoutWidget5)
        self.PSPReversal_dataMode.setObjectName(_fromUtf8("PSPReversal_dataMode"))
        self.horizontalLayout_8.addWidget(self.PSPReversal_dataMode)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.layoutWidget6 = QtGui.QWidget(self.groupBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(5, 80, 341, 25))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.PSPReversal_Alternation = QtGui.QCheckBox(self.layoutWidget6)
        self.PSPReversal_Alternation.setObjectName(_fromUtf8("PSPReversal_Alternation"))
        self.horizontalLayout_9.addWidget(self.PSPReversal_Alternation)
        self.PSPReversal_EvenOdd = QtGui.QCheckBox(self.layoutWidget6)
        self.PSPReversal_EvenOdd.setObjectName(_fromUtf8("PSPReversal_EvenOdd"))
        self.horizontalLayout_9.addWidget(self.PSPReversal_EvenOdd)
        self.layoutWidget7 = QtGui.QWidget(self.groupBox)
        self.layoutWidget7.setGeometry(QtCore.QRect(5, 285, 373, 29))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_12.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_18 = QtGui.QLabel(self.layoutWidget7)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_2.addWidget(self.label_18)
        self.PSPReversal_RMPMode = QtGui.QComboBox(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSPReversal_RMPMode.setFont(font)
        self.PSPReversal_RMPMode.setObjectName(_fromUtf8("PSPReversal_RMPMode"))
        self.PSPReversal_RMPMode.addItem(_fromUtf8(""))
        self.PSPReversal_RMPMode.addItem(_fromUtf8(""))
        self.PSPReversal_RMPMode.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.PSPReversal_RMPMode)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_5 = QtGui.QLabel(self.layoutWidget7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_10.addWidget(self.label_5)
        self.PSPReversal_Holding = QtGui.QLabel(self.layoutWidget7)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.PSPReversal_Holding.setPalette(palette)
        self.PSPReversal_Holding.setFrameShape(QtGui.QFrame.NoFrame)
        self.PSPReversal_Holding.setFrameShadow(QtGui.QFrame.Plain)
        self.PSPReversal_Holding.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_Holding.setObjectName(_fromUtf8("PSPReversal_Holding"))
        self.horizontalLayout_10.addWidget(self.PSPReversal_Holding)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_11 = QtGui.QLabel(self.layoutWidget7)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.PSPReversal_Junction = QtGui.QDoubleSpinBox(self.layoutWidget7)
        self.PSPReversal_Junction.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PSPReversal_Junction.setDecimals(1)
        self.PSPReversal_Junction.setMinimum(-50.0)
        self.PSPReversal_Junction.setMaximum(50.0)
        self.PSPReversal_Junction.setSingleStep(0.5)
        self.PSPReversal_Junction.setObjectName(_fromUtf8("PSPReversal_Junction"))
        self.horizontalLayout_11.addWidget(self.PSPReversal_Junction)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.PSPReversal_AveragePlot = QtGui.QCheckBox(self.groupBox)
        self.PSPReversal_AveragePlot.setGeometry(QtCore.QRect(100, 400, 87, 20))
        self.PSPReversal_AveragePlot.setObjectName(_fromUtf8("PSPReversal_AveragePlot"))
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.PSPReversal_IVLimits, self.PSPReversal_IVLimitMin)
        Form.setTabOrder(self.PSPReversal_IVLimitMin, self.PSPReversal_IVLimitMax)
        Form.setTabOrder(self.PSPReversal_IVLimitMax, self.PSPReversal_Sequence1)
        Form.setTabOrder(self.PSPReversal_Sequence1, self.PSPReversal_Sequence2)
        Form.setTabOrder(self.PSPReversal_Sequence2, self.PSPReversal_tauh_Commands)
        Form.setTabOrder(self.PSPReversal_tauh_Commands, self.PSPReversal_Alternation)
        Form.setTabOrder(self.PSPReversal_Alternation, self.PSPReversal_showHide_lrrmp)
        Form.setTabOrder(self.PSPReversal_showHide_lrrmp, self.PSPReversal_rmpTStart)
        Form.setTabOrder(self.PSPReversal_rmpTStart, self.PSPReversal_rmpTStop)
        Form.setTabOrder(self.PSPReversal_rmpTStop, self.PSPReversal_showHide_lrwin1)
        Form.setTabOrder(self.PSPReversal_showHide_lrwin1, self.PSPReversal_win1TStart)
        Form.setTabOrder(self.PSPReversal_win1TStart, self.PSPReversal_win1TStop)
        Form.setTabOrder(self.PSPReversal_win1TStop, self.PSPReversal_win1mode)
        Form.setTabOrder(self.PSPReversal_win1mode, self.PSPReversal_showHide_lrwin2)
        Form.setTabOrder(self.PSPReversal_showHide_lrwin2, self.PSPReversal_win2TStart)
        Form.setTabOrder(self.PSPReversal_win2TStart, self.PSPReversal_win2TStop)
        Form.setTabOrder(self.PSPReversal_win2TStop, self.PSPReversal_win2mode)
        Form.setTabOrder(self.PSPReversal_win2mode, self.PSPReversal_showHide_lrwin0)
        Form.setTabOrder(self.PSPReversal_showHide_lrwin0, self.PSPReversal_win0TStart)
        Form.setTabOrder(self.PSPReversal_win0TStart, self.PSPReversal_win0TStop)
        Form.setTabOrder(self.PSPReversal_win0TStop, self.PSPReversal_R_unCompensated)
        Form.setTabOrder(self.PSPReversal_R_unCompensated, self.PSPReversal_RMPMode)
        Form.setTabOrder(self.PSPReversal_RMPMode, self.PSPReversal_Junction)
        Form.setTabOrder(self.PSPReversal_Junction, self.PSPReversal_KeepAnalysis)
        Form.setTabOrder(self.PSPReversal_KeepAnalysis, self.PSPReversal_KeepT)
        Form.setTabOrder(self.PSPReversal_KeepT, self.PSP_Reversal_vrmp)
        Form.setTabOrder(self.PSP_Reversal_vrmp, self.PSPReversal_Tau)
        Form.setTabOrder(self.PSPReversal_Tau, self.PSPReversal_Rin)
        Form.setTabOrder(self.PSPReversal_Rin, self.PSPReversal_Tauh)
        Form.setTabOrder(self.PSPReversal_Tauh, self.PSPReversal_Update)
        Form.setTabOrder(self.PSPReversal_Update, self.dbStoreBtn)
        Form.setTabOrder(self.dbStoreBtn, self.PSPReversal_rePlotData)
        Form.setTabOrder(self.PSPReversal_rePlotData, self.PSPReversal_PrintResults)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "PSP Reversal V1.1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">I<span style=\" vertical-align:sub;\">0</span>/Vr</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "&tau;<sub>m</sub> (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "R<sub>in</sub>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&tau;<span style=\" vertical-align:sub;\">h</span> (ms)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_KeepAnalysis.setText(QtGui.QApplication.translate("Form", "Keep \n"
"Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_KeepT.setText(QtGui.QApplication.translate("Form", "Keep\n"
"Times", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "IV Cmd Limits", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_IVLimits.setText(QtGui.QApplication.translate("Form", "Use Limits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Seq1", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_Sequence1.setItemText(0, QtGui.QApplication.translate("Form", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_Sequence1.setItemText(1, QtGui.QApplication.translate("Form", "001", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_Sequence1.setItemText(2, QtGui.QApplication.translate("Form", "002", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_Sequence1.setItemText(3, QtGui.QApplication.translate("Form", "003", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_Sequence1.setItemText(4, QtGui.QApplication.translate("Form", "004", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Seq2", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_Sequence2.setItemText(0, QtGui.QApplication.translate("Form", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Cmd", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_tauh_Commands.setItemText(0, QtGui.QApplication.translate("Form", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_Update.setText(QtGui.QApplication.translate("Form", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.dbStoreBtn.setText(QtGui.QApplication.translate("Form", "-> db", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_rePlotData.setText(QtGui.QApplication.translate("Form", "RePlot", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_PrintResults.setText(QtGui.QApplication.translate("Form", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "T Start", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win1mode.setItemText(0, QtGui.QApplication.translate("Form", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win1mode.setItemText(1, QtGui.QApplication.translate("Form", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win1mode.setItemText(2, QtGui.QApplication.translate("Form", "Poly2", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win1mode.setItemText(3, QtGui.QApplication.translate("Form", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win1mode.setItemText(4, QtGui.QApplication.translate("Form", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win1mode.setItemText(5, QtGui.QApplication.translate("Form", "Abs", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win1mode.setItemText(6, QtGui.QApplication.translate("Form", "Sum", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win2mode.setItemText(0, QtGui.QApplication.translate("Form", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win2mode.setItemText(1, QtGui.QApplication.translate("Form", "Mean-Win1", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win2mode.setItemText(2, QtGui.QApplication.translate("Form", "Mean-Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win2mode.setItemText(3, QtGui.QApplication.translate("Form", "Mean-Poly2", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win2mode.setItemText(4, QtGui.QApplication.translate("Form", "Sum", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win2mode.setItemText(5, QtGui.QApplication.translate("Form", "Sum-Win1", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win2mode.setItemText(6, QtGui.QApplication.translate("Form", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win2mode.setItemText(7, QtGui.QApplication.translate("Form", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_win2mode.setItemText(8, QtGui.QApplication.translate("Form", "Abs", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_showHide_lrwin0.setText(QtGui.QApplication.translate("Form", "Exclude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "T Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_showHide_lrrmp.setText(QtGui.QApplication.translate("Form", "I0/Vr", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_showHide_lrwin1.setText(QtGui.QApplication.translate("Form", "Win1 (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_showHide_lrwin2.setText(QtGui.QApplication.translate("Form", "Win2 (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">R<span style=\" vertical-align:sub;\">uncomp</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_RsCorr.setText(QtGui.QApplication.translate("Form", "Ru Corr", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_dataMode.setText(QtGui.QApplication.translate("Form", "IC", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_Alternation.setText(QtGui.QApplication.translate("Form", "Alternation", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_EvenOdd.setText(QtGui.QApplication.translate("Form", "Even [odd]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Abcissa", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_RMPMode.setItemText(0, QtGui.QApplication.translate("Form", "T (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_RMPMode.setItemText(1, QtGui.QApplication.translate("Form", "I (pA)", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_RMPMode.setItemText(2, QtGui.QApplication.translate("Form", "Sp (#/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Hold", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_Holding.setText(QtGui.QApplication.translate("Form", "     mV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "JP", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_Junction.setSuffix(QtGui.QApplication.translate("Form", " mV", None, QtGui.QApplication.UnicodeUTF8))
        self.PSPReversal_AveragePlot.setText(QtGui.QApplication.translate("Form", "PlotAverages", None, QtGui.QApplication.UnicodeUTF8))

