# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/modules/PSPReversal/scriptTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 468)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(Qt.QRect(11, 5, 95, 16))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(Qt.QRect(10, 30, 331, 32))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PSPReversal_ScriptFile_Btn = QtWidgets.QPushButton(self.widget)
        self.PSPReversal_ScriptFile_Btn.setObjectName("PSPReversal_ScriptFile_Btn")
        self.horizontalLayout.addWidget(self.PSPReversal_ScriptFile_Btn)
        self.PSPReversal_ScriptRerun_Btn = QtWidgets.QPushButton(self.widget)
        self.PSPReversal_ScriptRerun_Btn.setObjectName("PSPReversal_ScriptRerun_Btn")
        self.horizontalLayout.addWidget(self.PSPReversal_ScriptRerun_Btn)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(Qt.QRect(5, 70, 341, 391))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.PSPReversal_ScriptFile = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PSPReversal_ScriptFile.sizePolicy().hasHeightForWidth())
        self.PSPReversal_ScriptFile.setSizePolicy(sizePolicy)
        self.PSPReversal_ScriptFile.setMinimumSize(Qt.QSize(220, 0))
        self.PSPReversal_ScriptFile.setObjectName("PSPReversal_ScriptFile")
        self.horizontalLayout_2.addWidget(self.PSPReversal_ScriptFile)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.PSPReversal_Script_TextEdit = QtWidgets.QPlainTextEdit(self.widget1)
        font = Qt.QFont()
        font.setKerning(False)
        self.PSPReversal_Script_TextEdit.setFont(font)
        self.PSPReversal_Script_TextEdit.setHorizontalScrollBarPolicy(Qt.Qt.ScrollBarAlwaysOn)
        self.PSPReversal_Script_TextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.PSPReversal_Script_TextEdit.setObjectName("PSPReversal_Script_TextEdit")
        self.verticalLayout.addWidget(self.PSPReversal_Script_TextEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.PSPReversal_ScriptPrint_Btn = QtWidgets.QPushButton(self.widget1)
        self.PSPReversal_ScriptPrint_Btn.setObjectName("PSPReversal_ScriptPrint_Btn")
        self.horizontalLayout_3.addWidget(self.PSPReversal_ScriptPrint_Btn)
        self.PSPReversal_ScriptCopy_Btn = QtWidgets.QPushButton(self.widget1)
        self.PSPReversal_ScriptCopy_Btn.setObjectName("PSPReversal_ScriptCopy_Btn")
        self.horizontalLayout_3.addWidget(self.PSPReversal_ScriptCopy_Btn)
        self.PSPReversal_ScriptFormatted_Btn = QtWidgets.QPushButton(self.widget1)
        self.PSPReversal_ScriptFormatted_Btn.setObjectName("PSPReversal_ScriptFormatted_Btn")
        self.horizontalLayout_3.addWidget(self.PSPReversal_ScriptFormatted_Btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.PSPReversal_ScriptResults_text = QtWidgets.QPlainTextEdit(self.widget1)
        self.PSPReversal_ScriptResults_text.setObjectName("PSPReversal_ScriptResults_text")
        self.verticalLayout.addWidget(self.PSPReversal_ScriptResults_text)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Script Manager"))
        self.PSPReversal_ScriptFile_Btn.setText(_translate("Form", "Open and Run"))
        self.PSPReversal_ScriptRerun_Btn.setText(_translate("Form", "Rerun"))
        self.label_3.setText(_translate("Form", "Script:"))
        self.PSPReversal_ScriptFile.setText(_translate("Form", "No File"))
        self.label_4.setText(_translate("Form", "Output"))
        self.PSPReversal_ScriptPrint_Btn.setText(_translate("Form", "Print"))
        self.PSPReversal_ScriptCopy_Btn.setText(_translate("Form", "Copy"))
        self.PSPReversal_ScriptFormatted_Btn.setText(_translate("Form", "Print Formtted"))

