#!/usr/bin/python -i
# -*- coding: utf-8 -*-
from scipy import zeros
#from graphicsWindows import *
from graphicsItems import *
from widgets import *
from PyQt4 import QtCore, QtGui
from helpers import loadImageDir

if QtGui.QApplication.instance() is None:
  qapp = QtGui.QApplication([])

#i = PlotWindow(array([0,1,2,1,2]), parent=None, title='')

class Win(QtGui.QMainWindow):
  pass

w1 = Win()
v1 = GraphicsView()
v1.invertY(True)
v1.setAspectLocked(True)
w1.setCentralWidget(v1)
s1 = QtGui.QGraphicsScene()
v1.setScene(s1)
w2 = Win()
v2 = GraphicsView()
v2.invertY(True)
v2.setAspectLocked(True)
w2.setCentralWidget(v2)
s2 = QtGui.QGraphicsScene()
v2.setScene(s2)

#p = Plot(array([0,2,1,3,4]), copy=False)
#s.addItem(p)


im1 = ImageItem()
s1.addItem(im1)
im2 = ImageItem()
s2.addItem(im2)


#g = Grid(view=v, bounds=QtCore.QRectF(0.1, 0.1, 0.8, 0.8))
g = Grid(view=v2)
s2.addItem(g)

#wid = RectROI([0,  0], [2, 2], maxBounds=QtCore.QRectF(-1, -1, 5, 5))
roi = LineROI([0,  0], [20, 20], width=5)
s1.addItem(roi)

arr = loadImageDir()
print arr.shape
arr1 = arr.mean(axis=0)
print arr1.shape
im1.updateImage(arr1, autoRange=True)


def updateImg(w):
  global im1, roi, arr
  tr = arr.transpose((1,2,0))
  arr1 = roi.getArrayRegion(tr, img=im1)
  im2.updateImage(arr1.mean(axis=2), autoRange=True)

roi.connect(QtCore.SIGNAL('regionChangeFinished'), updateImg)

w1.show()
w2.show()

