#!/usr/bin/python -i
from scipy import zeros
from graphicsWindows import *
from graphicsItems import *
from widgets import *
from PyQt4 import QtCore, QtGui

qapp = QtGui.QApplication([])

class Win(QtGui.QMainWindow):
  pass

w = Win()
v = QtGui.QGraphicsView()
v.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
v.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
#v.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
#v.setResizeAnchor(QtGui.QGraphicsView.NoAnchor)
#v.setViewportUpdateMode(QtGui.QGraphicsView.SmartViewportUpdate)


w.setCentralWidget(v)
s = QtGui.QGraphicsScene()
v.setScene(s)
#s.addItem(QtGui.QGraphicsRectItem(0, 0, 100, 100))
b1 = ViewBox(QtCore.QRectF(0.01, 0.01, 0.48, 0.98), view=v, showGrid=True)
b2 = ViewBox(QtCore.QRectF(0.51, 0.01, 0.48, 0.98), view=v, showGrid=True)
s.addItem(b2)
s.addItem(b1)
p = Plot(array([1,3,2,4]))
b1.addItem(p)

im = ImageItem(array([[1,2,3], [4,5,6], [7,8,9]]))
b2.addItem(im)
b2.invertY()
b2.setAspectLocked(True)

c1 = QtGui.QGraphicsEllipseItem(0, 0, 3, 3)
c1.setPen(QtGui.QPen(QtGui.QColor(100, 0, 0)))
c2 = QtGui.QGraphicsEllipseItem(0, 0, 3, 3)
c2.setPen(QtGui.QPen(QtGui.QColor(100, 0, 0)))
b1.addItem(c1)
b2.addItem(c2)

wg = RectROI([0, 0], [1, 1])
b1.addItem(wg)


w.show()

def printBounds(i):
  b = i.boundingRect()
  print b.x(), b.y(), b.width(), b.height()

