# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/modules/STDPAnalyzer/STDPControlTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(358, 751)
        self.gridLayout_7 = QtWidgets.QGridLayout(Form)
        self.gridLayout_7.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_7.setSpacing(3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.createSummaryBtn = QtWidgets.QPushButton(Form)
        self.createSummaryBtn.setObjectName("createSummaryBtn")
        self.gridLayout_7.addWidget(self.createSummaryBtn, 5, 0, 1, 1)
        self.traceDisplayGroup = QtWidgets.QGroupBox(Form)
        self.traceDisplayGroup.setObjectName("traceDisplayGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.traceDisplayGroup)
        self.gridLayout_3.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.averageCheck = QtWidgets.QCheckBox(self.traceDisplayGroup)
        self.averageCheck.setObjectName("averageCheck")
        self.gridLayout_3.addWidget(self.averageCheck, 0, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.excludeAPsCheck = QtWidgets.QGroupBox(self.traceDisplayGroup)
        self.excludeAPsCheck.setCheckable(True)
        self.excludeAPsCheck.setObjectName("excludeAPsCheck")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.excludeAPsCheck)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(self.excludeAPsCheck)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.startExcludeAPsSpin = SpinBox(self.excludeAPsCheck)
        self.startExcludeAPsSpin.setObjectName("startExcludeAPsSpin")
        self.horizontalLayout.addWidget(self.startExcludeAPsSpin)
        self.label_9 = QtWidgets.QLabel(self.excludeAPsCheck)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.endExcludeAPsSpin = SpinBox(self.excludeAPsCheck)
        self.endExcludeAPsSpin.setProperty("value", 0.25)
        self.endExcludeAPsSpin.setObjectName("endExcludeAPsSpin")
        self.horizontalLayout.addWidget(self.endExcludeAPsSpin)
        self.verticalLayout.addWidget(self.excludeAPsCheck)
        self.averageAnalysisCheck = QtWidgets.QCheckBox(self.traceDisplayGroup)
        self.averageAnalysisCheck.setMinimumSize(Qt.QSize(0, 20))
        self.averageAnalysisCheck.setChecked(True)
        self.averageAnalysisCheck.setObjectName("averageAnalysisCheck")
        self.verticalLayout.addWidget(self.averageAnalysisCheck)
        self.displayTracesCheck = QtWidgets.QCheckBox(self.traceDisplayGroup)
        self.displayTracesCheck.setMinimumSize(Qt.QSize(0, 20))
        self.displayTracesCheck.setObjectName("displayTracesCheck")
        self.verticalLayout.addWidget(self.displayTracesCheck)
        self.gridLayout_3.addLayout(self.verticalLayout, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 4, 0, 1, 3)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setHorizontalSpacing(0)
        self.gridLayout_8.setVerticalSpacing(2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.averageTimeRadio = QtWidgets.QRadioButton(self.traceDisplayGroup)
        self.averageTimeRadio.setChecked(True)
        self.averageTimeRadio.setObjectName("averageTimeRadio")
        self.gridLayout_8.addWidget(self.averageTimeRadio, 0, 0, 1, 1)
        self.averageTimeSpin = SpinBox(self.traceDisplayGroup)
        self.averageTimeSpin.setObjectName("averageTimeSpin")
        self.gridLayout_8.addWidget(self.averageTimeSpin, 0, 1, 1, 1)
        self.averageNumberRadio = QtWidgets.QRadioButton(self.traceDisplayGroup)
        self.averageNumberRadio.setObjectName("averageNumberRadio")
        self.gridLayout_8.addWidget(self.averageNumberRadio, 1, 0, 1, 1)
        self.averageNumberSpin = SpinBox(self.traceDisplayGroup)
        self.averageNumberSpin.setDecimals(0)
        self.averageNumberSpin.setMaximum(1000.0)
        self.averageNumberSpin.setProperty("value", 5.0)
        self.averageNumberSpin.setObjectName("averageNumberSpin")
        self.gridLayout_8.addWidget(self.averageNumberSpin, 1, 1, 1, 1)
        self.gridLayout_8.setColumnStretch(1, 3)
        self.gridLayout_3.addLayout(self.gridLayout_8, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.traceDisplayGroup, 0, 0, 1, 1)
        self.createBlindSummaryBtn = QtWidgets.QPushButton(Form)
        self.createBlindSummaryBtn.setObjectName("createBlindSummaryBtn")
        self.gridLayout_7.addWidget(self.createBlindSummaryBtn, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(337, 47, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 4, 0, 1, 1)
        self.storeToDBBtn = QtWidgets.QPushButton(Form)
        self.storeToDBBtn.setObjectName("storeToDBBtn")
        self.gridLayout_7.addWidget(self.storeToDBBtn, 3, 0, 1, 1)
        self.analysisGroup = QtWidgets.QGroupBox(Form)
        self.analysisGroup.setObjectName("analysisGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.analysisGroup)
        self.gridLayout_4.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.baselineCheck = QtWidgets.QCheckBox(self.analysisGroup)
        self.baselineCheck.setChecked(True)
        self.baselineCheck.setObjectName("baselineCheck")
        self.gridLayout_4.addWidget(self.baselineCheck, 0, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.analysisGroup)
        self.label.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.baselineStartSpin = SpinBox(self.analysisGroup)
        self.baselineStartSpin.setObjectName("baselineStartSpin")
        self.gridLayout.addWidget(self.baselineStartSpin, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.analysisGroup)
        self.label_2.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.baselineEndSpin = SpinBox(self.analysisGroup)
        self.baselineEndSpin.setObjectName("baselineEndSpin")
        self.gridLayout.addWidget(self.baselineEndSpin, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 3)
        self.pspCheck = QtWidgets.QCheckBox(self.analysisGroup)
        self.pspCheck.setChecked(True)
        self.pspCheck.setObjectName("pspCheck")
        self.gridLayout_4.addWidget(self.pspCheck, 2, 0, 1, 2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.analysisGroup)
        self.label_3.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.pspStartSpin = SpinBox(self.analysisGroup)
        self.pspStartSpin.setObjectName("pspStartSpin")
        self.gridLayout_5.addWidget(self.pspStartSpin, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.analysisGroup)
        self.label_4.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.pspEndSpin = SpinBox(self.analysisGroup)
        self.pspEndSpin.setObjectName("pspEndSpin")
        self.gridLayout_5.addWidget(self.pspEndSpin, 1, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.analysisGroup)
        self.label_7.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.measureModeCombo = ComboBox(self.analysisGroup)
        self.measureModeCombo.setObjectName("measureModeCombo")
        self.gridLayout_5.addWidget(self.measureModeCombo, 2, 1, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_5, 3, 0, 1, 3)
        self.healthCheck = QtWidgets.QCheckBox(self.analysisGroup)
        self.healthCheck.setChecked(True)
        self.healthCheck.setObjectName("healthCheck")
        self.gridLayout_4.addWidget(self.healthCheck, 4, 0, 1, 2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.healthStartSpin = SpinBox(self.analysisGroup)
        self.healthStartSpin.setObjectName("healthStartSpin")
        self.gridLayout_6.addWidget(self.healthStartSpin, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.analysisGroup)
        self.label_6.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.healthEndSpin = SpinBox(self.analysisGroup)
        self.healthEndSpin.setObjectName("healthEndSpin")
        self.gridLayout_6.addWidget(self.healthEndSpin, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.analysisGroup)
        self.label_5.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setColumnStretch(1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_6, 5, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(327, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 6, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.analysisGroup)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 7, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plasticityAdjustChk = QtWidgets.QCheckBox(self.analysisGroup)
        self.plasticityAdjustChk.setObjectName("plasticityAdjustChk")
        self.gridLayout_2.addWidget(self.plasticityAdjustChk, 0, 0, 1, 1)
        self.defaultRgnBtn = QtWidgets.QPushButton(self.analysisGroup)
        self.defaultRgnBtn.setObjectName("defaultRgnBtn")
        self.gridLayout_2.addWidget(self.defaultRgnBtn, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.analysisGroup)
        self.label_11.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.plasticityRgnStartSpin = SpinBox(self.analysisGroup)
        self.plasticityRgnStartSpin.setDecimals(1)
        self.plasticityRgnStartSpin.setProperty("value", 27.0)
        self.plasticityRgnStartSpin.setObjectName("plasticityRgnStartSpin")
        self.gridLayout_2.addWidget(self.plasticityRgnStartSpin, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.analysisGroup)
        self.label_12.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.plasticityRgnEndSpin = SpinBox(self.analysisGroup)
        self.plasticityRgnEndSpin.setDecimals(1)
        self.plasticityRgnEndSpin.setProperty("value", 47.0)
        self.plasticityRgnEndSpin.setObjectName("plasticityRgnEndSpin")
        self.gridLayout_2.addWidget(self.plasticityRgnEndSpin, 2, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_2, 8, 0, 2, 3)
        self.analyzeBtn = QtWidgets.QPushButton(self.analysisGroup)
        self.analyzeBtn.setObjectName("analyzeBtn")
        self.gridLayout_4.addWidget(self.analyzeBtn, 10, 0, 1, 3)
        self.gridLayout_7.addWidget(self.analysisGroup, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 1, 0, 1, 1)
        self.pspStartTimeSpin = SpinBox(self.groupBox)
        self.pspStartTimeSpin.setObjectName("pspStartTimeSpin")
        self.gridLayout_9.addWidget(self.pspStartTimeSpin, 0, 1, 1, 1)
        self.spikePeakSpin = SpinBox(self.groupBox)
        self.spikePeakSpin.setObjectName("spikePeakSpin")
        self.gridLayout_9.addWidget(self.spikePeakSpin, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 2, 0, 1, 1)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.createSummaryBtn.setText(_translate("Form", "Create Summary Sheet"))
        self.traceDisplayGroup.setTitle(_translate("Form", "Trace Display:"))
        self.averageCheck.setText(_translate("Form", "Average traces based on:"))
        self.excludeAPsCheck.setTitle(_translate("Form", "Exclude traces with action potentials"))
        self.label_8.setText(_translate("Form", "between"))
        self.label_9.setText(_translate("Form", "and"))
        self.averageAnalysisCheck.setText(_translate("Form", "Use averaged traces for analysis"))
        self.displayTracesCheck.setText(_translate("Form", "Display original traces (slow)"))
        self.averageTimeRadio.setText(_translate("Form", "Time:"))
        self.averageNumberRadio.setText(_translate("Form", "Number:"))
        self.createBlindSummaryBtn.setText(_translate("Form", "Create Blind Summary Sheet"))
        self.storeToDBBtn.setText(_translate("Form", "Store to Database"))
        self.analysisGroup.setTitle(_translate("Form", "PSP Analysis"))
        self.baselineCheck.setText(_translate("Form", "Baseline Region (green)"))
        self.label.setText(_translate("Form", "Start:"))
        self.label_2.setText(_translate("Form", "End:"))
        self.pspCheck.setText(_translate("Form", "Synaptic Event Region (red)"))
        self.label_3.setText(_translate("Form", "Start:"))
        self.label_4.setText(_translate("Form", "End:"))
        self.label_7.setText(_translate("Form", "Measure:"))
        self.healthCheck.setText(_translate("Form", "Cell Health Region (blue)"))
        self.label_6.setText(_translate("Form", "End:"))
        self.label_5.setText(_translate("Form", "Start:"))
        self.label_10.setText(_translate("Form", "Plasticity Region:"))
        self.plasticityAdjustChk.setText(_translate("Form", "Allow adjustment"))
        self.defaultRgnBtn.setText(_translate("Form", "Default"))
        self.label_11.setText(_translate("Form", "Start:"))
        self.plasticityRgnStartSpin.setSuffix(_translate("Form", " minutes"))
        self.label_12.setText(_translate("Form", "End:"))
        self.plasticityRgnEndSpin.setSuffix(_translate("Form", " minutes"))
        self.analyzeBtn.setText(_translate("Form", "Analyze!"))
        self.groupBox.setTitle(_translate("Form", "Conditioning Analysis"))
        self.label_13.setText(_translate("Form", "PSP Start time:"))
        self.label_14.setText(_translate("Form", "First Spike peak:"))

from acq4.pyqtgraph.widgets.ComboBox import ComboBox
from acq4.pyqtgraph.widgets.SpinBox import SpinBox
