# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PatchTemplate.ui'
#
# Created: Wed Apr  8 23:24:25 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(918, 728)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startBtn = QtGui.QPushButton(self.groupBox_2)
        self.startBtn.setCheckable(True)
        self.startBtn.setObjectName("startBtn")
        self.gridLayout_2.addWidget(self.startBtn, 0, 0, 1, 1)
        self.recordPlot = QtGui.QPushButton(self.groupBox_2)
        self.recordPlot.setCheckable(True)
        self.recordPlot.setObjectName("recordPlot")
        self.gridLayout_2.addWidget(self.recordPlot, 0, 1, 1, 1)
        self.vcModeRadio = QtGui.QRadioButton(self.groupBox_2)
        self.vcModeRadio.setChecked(True)
        self.vcModeRadio.setObjectName("vcModeRadio")
        self.gridLayout_2.addWidget(self.vcModeRadio, 1, 0, 1, 1)
        self.vcPulseCheck = QtGui.QCheckBox(self.groupBox_2)
        self.vcPulseCheck.setChecked(True)
        self.vcPulseCheck.setObjectName("vcPulseCheck")
        self.gridLayout_2.addWidget(self.vcPulseCheck, 1, 1, 1, 1)
        self.vcPulseSpin = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.vcPulseSpin.setMinimum(-100.0)
        self.vcPulseSpin.setMaximum(100.0)
        self.vcPulseSpin.setObjectName("vcPulseSpin")
        self.gridLayout_2.addWidget(self.vcPulseSpin, 1, 2, 1, 1)
        self.pulseLabel = QtGui.QLabel(self.groupBox_2)
        self.pulseLabel.setObjectName("pulseLabel")
        self.gridLayout_2.addWidget(self.pulseLabel, 1, 3, 1, 1)
        self.vcHoldCheck = QtGui.QCheckBox(self.groupBox_2)
        self.vcHoldCheck.setObjectName("vcHoldCheck")
        self.gridLayout_2.addWidget(self.vcHoldCheck, 2, 1, 1, 1)
        self.vcHoldSpin = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.vcHoldSpin.setMinimum(-100.0)
        self.vcHoldSpin.setMaximum(100.0)
        self.vcHoldSpin.setObjectName("vcHoldSpin")
        self.gridLayout_2.addWidget(self.vcHoldSpin, 2, 2, 1, 1)
        self.holdLabel = QtGui.QLabel(self.groupBox_2)
        self.holdLabel.setObjectName("holdLabel")
        self.gridLayout_2.addWidget(self.holdLabel, 2, 3, 1, 1)
        self.icModeRadio = QtGui.QRadioButton(self.groupBox_2)
        self.icModeRadio.setObjectName("icModeRadio")
        self.gridLayout_2.addWidget(self.icModeRadio, 3, 0, 1, 1)
        self.icPulseCheck = QtGui.QCheckBox(self.groupBox_2)
        self.icPulseCheck.setChecked(True)
        self.icPulseCheck.setObjectName("icPulseCheck")
        self.gridLayout_2.addWidget(self.icPulseCheck, 3, 1, 1, 1)
        self.icPulseSpin = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.icPulseSpin.setMinimum(-1000.0)
        self.icPulseSpin.setMaximum(1000.0)
        self.icPulseSpin.setObjectName("icPulseSpin")
        self.gridLayout_2.addWidget(self.icPulseSpin, 3, 2, 1, 1)
        self.pulseLabel_2 = QtGui.QLabel(self.groupBox_2)
        self.pulseLabel_2.setObjectName("pulseLabel_2")
        self.gridLayout_2.addWidget(self.pulseLabel_2, 3, 3, 2, 1)
        self.icHoldCheck = QtGui.QCheckBox(self.groupBox_2)
        self.icHoldCheck.setObjectName("icHoldCheck")
        self.gridLayout_2.addWidget(self.icHoldCheck, 5, 1, 1, 1)
        self.icHoldSpin = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.icHoldSpin.setMinimum(-1000.0)
        self.icHoldSpin.setMaximum(1000.0)
        self.icHoldSpin.setObjectName("icHoldSpin")
        self.gridLayout_2.addWidget(self.icHoldSpin, 4, 2, 2, 1)
        self.holdLabel_2 = QtGui.QLabel(self.groupBox_2)
        self.holdLabel_2.setObjectName("holdLabel_2")
        self.gridLayout_2.addWidget(self.holdLabel_2, 5, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.inputResistanceRadio = QtGui.QRadioButton(self.groupBox)
        self.inputResistanceRadio.setChecked(True)
        self.inputResistanceRadio.setObjectName("inputResistanceRadio")
        self.gridLayout_3.addWidget(self.inputResistanceRadio, 0, 0, 1, 2)
        self.inputResistanceLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.inputResistanceLabel.setFont(font)
        self.inputResistanceLabel.setObjectName("inputResistanceLabel")
        self.gridLayout_3.addWidget(self.inputResistanceLabel, 0, 2, 1, 1)
        self.restingPotentialRadio = QtGui.QRadioButton(self.groupBox)
        self.restingPotentialRadio.setObjectName("restingPotentialRadio")
        self.gridLayout_3.addWidget(self.restingPotentialRadio, 1, 0, 1, 2)
        self.restingPotentialLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.restingPotentialLabel.setFont(font)
        self.restingPotentialLabel.setObjectName("restingPotentialLabel")
        self.gridLayout_3.addWidget(self.restingPotentialLabel, 1, 2, 1, 1)
        self.timeConstantRadio = QtGui.QRadioButton(self.groupBox)
        self.timeConstantRadio.setObjectName("timeConstantRadio")
        self.gridLayout_3.addWidget(self.timeConstantRadio, 2, 0, 1, 2)
        self.timeConstantLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.timeConstantLabel.setFont(font)
        self.timeConstantLabel.setObjectName("timeConstantLabel")
        self.gridLayout_3.addWidget(self.timeConstantLabel, 2, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.averagingSpin = QtGui.QDoubleSpinBox(self.groupBox)
        self.averagingSpin.setObjectName("averagingSpin")
        self.gridLayout_3.addWidget(self.averagingSpin, 3, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.patchPlot = QwtPlot(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.patchPlot.sizePolicy().hasHeightForWidth())
        self.patchPlot.setSizePolicy(sizePolicy)
        self.patchPlot.setObjectName("patchPlot")
        self.verticalLayout_2.addWidget(self.patchPlot)
        self.commandPlot = QwtPlot(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.commandPlot.sizePolicy().hasHeightForWidth())
        self.commandPlot.setSizePolicy(sizePolicy)
        self.commandPlot.setObjectName("commandPlot")
        self.verticalLayout_2.addWidget(self.commandPlot)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.analysisPlot = QwtPlot(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.analysisPlot.sizePolicy().hasHeightForWidth())
        self.analysisPlot.setSizePolicy(sizePolicy)
        self.analysisPlot.setObjectName("analysisPlot")
        self.verticalLayout_3.addWidget(self.analysisPlot)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.startBtn.setText(QtGui.QApplication.translate("Form", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.recordPlot.setText(QtGui.QApplication.translate("Form", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.vcModeRadio.setText(QtGui.QApplication.translate("Form", "VC", None, QtGui.QApplication.UnicodeUTF8))
        self.vcPulseCheck.setText(QtGui.QApplication.translate("Form", "Pulse", None, QtGui.QApplication.UnicodeUTF8))
        self.pulseLabel.setText(QtGui.QApplication.translate("Form", "mV", None, QtGui.QApplication.UnicodeUTF8))
        self.vcHoldCheck.setText(QtGui.QApplication.translate("Form", "Hold", None, QtGui.QApplication.UnicodeUTF8))
        self.holdLabel.setText(QtGui.QApplication.translate("Form", "mV", None, QtGui.QApplication.UnicodeUTF8))
        self.icModeRadio.setText(QtGui.QApplication.translate("Form", "IC", None, QtGui.QApplication.UnicodeUTF8))
        self.icPulseCheck.setText(QtGui.QApplication.translate("Form", "Pulse", None, QtGui.QApplication.UnicodeUTF8))
        self.pulseLabel_2.setText(QtGui.QApplication.translate("Form", "pA", None, QtGui.QApplication.UnicodeUTF8))
        self.icHoldCheck.setText(QtGui.QApplication.translate("Form", "Hold", None, QtGui.QApplication.UnicodeUTF8))
        self.holdLabel_2.setText(QtGui.QApplication.translate("Form", "pA", None, QtGui.QApplication.UnicodeUTF8))
        self.inputResistanceRadio.setText(QtGui.QApplication.translate("Form", "Input Resistance", None, QtGui.QApplication.UnicodeUTF8))
        self.inputResistanceLabel.setText(QtGui.QApplication.translate("Form", "0 MOhm", None, QtGui.QApplication.UnicodeUTF8))
        self.restingPotentialRadio.setText(QtGui.QApplication.translate("Form", "Resting Potential", None, QtGui.QApplication.UnicodeUTF8))
        self.restingPotentialLabel.setText(QtGui.QApplication.translate("Form", "0 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.timeConstantRadio.setText(QtGui.QApplication.translate("Form", "Time constant", None, QtGui.QApplication.UnicodeUTF8))
        self.timeConstantLabel.setText(QtGui.QApplication.translate("Form", "0 ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Averaging:", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4.Qwt5 import QwtPlot
