# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/modules/DataManager/DataManagerTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 756)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.baseDirText = QtWidgets.QLineEdit(self.centralwidget)
        self.baseDirText.setObjectName("baseDirText")
        self.gridLayout.addWidget(self.baseDirText, 0, 1, 1, 1)
        self.selectDirBtn = QtWidgets.QPushButton(self.centralwidget)
        self.selectDirBtn.setObjectName("selectDirBtn")
        self.gridLayout.addWidget(self.selectDirBtn, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.currentDirText = QtWidgets.QLineEdit(self.centralwidget)
        self.currentDirText.setObjectName("currentDirText")
        self.gridLayout.addWidget(self.currentDirText, 1, 1, 1, 1)
        self.setCurrentDirBtn = QtWidgets.QPushButton(self.centralwidget)
        self.setCurrentDirBtn.setObjectName("setCurrentDirBtn")
        self.gridLayout.addWidget(self.setCurrentDirBtn, 1, 2, 1, 1)
        self.logDirText = QtWidgets.QLineEdit(self.centralwidget)
        self.logDirText.setObjectName("logDirText")
        self.gridLayout.addWidget(self.logDirText, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.setLogDirBtn = QtWidgets.QPushButton(self.centralwidget)
        self.setLogDirBtn.setObjectName("setLogDirBtn")
        self.gridLayout.addWidget(self.setLogDirBtn, 2, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(Qt.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newFolderList = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newFolderList.sizePolicy().hasHeightForWidth())
        self.newFolderList.setSizePolicy(sizePolicy)
        self.newFolderList.setObjectName("newFolderList")
        self.verticalLayout_2.addWidget(self.newFolderList)
        self.fileTreeWidget = DirTreeWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTreeWidget.sizePolicy().hasHeightForWidth())
        self.fileTreeWidget.setSizePolicy(sizePolicy)
        self.fileTreeWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.fileTreeWidget.setDragEnabled(True)
        self.fileTreeWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.fileTreeWidget.setObjectName("fileTreeWidget")
        self.fileTreeWidget.headerItem().setText(0, "1")
        self.fileTreeWidget.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.fileTreeWidget)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fileNameLabel = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileNameLabel.sizePolicy().hasHeightForWidth())
        self.fileNameLabel.setSizePolicy(sizePolicy)
        font = Qt.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.fileNameLabel.setFont(font)
        self.fileNameLabel.setText("")
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.verticalLayout_4.addWidget(self.fileNameLabel)
        self.fileDisplayTabs = QtWidgets.QTabWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileDisplayTabs.sizePolicy().hasHeightForWidth())
        self.fileDisplayTabs.setSizePolicy(sizePolicy)
        self.fileDisplayTabs.setObjectName("fileDisplayTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fileInfo = FileInfoView(self.tab)
        self.fileInfo.setObjectName("fileInfo")
        self.verticalLayout_3.addWidget(self.fileInfo)
        self.fileDisplayTabs.addTab(self.tab, "")
        self.logTab = QtWidgets.QWidget()
        self.logTab.setObjectName("logTab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.logTab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fileDisplayTabs.addTab(self.logTab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.dataViewWidget = FileDataView(self.tab_3)
        self.dataViewWidget.setObjectName("dataViewWidget")
        self.verticalLayout_7.addWidget(self.dataViewWidget)
        self.fileDisplayTabs.addTab(self.tab_3, "")
        self.analysisTab = QtWidgets.QWidget()
        self.analysisTab.setObjectName("analysisTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.analysisTab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fileDisplayTabs.addTab(self.analysisTab, "")
        self.verticalLayout_4.addWidget(self.fileDisplayTabs)
        self.verticalLayout_5.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.logDock = QtWidgets.QDockWidget(MainWindow)
        self.logDock.setFloating(False)
        self.logDock.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.logDock.setObjectName("logDock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logView = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.logView.setReadOnly(True)
        self.logView.setObjectName("logView")
        self.verticalLayout.addWidget(self.logView)
        self.logEntryText = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.logEntryText.setObjectName("logEntryText")
        self.verticalLayout.addWidget(self.logEntryText)
        self.logDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.Qt.DockWidgetArea(8), self.logDock)

        self.retranslateUi(MainWindow)
        self.fileDisplayTabs.setCurrentIndex(0)
        Qt.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = Qt.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Manager"))
        self.label_2.setText(_translate("MainWindow", "Top-level Directory:"))
        self.selectDirBtn.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Storage Directory:"))
        self.setCurrentDirBtn.setText(_translate("MainWindow", "Set"))
        self.label_3.setText(_translate("MainWindow", "Log Directory:"))
        self.setLogDirBtn.setText(_translate("MainWindow", "Set"))
        self.fileDisplayTabs.setTabText(self.fileDisplayTabs.indexOf(self.tab), _translate("MainWindow", "Info"))
        self.fileDisplayTabs.setTabText(self.fileDisplayTabs.indexOf(self.logTab), _translate("MainWindow", "Log"))
        self.fileDisplayTabs.setTabText(self.fileDisplayTabs.indexOf(self.tab_3), _translate("MainWindow", "Data"))
        self.fileDisplayTabs.setTabText(self.fileDisplayTabs.indexOf(self.analysisTab), _translate("MainWindow", "Analysis"))
        self.logDock.setWindowTitle(_translate("MainWindow", "Current Log"))

from FileDataView import FileDataView
from FileInfoView import FileInfoView
from acq4.util.DirTreeWidget import DirTreeWidget
