# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/scripts/builder/builderTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(758, 588)
        self.gridLayout_6 = QtWidgets.QGridLayout(Form)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(Qt.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.view = GraphicsView(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view.sizePolicy().hasHeightForWidth())
        self.view.setSizePolicy(sizePolicy)
        self.view.setObjectName("view")
        self.gridLayout_5.addWidget(self.view, 0, 0, 1, 1)
        self.zSlider = QtWidgets.QSlider(self.widget)
        self.zSlider.setOrientation(Qt.Qt.Horizontal)
        self.zSlider.setObjectName("zSlider")
        self.gridLayout_5.addWidget(self.zSlider, 1, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.dorsalRadio = QtWidgets.QRadioButton(self.groupBox)
        self.dorsalRadio.setObjectName("dorsalRadio")
        self.gridLayout.addWidget(self.dorsalRadio, 1, 1, 1, 1)
        self.rostralRadio = QtWidgets.QRadioButton(self.groupBox)
        self.rostralRadio.setObjectName("rostralRadio")
        self.gridLayout.addWidget(self.rostralRadio, 2, 1, 1, 1)
        self.rightRadio = QtWidgets.QRadioButton(self.groupBox)
        self.rightRadio.setChecked(True)
        self.rightRadio.setObjectName("rightRadio")
        self.gridLayout.addWidget(self.rightRadio, 0, 1, 1, 1)
        self.greyCheck = QtWidgets.QCheckBox(self.groupBox)
        self.greyCheck.setObjectName("greyCheck")
        self.gridLayout.addWidget(self.greyCheck, 4, 1, 1, 1)
        self.labelSlider = QtWidgets.QSlider(self.groupBox)
        self.labelSlider.setMaximum(255)
        self.labelSlider.setProperty("value", 50)
        self.labelSlider.setOrientation(Qt.Qt.Horizontal)
        self.labelSlider.setObjectName("labelSlider")
        self.gridLayout.addWidget(self.labelSlider, 6, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 1, 1, 1)
        self.overlayCheck = QtWidgets.QCheckBox(self.groupBox)
        self.overlayCheck.setObjectName("overlayCheck")
        self.gridLayout.addWidget(self.overlayCheck, 5, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.radiusSpin = QtWidgets.QSpinBox(self.groupBox_3)
        self.radiusSpin.setMinimum(1)
        self.radiusSpin.setObjectName("radiusSpin")
        self.gridLayout_3.addWidget(self.radiusSpin, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.labelSpin = QtWidgets.QSpinBox(self.groupBox_3)
        self.labelSpin.setMinimum(0)
        self.labelSpin.setMaximum(15)
        self.labelSpin.setProperty("value", 0)
        self.labelSpin.setObjectName("labelSpin")
        self.gridLayout_3.addWidget(self.labelSpin, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelTree = TreeWidget(self.groupBox_2)
        self.labelTree.setRootIsDecorated(False)
        self.labelTree.setItemsExpandable(False)
        self.labelTree.setExpandsOnDoubleClick(False)
        self.labelTree.setObjectName("labelTree")
        self.labelTree.headerItem().setText(1, "name")
        self.labelTree.header().setDefaultSectionSize(100)
        self.gridLayout_2.addWidget(self.labelTree, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.gridLayout_6.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "View"))
        self.dorsalRadio.setText(_translate("Form", "Dorsal"))
        self.rostralRadio.setText(_translate("Form", "Rostral"))
        self.rightRadio.setText(_translate("Form", "Right"))
        self.greyCheck.setText(_translate("Form", "Greyscale"))
        self.overlayCheck.setText(_translate("Form", "Overlay"))
        self.groupBox_3.setTitle(_translate("Form", "Drawing"))
        self.label.setText(_translate("Form", "Radius"))
        self.label_2.setText(_translate("Form", "Label"))
        self.groupBox_2.setTitle(_translate("Form", "Labels"))
        self.labelTree.headerItem().setText(0, _translate("Form", "color"))
        self.labelTree.headerItem().setText(2, _translate("Form", "id"))

from acq4.pyqtgraph import GraphicsView, TreeWidget
