from __future__ import annotations

import collections

import numpy as np

import pyqtgraph as pg
from acq4.Interfaces import InterfaceMixin
from acq4.modules.Visualize3D import Visualize3D
from acq4.util import Qt
from acq4.util.Mutex import Mutex
from acq4.util.geometry import Plane, Geometry, load_transform_from_anything
from coorx import SRT3DTransform, Transform
from pyqtgraph import opengl as gl
from pyqtgraph.parametertree import Parameter


def map_through_transform(
    obj: tuple | list | Qt.QPointF | Qt.QVector3D | np.ndarray, tr: Transform
):
    """Map an object through a transform."""
    if not isinstance(tr, Transform):
        raise TypeError(f"Transform must be a coorx Transform, not {type(tr)}")

    # handle special types
    if isinstance(obj, Qt.QPointF):
        return tr.map([obj.x(), obj.y()])
    elif isinstance(obj, Qt.QVector3D):
        return tr.map([obj.x(), obj.y(), obj.z()])
    elif isinstance(obj[0], (Qt.QPointF, Qt.QVector3D)):
        return [map_through_transform(o, tr) for o in obj]

    return tr.map(obj)


class OptomechDevice(InterfaceMixin):
    """
    OptomechDevice is a mixin to the Device class that manages coordinate system mapping between
    rigidly-connected optomechanical devices. For example: movable stages, micromanipulators, changeable
    objective lenses, and imaging/stimulation devices are all considered optomechanical devices.

    These devices are organized hierarchically with each optionally having a parent device and multiple child
    devices. Each device defines its own coordinate transformation that maps from its own local coordinate system
    into its parent's coordinate system.

    This organization makes it simple to map coordinates between devices and the global coordinate system.
    This allows, for example, asking what is the physical location corresponding to a specific pixel in a
    camera image or asking what set of mirror voltages to use in order to stimulate a specific
    physical location.

    In most cases, the transformation will be in the form of an affine matrix multiplication.
    Devices are free, however, to define an arbitrary transformation as well using custom subclasses of
    coorx.Transform.

    Devices may also have selectable sub-devices, providing a set of interchangeable transforms.
    For example, a microscope with multiple objectives may define one sub-device per objective.
    This does not affect the hierarchy of devices, but instead simply affects the way the microscope
    device reports its transformation. Furthermore, it is recommended to use information about the currently
    selected set of subdevices when storing and loading device calibration data (for example,
    a scanner device may store one calibration per objective).

    Example device hierarchy:

        <global coordinate system>
                  |
            [Motorized Stage]
                  |
         [Microscope focus drive]
                  |
         [Microscope objectives] ---- subdevices: [ 5x objective ], [ 63x objective ]
          |       |       |
       [Camera]   |    [Laser] (per-objective power calibration)
                  |
            [Scan Mirrors]
             (per-objective voltage calibration)

    Optomechanical devices may also provide information about their optical filtering characteristics.
    This makes it possible for any device in the system to receive a list of filters that stand between
    itself and the sample. For example:

        <global coordinate system>
                |
            [Microscope]
                |
            [Dichroic]--[Excitation filter]--[Light source]
                |
            [Emission filter]
                |
             [Camera]

    In the example above, images generated by the camera are automatically annotated with information
    about the filters in place between the camera and the sample, as well as the filters in the
    illumination path.
    """

    # these signals are proxied from the OptomechDevice object
    # we do this to avoid QObject double-inheritance issues.
    class SignalProxyObject(Qt.QObject):
        # emitted when this device's transform changes
        sigTransformChanged = Qt.Signal(object)  # self
        # emitted when the transform for this device or any of its parents changes
        sigGlobalTransformChanged = Qt.Signal(object, object)  # self, changed device

        # Emitted when the transform of a subdevice has changed
        sigSubdeviceTransformChanged = Qt.Signal(object, object)  # self, subdev
        # Emitted when the transform of a subdevice or any (grand)parent's subdevice has changed
        sigGlobalSubdeviceTransformChanged = Qt.Signal(object, object, object)  # self, dev, subdev

        # Emitted when this device's optics change
        sigOpticsChanged = Qt.Signal(object, object)  # self, port
        # Emitted when the optics for this device or any of its parents changes
        sigGlobalOpticsChanged = Qt.Signal(object, object, object)  # self, changed device, port

        # Emitted when this device changes its current subdevice
        sigSubdeviceChanged = Qt.Signal(object, object, object)  # self, new subdev, old subdev
        # Emitted when this device or any (grand)parent changes its current subdevice
        sigGlobalSubdeviceChanged = Qt.Signal(
            object, object, object, object
        )  # self, dev, new subdev, old subdev

        # Emitted when this device changes its list of available subdevices
        sigSubdeviceListChanged = Qt.Signal(object)  # self
        # Emitted when this device or any (grand)parent changes its list of available subdevices
        sigGlobalSubdeviceListChanged = Qt.Signal(object, object)  # self, dev

        sigGeometryChanged = Qt.Signal(object)  # self

    def __init__(self, dm, config, name):
        object.__init__(self)

        # create proxy object and wrap in its signals
        self.__sigProxy = OptomechDevice.SignalProxyObject()
        self.sigTransformChanged = self.__sigProxy.sigTransformChanged
        self.sigGlobalTransformChanged = self.__sigProxy.sigGlobalTransformChanged
        self.sigSubdeviceTransformChanged = self.__sigProxy.sigSubdeviceTransformChanged
        self.sigGlobalSubdeviceTransformChanged = self.__sigProxy.sigGlobalSubdeviceTransformChanged
        self.sigOpticsChanged = self.__sigProxy.sigOpticsChanged
        self.sigGlobalOpticsChanged = self.__sigProxy.sigGlobalOpticsChanged
        self.sigSubdeviceChanged = self.__sigProxy.sigSubdeviceChanged
        self.sigGlobalSubdeviceChanged = self.__sigProxy.sigGlobalSubdeviceChanged
        self.sigSubdeviceListChanged = self.__sigProxy.sigSubdeviceListChanged
        self.sigGlobalSubdeviceListChanged = self.__sigProxy.sigGlobalSubdeviceListChanged
        self.sigGeometryChanged = self.__sigProxy.sigGeometryChanged

        # Redundant: Device also saves these
        self.__devManager = dm
        self.__config = config
        self.__name = name

        # __ports is a list of port names to which devices may be attached.
        # Most devices will have a single port called 'default' to which all children attach.
        # In some cases, the device has a specific set of named ports where children
        # can be attached (eg: a dichroic filter cube might have "excitation" and "emission" ports).
        self.__ports = []

        # All devices have 0 or 1 parent
        self.__parent = None
        # When connected to a parent device, we also optionally specify *where* on
        # the device to connect (usually this is just 'default').
        self.__parentPort = None

        # keep track of children so that we can inform them quickly when a parent transform has changed
        self.__children = []

        # and might not be cacheable.
        # Transformation from this device to its parent (or to global if there is no parent)
        self.__transform: SRT3DTransform = SRT3DTransform(dims=(3, 3))
        # None indicates the cache is invalid
        self.__globalTransform: None | Transform = None
        self.__globalPhysicalTransform: None | Transform = None

        # Contains {port: [list of optics]} describing the optics (usually filters) for each port
        self.__optics = {}

        # Swappable sub-devices. (eg: objective changers, filter wheels)
        self.__subdevices = collections.OrderedDict()
        self.__subdevice = None

        self.__lock = Mutex(recursive=True, debug=False)

        self.sigTransformChanged.connect(
            self.__emitGlobalTransformChanged, type=Qt.Qt.DirectConnection
        )
        self.sigSubdeviceTransformChanged.connect(
            self.__emitGlobalSubdeviceTransformChanged, type=Qt.Qt.DirectConnection
        )
        self.sigOpticsChanged.connect(self.__emitGlobalOpticsChanged, type=Qt.Qt.DirectConnection)
        self.sigSubdeviceChanged.connect(
            self.__emitGlobalSubdeviceChanged, type=Qt.Qt.DirectConnection
        )
        self.sigSubdeviceListChanged.connect(
            self.__emitGlobalSubdeviceListChanged, type=Qt.Qt.DirectConnection
        )

        if config is not None:
            if "parentDevice" in config:
                try:
                    parent = config["parentDevice"]
                    if isinstance(parent, str):
                        self.setParentDevice(parent)
                    elif isinstance(parent, dict) and "name" in parent:
                        self.setParentDevice(parent["name"], port=parent.get("port", "default"))
                    else:
                        raise TypeError(f"Invalid parent device specification: {parent!r}")

                except Exception as ex:
                    if "No device named" not in ex.args[0]:
                        raise
                    print(
                        f"Cannot set parent device {config['parentDevice']!r}; no device by that name."
                    )
                    print("Available devices:", dm.listDevices())
            if "transform" in config:
                self.setDeviceTransform(config["transform"])

            self.__ports = config.get("ports", ["default"])
            assert isinstance(self.__ports, list)
            self.__optics = config.get("optics", {"default": []})
            assert isinstance(self.__optics, dict)

        # declare that this device supports the OptomechDevice API
        self.addInterface("OptomechDevice")
        self.addInterface(Visualize3D.interfaceName)
        dm.declareInterface(name, ["OptomechDevice", Visualize3D.interfaceName], self)

    def visualize3DAdapter(self, win):
        return OptomechDeviceVisualizerAdapter(self, win)

    def getGeometry(self, name=None) -> Geometry | None:
        if "geometry" in self.__config:
            name = self.geometryCacheKey if name is None else name
            return Geometry(
                config=self.__config["geometry"],
                name=f"[primary geometry of {name}]",
                parent_name=name,
            )
        return None

    @property
    def geometryCacheKey(self) -> str:
        key = self.getDeviceStateKey()
        if key:
            return str(key)
        return self.name()

    def getBoundaries(self):
        return []

    def getLimits(self):
        return []

    def name(self):
        return self.__name

    def ports(self):
        """Return a list of the names of ports to which children may be attached."""
        return self.__ports[:]

    def parentDevice(self) -> "OptomechDevice | None":
        """Return this device's parent, or None if there is no parent."""
        return self.__parent

    def parentPort(self):
        """Return the port on this device's parent to which this device is attached."""
        return self.__parentPort

    def setParentDevice(self, parent: "str | OptomechDevice", port="default"):
        """Set the parent of this device.

        If *parent* is None, then the device has no parent and its transform is assumed to
        be relative to the global coordinate system.

        If *port* is specified, then the device is attached to a named port on the
        parent device.
        """
        with self.__lock:
            # disconnect from previous parent if needed
            if self.__parent is not None:
                self.__parent.sigGlobalTransformChanged.disconnect(
                    self.__parentDeviceTransformChanged
                )
                self.__parent.sigGlobalSubdeviceTransformChanged.disconnect(
                    self.__parentSubdeviceTransformChanged
                )
                self.__parent.sigGlobalOpticsChanged.disconnect(self.__parentOpticsChanged)
                self.__parent.sigGlobalSubdeviceChanged.disconnect(self.__parentSubdeviceChanged)
                self.__parent.sigGlobalSubdeviceListChanged.disconnect(
                    self.__parentSubdeviceListChanged
                )
                self.__parent.__children.remove(self)

            # look up device from its name
            if isinstance(parent, str):
                parent = self.__devManager.getDevice(parent)

            # connect to the new parent
            self.__parent = None
            self.__parentPort = None
            if parent is None:
                return

            if port not in parent.ports():
                raise ValueError(
                    "Cannot connect to port %r on device %r; available ports are: %r"
                    % (port, parent, parent.ports())
                )

            parent.sigGlobalTransformChanged.connect(
                self.__parentDeviceTransformChanged, type=Qt.Qt.DirectConnection
            )
            parent.sigGlobalSubdeviceTransformChanged.connect(
                self.__parentSubdeviceTransformChanged, type=Qt.Qt.DirectConnection
            )
            parent.sigGlobalOpticsChanged.connect(
                self.__parentOpticsChanged, type=Qt.Qt.DirectConnection
            )
            parent.sigGlobalSubdeviceChanged.connect(
                self.__parentSubdeviceChanged, type=Qt.Qt.DirectConnection
            )
            parent.sigGlobalSubdeviceListChanged.connect(
                self.__parentSubdeviceListChanged, type=Qt.Qt.DirectConnection
            )
            parent.__children.append(self)
            self.__parent = parent
            self.__parentPort = port

    def mapToParentDevice(self, obj, subdev=None):
        """Map from local coordinates to the parent device (or to global if there is no parent)"""
        tr = self.deviceTransform(subdev)
        return map_through_transform(obj, tr)

    def mapToGlobal(self, obj, subdev=None):
        """Map *obj* from local coordinates to global."""
        tr = self.globalTransform(subdev)
        return map_through_transform(obj, tr)

    def mapToDevice(self, device, obj, subdev=None):
        """Map *obj* from local coordinates to *device*'s coordinate system."""
        subdev = self._subdevDict(subdev)
        return device.mapFromGlobal(self.mapToGlobal(obj, subdev), subdev)

    def mapFromParentDevice(self, obj, subdev=None):
        """Map *obj* from parent coordinates (or from global if there is no parent) to local coordinates."""
        tr = self.inverseDeviceTransform(subdev)
        return map_through_transform(obj, tr)

    def mapFromGlobal(self, obj, subdev=None):
        """Map *obj* from global to local coordinates."""
        tr = self.inverseGlobalTransform(subdev)
        return map_through_transform(obj, tr)

    def mapGlobalToParent(self, obj, subdev=None):
        """Map *obj* from global coordinates to the parent device coordinates.
        If this device has no parent, then *obj* is returned unchanged.
        """
        if self.parentDevice() is None:
            return obj
        else:
            return self.parentDevice().mapFromGlobal(obj, subdev)

    def mapParentToGlobal(self, obj, subdev=None):
        """Map *obj* from parent device coordinates to global coordinates.
        If this device has no parent, then *obj* is returned unchanged.
        """
        if self.parentDevice() is None:
            return obj
        else:
            return self.parentDevice().mapToGlobal(obj, subdev)

    def deviceTransform(self, subdev=None):
        """
        Return this device's affine transformation matrix.
        This matrix maps from the device's local coordinate system to the parent device's coordinate system
        (or to the global coordinate system, if there is no parent device)
        If no such matrix exists, return None instead. (this indicates that the device's
        transformation is non-affine, and thus the mapTo/mapFrom methods must be used instead.)

        If the device has sub-devices, then this function will account for the current
        sub-device when computing the transform.
        If *subdev* is given, then the transform is computed with that subdevice instead.
        *subdev* may be the name of the device or the device itself.
        """
        with self.__lock:
            tr = self.__transform

            # if a subdevice is specified, multiply by the subdevice's transform before returning
            dev = self.getSubdevice(subdev)
            if dev is not None:
                return tr * dev.deviceTransform()
            return tr

    def inverseDeviceTransform(self, subdev=None):
        """
        See deviceTransform; this method returns the inverse.
        """
        return self.deviceTransform(subdev).inverse

    def setDeviceTransform(self, tr):
        tr = load_transform_from_anything(tr)
        with self.__lock:
            self.__transform = tr
            self.invalidateCachedTransforms()

        self.sigTransformChanged.emit(self)

    def globalTransform(self, subdev=None) -> SRT3DTransform | None:
        """
        Return the transform mapping from local device coordinates to global coordinates.

        If *subdev* is given, it must be a dictionary of {deviceName: subdevice} or
        {deviceName: subdeviceName} pairs specifying the state to compute.
        """
        if subdev is not None:
            return self.__computeGlobalTransform(subdev)
        if self.__globalTransform is None:
            self.__globalTransform = self.__computeGlobalTransform()
        return self.__globalTransform

    def __computeGlobalTransform(self, subdev: dict | None = None):
        parent = self.parentDevice()
        if parent is None:
            return self.deviceTransform(subdev)
        return parent.globalTransform(subdev) * self.deviceTransform(subdev)

    def inverseGlobalTransform(self, subdev=None):
        """
        See globalTransform; this method returns the inverse.
        """
        return self.globalTransform(subdev).inverse

    def physicalTransform(self, subdev=None):
        """
        Return the transform mapping from local device coordinates to parent physical coordinates,
        much the same as deviceTransform. Override this if your device can distinguish optical
        transformations from physical ones.
        """
        return self.deviceTransform(subdev)

    def inversePhysicalTransform(self, subdev=None):
        """
        See physicalTransform; this method returns the inverse.
        """
        return self.physicalTransform(subdev).inverse

    def globalPhysicalTransform(self, subdev=None):
        """
        Return the transform mapping from local device coordinates to global physical coordinates.
        This is the same as globalTransform, except that the transform is not affected by the
        optical properties of any devices in the hierarchy.
        """
        if subdev is not None:
            return self.__computeGlobalPhysicalTransform(subdev)
        if self.__globalPhysicalTransform is None:
            self.__globalPhysicalTransform = self.__computeGlobalPhysicalTransform()
        return self.__globalPhysicalTransform

    def inverseGlobalPhysicalTransform(self, subdev=None):
        """
        See globalPhysicalTransform; this method returns the inverse.
        """
        return self.globalPhysicalTransform(subdev).inverse

    def __computeGlobalPhysicalTransform(self, subdev=None):
        parent = self.parentDevice()
        if parent is None:
            return self.physicalTransform(subdev)

        return parent.globalPhysicalTransform(subdev) * self.physicalTransform(subdev)

    def listOptics(self, port="default"):
        """Return a list of Optics this device adds to the optical
        path from its children to its parent, in physical order.

        If *port* is given, then optics are listed for the specified
        attachment port (eg: 'excitation' or 'emission' for dichroic devices).
        """
        optics = self.__optics.get(port, [])[:]

        # Add in optics from current subdevice. This allows swappable filter configurations.
        dev = self.getSubdevice()
        if dev is not None:
            optics = optics + dev.listOptics(port)
        return optics

    def setOptics(self, optics, port="default"):
        """Set this device's list of optics for the specified port."""
        self.__optics[port] = optics
        self.sigOpticsChanged.emit(self, port)

    def listGlobalOptics(self):
        """Return a list of all optics in the path from this device to the sample."""
        optics = []
        dev = self
        while True:
            parent = dev.parentDevice()
            if parent is None:
                break
            parentPort = dev.parentPort()
            optics += parent.listOptics(parentPort)
            dev = parent

        return optics

    def __emitGlobalTransformChanged(self):
        self.sigGlobalTransformChanged.emit(self, self)

    def __emitGlobalSubdeviceTransformChanged(self, sender, subdev):
        self.sigGlobalSubdeviceTransformChanged.emit(self, self, subdev)

    def __emitGlobalOpticsChanged(self, sender, port):
        self.sigGlobalOpticsChanged.emit(self, sender, port)

    def __emitGlobalSubdeviceChanged(self, sender, newDev, oldDev):
        self.sigGlobalSubdeviceChanged.emit(self, sender, newDev, oldDev)

    def __emitGlobalSubdeviceListChanged(self, device):
        self.sigGlobalSubdeviceListChanged.emit(self, device)

    def __parentDeviceTransformChanged(self, sender, changed):
        # called when any (grand)parent's transform has changed.
        self.invalidateCachedTransforms()
        self.sigGlobalTransformChanged.emit(self, changed)

    def __parentSubdeviceTransformChanged(self, sender, parent, subdev):
        # called when any (grand)parent's subdevice transform has changed.
        self.invalidateCachedTransforms()
        self.sigGlobalSubdeviceTransformChanged.emit(self, parent, subdev)

    def __parentOpticsChanged(self, sender, device, port):
        # called when any (grand)parent's optics have changed
        self.sigGlobalOpticsChanged.emit(self, device, port)

    def __parentSubdeviceChanged(self, sender, parent, newDev, oldDev):
        # called when any (grand)parent's current subdevice has changed.
        self.invalidateCachedTransforms()
        self.sigGlobalSubdeviceChanged.emit(self, parent, newDev, oldDev)

    def __parentSubdeviceListChanged(self, sender, device):
        # called when any (grand)parent's subdevice list has changed.
        self.sigGlobalSubdeviceListChanged.emit(self, device)

    def __subdeviceTransformChanged(self, subdev):
        self.invalidateCachedTransforms()
        self.sigTransformChanged.emit(self)
        self.sigSubdeviceTransformChanged.emit(self, subdev)

    def __subdeviceOpticsChanged(self, subdev, port):
        self.sigOpticsChanged.emit(self, port)

    def parentDevices(self):
        """
        Return a list of this device and its parent devices in hierarchical order:
        [self, parent, grandparent, ...]
        """
        parents = [self]
        p = self
        while True:
            p = p.parentDevice()
            if p is None:
                break
            parents.append(p)
        return parents

    def invalidateCachedTransforms(self, invalidateLocal=True):
        with self.__lock:
            self.__globalTransform = None
            self.__globalPhysicalTransform = None

        # child global transforms must also be invalidated before any change signals are emitted
        for ch in self.__children:
            ch.invalidateCachedTransforms(invalidateLocal=False)

    def addSubdevice(self, subdev):
        subdev.setParentDevice(self)
        self.invalidateCachedTransforms()
        subdev.sigTransformChanged.connect(
            self.__subdeviceTransformChanged, type=Qt.Qt.DirectConnection
        )
        subdev.sigOpticsChanged.connect(self.__subdeviceOpticsChanged, type=Qt.Qt.DirectConnection)
        with self.__lock:
            self.__subdevices[subdev.name()] = subdev
            if self.__subdevice is None:
                self.setCurrentSubdevice(subdev)
        self.sigSubdeviceListChanged.emit(self)

    def removeSubdevice(self, subdev):
        self.invalidateCachedTransforms()
        subdev = self.getSubdevice(subdev)
        subdev.sigTransformChanged.disconnect(self.__subdeviceTransformChanged)
        subdev.sigOpticsChanged.disconnect(self.__subdeviceOpticsChanged)
        with self.__lock:
            del self.__subdevices[subdev.name()]
            if len(self.__subdevices) == 0:
                self.setCurrentSubdevice(None)
        self.sigSubdeviceListChanged.emit(self)

    def listSubdevices(self):
        with self.__lock:
            return list(self.__subdevices.values())

    def getSubdevice(self, dev=None):
        """
        Return a subdevice.
        If *dev* is None return the current subdevice. (If there is no current subdevice, return None)
        If *dev* is a subdevice name, return the named device
        """
        with self.__lock:
            if isinstance(dev, dict):
                dev = dev.get(self.name(), None)

            if dev is None:
                dev = self.__subdevice

            if dev is None:
                return None
            elif hasattr(dev, "implements") and dev.implements("OptomechDevice"):
                return dev
            elif isinstance(dev, str):
                return self.__subdevices[dev]
            else:
                raise TypeError(f"Invalid argument: {dev}")

    def _subdevDict(self, dev):
        # Convert a variety of argument types to a
        # dictionary {devName: subdevName}
        if isinstance(dev, dict):
            return dev
        if dev is None:
            dev = self.__subdevice
            return {self.name(): dev}
        if isinstance(dev, str):
            return {self.name(): self.__subdevices[dev]}

    def setCurrentSubdevice(self, dev):
        self.invalidateCachedTransforms()
        with self.__lock:
            oldDev = self.__subdevice
            if dev is None:
                self.__subdevice = None
            else:
                dev = self.getSubdevice(dev)
                self.__subdevice = dev
        self.sigSubdeviceChanged.emit(self, dev, oldDev)
        self.sigTransformChanged.emit(self)

    def treeSubdeviceState(self):
        """return an ordered dict of {devName: subdevName} pairs indicating the currently
        selected subdevices throughout the tree."""
        devices = [self] + self.parentDevices()
        subdevs = collections.OrderedDict()
        for dev in devices:
            subdev = dev.getSubdevice()
            if subdev is not None:
                subdevs[dev.name()] = subdev.name()
        return subdevs

    def listTreeSubdevices(self):
        """return a dict of {device: [subdev1, ...]} pairs listing
        all available subdevices in the tree."""
        devices = [self] + self.parentDevices()
        subdevs = collections.OrderedDict()
        for dev in devices:
            subdev = dev.listSubdevices()
            if len(subdev) > 0:
                subdevs[dev] = subdev
        return subdevs

    def getDeviceStateKey(self) -> tuple[str, ...]:
        """
        Return a tuple that uniquely identifies the state of all subdevice selections in the system.
        This may be used as a key for storing/retrieving calibration data.
        """
        state = self.treeSubdeviceState()
        devs = sorted(state.keys())
        return tuple(f"{dev}__{state[dev]}" for dev in devs)

    def getFocusDepth(self):
        """Return the Z position of this device's origin, mapped to the global coordinate system."""
        return self.mapToGlobal([0, 0, 0])[2]

    def setFocusDepth(self, depth, speed="slow"):
        """Set microscope focus such that this device's origin is moved to the specified global Z position."""
        dev = self.getFocusDevice()
        if dev is None:
            raise ValueError(f"Device {dev} is not connected to a focus controller.")
        dz = depth - self.getFocusDepth()
        dpos = dev.globalPosition()
        return dev.moveToGlobal([dpos[0], dpos[1], dpos[2] + dz], speed)

    def getFocusDevice(self):
        """Return the device that provides focus capabilities for this device."""
        dev = self.parentDevice()
        from .Stage import Stage

        while dev is not None:
            if isinstance(dev, Stage) and dev.capabilities()["setPos"][2]:
                return dev
            dev = dev.parentDevice()
        return None


class DeviceTreeItemGroup(pg.ItemGroup):
    """
    Extension of QGraphicsItemGroup that maintains a hierarchy of item groups
    with transforms taken from their associated devices.

    This makes it simpler to display graphics that are automatically positioned and scaled relative to
    devices.
    """

    def __init__(self, device, includeSubdevices=True):
        """
        *item* must be a OptomechDevice instance. For the device and each
        of its (grand)parent devices, at least one item group
        will be created which automatically tracks the transform
        of its device. By default, any devices which have subdevices
        will have one item group per subdevice.
        """
        pg.ItemGroup.__init__(self)
        self.groups = {}  # {device: {subdevice: items}}
        self.device = device
        self.includeSubdevs = includeSubdevices
        self.topItem = None

        device.sigGlobalTransformChanged.connect(self.transformChanged)
        device.sigGlobalSubdeviceTransformChanged.connect(self.subdevTransformChanged)
        device.sigGlobalSubdeviceChanged.connect(self.subdevChanged)
        device.sigGlobalSubdeviceListChanged.connect(self.subdevListChanged)
        self.rebuildGroups()

    def makeGroup(self, dev, subdev):
        """Construct a QGraphicsItemGroup for the specified device/subdevice.
        This is a good method to extend in subclasses."""
        newGroup = Qt.QGraphicsItemGroup()
        newGroup.setTransform(dev.deviceTransform(subdev).as_pyqtgraph().as2D())
        return newGroup

    def transformChanged(self, sender, device):
        for subdev, items in self.groups[device].items():
            tr = device.deviceTransform(subdev).as_pyqtgraph().as2D()
            for item in items:
                item.setTransform(tr)

    def subdevTransformChanged(self, sender, device, subdev):
        tr = device.deviceTransform(subdev).as_pyqtgraph().as2D()
        for item in self.groups[device][subdev]:
            item.setTransform(tr)

    def subdevChanged(self, sender, device, newSubdev, oldSubdev):
        pass

    def subdevListChanged(self, sender, device):
        self.rebuildGroups()

    # def removeGroups(self, device, subdev, parentGroup=None):
    #     rem = []
    #     for group in self.groups[device][subdev]:
    #         if parentGroup is None or group.parentItem() is parentGroup:
    #             rem.append(group)
    #             for child in device.childDevices():
    #                 if child in self.groups:
    #                     self.removeGroups(child, subdev=None, parentGroup=group)
    #     for group in rem:
    #         self.groups[device][subdev].remove(group)
    #         scene = group.scene()
    #         if scene is not None:
    #             scene.removeItem(group)

    def rebuildGroups(self):
        """Create the tree of graphics items needed to display camera boundaries"""
        if self.topItem is not None:
            scene = self.topItem.scene()
            if scene is not None:
                scene.removeItem(self.topItem)
                self.topItem = None
        self.groups = {}

        devices = self.device.parentDevices()
        parentItems = [self]
        for dev in devices[::-1]:
            self.groups[dev] = {}
            subdevs = dev.listSubdevices()
            if len(subdevs) == 0:
                subdevs = [None]
            newItems = []
            for subdev in subdevs:
                # create one new group per parent group
                self.groups[dev][subdev] = []

                for parent in parentItems:
                    newGroup = self.makeGroup(dev, subdev)
                    self.groups[dev][subdev].append(newGroup)
                    newItems.append(newGroup)
                    newGroup.setParentItem(parent)
                    if parent is self:
                        self.topItem = newGroup

            parentItems = newItems

    def getGroups(self, device):
        """Return a list of all item groups for the given device"""
        groups = []
        for subdev, items in self.groups[device].items():
            groups.extend(items)
        return groups


class OptomechDeviceVisualizerAdapter:
    def __init__(self, dev: OptomechDevice, win: "VisualizerWindow"):
        self.device = dev
        self.win = win
        self._param = None
        self._limits = None
        self._mesh = None

        dev.sigGeometryChanged.connect(self.handleGeometryChange)
        self._geometry = dev.getGeometry()
        if self._geometry is None:
            return

        self._mesh = self._geometry.glMesh()

        # Add geometry to the scene
        self.win.add3DItem(self._mesh)
        dev.sigGlobalTransformChanged.connect(self.handleTransformUpdate)
        self.handleTransformUpdate(dev, dev)

        if limits := dev.getLimits():
            self._limits = self.drawBoundaries(limits, dev.globalTransform())

        self._param = self._buildControlParam()
        self.win.addControls(self._param)

    def _buildControlParam(self):
        children = [
            dict(name='Geometry', type='bool', value=True),
        ]
        if self._limits is not None:
            children.append(dict(name='Range of Motion', type='bool', value=False))

        param = Parameter.create(name=self.device.name(), type='bool', value=True, children=children)
        param.sigValueChanged.connect(self._handleDeviceToggle)
        param.child('Geometry').sigValueChanged.connect(self._handleGeometryVisible)
        if self._limits is not None:
            param.child('Range of Motion').sigValueChanged.connect(self._handleLimitsVisible)
        return param

    def _handleDeviceToggle(self, param, value):
        for child in param.children():
            child.setOpts(enabled=value)
        self._updateMeshVisibility()
        self._updateLimitsVisibility()

    def _handleGeometryVisible(self, param, value):
        self._updateMeshVisibility()

    def _handleLimitsVisible(self, param, value):
        self._updateLimitsVisibility()

    def _updateMeshVisibility(self):
        if self._mesh is None or self._param is None:
            return
        self._mesh.setVisible(
            self._param.value() and self._param.child('Geometry').value()
        )

    def _updateLimitsVisibility(self):
        if self._limits is None or self._param is None:
            return
        try:
            limits_on = self._param.child('Range of Motion').value()
        except KeyError:
            return
        self._limits.setVisible(self._param.value() and limits_on)

    def handleTransformUpdate(self, moved_device: "OptomechDevice", cause_device: "OptomechDevice"):
        geom = self._geometry
        if geom is None:
            return
        xform = moved_device.globalPhysicalTransform() * geom.transform
        self.setMeshTransform(moved_device, xform.as_pyqtgraph())

    def handleGeometryChange(self, dev: "OptomechDevice"):
        if self._mesh is not None:
            self.win.remove3DItem(self._mesh)
        self._mesh = None

        self._geometry = dev.getGeometry()
        if self._geometry is not None:
            self._mesh = self._geometry.glMesh()
            self.win.add3DItem(self._mesh)
            self._updateMeshVisibility()
            self.handleTransformUpdate(dev, dev)

    def setMeshTransform(self, dev, xform):
        self._mesh.setTransform(xform)

    def drawBoundaries(self, limits, local_to_global):
        edges = set()
        ndim = len(limits)
        vertices = list(np.ndindex(tuple([2] * ndim)))
        vertices = [tuple(limits[i][v] for i, v in enumerate(vertex)) for vertex in vertices]
        # find every edge between vertices that differ in exactly one coordinate
        for v1 in vertices:
            for v2 in vertices:
                if sum(a != b for a, b in zip(v1, v2)) == 1:
                    # dedup by sorting
                    edge = tuple(sorted((v1, v2)))
                    edges.add(edge)
        edges = [local_to_global.map(v) for edge in edges for v in edge]
        plot = gl.GLLinePlotItem(pos=np.array(edges), color=(1, 0, 0, 0.2), width=4, mode="lines")
        plot.setVisible(False)
        self.win.add3DItem(plot)
        return plot

    def clear(self):
        if self._mesh is not None:
            self.win.remove3DItem(self._mesh)
            self._mesh = None
        if self._limits is not None:
            self.win.remove3DItem(self._limits)
            self._limits = None
        if self._param is not None:
            self.win.removeControls(self._param)
            self._param = None
