# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/devices/Laser/taskTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(218, 190)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.outputPowerLabel = QtWidgets.QLabel(Form)
        self.outputPowerLabel.setObjectName("outputPowerLabel")
        self.gridLayout_2.addWidget(self.outputPowerLabel, 0, 1, 1, 1)
        self.checkPowerBtn = QtWidgets.QPushButton(Form)
        self.checkPowerBtn.setObjectName("checkPowerBtn")
        self.gridLayout_2.addWidget(self.checkPowerBtn, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        font = Qt.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.samplePowerLabel = QtWidgets.QLabel(Form)
        font = Qt.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.samplePowerLabel.setFont(font)
        self.samplePowerLabel.setObjectName("samplePowerLabel")
        self.gridLayout_2.addWidget(self.samplePowerLabel, 1, 1, 1, 1)
        self.wavelengthWidget = QtWidgets.QWidget(Form)
        self.wavelengthWidget.setObjectName("wavelengthWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wavelengthWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.setWavelengthCheck = QtWidgets.QCheckBox(self.wavelengthWidget)
        self.setWavelengthCheck.setObjectName("setWavelengthCheck")
        self.horizontalLayout.addWidget(self.setWavelengthCheck)
        self.wavelengthSpin = QtWidgets.QSpinBox(self.wavelengthWidget)
        self.wavelengthSpin.setMaximum(4000)
        self.wavelengthSpin.setSingleStep(10)
        self.wavelengthSpin.setProperty("value", 1080)
        self.wavelengthSpin.setObjectName("wavelengthSpin")
        self.horizontalLayout.addWidget(self.wavelengthSpin)
        self.gridLayout_2.addWidget(self.wavelengthWidget, 4, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(3, 0, 3, 3)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.powerWaveRadio = QtWidgets.QRadioButton(self.groupBox)
        self.powerWaveRadio.setChecked(True)
        self.powerWaveRadio.setObjectName("powerWaveRadio")
        self.gridLayout.addWidget(self.powerWaveRadio, 0, 0, 1, 1)
        self.switchWaveRadio = QtWidgets.QRadioButton(self.groupBox)
        self.switchWaveRadio.setObjectName("switchWaveRadio")
        self.gridLayout.addWidget(self.switchWaveRadio, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 5, 0, 1, 3)
        self.adjustLengthCheck = QtWidgets.QCheckBox(Form)
        self.adjustLengthCheck.setChecked(True)
        self.adjustLengthCheck.setTristate(False)
        self.adjustLengthCheck.setObjectName("adjustLengthCheck")
        self.gridLayout_2.addWidget(self.adjustLengthCheck, 3, 0, 1, 3)
        self.checkPowerCheck = QtWidgets.QCheckBox(Form)
        self.checkPowerCheck.setChecked(True)
        self.checkPowerCheck.setObjectName("checkPowerCheck")
        self.gridLayout_2.addWidget(self.checkPowerCheck, 2, 0, 1, 3)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Output Power:"))
        self.outputPowerLabel.setText(_translate("Form", "0mW"))
        self.checkPowerBtn.setText(_translate("Form", "Check Power"))
        self.label_3.setText(_translate("Form", "Power at Sample:"))
        self.samplePowerLabel.setText(_translate("Form", "0mW"))
        self.setWavelengthCheck.setText(_translate("Form", "Set wavelength"))
        self.wavelengthSpin.setSuffix(_translate("Form", " nm"))
        self.groupBox.setTitle(_translate("Form", "Control Mode:"))
        self.powerWaveRadio.setText(_translate("Form", "Power waveform (W)"))
        self.switchWaveRadio.setText(_translate("Form", "Switch waveform (%)"))
        self.adjustLengthCheck.setToolTip(_translate("Form", "If the output power of the laser changes, adjust the length of laser pulses to maintain constant pulse energy."))
        self.adjustLengthCheck.setText(_translate("Form", "Adjust pulse length if power changes"))
        self.checkPowerCheck.setText(_translate("Form", "Check power before task start"))

