"""Tests for the bundled example Autopatch protocols: the checked-in JSON must
be exactly what Protocol.save_json produces from the committed generator (so it
is guaranteed to round-trip through Protocol.load_json against the registered
engine Action types), and the first-run install step must seed a fresh config
dir with them without ever overwriting an operator's existing file."""
from __future__ import annotations

import json
import os

import pytest

import acq4.modules.Autopatch.example_protocols as example_protocols_pkg
from acq4.experiment.protocol import Protocol
from acq4.experiment.registry import action_type_name, get_action_class
from acq4.modules.Autopatch.example_protocols import install_example_protocols
from acq4.modules.Autopatch.example_protocols.generate import (
    build_example_patch,
    build_example_prompt,
)
from acq4.util import Qt

_EXAMPLES_DIR = os.path.dirname(example_protocols_pkg.__file__)


@pytest.fixture(scope="module")
def qapp():
    return Qt.QApplication.instance() or Qt.QApplication([])


def _assert_every_node_type_resolves(protocol: Protocol) -> None:
    for node in protocol.nodes.values():
        assert get_action_class(action_type_name(node)) is type(node)
    for handler in protocol.exceptionHandlers.values():
        _assert_every_node_type_resolves(handler)


@pytest.mark.parametrize(
    "filename,builder",
    [
        ("example_prompt.json", build_example_prompt),
        ("example_patch.json", build_example_patch),
    ],
)
def test_bundled_example_matches_the_committed_generator(filename, builder, tmp_path):
    """The shipped JSON must be exactly what save_json(builder()) produces --
    proof the file was generated by (and stays in sync with) the committed
    generator, not hand-edited out of sync with it."""
    generated_path = tmp_path / filename
    builder().save_json(str(generated_path))

    with open(generated_path) as fh:
        generated = json.load(fh)
    with open(os.path.join(_EXAMPLES_DIR, filename)) as fh:
        committed = json.load(fh)

    assert generated == committed


@pytest.mark.parametrize("filename", ["example_prompt.json", "example_patch.json"])
def test_bundled_example_loads_and_every_node_type_resolves(filename):
    path = os.path.join(_EXAMPLES_DIR, filename)
    protocol = Protocol.load_json(path)
    assert protocol.entry is not None
    _assert_every_node_type_resolves(protocol)


def test_example_prompt_exposes_message_as_a_public_param():
    protocol = Protocol.load_json(os.path.join(_EXAMPLES_DIR, "example_prompt.json"))
    assert {"node": "ask", "param": "message", "public": "message"} in protocol.publicParams


def test_example_patch_wires_patch_outcomes_and_exception_handler():
    protocol = Protocol.load_json(os.path.join(_EXAMPLES_DIR, "example_patch.json"))
    for outcome in ("whole cell", "cell attached", "bath"):
        assert protocol.next_node("patch", outcome) is not None
        assert action_type_name(protocol.nodes[protocol.next_node("patch", outcome)]) == "GoToNext"

    handler = protocol.handler_for("Exception")
    assert handler is not None
    assert action_type_name(handler.nodes[handler.entry]) == "Prompt"


def test_install_example_protocols_copies_into_a_fresh_config_dir(tmp_path):
    dest = tmp_path / "autopatch_protocols"
    install_example_protocols(str(dest))

    assert (dest / "example_prompt.json").exists()
    assert (dest / "example_patch.json").exists()
    # Every installed file must itself be a loadable Protocol.
    Protocol.load_json(str(dest / "example_prompt.json"))
    Protocol.load_json(str(dest / "example_patch.json"))


def test_install_example_protocols_never_overwrites_an_existing_file(tmp_path):
    dest = tmp_path / "autopatch_protocols"
    dest.mkdir()
    (dest / "example_prompt.json").write_text("operator's own edits, not valid JSON")

    install_example_protocols(str(dest))

    assert (dest / "example_prompt.json").read_text() == "operator's own edits, not valid JSON"
    # The other example is still installed since only the existing name was skipped.
    assert (dest / "example_patch.json").exists()


def test_autopatch_window_init_seeds_a_missing_protocol_dir_with_examples(qapp, tmp_path):
    """AutopatchWindow's own init -- not just install_example_protocols() called
    directly -- creates a not-yet-existing protocol dir and seeds it with both
    bundled examples before the picker lists its contents."""
    from acq4.modules.Autopatch.Autopatch import AutopatchWindow

    class _FakeDeviceSelector(Qt.QWidget):
        def getSelectedObj(self):
            return None

    protocolDir = tmp_path / "does_not_exist_yet" / "autopatch_protocols"
    win = AutopatchWindow(
        module=None,
        protocolDir=str(protocolDir),
        pipetteSelector=_FakeDeviceSelector(),
        cameraSelector=_FakeDeviceSelector(),
    )

    assert (protocolDir / "example_prompt.json").exists()
    assert (protocolDir / "example_patch.json").exists()
    items = {win.protocolPanel.fileCombo.itemText(i) for i in range(win.protocolPanel.fileCombo.count())}
    assert items == {"example_prompt.json", "example_patch.json"}
