# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/util/LogWidgetTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(633, 437)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(Qt.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.exportHtmlBtn = QtWidgets.QPushButton(self.widget)
        self.exportHtmlBtn.setObjectName("exportHtmlBtn")
        self.gridLayout.addWidget(self.exportHtmlBtn, 0, 2, 1, 1)
        self.dirLabel = QtWidgets.QLabel(self.widget)
        self.dirLabel.setText("")
        self.dirLabel.setObjectName("dirLabel")
        self.gridLayout.addWidget(self.dirLabel, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.output = QtWidgets.QTextBrowser(self.widget)
        self.output.setOpenLinks(False)
        self.output.setObjectName("output")
        self.gridLayout.addWidget(self.output, 1, 0, 1, 3)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filterTree = TreeWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterTree.sizePolicy().hasHeightForWidth())
        self.filterTree.setSizePolicy(sizePolicy)
        self.filterTree.setMinimumSize(Qt.QSize(210, 0))
        self.filterTree.setMaximumSize(Qt.QSize(8777205, 16777215))
        self.filterTree.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.filterTree.setProperty("showDropIndicator", False)
        self.filterTree.setDragEnabled(True)
        self.filterTree.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.filterTree.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.filterTree.setObjectName("filterTree")
        item_0 = QtWidgets.QTreeWidgetItem(self.filterTree)
        item_0.setCheckState(0, Qt.Qt.Unchecked)
        item_0.setFlags(Qt.Qt.ItemIsUserCheckable|Qt.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.filterTree)
        item_0.setCheckState(0, Qt.Qt.Checked)
        item_0.setFlags(Qt.Qt.ItemIsDropEnabled|Qt.Qt.ItemIsUserCheckable|Qt.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, Qt.Qt.Checked)
        item_1.setFlags(Qt.Qt.ItemIsUserCheckable|Qt.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, Qt.Qt.Checked)
        item_1.setFlags(Qt.Qt.ItemIsUserCheckable|Qt.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, Qt.Qt.Checked)
        item_1.setFlags(Qt.Qt.ItemIsUserCheckable|Qt.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, Qt.Qt.Checked)
        item_1.setFlags(Qt.Qt.ItemIsUserCheckable|Qt.Qt.ItemIsEnabled)
        self.verticalLayout.addWidget(self.filterTree)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = Qt.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setAlignment(Qt.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        font = Qt.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.importanceSlider = QtWidgets.QSlider(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importanceSlider.sizePolicy().hasHeightForWidth())
        self.importanceSlider.setSizePolicy(sizePolicy)
        self.importanceSlider.setMaximum(9)
        self.importanceSlider.setPageStep(0)
        self.importanceSlider.setProperty("value", 4)
        self.importanceSlider.setTracking(True)
        self.importanceSlider.setOrientation(Qt.Qt.Horizontal)
        self.importanceSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.importanceSlider.setTickInterval(1)
        self.importanceSlider.setObjectName("importanceSlider")
        self.verticalLayout.addWidget(self.importanceSlider)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.exportHtmlBtn.setText(_translate("Form", "Export HTML"))
        self.filterTree.headerItem().setText(0, _translate("Form", "Display:"))
        __sortingEnabled = self.filterTree.isSortingEnabled()
        self.filterTree.setSortingEnabled(False)
        self.filterTree.topLevelItem(0).setText(0, _translate("Form", "Current directory only"))
        self.filterTree.topLevelItem(1).setText(0, _translate("Form", "All message types:"))
        self.filterTree.topLevelItem(1).child(0).setText(0, _translate("Form", "user"))
        self.filterTree.topLevelItem(1).child(1).setText(0, _translate("Form", "status"))
        self.filterTree.topLevelItem(1).child(2).setText(0, _translate("Form", "warning"))
        self.filterTree.topLevelItem(1).child(3).setText(0, _translate("Form", "error"))
        self.filterTree.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("Form", "Low"))
        self.label.setText(_translate("Form", "Importance Filter:"))
        self.label_3.setText(_translate("Form", "High"))

from acq4.pyqtgraph import TreeWidget
