# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/modules/pbm_ImageAnalysis/ctrlTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(384, 410)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(Qt.QSize(384, 410))
        font = Qt.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMaximumSize(Qt.QSize(392, 410))
        font = Qt.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(Qt.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.ImagePhys_ImgNormalize = QtWidgets.QPushButton(self.groupBox)
        self.ImagePhys_ImgNormalize.setEnabled(False)
        self.ImagePhys_ImgNormalize.setGeometry(Qt.QRect(195, 180, 91, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_ImgNormalize.sizePolicy().hasHeightForWidth())
        self.ImagePhys_ImgNormalize.setSizePolicy(sizePolicy)
        self.ImagePhys_ImgNormalize.setObjectName("ImagePhys_ImgNormalize")
        self.ImagePhys_NormInfo = QtWidgets.QLabel(self.groupBox)
        self.ImagePhys_NormInfo.setEnabled(False)
        self.ImagePhys_NormInfo.setGeometry(Qt.QRect(290, 185, 76, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_NormInfo.sizePolicy().hasHeightForWidth())
        self.ImagePhys_NormInfo.setSizePolicy(sizePolicy)
        self.ImagePhys_NormInfo.setObjectName("ImagePhys_NormInfo")
        self.ImagePhys_Update = QtWidgets.QPushButton(self.groupBox)
        self.ImagePhys_Update.setGeometry(Qt.QRect(200, 155, 78, 32))
        self.ImagePhys_Update.setObjectName("ImagePhys_Update")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(Qt.QRect(190, 20, 171, 136))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(Qt.QRect(5, 20, 165, 120))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ImagePhys_View = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_View.sizePolicy().hasHeightForWidth())
        self.ImagePhys_View.setSizePolicy(sizePolicy)
        font = Qt.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(13)
        self.ImagePhys_View.setFont(font)
        self.ImagePhys_View.setObjectName("ImagePhys_View")
        self.ImagePhys_View.addItem("")
        self.ImagePhys_View.addItem("")
        self.ImagePhys_View.addItem("")
        self.ImagePhys_View.addItem("")
        self.ImagePhys_View.addItem("")
        self.ImagePhys_View.addItem("")
        self.verticalLayout_3.addWidget(self.ImagePhys_View)
        self.ImagePhys_ImgMethod = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_ImgMethod.sizePolicy().hasHeightForWidth())
        self.ImagePhys_ImgMethod.setSizePolicy(sizePolicy)
        font = Qt.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(13)
        self.ImagePhys_ImgMethod.setFont(font)
        self.ImagePhys_ImgMethod.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.ImagePhys_ImgMethod.setObjectName("ImagePhys_ImgMethod")
        self.ImagePhys_ImgMethod.addItem("")
        self.ImagePhys_ImgMethod.addItem("")
        self.ImagePhys_ImgMethod.addItem("")
        self.ImagePhys_ImgMethod.addItem("")
        self.ImagePhys_ImgMethod.addItem("")
        self.ImagePhys_ImgMethod.addItem("")
        self.verticalLayout_3.addWidget(self.ImagePhys_ImgMethod)
        self.ImagePhys_DisplayTraces = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_DisplayTraces.sizePolicy().hasHeightForWidth())
        self.ImagePhys_DisplayTraces.setSizePolicy(sizePolicy)
        self.ImagePhys_DisplayTraces.setObjectName("ImagePhys_DisplayTraces")
        self.verticalLayout_3.addWidget(self.ImagePhys_DisplayTraces)
        self.ImagePhys_ExportTiff = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_ExportTiff.sizePolicy().hasHeightForWidth())
        self.ImagePhys_ExportTiff.setSizePolicy(sizePolicy)
        self.ImagePhys_ExportTiff.setObjectName("ImagePhys_ExportTiff")
        self.verticalLayout_3.addWidget(self.ImagePhys_ExportTiff)
        self.ImagePhys_FileGroup = QtWidgets.QGroupBox(self.groupBox)
        self.ImagePhys_FileGroup.setEnabled(True)
        self.ImagePhys_FileGroup.setGeometry(Qt.QRect(10, 15, 151, 226))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.ImagePhys_FileGroup.sizePolicy().hasHeightForWidth())
        self.ImagePhys_FileGroup.setSizePolicy(sizePolicy)
        self.ImagePhys_FileGroup.setMinimumSize(Qt.QSize(140, 190))
        self.ImagePhys_FileGroup.setSizeIncrement(Qt.QSize(10, 10))
        self.ImagePhys_FileGroup.setBaseSize(Qt.QSize(100, 250))
        self.ImagePhys_FileGroup.setObjectName("ImagePhys_FileGroup")
        self.ImagePhys_ImageMode = QtWidgets.QComboBox(self.ImagePhys_FileGroup)
        self.ImagePhys_ImageMode.setGeometry(Qt.QRect(5, 40, 131, 21))
        font = Qt.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(13)
        self.ImagePhys_ImageMode.setFont(font)
        self.ImagePhys_ImageMode.setObjectName("ImagePhys_ImageMode")
        self.ImagePhys_ImageMode.addItem("")
        self.ImagePhys_ImageMode.addItem("")
        self.ImagePhys_clearRatio = QtWidgets.QPushButton(self.ImagePhys_FileGroup)
        self.ImagePhys_clearRatio.setGeometry(Qt.QRect(0, 170, 141, 30))
        self.ImagePhys_clearRatio.setObjectName("ImagePhys_clearRatio")
        self.ImagePhys_GetFileInfo = QtWidgets.QPushButton(self.ImagePhys_FileGroup)
        self.ImagePhys_GetFileInfo.setGeometry(Qt.QRect(0, 15, 136, 31))
        self.ImagePhys_GetFileInfo.setObjectName("ImagePhys_GetFileInfo")
        self.ImagePhys_getRatio = QtWidgets.QPushButton(self.ImagePhys_FileGroup)
        self.ImagePhys_getRatio.setGeometry(Qt.QRect(0, 145, 141, 30))
        self.ImagePhys_getRatio.setObjectName("ImagePhys_getRatio")
        self.layoutWidget1 = QtWidgets.QWidget(self.ImagePhys_FileGroup)
        self.layoutWidget1.setGeometry(Qt.QRect(5, 65, 157, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.ImagePhys_DataStruct = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_DataStruct.sizePolicy().hasHeightForWidth())
        self.ImagePhys_DataStruct.setSizePolicy(sizePolicy)
        self.ImagePhys_DataStruct.setMaxCount(10)
        self.ImagePhys_DataStruct.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.ImagePhys_DataStruct.setFrame(False)
        self.ImagePhys_DataStruct.setObjectName("ImagePhys_DataStruct")
        self.ImagePhys_DataStruct.addItem("")
        self.ImagePhys_DataStruct.addItem("")
        self.horizontalLayout_3.addWidget(self.ImagePhys_DataStruct)
        self.layoutWidget2 = QtWidgets.QWidget(self.ImagePhys_FileGroup)
        self.layoutWidget2.setGeometry(Qt.QRect(5, 115, 131, 27))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.ImagePhys_ignoreFirst = QtWidgets.QSpinBox(self.layoutWidget2)
        self.ImagePhys_ignoreFirst.setSuffix("")
        self.ImagePhys_ignoreFirst.setPrefix("")
        self.ImagePhys_ignoreFirst.setProperty("value", 1)
        self.ImagePhys_ignoreFirst.setObjectName("ImagePhys_ignoreFirst")
        self.horizontalLayout_4.addWidget(self.ImagePhys_ignoreFirst)
        self.layoutWidget3 = QtWidgets.QWidget(self.ImagePhys_FileGroup)
        self.layoutWidget3.setGeometry(Qt.QRect(5, 90, 159, 28))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_2.setAlignment(Qt.Qt.AlignLeading|Qt.Qt.AlignLeft|Qt.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.ImagePhys_Downsample = QtWidgets.QComboBox(self.layoutWidget3)
        font = Qt.QFont()
        font.setFamily("Lucida Grande")
        self.ImagePhys_Downsample.setFont(font)
        self.ImagePhys_Downsample.setEditable(True)
        self.ImagePhys_Downsample.setMaxCount(5000)
        self.ImagePhys_Downsample.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.ImagePhys_Downsample.setObjectName("ImagePhys_Downsample")
        self.ImagePhys_Downsample.addItem("")
        self.ImagePhys_Downsample.addItem("")
        self.ImagePhys_Downsample.addItem("")
        self.ImagePhys_Downsample.addItem("")
        self.ImagePhys_Downsample.addItem("")
        self.ImagePhys_Downsample.addItem("")
        self.ImagePhys_Downsample.addItem("")
        self.ImagePhys_Downsample.addItem("")
        self.ImagePhys_Downsample.addItem("")
        self.ImagePhys_Downsample.addItem("")
        self.horizontalLayout_5.addWidget(self.ImagePhys_Downsample)
        self.ImagePhys_RegisterStack = QtWidgets.QPushButton(self.ImagePhys_FileGroup)
        self.ImagePhys_RegisterStack.setGeometry(Qt.QRect(0, 195, 141, 29))
        self.ImagePhys_RegisterStack.setObjectName("ImagePhys_RegisterStack")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(Qt.QRect(195, 205, 116, 96))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget4.setGeometry(Qt.QRect(10, 25, 100, 62))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ImagePhys_Camera_check = QtWidgets.QCheckBox(self.layoutWidget4)
        self.ImagePhys_Camera_check.setContextMenuPolicy(Qt.Qt.NoContextMenu)
        self.ImagePhys_Camera_check.setChecked(True)
        self.ImagePhys_Camera_check.setObjectName("ImagePhys_Camera_check")
        self.verticalLayout_2.addWidget(self.ImagePhys_Camera_check)
        self.ImagePhys_PMT_check = QtWidgets.QCheckBox(self.layoutWidget4)
        self.ImagePhys_PMT_check.setChecked(True)
        self.ImagePhys_PMT_check.setObjectName("ImagePhys_PMT_check")
        self.verticalLayout_2.addWidget(self.ImagePhys_PMT_check)
        self.ImagePhys_Image_check = QtWidgets.QCheckBox(self.layoutWidget4)
        self.ImagePhys_Image_check.setObjectName("ImagePhys_Image_check")
        self.verticalLayout_2.addWidget(self.ImagePhys_Image_check)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(Qt.QRect(10, 235, 151, 171))
        self.groupBox_6.setObjectName("groupBox_6")
        self.ImagePhys_PMT_decomb_subpixel = QtWidgets.QCheckBox(self.groupBox_6)
        self.ImagePhys_PMT_decomb_subpixel.setGeometry(Qt.QRect(0, 80, 81, 20))
        self.ImagePhys_PMT_decomb_subpixel.setLayoutDirection(Qt.Qt.LeftToRight)
        self.ImagePhys_PMT_decomb_subpixel.setObjectName("ImagePhys_PMT_decomb_subpixel")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setGeometry(Qt.QRect(5, 120, 62, 16))
        self.label.setObjectName("label")
        self.ImagePhys_PMT_decomb = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.ImagePhys_PMT_decomb.setGeometry(Qt.QRect(75, 115, 71, 25))
        self.ImagePhys_PMT_decomb.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_PMT_decomb.setMinimum(-500.0)
        self.ImagePhys_PMT_decomb.setMaximum(500.0)
        self.ImagePhys_PMT_decomb.setObjectName("ImagePhys_PMT_decomb")
        self.ImagePhys_Restore_decomb = QtWidgets.QPushButton(self.groupBox_6)
        self.ImagePhys_Restore_decomb.setGeometry(Qt.QRect(0, 140, 121, 32))
        self.ImagePhys_Restore_decomb.setObjectName("ImagePhys_Restore_decomb")
        self.ImagePhys_PMT_auto_check = QtWidgets.QCheckBox(self.groupBox_6)
        self.ImagePhys_PMT_auto_check.setGeometry(Qt.QRect(0, 100, 51, 20))
        self.ImagePhys_PMT_auto_check.setLayoutDirection(Qt.Qt.LeftToRight)
        self.ImagePhys_PMT_auto_check.setObjectName("ImagePhys_PMT_auto_check")
        self.ImagePhys_PMT_autoButton = QtWidgets.QPushButton(self.groupBox_6)
        self.ImagePhys_PMT_autoButton.setGeometry(Qt.QRect(75, 85, 61, 23))
        self.ImagePhys_PMT_autoButton.setObjectName("ImagePhys_PMT_autoButton")
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget5.setGeometry(Qt.QRect(5, 20, 136, 32))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ImagePhys_PMT_LPF_check = QtWidgets.QCheckBox(self.layoutWidget5)
        self.ImagePhys_PMT_LPF_check.setObjectName("ImagePhys_PMT_LPF_check")
        self.horizontalLayout_2.addWidget(self.ImagePhys_PMT_LPF_check)
        self.ImagePhys_PMT_LPF = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        self.ImagePhys_PMT_LPF.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_PMT_LPF.setDecimals(1)
        self.ImagePhys_PMT_LPF.setMaximum(500.0)
        self.ImagePhys_PMT_LPF.setProperty("value", 50.0)
        self.ImagePhys_PMT_LPF.setObjectName("ImagePhys_PMT_LPF")
        self.horizontalLayout_2.addWidget(self.ImagePhys_PMT_LPF)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget6.setGeometry(Qt.QRect(5, 50, 138, 32))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_7.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ImagePhys_PMT_Notch_check = QtWidgets.QCheckBox(self.layoutWidget6)
        self.ImagePhys_PMT_Notch_check.setObjectName("ImagePhys_PMT_Notch_check")
        self.horizontalLayout_7.addWidget(self.ImagePhys_PMT_Notch_check)
        self.ImagePhys_PMT_Notch = QtWidgets.QDoubleSpinBox(self.layoutWidget6)
        self.ImagePhys_PMT_Notch.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_PMT_Notch.setDecimals(1)
        self.ImagePhys_PMT_Notch.setMaximum(500.0)
        self.ImagePhys_PMT_Notch.setProperty("value", 80.0)
        self.ImagePhys_PMT_Notch.setObjectName("ImagePhys_PMT_Notch")
        self.horizontalLayout_7.addWidget(self.ImagePhys_PMT_Notch)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(Qt.QRect(195, 300, 116, 96))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget7.setGeometry(Qt.QRect(10, 25, 96, 64))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ImagePhys_PhysROIPlot = QtWidgets.QCheckBox(self.layoutWidget7)
        self.ImagePhys_PhysROIPlot.setObjectName("ImagePhys_PhysROIPlot")
        self.verticalLayout.addWidget(self.ImagePhys_PhysROIPlot)
        self.ImagePhys_RectSelect = QtWidgets.QCheckBox(self.layoutWidget7)
        self.ImagePhys_RectSelect.setChecked(False)
        self.ImagePhys_RectSelect.setObjectName("ImagePhys_RectSelect")
        self.verticalLayout.addWidget(self.ImagePhys_RectSelect)
        self.ImagePhys_CorrTool_BL1 = QtWidgets.QCheckBox(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_CorrTool_BL1.sizePolicy().hasHeightForWidth())
        self.ImagePhys_CorrTool_BL1.setSizePolicy(sizePolicy)
        self.ImagePhys_CorrTool_BL1.setObjectName("ImagePhys_CorrTool_BL1")
        self.verticalLayout.addWidget(self.ImagePhys_CorrTool_BL1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Files, Corrections, and Filtering"))
        self.ImagePhys_ImgNormalize.setText(_translate("Form", "Normalize"))
        self.ImagePhys_NormInfo.setText(_translate("Form", "NormInfo"))
        self.ImagePhys_Update.setText(_translate("Form", "Update"))
        self.groupBox_4.setTitle(_translate("Form", "View"))
        self.ImagePhys_View.setItemText(0, _translate("Form", "Movie"))
        self.ImagePhys_View.setItemText(1, _translate("Form", "Average Image"))
        self.ImagePhys_View.setItemText(2, _translate("Form", "Reference Image"))
        self.ImagePhys_View.setItemText(3, _translate("Form", "Std Image"))
        self.ImagePhys_View.setItemText(4, _translate("Form", "Spectrum Image"))
        self.ImagePhys_View.setItemText(5, _translate("Form", "Ratio Image"))
        self.ImagePhys_ImgMethod.setItemText(0, _translate("Form", "dF/Fo"))
        self.ImagePhys_ImgMethod.setItemText(1, _translate("Form", "dF/Base"))
        self.ImagePhys_ImgMethod.setItemText(2, _translate("Form", "median"))
        self.ImagePhys_ImgMethod.setItemText(3, _translate("Form", "Norm\'d"))
        self.ImagePhys_ImgMethod.setItemText(4, _translate("Form", "Slow Filter"))
        self.ImagePhys_ImgMethod.setItemText(5, _translate("Form", "G/R"))
        self.ImagePhys_DisplayTraces.setText(_translate("Form", "dF/F -> MPL"))
        self.ImagePhys_ExportTiff.setText(_translate("Form", "Export TIFF"))
        self.ImagePhys_FileGroup.setTitle(_translate("Form", "File Operations"))
        self.ImagePhys_ImageMode.setItemText(0, _translate("Form", "Non-Ratiometric (dF/Fo)"))
        self.ImagePhys_ImageMode.setItemText(1, _translate("Form", "Ratiometric (G/R)"))
        self.ImagePhys_clearRatio.setText(_translate("Form", "Clear Ratio Image"))
        self.ImagePhys_GetFileInfo.setText(_translate("Form", "Get File Info"))
        self.ImagePhys_getRatio.setText(_translate("Form", "Get Ratio Image"))
        self.label_5.setText(_translate("Form", "Data"))
        self.ImagePhys_DataStruct.setItemText(0, _translate("Form", "Flat"))
        self.ImagePhys_DataStruct.setItemText(1, _translate("Form", "Interleaved"))
        self.label_4.setText(_translate("Form", "Ignore"))
        self.label_2.setText(_translate("Form", "Downsamp"))
        self.ImagePhys_Downsample.setItemText(0, _translate("Form", "1"))
        self.ImagePhys_Downsample.setItemText(1, _translate("Form", "2"))
        self.ImagePhys_Downsample.setItemText(2, _translate("Form", "5"))
        self.ImagePhys_Downsample.setItemText(3, _translate("Form", "10"))
        self.ImagePhys_Downsample.setItemText(4, _translate("Form", "20"))
        self.ImagePhys_Downsample.setItemText(5, _translate("Form", "50"))
        self.ImagePhys_Downsample.setItemText(6, _translate("Form", "100"))
        self.ImagePhys_Downsample.setItemText(7, _translate("Form", "200"))
        self.ImagePhys_Downsample.setItemText(8, _translate("Form", "500"))
        self.ImagePhys_Downsample.setItemText(9, _translate("Form", "1000"))
        self.ImagePhys_RegisterStack.setText(_translate("Form", "Register Stack"))
        self.groupBox_3.setTitle(_translate("Form", "Image types"))
        self.ImagePhys_Camera_check.setText(_translate("Form", "Camera"))
        self.ImagePhys_PMT_check.setText(_translate("Form", "PMT"))
        self.ImagePhys_Image_check.setText(_translate("Form", "Imaging.ma"))
        self.groupBox_6.setTitle(_translate("Form", "PMT Parameters"))
        self.ImagePhys_PMT_decomb_subpixel.setText(_translate("Form", "SubPixel"))
        self.label.setText(_translate("Form", "Decomb"))
        self.ImagePhys_Restore_decomb.setText(_translate("Form", "Restore Decomb"))
        self.ImagePhys_PMT_auto_check.setText(_translate("Form", "Auto"))
        self.ImagePhys_PMT_autoButton.setText(_translate("Form", "Auto"))
        self.ImagePhys_PMT_LPF_check.setText(_translate("Form", "LPF"))
        self.ImagePhys_PMT_Notch_check.setText(_translate("Form", "Notch"))
        self.groupBox_5.setTitle(_translate("Form", "Preferences"))
        self.ImagePhys_PhysROIPlot.setText(_translate("Form", "MultiPlot"))
        self.ImagePhys_RectSelect.setText(_translate("Form", "1-Button"))
        self.ImagePhys_CorrTool_BL1.setText(_translate("Form", "Baseline 1"))

