# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './acq4/analysis/modules/pbm_ImageAnalysis/ctrlTemplate.ui'
#
# Created: Tue Dec 24 01:49:14 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(384, 410)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(384, 410))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        Form.setFont(font)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setMaximumSize(QtCore.QSize(392, 410))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.ImagePhys_ImgNormalize = QtGui.QPushButton(self.groupBox)
        self.ImagePhys_ImgNormalize.setEnabled(False)
        self.ImagePhys_ImgNormalize.setGeometry(QtCore.QRect(0, 220, 101, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_ImgNormalize.sizePolicy().hasHeightForWidth())
        self.ImagePhys_ImgNormalize.setSizePolicy(sizePolicy)
        self.ImagePhys_ImgNormalize.setObjectName(_fromUtf8("ImagePhys_ImgNormalize"))
        self.ImagePhys_NormInfo = QtGui.QLabel(self.groupBox)
        self.ImagePhys_NormInfo.setEnabled(False)
        self.ImagePhys_NormInfo.setGeometry(QtCore.QRect(95, 225, 54, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_NormInfo.sizePolicy().hasHeightForWidth())
        self.ImagePhys_NormInfo.setSizePolicy(sizePolicy)
        self.ImagePhys_NormInfo.setObjectName(_fromUtf8("ImagePhys_NormInfo"))
        self.ImagePhys_Update = QtGui.QPushButton(self.groupBox)
        self.ImagePhys_Update.setGeometry(QtCore.QRect(165, 375, 78, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_Update.setFont(font)
        self.ImagePhys_Update.setObjectName(_fromUtf8("ImagePhys_Update"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(275, 20, 106, 286))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.groupBox_3.setPalette(palette)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.ImagePhys_clearRoi = QtGui.QPushButton(self.groupBox_3)
        self.ImagePhys_clearRoi.setGeometry(QtCore.QRect(0, 35, 106, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_clearRoi.setFont(font)
        self.ImagePhys_clearRoi.setObjectName(_fromUtf8("ImagePhys_clearRoi"))
        self.ImagePhys_addRoi = QtGui.QPushButton(self.groupBox_3)
        self.ImagePhys_addRoi.setGeometry(QtCore.QRect(0, 15, 106, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_addRoi.setFont(font)
        self.ImagePhys_addRoi.setObjectName(_fromUtf8("ImagePhys_addRoi"))
        self.ImagePhys_RecalculateROIs = QtGui.QPushButton(self.groupBox_3)
        self.ImagePhys_RecalculateROIs.setGeometry(QtCore.QRect(0, 205, 111, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_RecalculateROIs.setFont(font)
        self.ImagePhys_RecalculateROIs.setObjectName(_fromUtf8("ImagePhys_RecalculateROIs"))
        self.ImagePhys_RetrieveROI = QtGui.QPushButton(self.groupBox_3)
        self.ImagePhys_RetrieveROI.setGeometry(QtCore.QRect(0, 230, 111, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_RetrieveROI.setFont(font)
        self.ImagePhys_RetrieveROI.setObjectName(_fromUtf8("ImagePhys_RetrieveROI"))
        self.ImagePhys_SaveROI = QtGui.QPushButton(self.groupBox_3)
        self.ImagePhys_SaveROI.setGeometry(QtCore.QRect(0, 255, 111, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_SaveROI.setFont(font)
        self.ImagePhys_SaveROI.setObjectName(_fromUtf8("ImagePhys_SaveROI"))
        self.widget = QtGui.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(5, 130, 106, 27))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_13 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_15.addWidget(self.label_13)
        self.ImagePhys_ROISize = QtGui.QSpinBox(self.widget)
        self.ImagePhys_ROISize.setMinimum(1)
        self.ImagePhys_ROISize.setMaximum(25)
        self.ImagePhys_ROISize.setProperty("value", 1)
        self.ImagePhys_ROISize.setObjectName(_fromUtf8("ImagePhys_ROISize"))
        self.horizontalLayout_15.addWidget(self.ImagePhys_ROISize)
        self.widget1 = QtGui.QWidget(self.groupBox_3)
        self.widget1.setGeometry(QtCore.QRect(5, 80, 183, 48))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ImagePhys_ROIThrHigh = QtGui.QDoubleSpinBox(self.widget1)
        self.ImagePhys_ROIThrHigh.setMinimum(0.1)
        self.ImagePhys_ROIThrHigh.setMaximum(1.0)
        self.ImagePhys_ROIThrHigh.setSingleStep(0.1)
        self.ImagePhys_ROIThrHigh.setProperty("value", 1.0)
        self.ImagePhys_ROIThrHigh.setObjectName(_fromUtf8("ImagePhys_ROIThrHigh"))
        self.gridLayout_4.addWidget(self.ImagePhys_ROIThrHigh, 1, 1, 1, 1)
        self.ImagePhys_ROIThrLow = QtGui.QDoubleSpinBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_ROIThrLow.sizePolicy().hasHeightForWidth())
        self.ImagePhys_ROIThrLow.setSizePolicy(sizePolicy)
        self.ImagePhys_ROIThrLow.setMinimum(0.01)
        self.ImagePhys_ROIThrLow.setMaximum(1.0)
        self.ImagePhys_ROIThrLow.setSingleStep(0.1)
        self.ImagePhys_ROIThrLow.setProperty("value", 0.2)
        self.ImagePhys_ROIThrLow.setObjectName(_fromUtf8("ImagePhys_ROIThrLow"))
        self.gridLayout_4.addWidget(self.ImagePhys_ROIThrLow, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 0, 1, 1, 1)
        self.widget2 = QtGui.QWidget(self.groupBox_3)
        self.widget2.setGeometry(QtCore.QRect(5, 185, 101, 26))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_6 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_10.addWidget(self.label_6)
        self.ImagePhys_ROIKernel = QtGui.QComboBox(self.widget2)
        self.ImagePhys_ROIKernel.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.ImagePhys_ROIKernel.setFont(font)
        self.ImagePhys_ROIKernel.setToolTip(_fromUtf8(""))
        self.ImagePhys_ROIKernel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ImagePhys_ROIKernel.setStyleSheet(_fromUtf8("<align = \'right\'>"))
        self.ImagePhys_ROIKernel.setMaxVisibleItems(1)
        self.ImagePhys_ROIKernel.setMaxCount(10)
        self.ImagePhys_ROIKernel.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ImagePhys_ROIKernel.setFrame(False)
        self.ImagePhys_ROIKernel.setModelColumn(0)
        self.ImagePhys_ROIKernel.setObjectName(_fromUtf8("ImagePhys_ROIKernel"))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.ImagePhys_ROIKernel)
        self.ImagePhys_findROIs = QtGui.QPushButton(self.groupBox_3)
        self.ImagePhys_findROIs.setGeometry(QtCore.QRect(0, 55, 106, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_findROIs.setFont(font)
        self.ImagePhys_findROIs.setObjectName(_fromUtf8("ImagePhys_findROIs"))
        self.widget3 = QtGui.QWidget(self.groupBox_3)
        self.widget3.setGeometry(QtCore.QRect(5, 160, 100, 25))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.ImagePhys_StdRB = QtGui.QRadioButton(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ImagePhys_StdRB.setFont(font)
        self.ImagePhys_StdRB.setObjectName(_fromUtf8("ImagePhys_StdRB"))
        self.horizontalLayout_14.addWidget(self.ImagePhys_StdRB)
        self.ImagePhys_FFTRB = QtGui.QRadioButton(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ImagePhys_FFTRB.setFont(font)
        self.ImagePhys_FFTRB.setChecked(True)
        self.ImagePhys_FFTRB.setObjectName(_fromUtf8("ImagePhys_FFTRB"))
        self.horizontalLayout_14.addWidget(self.ImagePhys_FFTRB)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(150, 220, 121, 126))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.ImagePhys_View = QtGui.QComboBox(self.groupBox_4)
        self.ImagePhys_View.setGeometry(QtCore.QRect(5, 20, 111, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_View.setFont(font)
        self.ImagePhys_View.setObjectName(_fromUtf8("ImagePhys_View"))
        self.ImagePhys_View.addItem(_fromUtf8(""))
        self.ImagePhys_View.addItem(_fromUtf8(""))
        self.ImagePhys_View.addItem(_fromUtf8(""))
        self.ImagePhys_View.addItem(_fromUtf8(""))
        self.ImagePhys_View.addItem(_fromUtf8(""))
        self.ImagePhys_ImgMethod = QtGui.QComboBox(self.groupBox_4)
        self.ImagePhys_ImgMethod.setGeometry(QtCore.QRect(5, 45, 111, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_ImgMethod.setFont(font)
        self.ImagePhys_ImgMethod.setObjectName(_fromUtf8("ImagePhys_ImgMethod"))
        self.ImagePhys_ImgMethod.addItem(_fromUtf8(""))
        self.ImagePhys_ImgMethod.addItem(_fromUtf8(""))
        self.ImagePhys_ImgMethod.addItem(_fromUtf8(""))
        self.ImagePhys_ImgMethod.addItem(_fromUtf8(""))
        self.ImagePhys_ImgMethod.addItem(_fromUtf8(""))
        self.ImagePhys_ExportTiff = QtGui.QPushButton(self.groupBox_4)
        self.ImagePhys_ExportTiff.setGeometry(QtCore.QRect(0, 70, 121, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_ExportTiff.setFont(font)
        self.ImagePhys_ExportTiff.setObjectName(_fromUtf8("ImagePhys_ExportTiff"))
        self.ImagePhys_DisplayTraces = QtGui.QPushButton(self.groupBox_4)
        self.ImagePhys_DisplayTraces.setGeometry(QtCore.QRect(0, 95, 121, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_DisplayTraces.setFont(font)
        self.ImagePhys_DisplayTraces.setObjectName(_fromUtf8("ImagePhys_DisplayTraces"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(275, 310, 106, 91))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.ImagePhys_RectSelect = QtGui.QCheckBox(self.groupBox_5)
        self.ImagePhys_RectSelect.setGeometry(QtCore.QRect(5, 35, 96, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_RectSelect.setFont(font)
        self.ImagePhys_RectSelect.setChecked(True)
        self.ImagePhys_RectSelect.setObjectName(_fromUtf8("ImagePhys_RectSelect"))
        self.ImagePhys_PhysROIPlot = QtGui.QCheckBox(self.groupBox_5)
        self.ImagePhys_PhysROIPlot.setGeometry(QtCore.QRect(5, 20, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ImagePhys_PhysROIPlot.setFont(font)
        self.ImagePhys_PhysROIPlot.setObjectName(_fromUtf8("ImagePhys_PhysROIPlot"))
        self.ImagePhys_CorrTool_BL1 = QtGui.QCheckBox(self.groupBox_5)
        self.ImagePhys_CorrTool_BL1.setGeometry(QtCore.QRect(5, 60, 101, 18))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_CorrTool_BL1.sizePolicy().hasHeightForWidth())
        self.ImagePhys_CorrTool_BL1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_CorrTool_BL1.setFont(font)
        self.ImagePhys_CorrTool_BL1.setObjectName(_fromUtf8("ImagePhys_CorrTool_BL1"))
        self.ImagePhys_FileGroup = QtGui.QGroupBox(self.groupBox)
        self.ImagePhys_FileGroup.setEnabled(True)
        self.ImagePhys_FileGroup.setGeometry(QtCore.QRect(5, 20, 140, 197))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.ImagePhys_FileGroup.sizePolicy().hasHeightForWidth())
        self.ImagePhys_FileGroup.setSizePolicy(sizePolicy)
        self.ImagePhys_FileGroup.setMinimumSize(QtCore.QSize(140, 190))
        self.ImagePhys_FileGroup.setSizeIncrement(QtCore.QSize(10, 10))
        self.ImagePhys_FileGroup.setBaseSize(QtCore.QSize(100, 250))
        self.ImagePhys_FileGroup.setObjectName(_fromUtf8("ImagePhys_FileGroup"))
        self.ImagePhys_ImageMode = QtGui.QComboBox(self.ImagePhys_FileGroup)
        self.ImagePhys_ImageMode.setGeometry(QtCore.QRect(5, 40, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ImagePhys_ImageMode.setFont(font)
        self.ImagePhys_ImageMode.setObjectName(_fromUtf8("ImagePhys_ImageMode"))
        self.ImagePhys_ImageMode.addItem(_fromUtf8(""))
        self.ImagePhys_ImageMode.addItem(_fromUtf8(""))
        self.ImagePhys_clearRatio = QtGui.QPushButton(self.ImagePhys_FileGroup)
        self.ImagePhys_clearRatio.setGeometry(QtCore.QRect(0, 170, 141, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_clearRatio.setFont(font)
        self.ImagePhys_clearRatio.setObjectName(_fromUtf8("ImagePhys_clearRatio"))
        self.ImagePhys_GetFileInfo = QtGui.QPushButton(self.ImagePhys_FileGroup)
        self.ImagePhys_GetFileInfo.setGeometry(QtCore.QRect(0, 15, 136, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_GetFileInfo.setFont(font)
        self.ImagePhys_GetFileInfo.setObjectName(_fromUtf8("ImagePhys_GetFileInfo"))
        self.ImagePhys_getRatio = QtGui.QPushButton(self.ImagePhys_FileGroup)
        self.ImagePhys_getRatio.setGeometry(QtCore.QRect(0, 145, 141, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_getRatio.setFont(font)
        self.ImagePhys_getRatio.setObjectName(_fromUtf8("ImagePhys_getRatio"))
        self.layoutWidget = QtGui.QWidget(self.ImagePhys_FileGroup)
        self.layoutWidget.setGeometry(QtCore.QRect(5, 65, 174, 26))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.ImagePhys_DataStruct = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_DataStruct.sizePolicy().hasHeightForWidth())
        self.ImagePhys_DataStruct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_DataStruct.setFont(font)
        self.ImagePhys_DataStruct.setMaxCount(10)
        self.ImagePhys_DataStruct.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.ImagePhys_DataStruct.setFrame(False)
        self.ImagePhys_DataStruct.setObjectName(_fromUtf8("ImagePhys_DataStruct"))
        self.ImagePhys_DataStruct.addItem(_fromUtf8(""))
        self.ImagePhys_DataStruct.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.ImagePhys_DataStruct)
        self.layoutWidget1 = QtGui.QWidget(self.ImagePhys_FileGroup)
        self.layoutWidget1.setGeometry(QtCore.QRect(5, 115, 136, 27))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.ImagePhys_ignoreFirst = QtGui.QSpinBox(self.layoutWidget1)
        self.ImagePhys_ignoreFirst.setSuffix(_fromUtf8(""))
        self.ImagePhys_ignoreFirst.setPrefix(_fromUtf8(""))
        self.ImagePhys_ignoreFirst.setProperty("value", 1)
        self.ImagePhys_ignoreFirst.setObjectName(_fromUtf8("ImagePhys_ignoreFirst"))
        self.horizontalLayout_4.addWidget(self.ImagePhys_ignoreFirst)
        self.layoutWidget2 = QtGui.QWidget(self.ImagePhys_FileGroup)
        self.layoutWidget2.setGeometry(QtCore.QRect(5, 90, 156, 26))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.ImagePhys_Downsample = QtGui.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.ImagePhys_Downsample.setFont(font)
        self.ImagePhys_Downsample.setEditable(True)
        self.ImagePhys_Downsample.setMaxCount(5000)
        self.ImagePhys_Downsample.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.ImagePhys_Downsample.setObjectName(_fromUtf8("ImagePhys_Downsample"))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.ImagePhys_Downsample)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 20, 121, 197))
        self.groupBox_2.setMinimumSize(QtCore.QSize(120, 190))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.ImagePhys_RegisterStack = QtGui.QPushButton(self.groupBox_2)
        self.ImagePhys_RegisterStack.setGeometry(QtCore.QRect(-5, 15, 131, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_RegisterStack.setFont(font)
        self.ImagePhys_RegisterStack.setObjectName(_fromUtf8("ImagePhys_RegisterStack"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 40, 121, 32))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.ImagePhys_UnBleach = QtGui.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_UnBleach.setFont(font)
        self.ImagePhys_UnBleach.setObjectName(_fromUtf8("ImagePhys_UnBleach"))
        self.horizontalLayout_6.addWidget(self.ImagePhys_UnBleach)
        self.ImagePhys_BleachInfo = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.ImagePhys_BleachInfo.setFont(font)
        self.ImagePhys_BleachInfo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ImagePhys_BleachInfo.setFrameShadow(QtGui.QFrame.Sunken)
        self.ImagePhys_BleachInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.ImagePhys_BleachInfo.setObjectName(_fromUtf8("ImagePhys_BleachInfo"))
        self.horizontalLayout_6.addWidget(self.ImagePhys_BleachInfo)
        self.ImagePhys_SpecCalc = QtGui.QPushButton(self.groupBox_2)
        self.ImagePhys_SpecCalc.setGeometry(QtCore.QRect(0, 70, 116, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.ImagePhys_SpecCalc.setFont(font)
        self.ImagePhys_SpecCalc.setObjectName(_fromUtf8("ImagePhys_SpecCalc"))
        self.layoutWidget4 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 95, 119, 27))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.ImagePhys_SpecHPF = QtGui.QDoubleSpinBox(self.layoutWidget4)
        self.ImagePhys_SpecHPF.setProperty("value", 1.0)
        self.ImagePhys_SpecHPF.setObjectName(_fromUtf8("ImagePhys_SpecHPF"))
        self.horizontalLayout.addWidget(self.ImagePhys_SpecHPF)
        self.layoutWidget5 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 125, 119, 27))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_8 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_11.addWidget(self.label_8)
        self.ImagePhys_SpecLPF = QtGui.QDoubleSpinBox(self.layoutWidget5)
        self.ImagePhys_SpecLPF.setProperty("value", 10.0)
        self.ImagePhys_SpecLPF.setObjectName(_fromUtf8("ImagePhys_SpecLPF"))
        self.horizontalLayout_11.addWidget(self.ImagePhys_SpecLPF)
        self.layoutWidget6 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(1, 155, 132, 27))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        self.ImagePhys_FFTSmooth = QtGui.QSpinBox(self.layoutWidget6)
        self.ImagePhys_FFTSmooth.setMaximum(16)
        self.ImagePhys_FFTSmooth.setObjectName(_fromUtf8("ImagePhys_FFTSmooth"))
        self.horizontalLayout_12.addWidget(self.ImagePhys_FFTSmooth)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(5, 245, 141, 161))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.widget4 = QtGui.QWidget(self.groupBox_6)
        self.widget4.setGeometry(QtCore.QRect(5, 25, 136, 27))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget4)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtGui.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.ImagePhys_BaseEnd = QtGui.QDoubleSpinBox(self.widget4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.ImagePhys_BaseEnd.setFont(font)
        self.ImagePhys_BaseEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ImagePhys_BaseEnd.setMinimum(-5000.0)
        self.ImagePhys_BaseEnd.setMaximum(50000.0)
        self.ImagePhys_BaseEnd.setObjectName(_fromUtf8("ImagePhys_BaseEnd"))
        self.horizontalLayout_7.addWidget(self.ImagePhys_BaseEnd)
        self.widget5 = QtGui.QWidget(self.groupBox_6)
        self.widget5.setGeometry(QtCore.QRect(5, 55, 136, 27))
        self.widget5.setObjectName(_fromUtf8("widget5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget5)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.ImagePhys_BaseStart = QtGui.QDoubleSpinBox(self.widget5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.ImagePhys_BaseStart.setFont(font)
        self.ImagePhys_BaseStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ImagePhys_BaseStart.setMinimum(-5000.0)
        self.ImagePhys_BaseStart.setMaximum(50000.0)
        self.ImagePhys_BaseStart.setObjectName(_fromUtf8("ImagePhys_BaseStart"))
        self.horizontalLayout_2.addWidget(self.ImagePhys_BaseStart)
        self.widget6 = QtGui.QWidget(self.groupBox_6)
        self.widget6.setGeometry(QtCore.QRect(5, 85, 136, 32))
        self.widget6.setObjectName(_fromUtf8("widget6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget6)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.ImagePhys_CorrTool_LPF = QtGui.QCheckBox(self.widget6)
        self.ImagePhys_CorrTool_LPF.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.ImagePhys_CorrTool_LPF.setFont(font)
        self.ImagePhys_CorrTool_LPF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ImagePhys_CorrTool_LPF.setObjectName(_fromUtf8("ImagePhys_CorrTool_LPF"))
        self.horizontalLayout_8.addWidget(self.ImagePhys_CorrTool_LPF)
        self.ImagePhys_ImgLPF = QtGui.QDoubleSpinBox(self.widget6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.ImagePhys_ImgLPF.setFont(font)
        self.ImagePhys_ImgLPF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ImagePhys_ImgLPF.setDecimals(2)
        self.ImagePhys_ImgLPF.setMinimum(0.1)
        self.ImagePhys_ImgLPF.setMaximum(5000.0)
        self.ImagePhys_ImgLPF.setSingleStep(1.0)
        self.ImagePhys_ImgLPF.setProperty("value", 20.0)
        self.ImagePhys_ImgLPF.setObjectName(_fromUtf8("ImagePhys_ImgLPF"))
        self.horizontalLayout_8.addWidget(self.ImagePhys_ImgLPF)
        self.widget7 = QtGui.QWidget(self.groupBox_6)
        self.widget7.setGeometry(QtCore.QRect(5, 120, 137, 32))
        self.widget7.setObjectName(_fromUtf8("widget7"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget7)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.ImagePhys_CorrTool_HPF = QtGui.QCheckBox(self.widget7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.ImagePhys_CorrTool_HPF.setFont(font)
        self.ImagePhys_CorrTool_HPF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ImagePhys_CorrTool_HPF.setObjectName(_fromUtf8("ImagePhys_CorrTool_HPF"))
        self.horizontalLayout_9.addWidget(self.ImagePhys_CorrTool_HPF)
        self.ImagePhys_ImgHPF = QtGui.QDoubleSpinBox(self.widget7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.ImagePhys_ImgHPF.setFont(font)
        self.ImagePhys_ImgHPF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ImagePhys_ImgHPF.setSuffix(_fromUtf8(""))
        self.ImagePhys_ImgHPF.setDecimals(3)
        self.ImagePhys_ImgHPF.setMinimum(0.001)
        self.ImagePhys_ImgHPF.setMaximum(10.0)
        self.ImagePhys_ImgHPF.setSingleStep(0.2)
        self.ImagePhys_ImgHPF.setProperty("value", 0.2)
        self.ImagePhys_ImgHPF.setObjectName(_fromUtf8("ImagePhys_ImgHPF"))
        self.horizontalLayout_9.addWidget(self.ImagePhys_ImgHPF)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.ImagePhys_ROIKernel.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox.setTitle(_translate("Form", "Corrections, ROI\'s and Filtering", None))
        self.ImagePhys_ImgNormalize.setText(_translate("Form", "Normalize", None))
        self.ImagePhys_NormInfo.setText(_translate("Form", "NormInfo", None))
        self.ImagePhys_Update.setText(_translate("Form", "Update", None))
        self.groupBox_3.setTitle(_translate("Form", "ROIs", None))
        self.ImagePhys_clearRoi.setText(_translate("Form", "Clear All ROIs", None))
        self.ImagePhys_addRoi.setText(_translate("Form", "Add Roi", None))
        self.ImagePhys_RecalculateROIs.setText(_translate("Form", "Recalculate ROIs", None))
        self.ImagePhys_RetrieveROI.setText(_translate("Form", "Retrieve ROI File", None))
        self.ImagePhys_SaveROI.setText(_translate("Form", "Save ROI File", None))
        self.label_13.setText(_translate("Form", "ROI Size", None))
        self.label_11.setText(_translate("Form", "Thr(L)", None))
        self.label_12.setText(_translate("Form", "Thr(H)", None))
        self.label_6.setText(_translate("Form", "Kernel", None))
        self.ImagePhys_ROIKernel.setItemText(0, _translate("Form", "1", None))
        self.ImagePhys_ROIKernel.setItemText(1, _translate("Form", "3", None))
        self.ImagePhys_ROIKernel.setItemText(2, _translate("Form", "5", None))
        self.ImagePhys_ROIKernel.setItemText(3, _translate("Form", "7", None))
        self.ImagePhys_ROIKernel.setItemText(4, _translate("Form", "9", None))
        self.ImagePhys_ROIKernel.setItemText(5, _translate("Form", "11", None))
        self.ImagePhys_findROIs.setText(_translate("Form", "Auto ROI Detect", None))
        self.ImagePhys_StdRB.setText(_translate("Form", "Std", None))
        self.ImagePhys_FFTRB.setText(_translate("Form", "FFT", None))
        self.groupBox_4.setTitle(_translate("Form", "View", None))
        self.ImagePhys_View.setItemText(0, _translate("Form", "Movie", None))
        self.ImagePhys_View.setItemText(1, _translate("Form", "Reference Image", None))
        self.ImagePhys_View.setItemText(2, _translate("Form", "Std Image", None))
        self.ImagePhys_View.setItemText(3, _translate("Form", "Spectrum Image", None))
        self.ImagePhys_View.setItemText(4, _translate("Form", "Ratio Image", None))
        self.ImagePhys_ImgMethod.setItemText(0, _translate("Form", "dF/Fo", None))
        self.ImagePhys_ImgMethod.setItemText(1, _translate("Form", "median", None))
        self.ImagePhys_ImgMethod.setItemText(2, _translate("Form", "Norm\'d", None))
        self.ImagePhys_ImgMethod.setItemText(3, _translate("Form", "Slow Filter", None))
        self.ImagePhys_ImgMethod.setItemText(4, _translate("Form", "G/R", None))
        self.ImagePhys_ExportTiff.setText(_translate("Form", "Export TIFF", None))
        self.ImagePhys_DisplayTraces.setText(_translate("Form", "Display dF/F", None))
        self.groupBox_5.setTitle(_translate("Form", "Preferences", None))
        self.ImagePhys_RectSelect.setText(_translate("Form", "Select with \n"
"rectangle  box", None))
        self.ImagePhys_PhysROIPlot.setText(_translate("Form", "MultiPlot", None))
        self.ImagePhys_CorrTool_BL1.setText(_translate("Form", "Baseline 1", None))
        self.ImagePhys_FileGroup.setTitle(_translate("Form", "File Operations", None))
        self.ImagePhys_ImageMode.setItemText(0, _translate("Form", "Non-Ratiometric (dF/Fo)", None))
        self.ImagePhys_ImageMode.setItemText(1, _translate("Form", "Ratiometric (G/R)", None))
        self.ImagePhys_clearRatio.setText(_translate("Form", "Clear Ratio Image", None))
        self.ImagePhys_GetFileInfo.setText(_translate("Form", "Get File Info", None))
        self.ImagePhys_getRatio.setText(_translate("Form", "Get Ratio Image", None))
        self.label_5.setText(_translate("Form", "Data Struct", None))
        self.ImagePhys_DataStruct.setItemText(0, _translate("Form", "Flat", None))
        self.ImagePhys_DataStruct.setItemText(1, _translate("Form", "Interleaved", None))
        self.label_4.setText(_translate("Form", "Ignore images", None))
        self.label_2.setText(_translate("Form", "Downsample", None))
        self.ImagePhys_Downsample.setItemText(0, _translate("Form", "1", None))
        self.ImagePhys_Downsample.setItemText(1, _translate("Form", "2", None))
        self.ImagePhys_Downsample.setItemText(2, _translate("Form", "5", None))
        self.ImagePhys_Downsample.setItemText(3, _translate("Form", "10", None))
        self.ImagePhys_Downsample.setItemText(4, _translate("Form", "20", None))
        self.ImagePhys_Downsample.setItemText(5, _translate("Form", "50", None))
        self.ImagePhys_Downsample.setItemText(6, _translate("Form", "100", None))
        self.ImagePhys_Downsample.setItemText(7, _translate("Form", "200", None))
        self.ImagePhys_Downsample.setItemText(8, _translate("Form", "500", None))
        self.ImagePhys_Downsample.setItemText(9, _translate("Form", "1000", None))
        self.groupBox_2.setTitle(_translate("Form", "Corrections", None))
        self.ImagePhys_RegisterStack.setText(_translate("Form", "Register Stack", None))
        self.ImagePhys_UnBleach.setText(_translate("Form", "Bl Corr", None))
        self.ImagePhys_BleachInfo.setText(_translate("Form", "None", None))
        self.ImagePhys_SpecCalc.setText(_translate("Form", "Spectrum Calc", None))
        self.label_7.setText(_translate("Form", "Low", None))
        self.label_8.setText(_translate("Form", "High", None))
        self.label_10.setText(_translate("Form", "Spec Smooth", None))
        self.groupBox_6.setTitle(_translate("Form", "Filtering", None))
        self.label_3.setText(_translate("Form", "Base end", None))
        self.label.setText(_translate("Form", "Base begin", None))
        self.ImagePhys_CorrTool_LPF.setText(_translate("Form", "LPF Signal", None))
        self.ImagePhys_CorrTool_HPF.setText(_translate("Form", "HPF Signal", None))

