# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/modules/pbm_ImageAnalysis/ctrlTemplatePhysiology.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(315, 410)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = Qt.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(Qt.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 1, 2, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setGeometry(Qt.QRect(10, 5, 286, 156))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(Qt.QRect(10, 25, 266, 66))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.ImagePhys_PhysThresh = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.ImagePhys_PhysThresh.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_PhysThresh.setDecimals(1)
        self.ImagePhys_PhysThresh.setMinimum(-1998.0)
        self.ImagePhys_PhysThresh.setMaximum(2000.0)
        self.ImagePhys_PhysThresh.setSingleStep(5.0)
        self.ImagePhys_PhysThresh.setProperty("value", -50.0)
        self.ImagePhys_PhysThresh.setObjectName("ImagePhys_PhysThresh")
        self.gridLayout_4.addWidget(self.ImagePhys_PhysThresh, 1, 1, 1, 1)
        self.ImagePhys_PhysLPF = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.ImagePhys_PhysLPF.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_PhysLPF.setMinimum(-5000.0)
        self.ImagePhys_PhysLPF.setMaximum(50000.0)
        self.ImagePhys_PhysLPF.setProperty("value", 2500.0)
        self.ImagePhys_PhysLPF.setObjectName("ImagePhys_PhysLPF")
        self.gridLayout_4.addWidget(self.ImagePhys_PhysLPF, 0, 1, 1, 1)
        self.ImagePhys_DetectSpikes = QtWidgets.QPushButton(self.groupBox_2)
        self.ImagePhys_DetectSpikes.setGeometry(Qt.QRect(75, 100, 137, 32))
        self.ImagePhys_DetectSpikes.setMinimumSize(Qt.QSize(5, 0))
        self.ImagePhys_DetectSpikes.setObjectName("ImagePhys_DetectSpikes")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_3.setGeometry(Qt.QRect(15, 160, 281, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(Qt.QRect(15, 25, 236, 97))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 2)
        self.ImagePhys_burstISI = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        font = Qt.QFont()
        font.setPointSize(12)
        self.ImagePhys_burstISI.setFont(font)
        self.ImagePhys_burstISI.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_burstISI.setDecimals(1)
        self.ImagePhys_burstISI.setMinimum(1.0)
        self.ImagePhys_burstISI.setMaximum(1000.0)
        self.ImagePhys_burstISI.setSingleStep(10.0)
        self.ImagePhys_burstISI.setProperty("value", 100.0)
        self.ImagePhys_burstISI.setObjectName("ImagePhys_burstISI")
        self.gridLayout_3.addWidget(self.ImagePhys_burstISI, 0, 2, 1, 1)
        self.ImagePhys_minBurstSpikes = QtWidgets.QSpinBox(self.layoutWidget1)
        font = Qt.QFont()
        font.setPointSize(12)
        self.ImagePhys_minBurstSpikes.setFont(font)
        self.ImagePhys_minBurstSpikes.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_minBurstSpikes.setMinimum(2)
        self.ImagePhys_minBurstSpikes.setMaximum(20)
        self.ImagePhys_minBurstSpikes.setProperty("value", 3)
        self.ImagePhys_minBurstSpikes.setObjectName("ImagePhys_minBurstSpikes")
        self.gridLayout_3.addWidget(self.ImagePhys_minBurstSpikes, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 2)
        self.ImagePhys_withinBurstISI = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        font = Qt.QFont()
        font.setPointSize(12)
        self.ImagePhys_withinBurstISI.setFont(font)
        self.ImagePhys_withinBurstISI.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_withinBurstISI.setDecimals(1)
        self.ImagePhys_withinBurstISI.setMinimum(1.0)
        self.ImagePhys_withinBurstISI.setMaximum(1000.0)
        self.ImagePhys_withinBurstISI.setSingleStep(2.0)
        self.ImagePhys_withinBurstISI.setProperty("value", 40.0)
        self.ImagePhys_withinBurstISI.setObjectName("ImagePhys_withinBurstISI")
        self.gridLayout_3.addWidget(self.ImagePhys_withinBurstISI, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.ImagePhys_RevSTA = QtWidgets.QPushButton(self.groupBox_3)
        self.ImagePhys_RevSTA.setEnabled(False)
        self.ImagePhys_RevSTA.setGeometry(Qt.QRect(35, 185, 93, 32))
        self.ImagePhys_RevSTA.setObjectName("ImagePhys_RevSTA")
        self.ImagePhys_BTA = QtWidgets.QPushButton(self.groupBox_3)
        self.ImagePhys_BTA.setGeometry(Qt.QRect(35, 155, 195, 32))
        self.ImagePhys_BTA.setObjectName("ImagePhys_BTA")
        self.ImagePhys_STA = QtWidgets.QPushButton(self.groupBox_3)
        self.ImagePhys_STA.setGeometry(Qt.QRect(35, 125, 197, 32))
        self.ImagePhys_STA.setObjectName("ImagePhys_STA")
        self.gridLayout_2.addWidget(self.widget_2, 1, 0, 2, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Physiology Analysis Functions"))
        self.groupBox_2.setTitle(_translate("Form", "Physiology"))
        self.label_7.setText(_translate("Form", "LPF"))
        self.label_4.setText(_translate("Form", "Event Thresh"))
        self.ImagePhys_PhysThresh.setSuffix(_translate("Form", " pA"))
        self.ImagePhys_DetectSpikes.setText(_translate("Form", "Detect Spikes"))
        self.groupBox_3.setTitle(_translate("Form", "Spike Triggered Averages"))
        self.label_5.setText(_translate("Form", "Minimum # spikes/burst"))
        self.label_9.setText(_translate("Form", "Min Interburst Interval"))
        self.label_8.setText(_translate("Form", "Max burst ISI (msec)"))
        self.ImagePhys_RevSTA.setText(_translate("Form", "Rev STA"))
        self.ImagePhys_BTA.setText(_translate("Form", "Burst-triggered Average"))
        self.ImagePhys_STA.setText(_translate("Form", "Spike-triggered Average"))

