# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/modules/pbm_ImageAnalysis/ctrlROIsTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(384, 410)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(Qt.QSize(384, 410))
        font = Qt.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMaximumSize(Qt.QSize(392, 410))
        font = Qt.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(Qt.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(Qt.QRect(15, 20, 171, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        palette = Qt.QPalette()
        brush = Qt.QBrush(Qt.QColor(99, 99, 99))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Shadow, brush)
        brush = Qt.QBrush(Qt.QColor(99, 99, 99))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Shadow, brush)
        brush = Qt.QBrush(Qt.QColor(99, 99, 99))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Shadow, brush)
        self.groupBox_3.setPalette(palette)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(Qt.QRect(10, 240, 146, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_10.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.ImagePhys_ROIKernel = QtWidgets.QComboBox(self.layoutWidget)
        self.ImagePhys_ROIKernel.setMaximumSize(Qt.QSize(75, 16777215))
        self.ImagePhys_ROIKernel.setToolTip("")
        self.ImagePhys_ROIKernel.setLayoutDirection(Qt.Qt.LeftToRight)
        self.ImagePhys_ROIKernel.setStyleSheet("<align = \'right\'>")
        self.ImagePhys_ROIKernel.setMaxVisibleItems(1)
        self.ImagePhys_ROIKernel.setMaxCount(10)
        self.ImagePhys_ROIKernel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.ImagePhys_ROIKernel.setFrame(False)
        self.ImagePhys_ROIKernel.setModelColumn(0)
        self.ImagePhys_ROIKernel.setObjectName("ImagePhys_ROIKernel")
        self.ImagePhys_ROIKernel.addItem("")
        self.ImagePhys_ROIKernel.addItem("")
        self.ImagePhys_ROIKernel.addItem("")
        self.ImagePhys_ROIKernel.addItem("")
        self.ImagePhys_ROIKernel.addItem("")
        self.ImagePhys_ROIKernel.addItem("")
        self.horizontalLayout_10.addWidget(self.ImagePhys_ROIKernel)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(Qt.QRect(5, 215, 156, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_14.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ImagePhys_StdRB = QtWidgets.QRadioButton(self.layoutWidget1)
        self.ImagePhys_StdRB.setObjectName("ImagePhys_StdRB")
        self.horizontalLayout_14.addWidget(self.ImagePhys_StdRB)
        self.ImagePhys_FFTRB = QtWidgets.QRadioButton(self.layoutWidget1)
        self.ImagePhys_FFTRB.setChecked(True)
        self.ImagePhys_FFTRB.setObjectName("ImagePhys_FFTRB")
        self.horizontalLayout_14.addWidget(self.ImagePhys_FFTRB)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(Qt.QRect(10, 270, 146, 100))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ImagePhys_RecalculateROIs = QtWidgets.QPushButton(self.layoutWidget2)
        self.ImagePhys_RecalculateROIs.setObjectName("ImagePhys_RecalculateROIs")
        self.verticalLayout_2.addWidget(self.ImagePhys_RecalculateROIs)
        self.ImagePhys_RetrieveROI = QtWidgets.QPushButton(self.layoutWidget2)
        self.ImagePhys_RetrieveROI.setObjectName("ImagePhys_RetrieveROI")
        self.verticalLayout_2.addWidget(self.ImagePhys_RetrieveROI)
        self.ImagePhys_SaveROI = QtWidgets.QPushButton(self.layoutWidget2)
        self.ImagePhys_SaveROI.setObjectName("ImagePhys_SaveROI")
        self.verticalLayout_2.addWidget(self.ImagePhys_SaveROI)
        self.widget = QtWidgets.QWidget(self.groupBox_3)
        self.widget.setGeometry(Qt.QRect(5, 20, 161, 136))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ImagePhys_addRoi = QtWidgets.QPushButton(self.widget)
        self.ImagePhys_addRoi.setObjectName("ImagePhys_addRoi")
        self.gridLayout_2.addWidget(self.ImagePhys_addRoi, 0, 0, 1, 1)
        self.ImagePhys_clearRoi = QtWidgets.QPushButton(self.widget)
        self.ImagePhys_clearRoi.setObjectName("ImagePhys_clearRoi")
        self.gridLayout_2.addWidget(self.ImagePhys_clearRoi, 1, 0, 1, 1)
        self.ImagePhys_findROIs = QtWidgets.QPushButton(self.widget)
        self.ImagePhys_findROIs.setObjectName("ImagePhys_findROIs")
        self.gridLayout_2.addWidget(self.ImagePhys_findROIs, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.ImagePhys_ROISize = QtWidgets.QSpinBox(self.widget)
        self.ImagePhys_ROISize.setMinimum(1)
        self.ImagePhys_ROISize.setMaximum(25)
        self.ImagePhys_ROISize.setProperty("value", 2)
        self.ImagePhys_ROISize.setObjectName("ImagePhys_ROISize")
        self.horizontalLayout_3.addWidget(self.ImagePhys_ROISize)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.groupBox_3)
        self.widget1.setGeometry(Qt.QRect(5, 160, 161, 53))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(self.widget1)
        self.label_11.setAlignment(Qt.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.ImagePhys_ROIThrLow = QtWidgets.QDoubleSpinBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_ROIThrLow.sizePolicy().hasHeightForWidth())
        self.ImagePhys_ROIThrLow.setSizePolicy(sizePolicy)
        self.ImagePhys_ROIThrLow.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_ROIThrLow.setMinimum(0.01)
        self.ImagePhys_ROIThrLow.setMaximum(1.0)
        self.ImagePhys_ROIThrLow.setSingleStep(0.1)
        self.ImagePhys_ROIThrLow.setProperty("value", 0.2)
        self.ImagePhys_ROIThrLow.setObjectName("ImagePhys_ROIThrLow")
        self.verticalLayout.addWidget(self.ImagePhys_ROIThrLow)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.widget1)
        self.label_12.setAlignment(Qt.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.ImagePhys_ROIThrHigh = QtWidgets.QDoubleSpinBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_ROIThrHigh.sizePolicy().hasHeightForWidth())
        self.ImagePhys_ROIThrHigh.setSizePolicy(sizePolicy)
        self.ImagePhys_ROIThrHigh.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_ROIThrHigh.setMinimum(0.1)
        self.ImagePhys_ROIThrHigh.setMaximum(1.0)
        self.ImagePhys_ROIThrHigh.setSingleStep(0.1)
        self.ImagePhys_ROIThrHigh.setProperty("value", 1.0)
        self.ImagePhys_ROIThrHigh.setObjectName("ImagePhys_ROIThrHigh")
        self.verticalLayout_3.addWidget(self.ImagePhys_ROIThrHigh)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(Qt.QRect(205, 20, 156, 191))
        self.groupBox_2.setMinimumSize(Qt.QSize(120, 190))
        self.groupBox_2.setObjectName("groupBox_2")
        self.ImagePhys_RegisterStack = QtWidgets.QPushButton(self.groupBox_2)
        self.ImagePhys_RegisterStack.setGeometry(Qt.QRect(0, 15, 151, 29))
        self.ImagePhys_RegisterStack.setObjectName("ImagePhys_RegisterStack")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(Qt.QRect(0, 40, 141, 32))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ImagePhys_UnBleach = QtWidgets.QPushButton(self.layoutWidget3)
        self.ImagePhys_UnBleach.setCheckable(True)
        self.ImagePhys_UnBleach.setObjectName("ImagePhys_UnBleach")
        self.horizontalLayout_6.addWidget(self.ImagePhys_UnBleach)
        self.ImagePhys_BleachInfo = QtWidgets.QLabel(self.layoutWidget3)
        self.ImagePhys_BleachInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ImagePhys_BleachInfo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ImagePhys_BleachInfo.setAlignment(Qt.Qt.AlignCenter)
        self.ImagePhys_BleachInfo.setObjectName("ImagePhys_BleachInfo")
        self.horizontalLayout_6.addWidget(self.ImagePhys_BleachInfo)
        self.ImagePhys_SpecCalc = QtWidgets.QPushButton(self.groupBox_2)
        self.ImagePhys_SpecCalc.setGeometry(Qt.QRect(0, 70, 151, 30))
        self.ImagePhys_SpecCalc.setObjectName("ImagePhys_SpecCalc")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(Qt.QRect(0, 95, 146, 27))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.ImagePhys_SpecHPF = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.ImagePhys_SpecHPF.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_SpecHPF.setProperty("value", 1.0)
        self.ImagePhys_SpecHPF.setObjectName("ImagePhys_SpecHPF")
        self.horizontalLayout.addWidget(self.ImagePhys_SpecHPF)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget5.setGeometry(Qt.QRect(0, 125, 146, 27))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_11.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.ImagePhys_SpecLPF = QtWidgets.QDoubleSpinBox(self.layoutWidget5)
        self.ImagePhys_SpecLPF.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_SpecLPF.setProperty("value", 10.0)
        self.ImagePhys_SpecLPF.setObjectName("ImagePhys_SpecLPF")
        self.horizontalLayout_11.addWidget(self.ImagePhys_SpecLPF)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget6.setGeometry(Qt.QRect(1, 155, 149, 27))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_12.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.ImagePhys_FFTSmooth = QtWidgets.QSpinBox(self.layoutWidget6)
        self.ImagePhys_FFTSmooth.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_FFTSmooth.setMaximum(16)
        self.ImagePhys_FFTSmooth.setObjectName("ImagePhys_FFTSmooth")
        self.horizontalLayout_12.addWidget(self.ImagePhys_FFTSmooth)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(Qt.QRect(205, 220, 161, 161))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget7.setGeometry(Qt.QRect(5, 51, 152, 31))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_7.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.ImagePhys_BaseEnd = QtWidgets.QDoubleSpinBox(self.layoutWidget7)
        self.ImagePhys_BaseEnd.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_BaseEnd.setMinimum(-5000.0)
        self.ImagePhys_BaseEnd.setMaximum(50000.0)
        self.ImagePhys_BaseEnd.setObjectName("ImagePhys_BaseEnd")
        self.horizontalLayout_7.addWidget(self.ImagePhys_BaseEnd)
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget8.setGeometry(Qt.QRect(5, 20, 152, 27))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget8)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.ImagePhys_BaseStart = QtWidgets.QDoubleSpinBox(self.layoutWidget8)
        self.ImagePhys_BaseStart.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_BaseStart.setMinimum(-5000.0)
        self.ImagePhys_BaseStart.setMaximum(50000.0)
        self.ImagePhys_BaseStart.setObjectName("ImagePhys_BaseStart")
        self.horizontalLayout_2.addWidget(self.ImagePhys_BaseStart)
        self.layoutWidget9 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget9.setGeometry(Qt.QRect(5, 85, 151, 32))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_8.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ImagePhys_CorrTool_LPF = QtWidgets.QCheckBox(self.layoutWidget9)
        self.ImagePhys_CorrTool_LPF.setEnabled(True)
        self.ImagePhys_CorrTool_LPF.setLayoutDirection(Qt.Qt.RightToLeft)
        self.ImagePhys_CorrTool_LPF.setObjectName("ImagePhys_CorrTool_LPF")
        self.horizontalLayout_8.addWidget(self.ImagePhys_CorrTool_LPF)
        self.ImagePhys_ImgLPF = QtWidgets.QDoubleSpinBox(self.layoutWidget9)
        self.ImagePhys_ImgLPF.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_ImgLPF.setDecimals(2)
        self.ImagePhys_ImgLPF.setMinimum(0.1)
        self.ImagePhys_ImgLPF.setMaximum(5000.0)
        self.ImagePhys_ImgLPF.setSingleStep(1.0)
        self.ImagePhys_ImgLPF.setProperty("value", 20.0)
        self.ImagePhys_ImgLPF.setObjectName("ImagePhys_ImgLPF")
        self.horizontalLayout_8.addWidget(self.ImagePhys_ImgLPF)
        self.layoutWidget10 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget10.setGeometry(Qt.QRect(5, 120, 151, 32))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_9.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ImagePhys_CorrTool_HPF = QtWidgets.QCheckBox(self.layoutWidget10)
        self.ImagePhys_CorrTool_HPF.setLayoutDirection(Qt.Qt.RightToLeft)
        self.ImagePhys_CorrTool_HPF.setObjectName("ImagePhys_CorrTool_HPF")
        self.horizontalLayout_9.addWidget(self.ImagePhys_CorrTool_HPF)
        self.ImagePhys_ImgHPF = QtWidgets.QDoubleSpinBox(self.layoutWidget10)
        self.ImagePhys_ImgHPF.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_ImgHPF.setSuffix("")
        self.ImagePhys_ImgHPF.setDecimals(3)
        self.ImagePhys_ImgHPF.setMinimum(0.001)
        self.ImagePhys_ImgHPF.setMaximum(10.0)
        self.ImagePhys_ImgHPF.setSingleStep(0.2)
        self.ImagePhys_ImgHPF.setProperty("value", 0.2)
        self.ImagePhys_ImgHPF.setObjectName("ImagePhys_ImgHPF")
        self.horizontalLayout_9.addWidget(self.ImagePhys_ImgHPF)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.ImagePhys_ROIKernel.setCurrentIndex(1)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Corrections, ROI\'s and Filtering"))
        self.groupBox_3.setTitle(_translate("Form", "ROIs"))
        self.label_6.setText(_translate("Form", "Kernel"))
        self.ImagePhys_ROIKernel.setItemText(0, _translate("Form", "1"))
        self.ImagePhys_ROIKernel.setItemText(1, _translate("Form", "3"))
        self.ImagePhys_ROIKernel.setItemText(2, _translate("Form", "5"))
        self.ImagePhys_ROIKernel.setItemText(3, _translate("Form", "7"))
        self.ImagePhys_ROIKernel.setItemText(4, _translate("Form", "9"))
        self.ImagePhys_ROIKernel.setItemText(5, _translate("Form", "11"))
        self.ImagePhys_StdRB.setText(_translate("Form", "Std"))
        self.ImagePhys_FFTRB.setText(_translate("Form", "FFT"))
        self.ImagePhys_RecalculateROIs.setText(_translate("Form", "Recalc ROIs"))
        self.ImagePhys_RetrieveROI.setText(_translate("Form", "Get ROI File"))
        self.ImagePhys_SaveROI.setText(_translate("Form", "Save ROI File"))
        self.ImagePhys_addRoi.setText(_translate("Form", "Add Roi"))
        self.ImagePhys_clearRoi.setText(_translate("Form", "Clear ROIs"))
        self.ImagePhys_findROIs.setText(_translate("Form", "Auto ROI"))
        self.label_13.setText(_translate("Form", "ROI Size"))
        self.label_11.setText(_translate("Form", "Thr(L)"))
        self.label_12.setText(_translate("Form", "Thr(H)"))
        self.groupBox_2.setTitle(_translate("Form", "Corrections"))
        self.ImagePhys_RegisterStack.setText(_translate("Form", "Register Stack"))
        self.ImagePhys_UnBleach.setText(_translate("Form", "Bl Corr"))
        self.ImagePhys_BleachInfo.setText(_translate("Form", "None"))
        self.ImagePhys_SpecCalc.setText(_translate("Form", "Spectrum Calc"))
        self.label_7.setText(_translate("Form", "Low"))
        self.label_8.setText(_translate("Form", "High"))
        self.label_10.setText(_translate("Form", "Spec Smooth"))
        self.groupBox_6.setTitle(_translate("Form", "ROI Result Filtering"))
        self.label_3.setText(_translate("Form", "Base1(s)"))
        self.label.setText(_translate("Form", "Base0(s)"))
        self.ImagePhys_CorrTool_LPF.setText(_translate("Form", "LPF (Hz)"))
        self.ImagePhys_CorrTool_HPF.setText(_translate("Form", "HPF (Hz)"))

