# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/modules/pbm_ImageAnalysis/ctrlROIsTemplate.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from acq4.util import Qt

try:
    _fromUtf8 = Qt.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = Qt.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return Qt.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return Qt.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(384, 410)
        sizePolicy = Qt.QSizePolicy(Qt.QSizePolicy.Minimum, Qt.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(Qt.QSize(384, 410))
        font = Qt.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        Form.setFont(font)
        self.gridLayout = Qt.QGridLayout(Form)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = Qt.QGroupBox(Form)
        self.groupBox.setMaximumSize(Qt.QSize(392, 410))
        font = Qt.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(Qt.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_3 = Qt.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(Qt.QRect(15, 20, 171, 371))
        sizePolicy = Qt.QSizePolicy(Qt.QSizePolicy.Preferred, Qt.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        palette = Qt.QPalette()
        brush = Qt.QBrush(Qt.QColor(99, 99, 99))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Active, Qt.QPalette.Shadow, brush)
        brush = Qt.QBrush(Qt.QColor(99, 99, 99))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Inactive, Qt.QPalette.Shadow, brush)
        brush = Qt.QBrush(Qt.QColor(99, 99, 99))
        brush.setStyle(Qt.Qt.SolidPattern)
        palette.setBrush(Qt.QPalette.Disabled, Qt.QPalette.Shadow, brush)
        self.groupBox_3.setPalette(palette)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget = Qt.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(Qt.QRect(10, 240, 146, 26))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_10 = Qt.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_10.setMargin(9)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_6 = Qt.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_10.addWidget(self.label_6)
        self.ImagePhys_ROIKernel = Qt.QComboBox(self.layoutWidget)
        self.ImagePhys_ROIKernel.setMaximumSize(Qt.QSize(75, 16777215))
        self.ImagePhys_ROIKernel.setToolTip(_fromUtf8(""))
        self.ImagePhys_ROIKernel.setLayoutDirection(Qt.Qt.LeftToRight)
        self.ImagePhys_ROIKernel.setStyleSheet(_fromUtf8("<align = \'right\'>"))
        self.ImagePhys_ROIKernel.setMaxVisibleItems(1)
        self.ImagePhys_ROIKernel.setMaxCount(10)
        self.ImagePhys_ROIKernel.setSizeAdjustPolicy(Qt.QComboBox.AdjustToMinimumContentsLength)
        self.ImagePhys_ROIKernel.setFrame(False)
        self.ImagePhys_ROIKernel.setModelColumn(0)
        self.ImagePhys_ROIKernel.setObjectName(_fromUtf8("ImagePhys_ROIKernel"))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.ImagePhys_ROIKernel)
        self.layoutWidget1 = Qt.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(Qt.QRect(5, 215, 156, 25))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_14 = Qt.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_14.setMargin(9)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.ImagePhys_StdRB = Qt.QRadioButton(self.layoutWidget1)
        self.ImagePhys_StdRB.setObjectName(_fromUtf8("ImagePhys_StdRB"))
        self.horizontalLayout_14.addWidget(self.ImagePhys_StdRB)
        self.ImagePhys_FFTRB = Qt.QRadioButton(self.layoutWidget1)
        self.ImagePhys_FFTRB.setChecked(True)
        self.ImagePhys_FFTRB.setObjectName(_fromUtf8("ImagePhys_FFTRB"))
        self.horizontalLayout_14.addWidget(self.ImagePhys_FFTRB)
        self.layoutWidget2 = Qt.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(Qt.QRect(10, 270, 146, 100))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = Qt.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setMargin(9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.ImagePhys_RecalculateROIs = Qt.QPushButton(self.layoutWidget2)
        self.ImagePhys_RecalculateROIs.setObjectName(_fromUtf8("ImagePhys_RecalculateROIs"))
        self.verticalLayout_2.addWidget(self.ImagePhys_RecalculateROIs)
        self.ImagePhys_RetrieveROI = Qt.QPushButton(self.layoutWidget2)
        self.ImagePhys_RetrieveROI.setObjectName(_fromUtf8("ImagePhys_RetrieveROI"))
        self.verticalLayout_2.addWidget(self.ImagePhys_RetrieveROI)
        self.ImagePhys_SaveROI = Qt.QPushButton(self.layoutWidget2)
        self.ImagePhys_SaveROI.setObjectName(_fromUtf8("ImagePhys_SaveROI"))
        self.verticalLayout_2.addWidget(self.ImagePhys_SaveROI)
        self.widget = Qt.QWidget(self.groupBox_3)
        self.widget.setGeometry(Qt.QRect(5, 20, 161, 136))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = Qt.QGridLayout(self.widget)
        self.gridLayout_2.setMargin(9)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ImagePhys_addRoi = Qt.QPushButton(self.widget)
        self.ImagePhys_addRoi.setObjectName(_fromUtf8("ImagePhys_addRoi"))
        self.gridLayout_2.addWidget(self.ImagePhys_addRoi, 0, 0, 1, 1)
        self.ImagePhys_clearRoi = Qt.QPushButton(self.widget)
        self.ImagePhys_clearRoi.setObjectName(_fromUtf8("ImagePhys_clearRoi"))
        self.gridLayout_2.addWidget(self.ImagePhys_clearRoi, 1, 0, 1, 1)
        self.ImagePhys_findROIs = Qt.QPushButton(self.widget)
        self.ImagePhys_findROIs.setObjectName(_fromUtf8("ImagePhys_findROIs"))
        self.gridLayout_2.addWidget(self.ImagePhys_findROIs, 2, 0, 1, 1)
        self.horizontalLayout_3 = Qt.QHBoxLayout()
        self.horizontalLayout_3.setMargin(9)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_13 = Qt.QLabel(self.widget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_3.addWidget(self.label_13)
        self.ImagePhys_ROISize = Qt.QSpinBox(self.widget)
        self.ImagePhys_ROISize.setMinimum(1)
        self.ImagePhys_ROISize.setMaximum(25)
        self.ImagePhys_ROISize.setProperty("value", 2)
        self.ImagePhys_ROISize.setObjectName(_fromUtf8("ImagePhys_ROISize"))
        self.horizontalLayout_3.addWidget(self.ImagePhys_ROISize)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.widget1 = Qt.QWidget(self.groupBox_3)
        self.widget1.setGeometry(Qt.QRect(5, 160, 161, 53))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_4 = Qt.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setMargin(9)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = Qt.QVBoxLayout()
        self.verticalLayout.setMargin(9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_11 = Qt.QLabel(self.widget1)
        self.label_11.setAlignment(Qt.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.ImagePhys_ROIThrLow = Qt.QDoubleSpinBox(self.widget1)
        sizePolicy = Qt.QSizePolicy(Qt.QSizePolicy.Minimum, Qt.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_ROIThrLow.sizePolicy().hasHeightForWidth())
        self.ImagePhys_ROIThrLow.setSizePolicy(sizePolicy)
        self.ImagePhys_ROIThrLow.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_ROIThrLow.setMinimum(0.01)
        self.ImagePhys_ROIThrLow.setMaximum(1.0)
        self.ImagePhys_ROIThrLow.setSingleStep(0.1)
        self.ImagePhys_ROIThrLow.setProperty("value", 0.2)
        self.ImagePhys_ROIThrLow.setObjectName(_fromUtf8("ImagePhys_ROIThrLow"))
        self.verticalLayout.addWidget(self.ImagePhys_ROIThrLow)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = Qt.QVBoxLayout()
        self.verticalLayout_3.setMargin(9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_12 = Qt.QLabel(self.widget1)
        self.label_12.setAlignment(Qt.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_3.addWidget(self.label_12)
        self.ImagePhys_ROIThrHigh = Qt.QDoubleSpinBox(self.widget1)
        sizePolicy = Qt.QSizePolicy(Qt.QSizePolicy.Minimum, Qt.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_ROIThrHigh.sizePolicy().hasHeightForWidth())
        self.ImagePhys_ROIThrHigh.setSizePolicy(sizePolicy)
        self.ImagePhys_ROIThrHigh.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_ROIThrHigh.setMinimum(0.1)
        self.ImagePhys_ROIThrHigh.setMaximum(1.0)
        self.ImagePhys_ROIThrHigh.setSingleStep(0.1)
        self.ImagePhys_ROIThrHigh.setProperty("value", 1.0)
        self.ImagePhys_ROIThrHigh.setObjectName(_fromUtf8("ImagePhys_ROIThrHigh"))
        self.verticalLayout_3.addWidget(self.ImagePhys_ROIThrHigh)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.groupBox_2 = Qt.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(Qt.QRect(205, 20, 156, 191))
        self.groupBox_2.setMinimumSize(Qt.QSize(120, 190))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.ImagePhys_RegisterStack = Qt.QPushButton(self.groupBox_2)
        self.ImagePhys_RegisterStack.setGeometry(Qt.QRect(0, 15, 151, 29))
        self.ImagePhys_RegisterStack.setObjectName(_fromUtf8("ImagePhys_RegisterStack"))
        self.layoutWidget3 = Qt.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(Qt.QRect(0, 40, 141, 32))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_6 = Qt.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setMargin(9)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.ImagePhys_UnBleach = Qt.QPushButton(self.layoutWidget3)
        self.ImagePhys_UnBleach.setCheckable(True)
        self.ImagePhys_UnBleach.setObjectName(_fromUtf8("ImagePhys_UnBleach"))
        self.horizontalLayout_6.addWidget(self.ImagePhys_UnBleach)
        self.ImagePhys_BleachInfo = Qt.QLabel(self.layoutWidget3)
        self.ImagePhys_BleachInfo.setFrameShape(Qt.QFrame.StyledPanel)
        self.ImagePhys_BleachInfo.setFrameShadow(Qt.QFrame.Sunken)
        self.ImagePhys_BleachInfo.setAlignment(Qt.Qt.AlignCenter)
        self.ImagePhys_BleachInfo.setObjectName(_fromUtf8("ImagePhys_BleachInfo"))
        self.horizontalLayout_6.addWidget(self.ImagePhys_BleachInfo)
        self.ImagePhys_SpecCalc = Qt.QPushButton(self.groupBox_2)
        self.ImagePhys_SpecCalc.setGeometry(Qt.QRect(0, 70, 151, 30))
        self.ImagePhys_SpecCalc.setObjectName(_fromUtf8("ImagePhys_SpecCalc"))
        self.layoutWidget4 = Qt.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(Qt.QRect(0, 95, 146, 27))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout = Qt.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setMargin(9)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = Qt.QLabel(self.layoutWidget4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.ImagePhys_SpecHPF = Qt.QDoubleSpinBox(self.layoutWidget4)
        self.ImagePhys_SpecHPF.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_SpecHPF.setProperty("value", 1.0)
        self.ImagePhys_SpecHPF.setObjectName(_fromUtf8("ImagePhys_SpecHPF"))
        self.horizontalLayout.addWidget(self.ImagePhys_SpecHPF)
        self.layoutWidget5 = Qt.QWidget(self.groupBox_2)
        self.layoutWidget5.setGeometry(Qt.QRect(0, 125, 146, 27))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_11 = Qt.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_11.setMargin(9)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_8 = Qt.QLabel(self.layoutWidget5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_11.addWidget(self.label_8)
        self.ImagePhys_SpecLPF = Qt.QDoubleSpinBox(self.layoutWidget5)
        self.ImagePhys_SpecLPF.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_SpecLPF.setProperty("value", 10.0)
        self.ImagePhys_SpecLPF.setObjectName(_fromUtf8("ImagePhys_SpecLPF"))
        self.horizontalLayout_11.addWidget(self.ImagePhys_SpecLPF)
        self.layoutWidget6 = Qt.QWidget(self.groupBox_2)
        self.layoutWidget6.setGeometry(Qt.QRect(1, 155, 149, 27))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_12 = Qt.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_12.setMargin(9)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = Qt.QLabel(self.layoutWidget6)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        self.ImagePhys_FFTSmooth = Qt.QSpinBox(self.layoutWidget6)
        self.ImagePhys_FFTSmooth.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_FFTSmooth.setMaximum(16)
        self.ImagePhys_FFTSmooth.setObjectName(_fromUtf8("ImagePhys_FFTSmooth"))
        self.horizontalLayout_12.addWidget(self.ImagePhys_FFTSmooth)
        self.groupBox_6 = Qt.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(Qt.QRect(205, 220, 161, 161))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.layoutWidget7 = Qt.QWidget(self.groupBox_6)
        self.layoutWidget7.setGeometry(Qt.QRect(5, 51, 152, 31))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.horizontalLayout_7 = Qt.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_7.setMargin(9)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = Qt.QLabel(self.layoutWidget7)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.ImagePhys_BaseEnd = Qt.QDoubleSpinBox(self.layoutWidget7)
        self.ImagePhys_BaseEnd.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_BaseEnd.setMinimum(-5000.0)
        self.ImagePhys_BaseEnd.setMaximum(50000.0)
        self.ImagePhys_BaseEnd.setObjectName(_fromUtf8("ImagePhys_BaseEnd"))
        self.horizontalLayout_7.addWidget(self.ImagePhys_BaseEnd)
        self.layoutWidget8 = Qt.QWidget(self.groupBox_6)
        self.layoutWidget8.setGeometry(Qt.QRect(5, 20, 152, 27))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.horizontalLayout_2 = Qt.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_2.setMargin(9)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = Qt.QLabel(self.layoutWidget8)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.ImagePhys_BaseStart = Qt.QDoubleSpinBox(self.layoutWidget8)
        self.ImagePhys_BaseStart.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_BaseStart.setMinimum(-5000.0)
        self.ImagePhys_BaseStart.setMaximum(50000.0)
        self.ImagePhys_BaseStart.setObjectName(_fromUtf8("ImagePhys_BaseStart"))
        self.horizontalLayout_2.addWidget(self.ImagePhys_BaseStart)
        self.layoutWidget9 = Qt.QWidget(self.groupBox_6)
        self.layoutWidget9.setGeometry(Qt.QRect(5, 85, 151, 32))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.horizontalLayout_8 = Qt.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_8.setMargin(9)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.ImagePhys_CorrTool_LPF = Qt.QCheckBox(self.layoutWidget9)
        self.ImagePhys_CorrTool_LPF.setEnabled(True)
        self.ImagePhys_CorrTool_LPF.setLayoutDirection(Qt.Qt.RightToLeft)
        self.ImagePhys_CorrTool_LPF.setObjectName(_fromUtf8("ImagePhys_CorrTool_LPF"))
        self.horizontalLayout_8.addWidget(self.ImagePhys_CorrTool_LPF)
        self.ImagePhys_ImgLPF = Qt.QDoubleSpinBox(self.layoutWidget9)
        self.ImagePhys_ImgLPF.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_ImgLPF.setDecimals(2)
        self.ImagePhys_ImgLPF.setMinimum(0.1)
        self.ImagePhys_ImgLPF.setMaximum(5000.0)
        self.ImagePhys_ImgLPF.setSingleStep(1.0)
        self.ImagePhys_ImgLPF.setProperty("value", 20.0)
        self.ImagePhys_ImgLPF.setObjectName(_fromUtf8("ImagePhys_ImgLPF"))
        self.horizontalLayout_8.addWidget(self.ImagePhys_ImgLPF)
        self.layoutWidget10 = Qt.QWidget(self.groupBox_6)
        self.layoutWidget10.setGeometry(Qt.QRect(5, 120, 151, 32))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.horizontalLayout_9 = Qt.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_9.setMargin(9)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.ImagePhys_CorrTool_HPF = Qt.QCheckBox(self.layoutWidget10)
        self.ImagePhys_CorrTool_HPF.setLayoutDirection(Qt.Qt.RightToLeft)
        self.ImagePhys_CorrTool_HPF.setObjectName(_fromUtf8("ImagePhys_CorrTool_HPF"))
        self.horizontalLayout_9.addWidget(self.ImagePhys_CorrTool_HPF)
        self.ImagePhys_ImgHPF = Qt.QDoubleSpinBox(self.layoutWidget10)
        self.ImagePhys_ImgHPF.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.ImagePhys_ImgHPF.setSuffix(_fromUtf8(""))
        self.ImagePhys_ImgHPF.setDecimals(3)
        self.ImagePhys_ImgHPF.setMinimum(0.001)
        self.ImagePhys_ImgHPF.setMaximum(10.0)
        self.ImagePhys_ImgHPF.setSingleStep(0.2)
        self.ImagePhys_ImgHPF.setProperty("value", 0.2)
        self.ImagePhys_ImgHPF.setObjectName(_fromUtf8("ImagePhys_ImgHPF"))
        self.horizontalLayout_9.addWidget(self.ImagePhys_ImgHPF)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.ImagePhys_ROIKernel.setCurrentIndex(1)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox.setTitle(_translate("Form", "Corrections, ROI\'s and Filtering", None))
        self.groupBox_3.setTitle(_translate("Form", "ROIs", None))
        self.label_6.setText(_translate("Form", "Kernel", None))
        self.ImagePhys_ROIKernel.setItemText(0, _translate("Form", "1", None))
        self.ImagePhys_ROIKernel.setItemText(1, _translate("Form", "3", None))
        self.ImagePhys_ROIKernel.setItemText(2, _translate("Form", "5", None))
        self.ImagePhys_ROIKernel.setItemText(3, _translate("Form", "7", None))
        self.ImagePhys_ROIKernel.setItemText(4, _translate("Form", "9", None))
        self.ImagePhys_ROIKernel.setItemText(5, _translate("Form", "11", None))
        self.ImagePhys_StdRB.setText(_translate("Form", "Std", None))
        self.ImagePhys_FFTRB.setText(_translate("Form", "FFT", None))
        self.ImagePhys_RecalculateROIs.setText(_translate("Form", "Recalc ROIs", None))
        self.ImagePhys_RetrieveROI.setText(_translate("Form", "Get ROI File", None))
        self.ImagePhys_SaveROI.setText(_translate("Form", "Save ROI File", None))
        self.ImagePhys_addRoi.setText(_translate("Form", "Add Roi", None))
        self.ImagePhys_clearRoi.setText(_translate("Form", "Clear ROIs", None))
        self.ImagePhys_findROIs.setText(_translate("Form", "Auto ROI", None))
        self.label_13.setText(_translate("Form", "ROI Size", None))
        self.label_11.setText(_translate("Form", "Thr(L)", None))
        self.label_12.setText(_translate("Form", "Thr(H)", None))
        self.groupBox_2.setTitle(_translate("Form", "Corrections", None))
        self.ImagePhys_RegisterStack.setText(_translate("Form", "Register Stack", None))
        self.ImagePhys_UnBleach.setText(_translate("Form", "Bl Corr", None))
        self.ImagePhys_BleachInfo.setText(_translate("Form", "None", None))
        self.ImagePhys_SpecCalc.setText(_translate("Form", "Spectrum Calc", None))
        self.label_7.setText(_translate("Form", "Low", None))
        self.label_8.setText(_translate("Form", "High", None))
        self.label_10.setText(_translate("Form", "Spec Smooth", None))
        self.groupBox_6.setTitle(_translate("Form", "ROI Result Filtering", None))
        self.label_3.setText(_translate("Form", "Base1(s)", None))
        self.label.setText(_translate("Form", "Base0(s)", None))
        self.ImagePhys_CorrTool_LPF.setText(_translate("Form", "LPF (Hz)", None))
        self.ImagePhys_CorrTool_HPF.setText(_translate("Form", "HPF (Hz)", None))

