# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - libopengl0

sphinx:
  fail_on_warning: false
  configuration: doc/source/conf.py

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
