# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EventDetectionCtrlTemplate.ui'
#
# Created: Mon Jun 28 23:46:42 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_EventDetectionCtrlForm(object):
    def setupUi(self, EventDetectionCtrlForm):
        EventDetectionCtrlForm.setObjectName("EventDetectionCtrlForm")
        EventDetectionCtrlForm.resize(305, 313)
        self.verticalLayout_3 = QtGui.QVBoxLayout(EventDetectionCtrlForm)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(EventDetectionCtrlForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.preFilterList = FilterList(self.groupBox_2)
        self.preFilterList.setObjectName("preFilterList")
        self.gridLayout_3.addWidget(self.preFilterList, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(EventDetectionCtrlForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.detectMethodCombo = QtGui.QComboBox(self.groupBox)
        self.detectMethodCombo.setObjectName("detectMethodCombo")
        self.detectMethodCombo.addItem("")
        self.detectMethodCombo.addItem("")
        self.detectMethodCombo.addItem("")
        self.verticalLayout.addWidget(self.detectMethodCombo)
        self.detectMethodStack = QtGui.QStackedWidget(self.groupBox)
        self.detectMethodStack.setObjectName("detectMethodStack")
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtGui.QLabel(self.page_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.stThresholdSpin = SpinBox(self.page_3)
        self.stThresholdSpin.setProperty("value", 3.0)
        self.stThresholdSpin.setObjectName("stThresholdSpin")
        self.gridLayout_4.addWidget(self.stThresholdSpin, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.detectMethodStack.addWidget(self.page_3)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.page_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.zcSumThresholdSpin = QtGui.QDoubleSpinBox(self.page_2)
        self.zcSumThresholdSpin.setProperty("value", 8.0)
        self.zcSumThresholdSpin.setObjectName("zcSumThresholdSpin")
        self.gridLayout.addWidget(self.zcSumThresholdSpin, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.zcAmpThresholdSpin = QtGui.QDoubleSpinBox(self.page_2)
        self.zcAmpThresholdSpin.setProperty("value", 8.0)
        self.zcAmpThresholdSpin.setObjectName("zcAmpThresholdSpin")
        self.gridLayout.addWidget(self.zcAmpThresholdSpin, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.detectMethodStack.addWidget(self.page_2)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.cbThresholdSpin = QtGui.QDoubleSpinBox(self.page)
        self.cbThresholdSpin.setProperty("value", 4.0)
        self.cbThresholdSpin.setObjectName("cbThresholdSpin")
        self.gridLayout_2.addWidget(self.cbThresholdSpin, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.cbRiseTauSpin = QtGui.QDoubleSpinBox(self.page)
        self.cbRiseTauSpin.setProperty("value", 0.01)
        self.cbRiseTauSpin.setObjectName("cbRiseTauSpin")
        self.gridLayout_2.addWidget(self.cbRiseTauSpin, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.cbFallTauSpin = QtGui.QDoubleSpinBox(self.page)
        self.cbFallTauSpin.setProperty("value", 0.01)
        self.cbFallTauSpin.setObjectName("cbFallTauSpin")
        self.gridLayout_2.addWidget(self.cbFallTauSpin, 2, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.detectMethodStack.addWidget(self.page)
        self.verticalLayout.addWidget(self.detectMethodStack)
        self.verticalLayout_3.addWidget(self.groupBox)

        self.retranslateUi(EventDetectionCtrlForm)
        self.detectMethodStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(EventDetectionCtrlForm)

    def retranslateUi(self, EventDetectionCtrlForm):
        EventDetectionCtrlForm.setWindowTitle(QtGui.QApplication.translate("EventDetectionCtrlForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setToolTip(QtGui.QApplication.translate("EventDetectionCtrlForm", "Pre-processing options. Used for processing data before any event detection takes place. Processing is performed in the order listed.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("EventDetectionCtrlForm", "Pre-processing", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("EventDetectionCtrlForm", "Event Detection", None, QtGui.QApplication.UnicodeUTF8))
        self.detectMethodCombo.setItemText(0, QtGui.QApplication.translate("EventDetectionCtrlForm", "Stdev. Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.detectMethodCombo.setItemText(1, QtGui.QApplication.translate("EventDetectionCtrlForm", "Zero-crossing", None, QtGui.QApplication.UnicodeUTF8))
        self.detectMethodCombo.setItemText(2, QtGui.QApplication.translate("EventDetectionCtrlForm", "Clements-Bekkers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("EventDetectionCtrlForm", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("EventDetectionCtrlForm", "Sum Thresh.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("EventDetectionCtrlForm", "Amp. Thresh.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("EventDetectionCtrlForm", "Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("EventDetectionCtrlForm", "Rise Tau", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("EventDetectionCtrlForm", "Fall Tau", None, QtGui.QApplication.UnicodeUTF8))

from FilterList import FilterList
from lib.util.SpinBox import SpinBox
