# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UncagingControlTemplate.ui'
#
# Created: Wed May 19 11:39:49 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_UncagingControlWidget(object):
    def setupUi(self, UncagingControlWidget):
        UncagingControlWidget.setObjectName("UncagingControlWidget")
        UncagingControlWidget.resize(463, 296)
        self.gridLayout = QtGui.QGridLayout(UncagingControlWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(UncagingControlWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.thresholdSpin = QtGui.QDoubleSpinBox(UncagingControlWidget)
        self.thresholdSpin.setObjectName("thresholdSpin")
        self.horizontalLayout.addWidget(self.thresholdSpin)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(UncagingControlWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.directTimeSpin = QtGui.QDoubleSpinBox(UncagingControlWidget)
        self.directTimeSpin.setObjectName("directTimeSpin")
        self.horizontalLayout_2.addWidget(self.directTimeSpin)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(UncagingControlWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.poststimTimeSpin = QtGui.QDoubleSpinBox(UncagingControlWidget)
        self.poststimTimeSpin.setObjectName("poststimTimeSpin")
        self.horizontalLayout_3.addWidget(self.poststimTimeSpin)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 3)
        self.groupBox = QtGui.QGroupBox(UncagingControlWidget)
        self.groupBox.setObjectName("groupBox")
        self.useSpontActCheck = QtGui.QCheckBox(self.groupBox)
        self.useSpontActCheck.setGeometry(QtCore.QRect(10, 80, 116, 21))
        self.useSpontActCheck.setObjectName("useSpontActCheck")
        self.chargeTransferRadio = QtGui.QRadioButton(self.groupBox)
        self.chargeTransferRadio.setGeometry(QtCore.QRect(10, 50, 125, 21))
        self.chargeTransferRadio.setObjectName("chargeTransferRadio")
        self.eventFindRadio = QtGui.QRadioButton(self.groupBox)
        self.eventFindRadio.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.eventFindRadio.setObjectName("eventFindRadio")
        self.gridLayout.addWidget(self.groupBox, 3, 0, 2, 2)
        self.label_5 = QtGui.QLabel(UncagingControlWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(84, 70, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtGui.QGroupBox(UncagingControlWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rainbowRadio = QtGui.QRadioButton(self.groupBox_2)
        self.rainbowRadio.setObjectName("rainbowRadio")
        self.verticalLayout_3.addWidget(self.rainbowRadio)
        self.rgbRadio = QtGui.QRadioButton(self.groupBox_2)
        self.rgbRadio.setObjectName("rgbRadio")
        self.verticalLayout_3.addWidget(self.rgbRadio)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(UncagingControlWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scaledRadio = QtGui.QRadioButton(self.groupBox_3)
        self.scaledRadio.setObjectName("scaledRadio")
        self.verticalLayout.addWidget(self.scaledRadio)
        self.absoluteRadio = QtGui.QRadioButton(self.groupBox_3)
        self.absoluteRadio.setObjectName("absoluteRadio")
        self.verticalLayout.addWidget(self.absoluteRadio)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 2, 1, 1)
        self.recolorBtn = QtGui.QPushButton(UncagingControlWidget)
        self.recolorBtn.setObjectName("recolorBtn")
        self.gridLayout.addWidget(self.recolorBtn, 6, 2, 1, 1)

        self.retranslateUi(UncagingControlWidget)
        QtCore.QMetaObject.connectSlotsByName(UncagingControlWidget)

    def retranslateUi(self, UncagingControlWidget):
        UncagingControlWidget.setWindowTitle(QtGui.QApplication.translate("UncagingControlWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("UncagingControlWidget", "Noise Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("UncagingControlWidget", "Direct Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("UncagingControlWidget", "Post-Stimulation Time", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("UncagingControlWidget", "Analysis Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.useSpontActCheck.setText(QtGui.QApplication.translate("UncagingControlWidget", "Use Spontaneous Activity", None, QtGui.QApplication.UnicodeUTF8))
        self.chargeTransferRadio.setText(QtGui.QApplication.translate("UncagingControlWidget", "Total Charge Transfer", None, QtGui.QApplication.UnicodeUTF8))
        self.eventFindRadio.setText(QtGui.QApplication.translate("UncagingControlWidget", "Event Finding", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("UncagingControlWidget", "Coloring Scheme:", None, QtGui.QApplication.UnicodeUTF8))
        self.rainbowRadio.setText(QtGui.QApplication.translate("UncagingControlWidget", "Rainbow", None, QtGui.QApplication.UnicodeUTF8))
        self.rgbRadio.setText(QtGui.QApplication.translate("UncagingControlWidget", "RGB", None, QtGui.QApplication.UnicodeUTF8))
        self.scaledRadio.setText(QtGui.QApplication.translate("UncagingControlWidget", "Scaled", None, QtGui.QApplication.UnicodeUTF8))
        self.absoluteRadio.setText(QtGui.QApplication.translate("UncagingControlWidget", "Absolute", None, QtGui.QApplication.UnicodeUTF8))
        self.recolorBtn.setText(QtGui.QApplication.translate("UncagingControlWidget", "Re-Color", None, QtGui.QApplication.UnicodeUTF8))

