# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UncagingControlTemplate.ui'
#
# Created: Sat May 22 20:47:44 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_UncagingControlWidget(object):
    def setupUi(self, UncagingControlWidget):
        UncagingControlWidget.setObjectName("UncagingControlWidget")
        UncagingControlWidget.resize(357, 199)
        self.gridLayout_4 = QtGui.QGridLayout(UncagingControlWidget)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(UncagingControlWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.thresholdSpin = QtGui.QDoubleSpinBox(UncagingControlWidget)
        self.thresholdSpin.setObjectName("thresholdSpin")
        self.gridLayout.addWidget(self.thresholdSpin, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(UncagingControlWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.directTimeSpin = QtGui.QDoubleSpinBox(UncagingControlWidget)
        self.directTimeSpin.setObjectName("directTimeSpin")
        self.gridLayout.addWidget(self.directTimeSpin, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(UncagingControlWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.poststimTimeSpin = QtGui.QDoubleSpinBox(UncagingControlWidget)
        self.poststimTimeSpin.setObjectName("poststimTimeSpin")
        self.gridLayout.addWidget(self.poststimTimeSpin, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(UncagingControlWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rainbowRadio = QtGui.QRadioButton(self.groupBox_2)
        self.rainbowRadio.setObjectName("rainbowRadio")
        self.gridLayout_3.addWidget(self.rainbowRadio, 0, 0, 1, 1)
        self.colorSpin1 = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.colorSpin1.setObjectName("colorSpin1")
        self.gridLayout_3.addWidget(self.colorSpin1, 1, 0, 1, 1)
        self.colorSpin2 = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.colorSpin2.setObjectName("colorSpin2")
        self.gridLayout_3.addWidget(self.colorSpin2, 2, 0, 1, 1)
        self.colorSpin3 = QtGui.QSpinBox(self.groupBox_2)
        self.colorSpin3.setObjectName("colorSpin3")
        self.gridLayout_3.addWidget(self.colorSpin3, 3, 0, 1, 1)
        self.rgbRadio = QtGui.QRadioButton(self.groupBox_2)
        self.rgbRadio.setObjectName("rgbRadio")
        self.gridLayout_3.addWidget(self.rgbRadio, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 5, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scaledRadio = QtGui.QRadioButton(self.groupBox_3)
        self.scaledRadio.setObjectName("scaledRadio")
        self.verticalLayout.addWidget(self.scaledRadio)
        self.absoluteRadio = QtGui.QRadioButton(self.groupBox_3)
        self.absoluteRadio.setObjectName("absoluteRadio")
        self.verticalLayout.addWidget(self.absoluteRadio)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 1, 2, 1)
        self.groupBox = QtGui.QGroupBox(UncagingControlWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.eventFindRadio = QtGui.QRadioButton(self.groupBox)
        self.eventFindRadio.setObjectName("eventFindRadio")
        self.gridLayout_2.addWidget(self.eventFindRadio, 0, 0, 1, 1)
        self.chargeTransferRadio = QtGui.QRadioButton(self.groupBox)
        self.chargeTransferRadio.setObjectName("chargeTransferRadio")
        self.gridLayout_2.addWidget(self.chargeTransferRadio, 1, 0, 1, 1)
        self.useSpontActCheck = QtGui.QCheckBox(self.groupBox)
        self.useSpontActCheck.setObjectName("useSpontActCheck")
        self.gridLayout_2.addWidget(self.useSpontActCheck, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 1)
        self.recolorBtn = QtGui.QPushButton(UncagingControlWidget)
        self.recolorBtn.setObjectName("recolorBtn")
        self.gridLayout_4.addWidget(self.recolorBtn, 2, 0, 1, 2)

        self.retranslateUi(UncagingControlWidget)
        QtCore.QMetaObject.connectSlotsByName(UncagingControlWidget)

    def retranslateUi(self, UncagingControlWidget):
        UncagingControlWidget.setWindowTitle(QtGui.QApplication.translate("UncagingControlWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("UncagingControlWidget", "Noise Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("UncagingControlWidget", "Direct Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("UncagingControlWidget", "Post-Stim. Time", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("UncagingControlWidget", "Coloring Scheme:", None, QtGui.QApplication.UnicodeUTF8))
        self.rainbowRadio.setText(QtGui.QApplication.translate("UncagingControlWidget", "Rainbow", None, QtGui.QApplication.UnicodeUTF8))
        self.rgbRadio.setText(QtGui.QApplication.translate("UncagingControlWidget", "RGB", None, QtGui.QApplication.UnicodeUTF8))
        self.scaledRadio.setText(QtGui.QApplication.translate("UncagingControlWidget", "Scaled", None, QtGui.QApplication.UnicodeUTF8))
        self.absoluteRadio.setText(QtGui.QApplication.translate("UncagingControlWidget", "Absolute", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("UncagingControlWidget", "Analysis Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.eventFindRadio.setText(QtGui.QApplication.translate("UncagingControlWidget", "Event Finding", None, QtGui.QApplication.UnicodeUTF8))
        self.chargeTransferRadio.setText(QtGui.QApplication.translate("UncagingControlWidget", "Total Charge Transfer", None, QtGui.QApplication.UnicodeUTF8))
        self.useSpontActCheck.setText(QtGui.QApplication.translate("UncagingControlWidget", "Use Spont. Activity", None, QtGui.QApplication.UnicodeUTF8))
        self.recolorBtn.setText(QtGui.QApplication.translate("UncagingControlWidget", "Re-Color", None, QtGui.QApplication.UnicodeUTF8))

