# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/modules/Photostim/MapCtrlTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(299, 371)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mapTable = QtWidgets.QTreeWidget(self.groupBox_2)
        self.mapTable.setObjectName("mapTable")
        self.gridLayout_3.addWidget(self.mapTable, 0, 0, 1, 3)
        self.newMapBtn = FeedbackButton(self.groupBox_2)
        self.newMapBtn.setObjectName("newMapBtn")
        self.gridLayout_3.addWidget(self.newMapBtn, 1, 0, 1, 1)
        self.loadMapBtn = FeedbackButton(self.groupBox_2)
        self.loadMapBtn.setObjectName("loadMapBtn")
        self.gridLayout_3.addWidget(self.loadMapBtn, 1, 1, 1, 1)
        self.delMapBtn = FeedbackButton(self.groupBox_2)
        self.delMapBtn.setObjectName("delMapBtn")
        self.gridLayout_3.addWidget(self.delMapBtn, 1, 2, 1, 1)
        self.addScanBtn = FeedbackButton(self.groupBox_2)
        self.addScanBtn.setObjectName("addScanBtn")
        self.gridLayout_3.addWidget(self.addScanBtn, 2, 0, 1, 1)
        self.removeScanBtn = FeedbackButton(self.groupBox_2)
        self.removeScanBtn.setObjectName("removeScanBtn")
        self.gridLayout_3.addWidget(self.removeScanBtn, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 3, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.storeDBSpotBtn = FeedbackButton(self.groupBox)
        self.storeDBSpotBtn.setObjectName("storeDBSpotBtn")
        self.gridLayout_2.addWidget(self.storeDBSpotBtn, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.rewriteSpotPosBtn = FeedbackButton(self.groupBox)
        self.rewriteSpotPosBtn.setObjectName("rewriteSpotPosBtn")
        self.gridLayout_2.addWidget(self.rewriteSpotPosBtn, 3, 1, 1, 2)
        self.clearDBScanBtn = FeedbackButton(self.groupBox)
        self.clearDBScanBtn.setObjectName("clearDBScanBtn")
        self.gridLayout_2.addWidget(self.clearDBScanBtn, 1, 1, 1, 1)
        self.clearDBSpotBtn = FeedbackButton(self.groupBox)
        self.clearDBSpotBtn.setObjectName("clearDBSpotBtn")
        self.gridLayout_2.addWidget(self.clearDBSpotBtn, 2, 1, 1, 1)
        self.storeDBScanBtn = FeedbackButton(self.groupBox)
        self.storeDBScanBtn.setObjectName("storeDBScanBtn")
        self.gridLayout_2.addWidget(self.storeDBScanBtn, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.scanTree = TreeWidget(self.groupBox)
        self.scanTree.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.scanTree.setHeaderHidden(False)
        self.scanTree.setObjectName("scanTree")
        self.scanTree.header().setDefaultSectionSize(60)
        self.scanTree.header().setMinimumSectionSize(10)
        self.gridLayout_2.addWidget(self.scanTree, 0, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 3)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "Maps"))
        self.mapTable.headerItem().setText(0, _translate("Form", "Map/Scan"))
        self.newMapBtn.setText(_translate("Form", "New Map"))
        self.loadMapBtn.setText(_translate("Form", "Load Selected"))
        self.delMapBtn.setText(_translate("Form", "Delete"))
        self.addScanBtn.setText(_translate("Form", "Add Scan"))
        self.removeScanBtn.setText(_translate("Form", "Remove Scan"))
        self.groupBox.setTitle(_translate("Form", "Scans Loaded"))
        self.storeDBSpotBtn.setText(_translate("Form", "Store to DB"))
        self.label_2.setText(_translate("Form", "Selected Scan:"))
        self.rewriteSpotPosBtn.setText(_translate("Form", "Re-write spot locations"))
        self.clearDBScanBtn.setText(_translate("Form", "Clear DB Entry"))
        self.clearDBSpotBtn.setText(_translate("Form", "Clear DB Entry"))
        self.storeDBScanBtn.setText(_translate("Form", "Store to DB"))
        self.label.setText(_translate("Form", "Selected Spot:"))
        self.scanTree.headerItem().setText(0, _translate("Form", "Scan"))
        self.scanTree.headerItem().setText(1, _translate("Form", "Display"))
        self.scanTree.headerItem().setText(2, _translate("Form", "Events"))
        self.scanTree.headerItem().setText(3, _translate("Form", "Stats"))

from acq4.pyqtgraph import FeedbackButton, TreeWidget
