# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProtocolTemplate.ui'
#
# Created: Wed Jun 17 00:21:04 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(718, 444)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_2 = QtGui.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cameraGroupBox = QtGui.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.cameraGroupBox.setFont(font)
        self.cameraGroupBox.setObjectName("cameraGroupBox")
        self.gridLayout = QtGui.QGridLayout(self.cameraGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.recordCheck = QtGui.QCheckBox(self.cameraGroupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.recordCheck.setFont(font)
        self.recordCheck.setChecked(True)
        self.recordCheck.setObjectName("recordCheck")
        self.gridLayout.addWidget(self.recordCheck, 0, 0, 1, 1)
        self.displayCheck = QtGui.QCheckBox(self.cameraGroupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.displayCheck.setFont(font)
        self.displayCheck.setChecked(True)
        self.displayCheck.setObjectName("displayCheck")
        self.gridLayout.addWidget(self.displayCheck, 0, 1, 1, 1)
        self.triggerModeCombo = QtGui.QComboBox(self.cameraGroupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.triggerModeCombo.setFont(font)
        self.triggerModeCombo.setObjectName("triggerModeCombo")
        self.gridLayout.addWidget(self.triggerModeCombo, 1, 0, 1, 2)
        self.triggerCheck = QtGui.QCheckBox(self.cameraGroupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.triggerCheck.setFont(font)
        self.triggerCheck.setObjectName("triggerCheck")
        self.gridLayout.addWidget(self.triggerCheck, 2, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.cameraGroupBox)
        self.exposureGroupBox = QtGui.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.exposureGroupBox.setFont(font)
        self.exposureGroupBox.setObjectName("exposureGroupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.exposureGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.recordExposeCheck = QtGui.QCheckBox(self.exposureGroupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.recordExposeCheck.setFont(font)
        self.recordExposeCheck.setObjectName("recordExposeCheck")
        self.horizontalLayout.addWidget(self.recordExposeCheck)
        self.displayExposureCheck = QtGui.QCheckBox(self.exposureGroupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.displayExposureCheck.setFont(font)
        self.displayExposureCheck.setObjectName("displayExposureCheck")
        self.horizontalLayout.addWidget(self.displayExposureCheck)
        self.verticalLayout_2.addWidget(self.exposureGroupBox)
        self.triggerGroupBox = QtGui.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.triggerGroupBox.setFont(font)
        self.triggerGroupBox.setCheckable(False)
        self.triggerGroupBox.setObjectName("triggerGroupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.triggerGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.displayTriggerCheck = QtGui.QCheckBox(self.triggerGroupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.displayTriggerCheck.setFont(font)
        self.displayTriggerCheck.setObjectName("displayTriggerCheck")
        self.gridLayout_2.addWidget(self.displayTriggerCheck, 0, 1, 1, 1)
        self.triggerGenerator = StimGenerator(self.triggerGroupBox)
        self.triggerGenerator.setObjectName("triggerGenerator")
        self.gridLayout_2.addWidget(self.triggerGenerator, 1, 0, 1, 2)
        self.triggerOutputCheck = QtGui.QCheckBox(self.triggerGroupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.triggerOutputCheck.setFont(font)
        self.triggerOutputCheck.setObjectName("triggerOutputCheck")
        self.gridLayout_2.addWidget(self.triggerOutputCheck, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.triggerGroupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.imageView = ImageView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageView.sizePolicy().hasHeightForWidth())
        self.imageView.setSizePolicy(sizePolicy)
        self.imageView.setObjectName("imageView")
        self.exposePlot = PlotWidget(self.splitter)
        self.exposePlot.setObjectName("exposePlot")
        self.triggerPlot = PlotWidget(self.splitter)
        self.triggerPlot.setObjectName("triggerPlot")
        self.verticalLayout_3.addWidget(self.splitter_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.cameraGroupBox.setTitle(QtGui.QApplication.translate("Form", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.recordCheck.setText(QtGui.QApplication.translate("Form", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.displayCheck.setText(QtGui.QApplication.translate("Form", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerCheck.setToolTip(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Checking this forces the camera to start <span style=\" font-style:italic;\">after</span> all</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">other devices in the protocol have started so that it</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">can correctly act as a starting trigger.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerCheck.setText(QtGui.QApplication.translate("Form", "Camera triggers protocol", None, QtGui.QApplication.UnicodeUTF8))
        self.exposureGroupBox.setTitle(QtGui.QApplication.translate("Form", "Exposure Channel (in)", None, QtGui.QApplication.UnicodeUTF8))
        self.recordExposeCheck.setText(QtGui.QApplication.translate("Form", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.displayExposureCheck.setText(QtGui.QApplication.translate("Form", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerGroupBox.setTitle(QtGui.QApplication.translate("Form", "Trigger Channel (out)", None, QtGui.QApplication.UnicodeUTF8))
        self.displayTriggerCheck.setText(QtGui.QApplication.translate("Form", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerOutputCheck.setText(QtGui.QApplication.translate("Form", "Enable", None, QtGui.QApplication.UnicodeUTF8))

from lib.util.generator.StimGenerator import StimGenerator
from lib.util.qtgraph.ImageView import ImageView
from lib.util.PlotWidget import PlotWidget
