# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/devices/Pipette/cameraModTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(209, 188)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.setCenterBtn = QtWidgets.QPushButton(self.groupBox)
        self.setCenterBtn.setCheckable(True)
        self.setCenterBtn.setObjectName("setCenterBtn")
        self.gridLayout.addWidget(self.setCenterBtn, 2, 0, 1, 1)
        self.autoCalibrateBtn = QtWidgets.QPushButton(self.groupBox)
        self.autoCalibrateBtn.setObjectName("autoCalibrateBtn")
        self.gridLayout.addWidget(self.autoCalibrateBtn, 3, 0, 1, 1)
        self.getRefBtn = QtWidgets.QPushButton(self.groupBox)
        self.getRefBtn.setObjectName("getRefBtn")
        self.gridLayout.addWidget(self.getRefBtn, 3, 1, 1, 1)
        self.setOrientationBtn = QtWidgets.QPushButton(self.groupBox)
        self.setOrientationBtn.setCheckable(True)
        self.setOrientationBtn.setObjectName("setOrientationBtn")
        self.gridLayout.addWidget(self.setOrientationBtn, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.homeBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.homeBtn.setObjectName("homeBtn")
        self.gridLayout_2.addWidget(self.homeBtn, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slowRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.slowRadio.setChecked(True)
        self.slowRadio.setObjectName("slowRadio")
        self.horizontalLayout.addWidget(self.slowRadio)
        self.fastRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.fastRadio.setObjectName("fastRadio")
        self.horizontalLayout.addWidget(self.fastRadio)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.setTargetBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.setTargetBtn.setCheckable(True)
        self.setTargetBtn.setObjectName("setTargetBtn")
        self.gridLayout_2.addWidget(self.setTargetBtn, 6, 0, 1, 1)
        self.searchBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.searchBtn.setMaximumSize(Qt.QSize(70, 16777215))
        self.searchBtn.setObjectName("searchBtn")
        self.gridLayout_2.addWidget(self.searchBtn, 1, 1, 1, 1)
        self.idleBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.idleBtn.setMaximumSize(Qt.QSize(50, 16777215))
        self.idleBtn.setObjectName("idleBtn")
        self.gridLayout_2.addWidget(self.idleBtn, 1, 2, 1, 1)
        self.targetBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.targetBtn.setEnabled(False)
        self.targetBtn.setMaximumSize(Qt.QSize(50, 16777215))
        self.targetBtn.setObjectName("targetBtn")
        self.gridLayout_2.addWidget(self.targetBtn, 7, 2, 1, 1)
        self.aboveTargetBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.aboveTargetBtn.setObjectName("aboveTargetBtn")
        self.gridLayout_2.addWidget(self.aboveTargetBtn, 6, 1, 1, 2)
        self.approachBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.approachBtn.setEnabled(False)
        self.approachBtn.setMaximumSize(Qt.QSize(70, 16777215))
        self.approachBtn.setObjectName("approachBtn")
        self.gridLayout_2.addWidget(self.approachBtn, 7, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Calibration"))
        self.setCenterBtn.setText(_translate("Form", "Set center"))
        self.autoCalibrateBtn.setText(_translate("Form", "Auto calibrate"))
        self.getRefBtn.setText(_translate("Form", "Get ref. frames"))
        self.setOrientationBtn.setText(_translate("Form", "Set orientation"))
        self.groupBox_2.setTitle(_translate("Form", "Set points"))
        self.homeBtn.setText(_translate("Form", "Home"))
        self.slowRadio.setText(_translate("Form", "slow"))
        self.fastRadio.setText(_translate("Form", "fast"))
        self.setTargetBtn.setText(_translate("Form", "Set Target"))
        self.searchBtn.setText(_translate("Form", "Search"))
        self.idleBtn.setText(_translate("Form", "Idle"))
        self.targetBtn.setText(_translate("Form", "Target"))
        self.aboveTargetBtn.setText(_translate("Form", "Above Target"))
        self.approachBtn.setText(_translate("Form", "Approach"))

