# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/old/AnalyzerTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 559)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.loaderDock = QtWidgets.QDockWidget(MainWindow)
        self.loaderDock.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        self.loaderDock.setObjectName("loaderDock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.loaderDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.Qt.DockWidgetArea(4), self.loaderDock)
        self.dataDock = QtWidgets.QDockWidget(MainWindow)
        self.dataDock.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        self.dataDock.setObjectName("dataDock")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadDataBtn = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.loadDataBtn.setObjectName("loadDataBtn")
        self.verticalLayout.addWidget(self.loadDataBtn)
        self.loadSequenceBtn = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.loadSequenceBtn.setObjectName("loadSequenceBtn")
        self.verticalLayout.addWidget(self.loadSequenceBtn)
        self.loadSessionBtn = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.loadSessionBtn.setObjectName("loadSessionBtn")
        self.verticalLayout.addWidget(self.loadSessionBtn)
        self.dataSourceCombo = InterfaceCombo(self.dockWidgetContents_2)
        self.dataSourceCombo.setObjectName("dataSourceCombo")
        self.dataSourceCombo.addItem("")
        self.verticalLayout.addWidget(self.dataSourceCombo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.recompSelectedBtn = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.recompSelectedBtn.setObjectName("recompSelectedBtn")
        self.verticalLayout.addWidget(self.recompSelectedBtn)
        self.recompAllBtn = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.recompAllBtn.setObjectName("recompAllBtn")
        self.verticalLayout.addWidget(self.recompAllBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.saveSelectedBtn = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.saveSelectedBtn.setObjectName("saveSelectedBtn")
        self.verticalLayout.addWidget(self.saveSelectedBtn)
        self.saveAllBtn = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.saveAllBtn.setObjectName("saveAllBtn")
        self.verticalLayout.addWidget(self.saveAllBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.dataTree = QtWidgets.QTreeWidget(self.dockWidgetContents_2)
        self.dataTree.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.dataTree.setObjectName("dataTree")
        self.dataTree.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.dataTree)
        self.dataDock.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.Qt.DockWidgetArea(4), self.dataDock)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dockList = QtWidgets.QListWidget(self.dockWidgetContents_3)
        self.dockList.setObjectName("dockList")
        self.gridLayout.addWidget(self.dockList, 0, 1, 6, 1)
        self.addOutputBtn = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.addOutputBtn.setObjectName("addOutputBtn")
        self.gridLayout.addWidget(self.addOutputBtn, 1, 0, 1, 1)
        self.addPlotBtn = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.addPlotBtn.setObjectName("addPlotBtn")
        self.gridLayout.addWidget(self.addPlotBtn, 2, 0, 1, 1)
        self.addCanvasBtn = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.addCanvasBtn.setObjectName("addCanvasBtn")
        self.gridLayout.addWidget(self.addCanvasBtn, 3, 0, 1, 1)
        self.addTableBtn = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.addTableBtn.setObjectName("addTableBtn")
        self.gridLayout.addWidget(self.addTableBtn, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 46, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 0, 2, 1)
        self.removeDockBtn = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.removeDockBtn.setObjectName("removeDockBtn")
        self.gridLayout.addWidget(self.removeDockBtn, 6, 1, 1, 1)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(Qt.Qt.DockWidgetArea(4), self.dockWidget_3)

        self.retranslateUi(MainWindow)
        Qt.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = Qt.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analysis"))
        self.loaderDock.setWindowTitle(_translate("MainWindow", "Loader"))
        self.dataDock.setWindowTitle(_translate("MainWindow", "Data"))
        self.loadDataBtn.setText(_translate("MainWindow", "Load Data"))
        self.loadSequenceBtn.setText(_translate("MainWindow", "Load Sequence"))
        self.loadSessionBtn.setText(_translate("MainWindow", "Load Session"))
        self.dataSourceCombo.setItemText(0, _translate("MainWindow", "Select source.."))
        self.recompSelectedBtn.setText(_translate("MainWindow", "Recompute Selected"))
        self.recompAllBtn.setText(_translate("MainWindow", "Recompute All"))
        self.saveSelectedBtn.setText(_translate("MainWindow", "Save Selected"))
        self.saveAllBtn.setText(_translate("MainWindow", "Save Session"))
        self.dockWidget_3.setWindowTitle(_translate("MainWindow", "Components"))
        self.label.setText(_translate("MainWindow", "Add:"))
        self.addOutputBtn.setText(_translate("MainWindow", "Output"))
        self.addPlotBtn.setText(_translate("MainWindow", "Plot"))
        self.addCanvasBtn.setText(_translate("MainWindow", "Canvas"))
        self.addTableBtn.setText(_translate("MainWindow", "Table"))
        self.removeDockBtn.setText(_translate("MainWindow", "Remove"))

from acq4.util.InterfaceCombo import InterfaceCombo
