# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/old/EventDetectionCtrlTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EventDetectionCtrlForm(object):
    def setupUi(self, EventDetectionCtrlForm):
        EventDetectionCtrlForm.setObjectName("EventDetectionCtrlForm")
        EventDetectionCtrlForm.resize(264, 340)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(EventDetectionCtrlForm)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(EventDetectionCtrlForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.preFilterList = FilterList(self.groupBox_2)
        self.preFilterList.setObjectName("preFilterList")
        self.gridLayout_3.addWidget(self.preFilterList, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(EventDetectionCtrlForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.detectMethodCombo = QtWidgets.QComboBox(self.groupBox)
        self.detectMethodCombo.setObjectName("detectMethodCombo")
        self.detectMethodCombo.addItem("")
        self.detectMethodCombo.addItem("")
        self.detectMethodCombo.addItem("")
        self.verticalLayout.addWidget(self.detectMethodCombo)
        self.detectMethodStack = QtWidgets.QStackedWidget(self.groupBox)
        self.detectMethodStack.setObjectName("detectMethodStack")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.stThresholdSpin = SpinBox(self.page_3)
        self.stThresholdSpin.setProperty("value", 3.0)
        self.stThresholdSpin.setObjectName("stThresholdSpin")
        self.gridLayout_4.addWidget(self.stThresholdSpin, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.detectMethodStack.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.zcSumAbsThresholdSpin = SpinBox(self.page_2)
        self.zcSumAbsThresholdSpin.setObjectName("zcSumAbsThresholdSpin")
        self.gridLayout.addWidget(self.zcSumAbsThresholdSpin, 1, 2, 1, 1)
        self.zcAmpAbsThresholdSpin = SpinBox(self.page_2)
        self.zcAmpAbsThresholdSpin.setEnabled(True)
        self.zcAmpAbsThresholdSpin.setObjectName("zcAmpAbsThresholdSpin")
        self.gridLayout.addWidget(self.zcAmpAbsThresholdSpin, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.zcAmpRelThresholdSpin = QtWidgets.QDoubleSpinBox(self.page_2)
        self.zcAmpRelThresholdSpin.setEnabled(False)
        self.zcAmpRelThresholdSpin.setProperty("value", 8.0)
        self.zcAmpRelThresholdSpin.setObjectName("zcAmpRelThresholdSpin")
        self.gridLayout.addWidget(self.zcAmpRelThresholdSpin, 2, 3, 1, 1)
        self.zcSumRelThresholdSpin = QtWidgets.QDoubleSpinBox(self.page_2)
        self.zcSumRelThresholdSpin.setProperty("value", 8.0)
        self.zcSumRelThresholdSpin.setObjectName("zcSumRelThresholdSpin")
        self.gridLayout.addWidget(self.zcSumRelThresholdSpin, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_2.setEnabled(False)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 3, 3, 1, 1)
        self.zcLenAbsThresholdSpin = QtWidgets.QSpinBox(self.page_2)
        self.zcLenAbsThresholdSpin.setMaximum(100000)
        self.zcLenAbsThresholdSpin.setProperty("value", 3)
        self.zcLenAbsThresholdSpin.setObjectName("zcLenAbsThresholdSpin")
        self.gridLayout.addWidget(self.zcLenAbsThresholdSpin, 3, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.detectMethodStack.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.cbThresholdSpin = QtWidgets.QDoubleSpinBox(self.page)
        self.cbThresholdSpin.setProperty("value", 4.0)
        self.cbThresholdSpin.setObjectName("cbThresholdSpin")
        self.gridLayout_2.addWidget(self.cbThresholdSpin, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.cbRiseTauSpin = QtWidgets.QDoubleSpinBox(self.page)
        self.cbRiseTauSpin.setProperty("value", 0.01)
        self.cbRiseTauSpin.setObjectName("cbRiseTauSpin")
        self.gridLayout_2.addWidget(self.cbRiseTauSpin, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.cbFallTauSpin = QtWidgets.QDoubleSpinBox(self.page)
        self.cbFallTauSpin.setProperty("value", 0.01)
        self.cbFallTauSpin.setObjectName("cbFallTauSpin")
        self.gridLayout_2.addWidget(self.cbFallTauSpin, 2, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.detectMethodStack.addWidget(self.page)
        self.verticalLayout.addWidget(self.detectMethodStack)
        self.verticalLayout_3.addWidget(self.groupBox)

        self.retranslateUi(EventDetectionCtrlForm)
        self.detectMethodCombo.setCurrentIndex(1)
        self.detectMethodStack.setCurrentIndex(1)
        Qt.QMetaObject.connectSlotsByName(EventDetectionCtrlForm)

    def retranslateUi(self, EventDetectionCtrlForm):
        _translate = Qt.QCoreApplication.translate
        EventDetectionCtrlForm.setWindowTitle(_translate("EventDetectionCtrlForm", "Form"))
        self.groupBox_2.setToolTip(_translate("EventDetectionCtrlForm", "Pre-processing options. Used for processing data before any event detection takes place. Processing is performed in the order listed."))
        self.groupBox_2.setTitle(_translate("EventDetectionCtrlForm", "Pre-processing"))
        self.groupBox.setTitle(_translate("EventDetectionCtrlForm", "Event Detection"))
        self.detectMethodCombo.setItemText(0, _translate("EventDetectionCtrlForm", "Stdev. Threshold"))
        self.detectMethodCombo.setItemText(1, _translate("EventDetectionCtrlForm", "Zero-crossing"))
        self.detectMethodCombo.setItemText(2, _translate("EventDetectionCtrlForm", "Clements-Bekkers"))
        self.label_6.setText(_translate("EventDetectionCtrlForm", "Threshold"))
        self.label.setText(_translate("EventDetectionCtrlForm", "Sum Thresh."))
        self.label_3.setText(_translate("EventDetectionCtrlForm", "Amp. Thresh."))
        self.label_8.setText(_translate("EventDetectionCtrlForm", "Abs."))
        self.label_9.setText(_translate("EventDetectionCtrlForm", "Len. Thresh."))
        self.label_7.setText(_translate("EventDetectionCtrlForm", "Rel."))
        self.label_2.setText(_translate("EventDetectionCtrlForm", "Threshold"))
        self.label_4.setText(_translate("EventDetectionCtrlForm", "Rise Tau"))
        self.label_5.setText(_translate("EventDetectionCtrlForm", "Fall Tau"))

from FilterList import FilterList
from SpinBox import SpinBox
