# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/analysis/old/MosaicTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(Qt.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget = QtWidgets.QWidget(self.splitter_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.setRootBtn = QtWidgets.QPushButton(self.widget)
        self.setRootBtn.setObjectName("setRootBtn")
        self.verticalLayout_3.addWidget(self.setRootBtn)
        self.fileTree = DirTreeWidget(self.widget)
        self.fileTree.setObjectName("fileTree")
        self.verticalLayout_3.addWidget(self.fileTree)
        self.loadBtn = QtWidgets.QPushButton(self.widget)
        self.loadBtn.setObjectName("loadBtn")
        self.verticalLayout_3.addWidget(self.loadBtn)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.transformList = QtWidgets.QListView(self.groupBox)
        self.transformList.setObjectName("transformList")
        self.gridLayout.addWidget(self.transformList, 0, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.translateXSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.translateXSpin.setObjectName("translateXSpin")
        self.gridLayout.addWidget(self.translateXSpin, 1, 1, 1, 2)
        self.translateYSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.translateYSpin.setObjectName("translateYSpin")
        self.gridLayout.addWidget(self.translateYSpin, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.rotateSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.rotateSpin.setObjectName("rotateSpin")
        self.gridLayout.addWidget(self.rotateSpin, 2, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.scaleYSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.scaleYSpin.setObjectName("scaleYSpin")
        self.gridLayout.addWidget(self.scaleYSpin, 3, 3, 1, 1)
        self.scaleXSpin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.scaleXSpin.setObjectName("scaleXSpin")
        self.gridLayout.addWidget(self.scaleXSpin, 3, 1, 1, 2)
        self.saveBtn = QtWidgets.QPushButton(self.groupBox)
        self.saveBtn.setObjectName("saveBtn")
        self.gridLayout.addWidget(self.saveBtn, 4, 0, 1, 2)
        self.saveAllBtn = QtWidgets.QPushButton(self.groupBox)
        self.saveAllBtn.setObjectName("saveAllBtn")
        self.gridLayout.addWidget(self.saveAllBtn, 4, 2, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(Qt.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addMarkerBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.addMarkerBtn.setObjectName("addMarkerBtn")
        self.gridLayout_2.addWidget(self.addMarkerBtn, 0, 0, 1, 1)
        self.delMarkerPen = QtWidgets.QPushButton(self.groupBox_3)
        self.delMarkerPen.setObjectName("delMarkerPen")
        self.gridLayout_2.addWidget(self.delMarkerPen, 0, 1, 1, 1)
        self.markerList = QtWidgets.QListView(self.groupBox_3)
        self.markerList.setObjectName("markerList")
        self.gridLayout_2.addWidget(self.markerList, 1, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.normalizeBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.normalizeBtn.setObjectName("normalizeBtn")
        self.verticalLayout.addWidget(self.normalizeBtn)
        self.blendBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.blendBtn.setObjectName("blendBtn")
        self.verticalLayout.addWidget(self.blendBtn)
        self.autoRangeBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.autoRangeBtn.setObjectName("autoRangeBtn")
        self.verticalLayout.addWidget(self.autoRangeBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.exportSvgBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.exportSvgBtn.setObjectName("exportSvgBtn")
        self.verticalLayout_2.addWidget(self.exportSvgBtn)
        self.exportPngBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.exportPngBtn.setObjectName("exportPngBtn")
        self.verticalLayout_2.addWidget(self.exportPngBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.canvas = Canvas(self.splitter)
        self.canvas.setObjectName("canvas")
        self.gridLayout_4.addWidget(self.splitter_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        Qt.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = Qt.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mosaic"))
        self.setRootBtn.setText(_translate("MainWindow", "--> Set Root Directory"))
        self.loadBtn.setText(_translate("MainWindow", "Load Selected -->"))
        self.groupBox.setTitle(_translate("MainWindow", "Transformations"))
        self.label.setText(_translate("MainWindow", "Translate"))
        self.label_2.setText(_translate("MainWindow", "Rotate"))
        self.label_3.setText(_translate("MainWindow", "Scale"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.saveAllBtn.setText(_translate("MainWindow", "Save All"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Markers"))
        self.addMarkerBtn.setText(_translate("MainWindow", "Add..."))
        self.delMarkerPen.setText(_translate("MainWindow", "Del"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Image Correction"))
        self.normalizeBtn.setText(_translate("MainWindow", "Normalize"))
        self.blendBtn.setText(_translate("MainWindow", "Blend"))
        self.autoRangeBtn.setText(_translate("MainWindow", "Auto Range"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Export"))
        self.exportSvgBtn.setText(_translate("MainWindow", "SVG"))
        self.exportPngBtn.setText(_translate("MainWindow", "PNG"))

from acq4.util.Canvas import Canvas
from acq4.util.DirTreeWidget import DirTreeWidget
