# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './lib/devices/Scanner/ProtocolTemplate.ui'
#
# Created: Wed Aug 17 13:49:53 2011
#      by: pyside-uic 0.2.11 running on PySide 1.0.5
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(898, 481)
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.cameraCombo = QtGui.QComboBox(Form)
        self.cameraCombo.setObjectName("cameraCombo")
        self.horizontalLayout_3.addWidget(self.cameraCombo)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 3, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.laserCombo = QtGui.QComboBox(Form)
        self.laserCombo.setObjectName("laserCombo")
        self.horizontalLayout_4.addWidget(self.laserCombo)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addLineScanBtn = QtGui.QPushButton(Form)
        self.addLineScanBtn.setEnabled(False)
        self.addLineScanBtn.setObjectName("addLineScanBtn")
        self.verticalLayout.addWidget(self.addLineScanBtn)
        self.addCircleScanBtn = QtGui.QPushButton(Form)
        self.addCircleScanBtn.setEnabled(False)
        self.addCircleScanBtn.setObjectName("addCircleScanBtn")
        self.verticalLayout.addWidget(self.addCircleScanBtn)
        self.addSpiralScanBtn = QtGui.QPushButton(Form)
        self.addSpiralScanBtn.setEnabled(False)
        self.addSpiralScanBtn.setObjectName("addSpiralScanBtn")
        self.verticalLayout.addWidget(self.addSpiralScanBtn)
        self.deleteStepBtn = QtGui.QPushButton(Form)
        self.deleteStepBtn.setEnabled(False)
        self.deleteStepBtn.setObjectName("deleteStepBtn")
        self.verticalLayout.addWidget(self.deleteStepBtn)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.previewBtn = QtGui.QPushButton(Form)
        self.previewBtn.setEnabled(False)
        self.previewBtn.setObjectName("previewBtn")
        self.verticalLayout.addWidget(self.previewBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.programTable = QtGui.QTableWidget(Form)
        self.programTable.setObjectName("programTable")
        self.programTable.setColumnCount(0)
        self.programTable.setRowCount(0)
        self.horizontalLayout.addWidget(self.programTable)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 3, 7, 1)
        spacerItem1 = QtGui.QSpacerItem(63, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 4, 1, 1)
        self.simulateShutterCheck = QtGui.QCheckBox(Form)
        self.simulateShutterCheck.setObjectName("simulateShutterCheck")
        self.gridLayout_2.addWidget(self.simulateShutterCheck, 2, 0, 1, 2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.minTimeSpin = SpinBox(Form)
        self.minTimeSpin.setSuffix("")
        self.minTimeSpin.setDecimals(2)
        self.minTimeSpin.setMaximum(1000000.0)
        self.minTimeSpin.setObjectName("minTimeSpin")
        self.gridLayout.addWidget(self.minTimeSpin, 0, 0, 1, 1)
        self.minDistSpin = SpinBox(Form)
        self.minDistSpin.setSuffix("")
        self.minDistSpin.setMaximum(1000000.0)
        self.minDistSpin.setObjectName("minDistSpin")
        self.gridLayout.addWidget(self.minDistSpin, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.spotSizeLabel = QtGui.QLabel(Form)
        self.spotSizeLabel.setObjectName("spotSizeLabel")
        self.verticalLayout_2.addWidget(self.spotSizeLabel)
        self.sizeFromCalibrationRadio = QtGui.QRadioButton(Form)
        self.sizeFromCalibrationRadio.setChecked(True)
        self.sizeFromCalibrationRadio.setObjectName("sizeFromCalibrationRadio")
        self.verticalLayout_2.addWidget(self.sizeFromCalibrationRadio)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sizeCustomRadio = QtGui.QRadioButton(Form)
        self.sizeCustomRadio.setObjectName("sizeCustomRadio")
        self.horizontalLayout_2.addWidget(self.sizeCustomRadio)
        self.sizeSpin = SpinBox(Form)
        self.sizeSpin.setSuffix("")
        self.sizeSpin.setMinimum(0.0)
        self.sizeSpin.setMaximum(100000.0)
        self.sizeSpin.setSingleStep(1e-06)
        self.sizeSpin.setProperty("value", 0.0)
        self.sizeSpin.setObjectName("sizeSpin")
        self.horizontalLayout_2.addWidget(self.sizeSpin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 4, 0, 1, 2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.addPointBtn = QtGui.QPushButton(Form)
        self.addPointBtn.setObjectName("addPointBtn")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.addPointBtn)
        self.addOcclusionBtn = QtGui.QPushButton(Form)
        self.addOcclusionBtn.setObjectName("addOcclusionBtn")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.addOcclusionBtn)
        self.addGridBtn = QtGui.QPushButton(Form)
        self.addGridBtn.setObjectName("addGridBtn")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.addGridBtn)
        self.addProgramBtn = QtGui.QPushButton(Form)
        self.addProgramBtn.setObjectName("addProgramBtn")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.addProgramBtn)
        self.deleteBtn = QtGui.QPushButton(Form)
        self.deleteBtn.setObjectName("deleteBtn")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.deleteBtn)
        self.deleteAllBtn = QtGui.QPushButton(Form)
        self.deleteAllBtn.setObjectName("deleteAllBtn")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.deleteAllBtn)
        self.gridLayout_2.addLayout(self.formLayout, 5, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(83, 59, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 6, 0, 1, 1)
        self.recomputeBtn = QtGui.QPushButton(Form)
        self.recomputeBtn.setObjectName("recomputeBtn")
        self.gridLayout_2.addWidget(self.recomputeBtn, 7, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 7, 1, 1, 1)
        self.timeLabel = QtGui.QLabel(Form)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout_2.addWidget(self.timeLabel, 8, 0, 1, 1)
        self.hideCheck = QtGui.QCheckBox(Form)
        self.hideCheck.setEnabled(True)
        self.hideCheck.setChecked(False)
        self.hideCheck.setObjectName("hideCheck")
        self.gridLayout_2.addWidget(self.hideCheck, 8, 2, 1, 1)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.itemTree = TreeWidget(Form)
        self.itemTree.setObjectName("itemTree")
        self.gridLayout_2.addWidget(self.itemTree, 1, 2, 7, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Camera Module:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Program Controls:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Laser Device:", None, QtGui.QApplication.UnicodeUTF8))
        self.addLineScanBtn.setText(QtGui.QApplication.translate("Form", "Add Line Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.addCircleScanBtn.setText(QtGui.QApplication.translate("Form", "Add Circle Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.addSpiralScanBtn.setText(QtGui.QApplication.translate("Form", "Add Spiral Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteStepBtn.setText(QtGui.QApplication.translate("Form", "Delete Step", None, QtGui.QApplication.UnicodeUTF8))
        self.previewBtn.setText(QtGui.QApplication.translate("Form", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.programTable.setSortingEnabled(True)
        self.simulateShutterCheck.setText(QtGui.QApplication.translate("Form", "Simulate Shutter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Minimum distance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Minimum time", None, QtGui.QApplication.UnicodeUTF8))
        self.spotSizeLabel.setText(QtGui.QApplication.translate("Form", "Spot Display Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeFromCalibrationRadio.setText(QtGui.QApplication.translate("Form", "Use size from calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeCustomRadio.setText(QtGui.QApplication.translate("Form", "Use custom size:", None, QtGui.QApplication.UnicodeUTF8))
        self.addPointBtn.setText(QtGui.QApplication.translate("Form", "Add Point", None, QtGui.QApplication.UnicodeUTF8))
        self.addOcclusionBtn.setText(QtGui.QApplication.translate("Form", "Add Occlusion", None, QtGui.QApplication.UnicodeUTF8))
        self.addGridBtn.setText(QtGui.QApplication.translate("Form", "Add Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.addProgramBtn.setText(QtGui.QApplication.translate("Form", "Add Program", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteBtn.setText(QtGui.QApplication.translate("Form", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteAllBtn.setText(QtGui.QApplication.translate("Form", "Delete All", None, QtGui.QApplication.UnicodeUTF8))
        self.recomputeBtn.setText(QtGui.QApplication.translate("Form", "Recompute", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Form", "Auto recompute", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLabel.setText(QtGui.QApplication.translate("Form", "Total Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.hideCheck.setText(QtGui.QApplication.translate("Form", "Hide items", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Items", None, QtGui.QApplication.UnicodeUTF8))
        self.itemTree.headerItem().setText(0, QtGui.QApplication.translate("Form", "Item", None, QtGui.QApplication.UnicodeUTF8))
        self.itemTree.headerItem().setText(1, QtGui.QApplication.translate("Form", "Grid Spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.itemTree.headerItem().setText(2, QtGui.QApplication.translate("Form", "Grid Layout", None, QtGui.QApplication.UnicodeUTF8))
        self.itemTree.headerItem().setText(3, QtGui.QApplication.translate("Form", "# of points", None, QtGui.QApplication.UnicodeUTF8))

from SpinBox import SpinBox
from TreeWidget import TreeWidget
