# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\maiTaiTemplate.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(660, 264)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.maitaiControlGroup = QtGui.QGroupBox(Form)
        self.maitaiControlGroup.setObjectName(_fromUtf8("maitaiControlGroup"))
        self.gridLayout_12 = QtGui.QGridLayout(self.maitaiControlGroup)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.ExternalShutterBtn = QtGui.QPushButton(self.maitaiControlGroup)
        self.ExternalShutterBtn.setCheckable(True)
        self.ExternalShutterBtn.setObjectName(_fromUtf8("ExternalShutterBtn"))
        self.gridLayout_12.addWidget(self.ExternalShutterBtn, 0, 2, 1, 1)
        self.turnOnOffBtn = QtGui.QPushButton(self.maitaiControlGroup)
        self.turnOnOffBtn.setStyleSheet(_fromUtf8(""))
        self.turnOnOffBtn.setCheckable(True)
        self.turnOnOffBtn.setObjectName(_fromUtf8("turnOnOffBtn"))
        self.gridLayout_12.addWidget(self.turnOnOffBtn, 0, 0, 1, 1)
        self.InternalShutterBtn = QtGui.QPushButton(self.maitaiControlGroup)
        self.InternalShutterBtn.setCheckable(True)
        self.InternalShutterBtn.setObjectName(_fromUtf8("InternalShutterBtn"))
        self.gridLayout_12.addWidget(self.InternalShutterBtn, 0, 1, 1, 1)
        self.MaiTaiGroup = QtGui.QGroupBox(self.maitaiControlGroup)
        self.MaiTaiGroup.setTitle(_fromUtf8(""))
        self.MaiTaiGroup.setObjectName(_fromUtf8("MaiTaiGroup"))
        self.gridLayout_11 = QtGui.QGridLayout(self.MaiTaiGroup)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_15 = QtGui.QLabel(self.MaiTaiGroup)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_11.addWidget(self.label_15, 3, 0, 1, 1)
        self.P2OptimizationLabel = QtGui.QLabel(self.MaiTaiGroup)
        self.P2OptimizationLabel.setText(_fromUtf8(""))
        self.P2OptimizationLabel.setObjectName(_fromUtf8("P2OptimizationLabel"))
        self.gridLayout_11.addWidget(self.P2OptimizationLabel, 3, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.MaiTaiGroup)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_11.addWidget(self.label_18, 3, 2, 1, 1)
        self.systemStatusLabel = QtGui.QLabel(self.MaiTaiGroup)
        self.systemStatusLabel.setText(_fromUtf8(""))
        self.systemStatusLabel.setObjectName(_fromUtf8("systemStatusLabel"))
        self.gridLayout_11.addWidget(self.systemStatusLabel, 3, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.MaiTaiGroup)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_11.addWidget(self.label_14, 1, 0, 1, 1)
        self.PulsingLabel = QtGui.QLabel(self.MaiTaiGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PulsingLabel.setFont(font)
        self.PulsingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PulsingLabel.setObjectName(_fromUtf8("PulsingLabel"))
        self.gridLayout_11.addWidget(self.PulsingLabel, 0, 3, 1, 1)
        self.InternalShutterLabel = QtGui.QLabel(self.MaiTaiGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.InternalShutterLabel.setFont(font)
        self.InternalShutterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InternalShutterLabel.setObjectName(_fromUtf8("InternalShutterLabel"))
        self.gridLayout_11.addWidget(self.InternalShutterLabel, 0, 1, 1, 1)
        self.EmissionLabel = QtGui.QLabel(self.MaiTaiGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.EmissionLabel.setFont(font)
        self.EmissionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.EmissionLabel.setObjectName(_fromUtf8("EmissionLabel"))
        self.gridLayout_11.addWidget(self.EmissionLabel, 0, 0, 1, 1)
        self.ExternalShutterLabel = QtGui.QLabel(self.MaiTaiGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ExternalShutterLabel.setFont(font)
        self.ExternalShutterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ExternalShutterLabel.setObjectName(_fromUtf8("ExternalShutterLabel"))
        self.gridLayout_11.addWidget(self.ExternalShutterLabel, 0, 2, 1, 1)
        self.pumpModeLabel = QtGui.QLabel(self.MaiTaiGroup)
        self.pumpModeLabel.setText(_fromUtf8(""))
        self.pumpModeLabel.setObjectName(_fromUtf8("pumpModeLabel"))
        self.gridLayout_11.addWidget(self.pumpModeLabel, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.MaiTaiGroup)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_11.addWidget(self.label_6, 1, 2, 1, 1)
        self.relHumidityLabel = QtGui.QLabel(self.MaiTaiGroup)
        self.relHumidityLabel.setText(_fromUtf8(""))
        self.relHumidityLabel.setObjectName(_fromUtf8("relHumidityLabel"))
        self.gridLayout_11.addWidget(self.relHumidityLabel, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.MaiTaiGroup)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_11.addWidget(self.label_16, 2, 0, 1, 1)
        self.pumpPowerLabel = QtGui.QLabel(self.MaiTaiGroup)
        self.pumpPowerLabel.setText(_fromUtf8(""))
        self.pumpPowerLabel.setObjectName(_fromUtf8("pumpPowerLabel"))
        self.gridLayout_11.addWidget(self.pumpPowerLabel, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.MaiTaiGroup, 2, 0, 1, 4)
        self.alignmentModeBtn = QtGui.QPushButton(self.maitaiControlGroup)
        self.alignmentModeBtn.setCheckable(True)
        self.alignmentModeBtn.setObjectName(_fromUtf8("alignmentModeBtn"))
        self.gridLayout_12.addWidget(self.alignmentModeBtn, 0, 3, 1, 1)
        self.linkLaserExtSwitchCheckBox = QtGui.QCheckBox(self.maitaiControlGroup)
        self.linkLaserExtSwitchCheckBox.setChecked(True)
        self.linkLaserExtSwitchCheckBox.setObjectName(_fromUtf8("linkLaserExtSwitchCheckBox"))
        self.gridLayout_12.addWidget(self.linkLaserExtSwitchCheckBox, 1, 0, 1, 2)
        self.externalSwitchBtn = QtGui.QPushButton(self.maitaiControlGroup)
        self.externalSwitchBtn.setEnabled(False)
        self.externalSwitchBtn.setCheckable(True)
        self.externalSwitchBtn.setChecked(True)
        self.externalSwitchBtn.setObjectName(_fromUtf8("externalSwitchBtn"))
        self.gridLayout_12.addWidget(self.externalSwitchBtn, 1, 2, 1, 2)
        self.maitaiWavelengthGroup = QtGui.QGroupBox(self.maitaiControlGroup)
        self.maitaiWavelengthGroup.setTitle(_fromUtf8(""))
        self.maitaiWavelengthGroup.setObjectName(_fromUtf8("maitaiWavelengthGroup"))
        self.gridLayout_9 = QtGui.QGridLayout(self.maitaiWavelengthGroup)
        self.gridLayout_9.setMargin(6)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_13 = QtGui.QLabel(self.maitaiWavelengthGroup)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_9.addWidget(self.label_13, 0, 0, 1, 1)
        self.wavelengthSpin_2 = SpinBox(self.maitaiWavelengthGroup)
        self.wavelengthSpin_2.setSuffix(_fromUtf8(""))
        self.wavelengthSpin_2.setObjectName(_fromUtf8("wavelengthSpin_2"))
        self.gridLayout_9.addWidget(self.wavelengthSpin_2, 0, 2, 1, 1)
        self.currentWaveLengthLabel = QtGui.QLabel(self.maitaiWavelengthGroup)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.currentWaveLengthLabel.setFont(font)
        self.currentWaveLengthLabel.setText(_fromUtf8(""))
        self.currentWaveLengthLabel.setObjectName(_fromUtf8("currentWaveLengthLabel"))
        self.gridLayout_9.addWidget(self.currentWaveLengthLabel, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.maitaiWavelengthGroup)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_9.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.maitaiWavelengthGroup, 3, 0, 1, 4)
        self.verticalLayout.addWidget(self.maitaiControlGroup)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.maitaiControlGroup.setTitle(_translate("Form", "Mai Tai Control", None))
        self.ExternalShutterBtn.setText(_translate("Form", "Open External Shutter", None))
        self.turnOnOffBtn.setText(_translate("Form", "Turn Laser On", None))
        self.InternalShutterBtn.setText(_translate("Form", "Open Laser Shutter", None))
        self.label_15.setText(_translate("Form", "System Status:", None))
        self.label_18.setText(_translate("Form", "P2 Optimization:", None))
        self.label_14.setText(_translate("Form", "relative Humidity:", None))
        self.PulsingLabel.setText(_translate("Form", "Not Pulsing", None))
        self.InternalShutterLabel.setText(_translate("Form", "Laser Shutter Closed", None))
        self.EmissionLabel.setText(_translate("Form", "Emission Off", None))
        self.ExternalShutterLabel.setText(_translate("Form", "External Shutter Closed", None))
        self.label_6.setText(_translate("Form", "Pump Mode:", None))
        self.label_16.setText(_translate("Form", "Current Pump Power:", None))
        self.alignmentModeBtn.setText(_translate("Form", "Alignment mode Off", None))
        self.linkLaserExtSwitchCheckBox.setText(_translate("Form", "Link Laser Schutter to external Switch", None))
        self.externalSwitchBtn.setText(_translate("Form", "External Switch ON", None))
        self.label_13.setText(_translate("Form", "Set Wavelength: ", None))
        self.label_2.setText(_translate("Form", "Current Wavelength:", None))

from acq4.pyqtgraph import SpinBox
