# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/modules/TaskRunner/analysisModules/Uncaging/UncagingTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(292, 355)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.cameraModCombo = InterfaceCombo(Form)
        self.cameraModCombo.setObjectName("cameraModCombo")
        self.gridLayout.addWidget(self.cameraModCombo, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.clampDevCombo = InterfaceCombo(Form)
        self.clampDevCombo.setObjectName("clampDevCombo")
        self.gridLayout.addWidget(self.clampDevCombo, 4, 1, 1, 2)
        self.taskList = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskList.sizePolicy().hasHeightForWidth())
        self.taskList.setSizePolicy(sizePolicy)
        self.taskList.setObjectName("taskList")
        self.gridLayout.addWidget(self.taskList, 5, 0, 1, 3)
        self.deleteBtn = QtWidgets.QPushButton(Form)
        self.deleteBtn.setObjectName("deleteBtn")
        self.gridLayout.addWidget(self.deleteBtn, 6, 0, 1, 1)
        self.alphaSlider = QtWidgets.QSlider(Form)
        self.alphaSlider.setMaximum(255)
        self.alphaSlider.setPageStep(10)
        self.alphaSlider.setProperty("value", 150)
        self.alphaSlider.setOrientation(Qt.Qt.Horizontal)
        self.alphaSlider.setObjectName("alphaSlider")
        self.gridLayout.addWidget(self.alphaSlider, 6, 1, 1, 2)
        self.scannerDevCombo = InterfaceCombo(Form)
        self.scannerDevCombo.setObjectName("scannerDevCombo")
        self.gridLayout.addWidget(self.scannerDevCombo, 3, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.clampStopSpin = QtWidgets.QLabel(Form)
        self.clampStopSpin.setObjectName("clampStopSpin")
        self.gridLayout.addWidget(self.clampStopSpin, 9, 0, 1, 1)
        self.enabledCheck = QtWidgets.QCheckBox(Form)
        self.enabledCheck.setObjectName("enabledCheck")
        self.gridLayout.addWidget(self.enabledCheck, 0, 1, 1, 1)
        self.clampBaseStartSpin = QtWidgets.QDoubleSpinBox(Form)
        self.clampBaseStartSpin.setMaximum(100000.0)
        self.clampBaseStartSpin.setObjectName("clampBaseStartSpin")
        self.gridLayout.addWidget(self.clampBaseStartSpin, 8, 1, 1, 1)
        self.clampTestStartSpin = QtWidgets.QDoubleSpinBox(Form)
        self.clampTestStartSpin.setMaximum(100000.0)
        self.clampTestStartSpin.setProperty("value", 400.0)
        self.clampTestStartSpin.setObjectName("clampTestStartSpin")
        self.gridLayout.addWidget(self.clampTestStartSpin, 9, 1, 1, 1)
        self.clampTestStopSpin = QtWidgets.QDoubleSpinBox(Form)
        self.clampTestStopSpin.setMaximum(100000.0)
        self.clampTestStopSpin.setProperty("value", 450.0)
        self.clampTestStopSpin.setObjectName("clampTestStopSpin")
        self.gridLayout.addWidget(self.clampTestStopSpin, 9, 2, 1, 1)
        self.clampBaseStopSpin = QtWidgets.QDoubleSpinBox(Form)
        self.clampBaseStopSpin.setMaximum(100000.0)
        self.clampBaseStopSpin.setProperty("value", 380.0)
        self.clampBaseStopSpin.setObjectName("clampBaseStopSpin")
        self.gridLayout.addWidget(self.clampBaseStopSpin, 8, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 10, 0, 1, 1)
        self.pspToleranceSpin = QtWidgets.QDoubleSpinBox(Form)
        self.pspToleranceSpin.setProperty("value", 4.0)
        self.pspToleranceSpin.setObjectName("pspToleranceSpin")
        self.gridLayout.addWidget(self.pspToleranceSpin, 10, 1, 1, 2)
        self.recomputeBtn = QtWidgets.QPushButton(Form)
        self.recomputeBtn.setObjectName("recomputeBtn")
        self.gridLayout.addWidget(self.recomputeBtn, 13, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Camera Module:"))
        self.label_3.setText(_translate("Form", "Clamp Device:"))
        self.deleteBtn.setText(_translate("Form", "Delete"))
        self.label_4.setText(_translate("Form", "Scanner Device:"))
        self.label_5.setText(_translate("Form", "Clamp Baseline"))
        self.clampStopSpin.setText(_translate("Form", "Clamp Test"))
        self.enabledCheck.setText(_translate("Form", "Enabled"))
        self.label_6.setText(_translate("Form", "PSP Tolerance"))
        self.recomputeBtn.setText(_translate("Form", "Recompute"))

from acq4.util.InterfaceCombo import InterfaceCombo
