# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './lib/analysis/modules/pbm_ImageAnalysis/ctrlTemplate.ui'
#
# Created: Wed Oct 10 10:10:35 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(384, 410)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(384, 410))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        Form.setFont(font)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setMaximumSize(QtCore.QSize(392, 410))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.ImagePhys_CorrTool_LPF = QtGui.QCheckBox(self.groupBox)
        self.ImagePhys_CorrTool_LPF.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_CorrTool_LPF.setFont(font)
        self.ImagePhys_CorrTool_LPF.setObjectName(_fromUtf8("ImagePhys_CorrTool_LPF"))
        self.horizontalLayout_8.addWidget(self.ImagePhys_CorrTool_LPF)
        self.ImagePhys_ImgLPF = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_ImgLPF.setFont(font)
        self.ImagePhys_ImgLPF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ImagePhys_ImgLPF.setDecimals(2)
        self.ImagePhys_ImgLPF.setMinimum(0.1)
        self.ImagePhys_ImgLPF.setMaximum(5000.0)
        self.ImagePhys_ImgLPF.setSingleStep(1.0)
        self.ImagePhys_ImgLPF.setProperty("value", 20.0)
        self.ImagePhys_ImgLPF.setObjectName(_fromUtf8("ImagePhys_ImgLPF"))
        self.horizontalLayout_8.addWidget(self.ImagePhys_ImgLPF)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 20, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.ImagePhys_CorrTool_HPF = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_CorrTool_HPF.setFont(font)
        self.ImagePhys_CorrTool_HPF.setObjectName(_fromUtf8("ImagePhys_CorrTool_HPF"))
        self.horizontalLayout_9.addWidget(self.ImagePhys_CorrTool_HPF)
        self.ImagePhys_ImgHPF = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_ImgHPF.setFont(font)
        self.ImagePhys_ImgHPF.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ImagePhys_ImgHPF.setSuffix(_fromUtf8(""))
        self.ImagePhys_ImgHPF.setDecimals(3)
        self.ImagePhys_ImgHPF.setMinimum(0.001)
        self.ImagePhys_ImgHPF.setMaximum(10.0)
        self.ImagePhys_ImgHPF.setSingleStep(0.2)
        self.ImagePhys_ImgHPF.setProperty("value", 0.2)
        self.ImagePhys_ImgHPF.setObjectName(_fromUtf8("ImagePhys_ImgHPF"))
        self.horizontalLayout_9.addWidget(self.ImagePhys_ImgHPF)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 22, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.ImagePhys_BaseStart = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_BaseStart.setFont(font)
        self.ImagePhys_BaseStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ImagePhys_BaseStart.setMinimum(-5000.0)
        self.ImagePhys_BaseStart.setMaximum(50000.0)
        self.ImagePhys_BaseStart.setObjectName(_fromUtf8("ImagePhys_BaseStart"))
        self.horizontalLayout_2.addWidget(self.ImagePhys_BaseStart)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 19, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.ImagePhys_BaseEnd = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_BaseEnd.setFont(font)
        self.ImagePhys_BaseEnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ImagePhys_BaseEnd.setMinimum(-5000.0)
        self.ImagePhys_BaseEnd.setMaximum(50000.0)
        self.ImagePhys_BaseEnd.setObjectName(_fromUtf8("ImagePhys_BaseEnd"))
        self.horizontalLayout_7.addWidget(self.ImagePhys_BaseEnd)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 18, 0, 1, 1)
        self.ImagePhys_ImgMethod = QtGui.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_ImgMethod.setFont(font)
        self.ImagePhys_ImgMethod.setObjectName(_fromUtf8("ImagePhys_ImgMethod"))
        self.ImagePhys_ImgMethod.addItem(_fromUtf8(""))
        self.ImagePhys_ImgMethod.addItem(_fromUtf8(""))
        self.ImagePhys_ImgMethod.addItem(_fromUtf8(""))
        self.ImagePhys_ImgMethod.addItem(_fromUtf8(""))
        self.ImagePhys_ImgMethod.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.ImagePhys_ImgMethod, 5, 2, 1, 1)
        self.ImagePhys_View = QtGui.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_View.setFont(font)
        self.ImagePhys_View.setObjectName(_fromUtf8("ImagePhys_View"))
        self.ImagePhys_View.addItem(_fromUtf8(""))
        self.ImagePhys_View.addItem(_fromUtf8(""))
        self.ImagePhys_View.addItem(_fromUtf8(""))
        self.ImagePhys_View.addItem(_fromUtf8(""))
        self.ImagePhys_View.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.ImagePhys_View, 4, 2, 1, 1)
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2.addWidget(self.frame, 0, 0, 2, 1)
        self.ImagePhys_DisplayTraces = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_DisplayTraces.setFont(font)
        self.ImagePhys_DisplayTraces.setObjectName(_fromUtf8("ImagePhys_DisplayTraces"))
        self.gridLayout_2.addWidget(self.ImagePhys_DisplayTraces, 6, 2, 1, 1)
        self.ImagePhys_ExportTiff = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_ExportTiff.setFont(font)
        self.ImagePhys_ExportTiff.setObjectName(_fromUtf8("ImagePhys_ExportTiff"))
        self.gridLayout_2.addWidget(self.ImagePhys_ExportTiff, 7, 2, 1, 1)
        self.ImagePhys_ImgNormalize = QtGui.QPushButton(self.groupBox)
        self.ImagePhys_ImgNormalize.setEnabled(False)
        self.ImagePhys_ImgNormalize.setObjectName(_fromUtf8("ImagePhys_ImgNormalize"))
        self.gridLayout_2.addWidget(self.ImagePhys_ImgNormalize, 15, 0, 1, 1)
        self.ImagePhys_NormInfo = QtGui.QLabel(self.groupBox)
        self.ImagePhys_NormInfo.setEnabled(False)
        self.ImagePhys_NormInfo.setObjectName(_fromUtf8("ImagePhys_NormInfo"))
        self.gridLayout_2.addWidget(self.ImagePhys_NormInfo, 17, 0, 1, 1)
        self.ImagePhys_Update = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_Update.setFont(font)
        self.ImagePhys_Update.setObjectName(_fromUtf8("ImagePhys_Update"))
        self.gridLayout_2.addWidget(self.ImagePhys_Update, 15, 1, 1, 1)
        self.ImagePhys_CorrTool_BL1 = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_CorrTool_BL1.setFont(font)
        self.ImagePhys_CorrTool_BL1.setObjectName(_fromUtf8("ImagePhys_CorrTool_BL1"))
        self.gridLayout_2.addWidget(self.ImagePhys_CorrTool_BL1, 18, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 19, 1, 1, 1)
        self.ImagePhys_RectSelect = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_RectSelect.setFont(font)
        self.ImagePhys_RectSelect.setChecked(True)
        self.ImagePhys_RectSelect.setObjectName(_fromUtf8("ImagePhys_RectSelect"))
        self.gridLayout_2.addWidget(self.ImagePhys_RectSelect, 20, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_10.addWidget(self.label_6)
        self.ImagePhys_ROIKernel = QtGui.QComboBox(self.groupBox)
        self.ImagePhys_ROIKernel.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.ImagePhys_ROIKernel.setFont(font)
        self.ImagePhys_ROIKernel.setToolTip(_fromUtf8(""))
        self.ImagePhys_ROIKernel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ImagePhys_ROIKernel.setStyleSheet(_fromUtf8("<align = \'right\'>"))
        self.ImagePhys_ROIKernel.setMaxVisibleItems(1)
        self.ImagePhys_ROIKernel.setMaxCount(10)
        self.ImagePhys_ROIKernel.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ImagePhys_ROIKernel.setFrame(False)
        self.ImagePhys_ROIKernel.setModelColumn(0)
        self.ImagePhys_ROIKernel.setObjectName(_fromUtf8("ImagePhys_ROIKernel"))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.ImagePhys_ROIKernel.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.ImagePhys_ROIKernel)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 10, 2, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ImagePhys_ROIThrHigh = QtGui.QDoubleSpinBox(self.groupBox)
        self.ImagePhys_ROIThrHigh.setMinimum(0.1)
        self.ImagePhys_ROIThrHigh.setMaximum(1.0)
        self.ImagePhys_ROIThrHigh.setSingleStep(0.1)
        self.ImagePhys_ROIThrHigh.setProperty("value", 1.0)
        self.ImagePhys_ROIThrHigh.setObjectName(_fromUtf8("ImagePhys_ROIThrHigh"))
        self.gridLayout_4.addWidget(self.ImagePhys_ROIThrHigh, 1, 1, 1, 1)
        self.ImagePhys_ROIThrLow = QtGui.QDoubleSpinBox(self.groupBox)
        self.ImagePhys_ROIThrLow.setMinimum(0.01)
        self.ImagePhys_ROIThrLow.setMaximum(1.0)
        self.ImagePhys_ROIThrLow.setSingleStep(0.1)
        self.ImagePhys_ROIThrLow.setProperty("value", 0.2)
        self.ImagePhys_ROIThrLow.setObjectName(_fromUtf8("ImagePhys_ROIThrLow"))
        self.gridLayout_4.addWidget(self.ImagePhys_ROIThrLow, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 12, 2, 3, 1)
        self.ImagePhys_findROIs = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_findROIs.setFont(font)
        self.ImagePhys_findROIs.setObjectName(_fromUtf8("ImagePhys_findROIs"))
        self.gridLayout_2.addWidget(self.ImagePhys_findROIs, 9, 2, 1, 1)
        self.ImagePhys_clearRoi = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_clearRoi.setFont(font)
        self.ImagePhys_clearRoi.setObjectName(_fromUtf8("ImagePhys_clearRoi"))
        self.gridLayout_2.addWidget(self.ImagePhys_clearRoi, 8, 2, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_15.addWidget(self.label_13)
        self.ImagePhys_ROISize = QtGui.QSpinBox(self.groupBox)
        self.ImagePhys_ROISize.setMinimum(1)
        self.ImagePhys_ROISize.setMaximum(25)
        self.ImagePhys_ROISize.setProperty("value", 1)
        self.ImagePhys_ROISize.setObjectName(_fromUtf8("ImagePhys_ROISize"))
        self.horizontalLayout_15.addWidget(self.ImagePhys_ROISize)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 15, 2, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.ImagePhys_StdRB = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ImagePhys_StdRB.setFont(font)
        self.ImagePhys_StdRB.setObjectName(_fromUtf8("ImagePhys_StdRB"))
        self.horizontalLayout_14.addWidget(self.ImagePhys_StdRB)
        self.ImagePhys_FFTRB = QtGui.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ImagePhys_FFTRB.setFont(font)
        self.ImagePhys_FFTRB.setChecked(True)
        self.ImagePhys_FFTRB.setObjectName(_fromUtf8("ImagePhys_FFTRB"))
        self.horizontalLayout_14.addWidget(self.ImagePhys_FFTRB)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 17, 2, 1, 1)
        self.ImagePhys_addRoi = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_addRoi.setFont(font)
        self.ImagePhys_addRoi.setObjectName(_fromUtf8("ImagePhys_addRoi"))
        self.gridLayout_2.addWidget(self.ImagePhys_addRoi, 18, 2, 1, 1)
        self.ImagePhys_RecalculateROIs = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_RecalculateROIs.setFont(font)
        self.ImagePhys_RecalculateROIs.setObjectName(_fromUtf8("ImagePhys_RecalculateROIs"))
        self.gridLayout_2.addWidget(self.ImagePhys_RecalculateROIs, 19, 2, 1, 1)
        self.ImagePhys_RetrieveROI = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_RetrieveROI.setFont(font)
        self.ImagePhys_RetrieveROI.setObjectName(_fromUtf8("ImagePhys_RetrieveROI"))
        self.gridLayout_2.addWidget(self.ImagePhys_RetrieveROI, 20, 2, 1, 1)
        self.ImagePhys_SaveROI = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_SaveROI.setFont(font)
        self.ImagePhys_SaveROI.setObjectName(_fromUtf8("ImagePhys_SaveROI"))
        self.gridLayout_2.addWidget(self.ImagePhys_SaveROI, 22, 2, 1, 1)
        self.ImagePhys_PhysROIPlot = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ImagePhys_PhysROIPlot.setFont(font)
        self.ImagePhys_PhysROIPlot.setObjectName(_fromUtf8("ImagePhys_PhysROIPlot"))
        self.gridLayout_2.addWidget(self.ImagePhys_PhysROIPlot, 22, 1, 1, 1)
        self.ImagePhys_FileGroup = QtGui.QGroupBox(self.groupBox)
        self.ImagePhys_FileGroup.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.ImagePhys_FileGroup.sizePolicy().hasHeightForWidth())
        self.ImagePhys_FileGroup.setSizePolicy(sizePolicy)
        self.ImagePhys_FileGroup.setMinimumSize(QtCore.QSize(100, 190))
        self.ImagePhys_FileGroup.setSizeIncrement(QtCore.QSize(10, 10))
        self.ImagePhys_FileGroup.setBaseSize(QtCore.QSize(100, 250))
        self.ImagePhys_FileGroup.setObjectName(_fromUtf8("ImagePhys_FileGroup"))
        self.ImagePhys_ImageMode = QtGui.QComboBox(self.ImagePhys_FileGroup)
        self.ImagePhys_ImageMode.setGeometry(QtCore.QRect(5, 40, 116, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ImagePhys_ImageMode.setFont(font)
        self.ImagePhys_ImageMode.setObjectName(_fromUtf8("ImagePhys_ImageMode"))
        self.ImagePhys_ImageMode.addItem(_fromUtf8(""))
        self.ImagePhys_ImageMode.addItem(_fromUtf8(""))
        self.ImagePhys_clearRatio = QtGui.QPushButton(self.ImagePhys_FileGroup)
        self.ImagePhys_clearRatio.setGeometry(QtCore.QRect(0, 160, 116, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_clearRatio.setFont(font)
        self.ImagePhys_clearRatio.setObjectName(_fromUtf8("ImagePhys_clearRatio"))
        self.ImagePhys_GetFileInfo = QtGui.QPushButton(self.ImagePhys_FileGroup)
        self.ImagePhys_GetFileInfo.setGeometry(QtCore.QRect(0, 15, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_GetFileInfo.setFont(font)
        self.ImagePhys_GetFileInfo.setObjectName(_fromUtf8("ImagePhys_GetFileInfo"))
        self.ImagePhys_getRatio = QtGui.QPushButton(self.ImagePhys_FileGroup)
        self.ImagePhys_getRatio.setGeometry(QtCore.QRect(0, 140, 116, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_getRatio.setFont(font)
        self.ImagePhys_getRatio.setObjectName(_fromUtf8("ImagePhys_getRatio"))
        self.widget = QtGui.QWidget(self.ImagePhys_FileGroup)
        self.widget.setGeometry(QtCore.QRect(5, 65, 111, 26))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.ImagePhys_DataStruct = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagePhys_DataStruct.sizePolicy().hasHeightForWidth())
        self.ImagePhys_DataStruct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_DataStruct.setFont(font)
        self.ImagePhys_DataStruct.setMaxCount(10)
        self.ImagePhys_DataStruct.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.ImagePhys_DataStruct.setFrame(False)
        self.ImagePhys_DataStruct.setObjectName(_fromUtf8("ImagePhys_DataStruct"))
        self.ImagePhys_DataStruct.addItem(_fromUtf8(""))
        self.ImagePhys_DataStruct.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.ImagePhys_DataStruct)
        self.widget1 = QtGui.QWidget(self.ImagePhys_FileGroup)
        self.widget1.setGeometry(QtCore.QRect(5, 115, 111, 27))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.ImagePhys_ignoreFirst = QtGui.QSpinBox(self.widget1)
        self.ImagePhys_ignoreFirst.setSuffix(_fromUtf8(""))
        self.ImagePhys_ignoreFirst.setPrefix(_fromUtf8(""))
        self.ImagePhys_ignoreFirst.setProperty("value", 1)
        self.ImagePhys_ignoreFirst.setObjectName(_fromUtf8("ImagePhys_ignoreFirst"))
        self.horizontalLayout_4.addWidget(self.ImagePhys_ignoreFirst)
        self.widget2 = QtGui.QWidget(self.ImagePhys_FileGroup)
        self.widget2.setGeometry(QtCore.QRect(5, 90, 111, 26))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.ImagePhys_Downsample = QtGui.QComboBox(self.widget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.ImagePhys_Downsample.setFont(font)
        self.ImagePhys_Downsample.setEditable(True)
        self.ImagePhys_Downsample.setMaxCount(5000)
        self.ImagePhys_Downsample.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.ImagePhys_Downsample.setObjectName(_fromUtf8("ImagePhys_Downsample"))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.ImagePhys_Downsample.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.ImagePhys_Downsample)
        self.gridLayout_2.addWidget(self.ImagePhys_FileGroup, 4, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setMinimumSize(QtCore.QSize(120, 190))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.ImagePhys_RegisterStack = QtGui.QPushButton(self.groupBox_2)
        self.ImagePhys_RegisterStack.setGeometry(QtCore.QRect(-5, 15, 131, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_RegisterStack.setFont(font)
        self.ImagePhys_RegisterStack.setObjectName(_fromUtf8("ImagePhys_RegisterStack"))
        self.widget3 = QtGui.QWidget(self.groupBox_2)
        self.widget3.setGeometry(QtCore.QRect(0, 40, 121, 32))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.ImagePhys_UnBleach = QtGui.QPushButton(self.widget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.ImagePhys_UnBleach.setFont(font)
        self.ImagePhys_UnBleach.setObjectName(_fromUtf8("ImagePhys_UnBleach"))
        self.horizontalLayout_6.addWidget(self.ImagePhys_UnBleach)
        self.ImagePhys_BleachInfo = QtGui.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.ImagePhys_BleachInfo.setFont(font)
        self.ImagePhys_BleachInfo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ImagePhys_BleachInfo.setFrameShadow(QtGui.QFrame.Sunken)
        self.ImagePhys_BleachInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.ImagePhys_BleachInfo.setObjectName(_fromUtf8("ImagePhys_BleachInfo"))
        self.horizontalLayout_6.addWidget(self.ImagePhys_BleachInfo)
        self.ImagePhys_SpecCalc = QtGui.QPushButton(self.groupBox_2)
        self.ImagePhys_SpecCalc.setGeometry(QtCore.QRect(0, 70, 116, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.ImagePhys_SpecCalc.setFont(font)
        self.ImagePhys_SpecCalc.setObjectName(_fromUtf8("ImagePhys_SpecCalc"))
        self.widget4 = QtGui.QWidget(self.groupBox_2)
        self.widget4.setGeometry(QtCore.QRect(0, 95, 119, 27))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.ImagePhys_SpecHPF = QtGui.QDoubleSpinBox(self.widget4)
        self.ImagePhys_SpecHPF.setProperty("value", 1.0)
        self.ImagePhys_SpecHPF.setObjectName(_fromUtf8("ImagePhys_SpecHPF"))
        self.horizontalLayout.addWidget(self.ImagePhys_SpecHPF)
        self.widget5 = QtGui.QWidget(self.groupBox_2)
        self.widget5.setGeometry(QtCore.QRect(0, 125, 119, 27))
        self.widget5.setObjectName(_fromUtf8("widget5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget5)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_8 = QtGui.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_11.addWidget(self.label_8)
        self.ImagePhys_SpecLPF = QtGui.QDoubleSpinBox(self.widget5)
        self.ImagePhys_SpecLPF.setProperty("value", 10.0)
        self.ImagePhys_SpecLPF.setObjectName(_fromUtf8("ImagePhys_SpecLPF"))
        self.horizontalLayout_11.addWidget(self.ImagePhys_SpecLPF)
        self.widget6 = QtGui.QWidget(self.groupBox_2)
        self.widget6.setGeometry(QtCore.QRect(1, 155, 116, 27))
        self.widget6.setObjectName(_fromUtf8("widget6"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget6)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = QtGui.QLabel(self.widget6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        self.ImagePhys_FFTSmooth = QtGui.QSpinBox(self.widget6)
        self.ImagePhys_FFTSmooth.setMaximum(16)
        self.ImagePhys_FFTSmooth.setObjectName(_fromUtf8("ImagePhys_FFTSmooth"))
        self.horizontalLayout_12.addWidget(self.ImagePhys_FFTSmooth)
        self.gridLayout_2.addWidget(self.groupBox_2, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.ImagePhys_ROIKernel.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Corrections, ROI\'s and Filtering", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_CorrTool_LPF.setText(QtGui.QApplication.translate("Form", "LPF Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_CorrTool_HPF.setText(QtGui.QApplication.translate("Form", "HPF Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Baseline begin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Baseine end", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ImgMethod.setItemText(0, QtGui.QApplication.translate("Form", "dF/Fo", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ImgMethod.setItemText(1, QtGui.QApplication.translate("Form", "median", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ImgMethod.setItemText(2, QtGui.QApplication.translate("Form", "Norm\'d", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ImgMethod.setItemText(3, QtGui.QApplication.translate("Form", "Slow Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ImgMethod.setItemText(4, QtGui.QApplication.translate("Form", "G/R", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_View.setItemText(0, QtGui.QApplication.translate("Form", "Movie", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_View.setItemText(1, QtGui.QApplication.translate("Form", "Reference Image", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_View.setItemText(2, QtGui.QApplication.translate("Form", "Std Image", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_View.setItemText(3, QtGui.QApplication.translate("Form", "Spectrum Image", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_View.setItemText(4, QtGui.QApplication.translate("Form", "Ratio Image", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_DisplayTraces.setText(QtGui.QApplication.translate("Form", "Display dF/F", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ExportTiff.setText(QtGui.QApplication.translate("Form", "Export TIFF", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ImgNormalize.setText(QtGui.QApplication.translate("Form", "Normalize", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_NormInfo.setText(QtGui.QApplication.translate("Form", "NormInfo", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_Update.setText(QtGui.QApplication.translate("Form", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_CorrTool_BL1.setText(QtGui.QApplication.translate("Form", "Baseline 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_RectSelect.setText(QtGui.QApplication.translate("Form", "Select with \n"
"rectangle  box", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Kernel", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ROIKernel.setItemText(0, QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ROIKernel.setItemText(1, QtGui.QApplication.translate("Form", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ROIKernel.setItemText(2, QtGui.QApplication.translate("Form", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ROIKernel.setItemText(3, QtGui.QApplication.translate("Form", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ROIKernel.setItemText(4, QtGui.QApplication.translate("Form", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ROIKernel.setItemText(5, QtGui.QApplication.translate("Form", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Thr(L)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Thr(H)", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_findROIs.setText(QtGui.QApplication.translate("Form", "Auto ROI Detect", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_clearRoi.setText(QtGui.QApplication.translate("Form", "Clear All ROIs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "ROI Size", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_StdRB.setText(QtGui.QApplication.translate("Form", "Std", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_FFTRB.setText(QtGui.QApplication.translate("Form", "FFT", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_addRoi.setText(QtGui.QApplication.translate("Form", "Add Roi", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_RecalculateROIs.setText(QtGui.QApplication.translate("Form", "Recalculate ROIs", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_RetrieveROI.setText(QtGui.QApplication.translate("Form", "Retrieve ROI File", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_SaveROI.setText(QtGui.QApplication.translate("Form", "Save ROI File", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_PhysROIPlot.setText(QtGui.QApplication.translate("Form", "MultiPlot", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_FileGroup.setTitle(QtGui.QApplication.translate("Form", "File Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ImageMode.setItemText(0, QtGui.QApplication.translate("Form", "Non-Ratiometric (dF/Fo)", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_ImageMode.setItemText(1, QtGui.QApplication.translate("Form", "Ratiometric (G/R)", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_clearRatio.setText(QtGui.QApplication.translate("Form", "Clear Ratio Image", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_GetFileInfo.setText(QtGui.QApplication.translate("Form", "Get File Info", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_getRatio.setText(QtGui.QApplication.translate("Form", "Get Ratio Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Data Struct", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_DataStruct.setItemText(0, QtGui.QApplication.translate("Form", "Flat", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_DataStruct.setItemText(1, QtGui.QApplication.translate("Form", "Interleaved", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Ignore images", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Downsample", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_Downsample.setItemText(0, QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_Downsample.setItemText(1, QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_Downsample.setItemText(2, QtGui.QApplication.translate("Form", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_Downsample.setItemText(3, QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_Downsample.setItemText(4, QtGui.QApplication.translate("Form", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_Downsample.setItemText(5, QtGui.QApplication.translate("Form", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_Downsample.setItemText(6, QtGui.QApplication.translate("Form", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_Downsample.setItemText(7, QtGui.QApplication.translate("Form", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_Downsample.setItemText(8, QtGui.QApplication.translate("Form", "500", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_Downsample.setItemText(9, QtGui.QApplication.translate("Form", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Corrections", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_RegisterStack.setText(QtGui.QApplication.translate("Form", "Register Stack", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_UnBleach.setText(QtGui.QApplication.translate("Form", "Bleach Corr", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_BleachInfo.setText(QtGui.QApplication.translate("Form", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.ImagePhys_SpecCalc.setText(QtGui.QApplication.translate("Form", "Spectrum Calc", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Low", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "High", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Spec Smooth", None, QtGui.QApplication.UnicodeUTF8))

