# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multipatchTemplate.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MultiPatch(object):
    def setupUi(self, MultiPatch):
        MultiPatch.setObjectName(_fromUtf8("MultiPatch"))
        MultiPatch.resize(941, 349)
        self.gridLayout = QtGui.QGridLayout(MultiPatch)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sealBtn = QtGui.QPushButton(MultiPatch)
        self.sealBtn.setObjectName(_fromUtf8("sealBtn"))
        self.gridLayout.addWidget(self.sealBtn, 0, 0, 1, 1)
        self.breakInBtn = QtGui.QPushButton(MultiPatch)
        self.breakInBtn.setObjectName(_fromUtf8("breakInBtn"))
        self.gridLayout.addWidget(self.breakInBtn, 0, 1, 1, 1)
        self.reSealBtn = QtGui.QPushButton(MultiPatch)
        self.reSealBtn.setObjectName(_fromUtf8("reSealBtn"))
        self.gridLayout.addWidget(self.reSealBtn, 0, 2, 1, 1)
        self.setTargetBtn = QtGui.QPushButton(MultiPatch)
        self.setTargetBtn.setCheckable(True)
        self.setTargetBtn.setObjectName(_fromUtf8("setTargetBtn"))
        self.gridLayout.addWidget(self.setTargetBtn, 1, 0, 1, 1)
        self.hideMarkersBtn = QtGui.QPushButton(MultiPatch)
        self.hideMarkersBtn.setCheckable(True)
        self.hideMarkersBtn.setObjectName(_fromUtf8("hideMarkersBtn"))
        self.gridLayout.addWidget(self.hideMarkersBtn, 1, 1, 1, 1)
        self.homeBtn = QtGui.QPushButton(MultiPatch)
        self.homeBtn.setObjectName(_fromUtf8("homeBtn"))
        self.gridLayout.addWidget(self.homeBtn, 1, 2, 1, 1)
        self.coarseSearchBtn = QtGui.QPushButton(MultiPatch)
        self.coarseSearchBtn.setObjectName(_fromUtf8("coarseSearchBtn"))
        self.gridLayout.addWidget(self.coarseSearchBtn, 2, 0, 1, 1)
        self.fineSearchBtn = QtGui.QPushButton(MultiPatch)
        self.fineSearchBtn.setObjectName(_fromUtf8("fineSearchBtn"))
        self.gridLayout.addWidget(self.fineSearchBtn, 2, 1, 1, 1)
        self.calibrateBtn = QtGui.QPushButton(MultiPatch)
        self.calibrateBtn.setCheckable(True)
        self.calibrateBtn.setObjectName(_fromUtf8("calibrateBtn"))
        self.gridLayout.addWidget(self.calibrateBtn, 2, 2, 1, 1)
        self.aboveTargetBtn = QtGui.QPushButton(MultiPatch)
        self.aboveTargetBtn.setObjectName(_fromUtf8("aboveTargetBtn"))
        self.gridLayout.addWidget(self.aboveTargetBtn, 3, 0, 1, 1)
        self.approachBtn = QtGui.QPushButton(MultiPatch)
        self.approachBtn.setObjectName(_fromUtf8("approachBtn"))
        self.gridLayout.addWidget(self.approachBtn, 3, 1, 1, 1)
        self.autoCalibrateBtn = QtGui.QPushButton(MultiPatch)
        self.autoCalibrateBtn.setObjectName(_fromUtf8("autoCalibrateBtn"))
        self.gridLayout.addWidget(self.autoCalibrateBtn, 3, 2, 1, 1)
        self.slowBtn = QtGui.QPushButton(MultiPatch)
        self.slowBtn.setCheckable(True)
        self.slowBtn.setObjectName(_fromUtf8("slowBtn"))
        self.gridLayout.addWidget(self.slowBtn, 4, 0, 1, 1)
        self.fastBtn = QtGui.QPushButton(MultiPatch)
        self.fastBtn.setCheckable(True)
        self.fastBtn.setObjectName(_fromUtf8("fastBtn"))
        self.gridLayout.addWidget(self.fastBtn, 4, 2, 1, 1)
        self.stepInBtn = QtGui.QPushButton(MultiPatch)
        self.stepInBtn.setObjectName(_fromUtf8("stepInBtn"))
        self.gridLayout.addWidget(self.stepInBtn, 5, 0, 1, 1)
        self.stepOutBtn = QtGui.QPushButton(MultiPatch)
        self.stepOutBtn.setObjectName(_fromUtf8("stepOutBtn"))
        self.gridLayout.addWidget(self.stepOutBtn, 5, 1, 1, 1)
        self.moveInBtn = QtGui.QPushButton(MultiPatch)
        self.moveInBtn.setObjectName(_fromUtf8("moveInBtn"))
        self.gridLayout.addWidget(self.moveInBtn, 5, 2, 1, 1)
        self.label = QtGui.QLabel(MultiPatch)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.stepSizeSpin = SpinBox(MultiPatch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepSizeSpin.sizePolicy().hasHeightForWidth())
        self.stepSizeSpin.setSizePolicy(sizePolicy)
        self.stepSizeSpin.setObjectName(_fromUtf8("stepSizeSpin"))
        self.gridLayout.addWidget(self.stepSizeSpin, 6, 1, 1, 1)
        self.toTargetBtn = QtGui.QPushButton(MultiPatch)
        self.toTargetBtn.setObjectName(_fromUtf8("toTargetBtn"))
        self.gridLayout.addWidget(self.toTargetBtn, 6, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 1, 1, 1)
        self.selectedGroupBox = QtGui.QGroupBox(MultiPatch)
        self.selectedGroupBox.setObjectName(_fromUtf8("selectedGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.selectedGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.autoPressureBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.autoPressureBtn.setCheckable(True)
        self.autoPressureBtn.setObjectName(_fromUtf8("autoPressureBtn"))
        self.gridLayout_2.addWidget(self.autoPressureBtn, 0, 0, 1, 1)
        self.pressureSpin = QtGui.QDoubleSpinBox(self.selectedGroupBox)
        self.pressureSpin.setObjectName(_fromUtf8("pressureSpin"))
        self.gridLayout_2.addWidget(self.pressureSpin, 0, 1, 1, 1)
        self.userPressureBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.userPressureBtn.setCheckable(True)
        self.userPressureBtn.setObjectName(_fromUtf8("userPressureBtn"))
        self.gridLayout_2.addWidget(self.userPressureBtn, 0, 2, 1, 1)
        self.testPulseBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.testPulseBtn.setCheckable(True)
        self.testPulseBtn.setObjectName(_fromUtf8("testPulseBtn"))
        self.gridLayout_2.addWidget(self.testPulseBtn, 1, 0, 1, 1)
        self.resetBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.resetBtn.setObjectName(_fromUtf8("resetBtn"))
        self.gridLayout_2.addWidget(self.resetBtn, 1, 1, 1, 1)
        self.recordBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.recordBtn.setCheckable(True)
        self.recordBtn.setObjectName(_fromUtf8("recordBtn"))
        self.gridLayout_2.addWidget(self.recordBtn, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.selectedGroupBox, 8, 0, 1, 3)
        self.matrixWidget = QtGui.QWidget(MultiPatch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matrixWidget.sizePolicy().hasHeightForWidth())
        self.matrixWidget.setSizePolicy(sizePolicy)
        self.matrixWidget.setObjectName(_fromUtf8("matrixWidget"))
        self.matrixLayout = QtGui.QGridLayout(self.matrixWidget)
        self.matrixLayout.setMargin(0)
        self.matrixLayout.setSpacing(0)
        self.matrixLayout.setObjectName(_fromUtf8("matrixLayout"))
        self.gridLayout.addWidget(self.matrixWidget, 0, 3, 9, 1)

        self.retranslateUi(MultiPatch)
        QtCore.QMetaObject.connectSlotsByName(MultiPatch)

    def retranslateUi(self, MultiPatch):
        MultiPatch.setWindowTitle(_translate("MultiPatch", "Form", None))
        self.sealBtn.setText(_translate("MultiPatch", "Seal", None))
        self.breakInBtn.setText(_translate("MultiPatch", "Break In", None))
        self.reSealBtn.setText(_translate("MultiPatch", "ReSeal", None))
        self.setTargetBtn.setText(_translate("MultiPatch", "Set target", None))
        self.hideMarkersBtn.setText(_translate("MultiPatch", "Hide Markers", None))
        self.homeBtn.setText(_translate("MultiPatch", "Home", None))
        self.coarseSearchBtn.setText(_translate("MultiPatch", "Coarse Search", None))
        self.fineSearchBtn.setText(_translate("MultiPatch", "Fine Search", None))
        self.calibrateBtn.setText(_translate("MultiPatch", "Calibrate", None))
        self.aboveTargetBtn.setText(_translate("MultiPatch", "Above target", None))
        self.approachBtn.setText(_translate("MultiPatch", "Approach", None))
        self.autoCalibrateBtn.setText(_translate("MultiPatch", "Auto cal.", None))
        self.slowBtn.setText(_translate("MultiPatch", "Slow", None))
        self.fastBtn.setText(_translate("MultiPatch", "Fast", None))
        self.stepInBtn.setText(_translate("MultiPatch", "Step in", None))
        self.stepOutBtn.setText(_translate("MultiPatch", "Step out", None))
        self.moveInBtn.setText(_translate("MultiPatch", "Move in", None))
        self.label.setText(_translate("MultiPatch", "Step size", None))
        self.toTargetBtn.setText(_translate("MultiPatch", "To target", None))
        self.selectedGroupBox.setTitle(_translate("MultiPatch", "Selected: ", None))
        self.autoPressureBtn.setText(_translate("MultiPatch", "Auto Pressure", None))
        self.userPressureBtn.setText(_translate("MultiPatch", "User", None))
        self.testPulseBtn.setText(_translate("MultiPatch", "Test Pulse", None))
        self.resetBtn.setText(_translate("MultiPatch", "Reset History", None))
        self.recordBtn.setText(_translate("MultiPatch", "Record", None))

from acq4.pyqtgraph import SpinBox
