# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multipatchTemplate.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MultiPatch(object):
    def setupUi(self, MultiPatch):
        MultiPatch.setObjectName(_fromUtf8("MultiPatch"))
        MultiPatch.resize(941, 466)
        self.gridLayout = QtGui.QGridLayout(MultiPatch)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(MultiPatch)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.recordBtn = QtGui.QPushButton(MultiPatch)
        self.recordBtn.setCheckable(True)
        self.recordBtn.setObjectName(_fromUtf8("recordBtn"))
        self.gridLayout.addWidget(self.recordBtn, 2, 0, 1, 1)
        self.matrixWidget = QtGui.QWidget(MultiPatch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matrixWidget.sizePolicy().hasHeightForWidth())
        self.matrixWidget.setSizePolicy(sizePolicy)
        self.matrixWidget.setObjectName(_fromUtf8("matrixWidget"))
        self.matrixLayout = QtGui.QGridLayout(self.matrixWidget)
        self.matrixLayout.setMargin(0)
        self.matrixLayout.setSpacing(0)
        self.matrixLayout.setObjectName(_fromUtf8("matrixLayout"))
        self.gridLayout.addWidget(self.matrixWidget, 0, 2, 4, 1)
        self.selectedGroupBox = QtGui.QGroupBox(MultiPatch)
        self.selectedGroupBox.setObjectName(_fromUtf8("selectedGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.selectedGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton = QtGui.QPushButton(self.selectedGroupBox)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 10, 0, 1, 1)
        self.homeBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.homeBtn.setObjectName(_fromUtf8("homeBtn"))
        self.gridLayout_2.addWidget(self.homeBtn, 3, 1, 1, 1)
        self.coarseSearchBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.coarseSearchBtn.setObjectName(_fromUtf8("coarseSearchBtn"))
        self.gridLayout_2.addWidget(self.coarseSearchBtn, 1, 1, 1, 1)
        self.aboveTargetBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.aboveTargetBtn.setObjectName(_fromUtf8("aboveTargetBtn"))
        self.gridLayout_2.addWidget(self.aboveTargetBtn, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 8, 0, 1, 1)
        self.slowBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.slowBtn.setCheckable(True)
        self.slowBtn.setObjectName(_fromUtf8("slowBtn"))
        self.gridLayout_2.addWidget(self.slowBtn, 4, 0, 1, 1)
        self.fastBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.fastBtn.setCheckable(True)
        self.fastBtn.setObjectName(_fromUtf8("fastBtn"))
        self.gridLayout_2.addWidget(self.fastBtn, 4, 2, 1, 1)
        self.autoCalibrateBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.autoCalibrateBtn.setObjectName(_fromUtf8("autoCalibrateBtn"))
        self.gridLayout_2.addWidget(self.autoCalibrateBtn, 2, 2, 1, 1)
        self.cellDetectBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.cellDetectBtn.setObjectName(_fromUtf8("cellDetectBtn"))
        self.gridLayout_2.addWidget(self.cellDetectBtn, 6, 2, 1, 1)
        self.breakInBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.breakInBtn.setObjectName(_fromUtf8("breakInBtn"))
        self.gridLayout_2.addWidget(self.breakInBtn, 6, 1, 1, 1)
        self.toTargetBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.toTargetBtn.setObjectName(_fromUtf8("toTargetBtn"))
        self.gridLayout_2.addWidget(self.toTargetBtn, 3, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 1)
        self.setTargetBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.setTargetBtn.setCheckable(True)
        self.setTargetBtn.setObjectName(_fromUtf8("setTargetBtn"))
        self.gridLayout_2.addWidget(self.setTargetBtn, 1, 0, 1, 1)
        self.fineSearchBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.fineSearchBtn.setObjectName(_fromUtf8("fineSearchBtn"))
        self.gridLayout_2.addWidget(self.fineSearchBtn, 2, 1, 1, 1)
        self.calibrateBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.calibrateBtn.setCheckable(True)
        self.calibrateBtn.setObjectName(_fromUtf8("calibrateBtn"))
        self.gridLayout_2.addWidget(self.calibrateBtn, 1, 2, 1, 1)
        self.sealBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.sealBtn.setObjectName(_fromUtf8("sealBtn"))
        self.gridLayout_2.addWidget(self.sealBtn, 6, 0, 1, 1)
        self.reSealBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.reSealBtn.setObjectName(_fromUtf8("reSealBtn"))
        self.gridLayout_2.addWidget(self.reSealBtn, 7, 0, 1, 1)
        self.approachBtn = QtGui.QPushButton(self.selectedGroupBox)
        self.approachBtn.setObjectName(_fromUtf8("approachBtn"))
        self.gridLayout_2.addWidget(self.approachBtn, 3, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.selectedGroupBox)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 10, 2, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.selectedGroupBox)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 10, 1, 1, 1)
        self.gridLayout.addWidget(self.selectedGroupBox, 1, 0, 1, 2)
        self.hideMarkersBtn = QtGui.QPushButton(MultiPatch)
        self.hideMarkersBtn.setCheckable(True)
        self.hideMarkersBtn.setObjectName(_fromUtf8("hideMarkersBtn"))
        self.gridLayout.addWidget(self.hideMarkersBtn, 3, 1, 1, 1)
        self.resetBtn = QtGui.QPushButton(MultiPatch)
        self.resetBtn.setObjectName(_fromUtf8("resetBtn"))
        self.gridLayout.addWidget(self.resetBtn, 2, 1, 1, 1)
        self.profileCombo = QtGui.QComboBox(MultiPatch)
        self.profileCombo.setObjectName(_fromUtf8("profileCombo"))
        self.gridLayout.addWidget(self.profileCombo, 0, 1, 1, 1)

        self.retranslateUi(MultiPatch)
        QtCore.QMetaObject.connectSlotsByName(MultiPatch)

    def retranslateUi(self, MultiPatch):
        MultiPatch.setWindowTitle(_translate("MultiPatch", "Form", None))
        self.label.setText(_translate("MultiPatch", "Profile:", None))
        self.recordBtn.setText(_translate("MultiPatch", "Record", None))
        self.selectedGroupBox.setTitle(_translate("MultiPatch", "Selected: ", None))
        self.pushButton.setText(_translate("MultiPatch", "Pip. Offset", None))
        self.homeBtn.setText(_translate("MultiPatch", "Home", None))
        self.coarseSearchBtn.setText(_translate("MultiPatch", "Coarse Search", None))
        self.aboveTargetBtn.setText(_translate("MultiPatch", "Above target", None))
        self.slowBtn.setText(_translate("MultiPatch", "Slow", None))
        self.fastBtn.setText(_translate("MultiPatch", "Fast", None))
        self.autoCalibrateBtn.setText(_translate("MultiPatch", "Auto cal.", None))
        self.cellDetectBtn.setText(_translate("MultiPatch", "Cell Detect", None))
        self.breakInBtn.setText(_translate("MultiPatch", "Break In", None))
        self.toTargetBtn.setText(_translate("MultiPatch", "To target", None))
        self.setTargetBtn.setText(_translate("MultiPatch", "Set target", None))
        self.fineSearchBtn.setText(_translate("MultiPatch", "Fine Search", None))
        self.calibrateBtn.setText(_translate("MultiPatch", "Calibrate", None))
        self.sealBtn.setText(_translate("MultiPatch", "Seal", None))
        self.reSealBtn.setText(_translate("MultiPatch", "ReSeal", None))
        self.approachBtn.setText(_translate("MultiPatch", "Approach", None))
        self.pushButton_2.setText(_translate("MultiPatch", "Bridge Balance", None))
        self.pushButton_3.setText(_translate("MultiPatch", "Pip. Capacit.", None))
        self.hideMarkersBtn.setText(_translate("MultiPatch", "Hide Markers", None))
        self.resetBtn.setText(_translate("MultiPatch", "Reset History", None))

