# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/modules/MultiPatch/pipetteTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PipetteControl(object):
    def setupUi(self, PipetteControl):
        PipetteControl.setObjectName("PipetteControl")
        PipetteControl.resize(333, 75)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PipetteControl.sizePolicy().hasHeightForWidth())
        PipetteControl.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(PipetteControl)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.targetBtn = QtWidgets.QPushButton(PipetteControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetBtn.sizePolicy().hasHeightForWidth())
        self.targetBtn.setSizePolicy(sizePolicy)
        self.targetBtn.setMaximumSize(Qt.QSize(40, 16777215))
        self.targetBtn.setObjectName("targetBtn")
        self.gridLayout.addWidget(self.targetBtn, 1, 4, 1, 1)
        self.stateCombo = QtWidgets.QComboBox(PipetteControl)
        self.stateCombo.setObjectName("stateCombo")
        self.stateCombo.addItem("")
        self.stateCombo.addItem("")
        self.stateCombo.addItem("")
        self.stateCombo.addItem("")
        self.stateCombo.addItem("")
        self.stateCombo.addItem("")
        self.stateCombo.addItem("")
        self.stateCombo.addItem("")
        self.gridLayout.addWidget(self.stateCombo, 0, 3, 1, 2)
        self.plotLayoutWidget = QtWidgets.QWidget(PipetteControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotLayoutWidget.sizePolicy().hasHeightForWidth())
        self.plotLayoutWidget.setSizePolicy(sizePolicy)
        self.plotLayoutWidget.setObjectName("plotLayoutWidget")
        self.plotLayout = QtWidgets.QHBoxLayout(self.plotLayoutWidget)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setSpacing(0)
        self.plotLayout.setObjectName("plotLayout")
        self.gridLayout.addWidget(self.plotLayoutWidget, 0, 5, 4, 1)
        self.selectBtn = QtWidgets.QPushButton(PipetteControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectBtn.sizePolicy().hasHeightForWidth())
        self.selectBtn.setSizePolicy(sizePolicy)
        self.selectBtn.setMaximumSize(Qt.QSize(30, 16777215))
        font = Qt.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.selectBtn.setFont(font)
        self.selectBtn.setCheckable(True)
        self.selectBtn.setObjectName("selectBtn")
        self.gridLayout.addWidget(self.selectBtn, 0, 0, 4, 1)
        self.tipBtn = QtWidgets.QPushButton(PipetteControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tipBtn.sizePolicy().hasHeightForWidth())
        self.tipBtn.setSizePolicy(sizePolicy)
        self.tipBtn.setMaximumSize(Qt.QSize(40, 16777215))
        self.tipBtn.setObjectName("tipBtn")
        self.gridLayout.addWidget(self.tipBtn, 2, 4, 1, 1)
        self.soloBtn = QtWidgets.QPushButton(PipetteControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.soloBtn.sizePolicy().hasHeightForWidth())
        self.soloBtn.setSizePolicy(sizePolicy)
        self.soloBtn.setMaximumSize(Qt.QSize(30, 16777215))
        self.soloBtn.setCheckable(True)
        self.soloBtn.setObjectName("soloBtn")
        self.gridLayout.addWidget(self.soloBtn, 2, 3, 1, 1)
        self.lockBtn = QtWidgets.QPushButton(PipetteControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lockBtn.sizePolicy().hasHeightForWidth())
        self.lockBtn.setSizePolicy(sizePolicy)
        self.lockBtn.setMaximumSize(Qt.QSize(30, 16777215))
        self.lockBtn.setCheckable(True)
        self.lockBtn.setObjectName("lockBtn")
        self.gridLayout.addWidget(self.lockBtn, 1, 3, 1, 1)

        self.retranslateUi(PipetteControl)
        Qt.QMetaObject.connectSlotsByName(PipetteControl)

    def retranslateUi(self, PipetteControl):
        _translate = Qt.QCoreApplication.translate
        PipetteControl.setWindowTitle(_translate("PipetteControl", "Form"))
        self.targetBtn.setText(_translate("PipetteControl", "target"))
        self.stateCombo.setItemText(0, _translate("PipetteControl", "out"))
        self.stateCombo.setItemText(1, _translate("PipetteControl", "bath"))
        self.stateCombo.setItemText(2, _translate("PipetteControl", "approach"))
        self.stateCombo.setItemText(3, _translate("PipetteControl", "seal"))
        self.stateCombo.setItemText(4, _translate("PipetteControl", "attached"))
        self.stateCombo.setItemText(5, _translate("PipetteControl", "break in"))
        self.stateCombo.setItemText(6, _translate("PipetteControl", "whole cell"))
        self.stateCombo.setItemText(7, _translate("PipetteControl", "outside-out"))
        self.selectBtn.setText(_translate("PipetteControl", "1"))
        self.tipBtn.setText(_translate("PipetteControl", "tip"))
        self.soloBtn.setText(_translate("PipetteControl", "Solo"))
        self.lockBtn.setText(_translate("PipetteControl", "Lock"))

