# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './acq4/modules/Imager/imagerTemplate.ui'
#
# Created: Tue Dec 24 01:49:10 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(233, 284)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 231, 281))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(231, 0))
        self.frame.setMaximumSize(QtCore.QSize(400, 281))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 11, 218, 255))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.xpos = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xpos.sizePolicy().hasHeightForWidth())
        self.xpos.setSizePolicy(sizePolicy)
        self.xpos.setObjectName(_fromUtf8("xpos"))
        self.gridLayout.addWidget(self.xpos, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.width = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.width.sizePolicy().hasHeightForWidth())
        self.width.setSizePolicy(sizePolicy)
        self.width.setObjectName(_fromUtf8("width"))
        self.gridLayout.addWidget(self.width, 0, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.ypos = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ypos.sizePolicy().hasHeightForWidth())
        self.ypos.setSizePolicy(sizePolicy)
        self.ypos.setObjectName(_fromUtf8("ypos"))
        self.gridLayout.addWidget(self.ypos, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.height = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.height.sizePolicy().hasHeightForWidth())
        self.height.setSizePolicy(sizePolicy)
        self.height.setObjectName(_fromUtf8("height"))
        self.gridLayout.addWidget(self.height, 1, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.pixelSize = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixelSize.sizePolicy().hasHeightForWidth())
        self.pixelSize.setSizePolicy(sizePolicy)
        self.pixelSize.setObjectName(_fromUtf8("pixelSize"))
        self.gridLayout.addWidget(self.pixelSize, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 2, 1, 1)
        self.dwellTime = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwellTime.sizePolicy().hasHeightForWidth())
        self.dwellTime.setSizePolicy(sizePolicy)
        self.dwellTime.setObjectName(_fromUtf8("dwellTime"))
        self.gridLayout.addWidget(self.dwellTime, 2, 3, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.snap_Button = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snap_Button.sizePolicy().hasHeightForWidth())
        self.snap_Button.setSizePolicy(sizePolicy)
        self.snap_Button.setMinimumSize(QtCore.QSize(90, 0))
        self.snap_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.snap_Button.setAutoFillBackground(False)
        self.snap_Button.setObjectName(_fromUtf8("snap_Button"))
        self.gridLayout_2.addWidget(self.snap_Button, 0, 0, 1, 1)
        self.video_button = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_button.sizePolicy().hasHeightForWidth())
        self.video_button.setSizePolicy(sizePolicy)
        self.video_button.setMinimumSize(QtCore.QSize(90, 0))
        self.video_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.video_button.setAutoFillBackground(False)
        self.video_button.setCheckable(True)
        self.video_button.setObjectName(_fromUtf8("video_button"))
        self.gridLayout_2.addWidget(self.video_button, 0, 1, 1, 1)
        self.snap_Standard_Button = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snap_Standard_Button.sizePolicy().hasHeightForWidth())
        self.snap_Standard_Button.setSizePolicy(sizePolicy)
        self.snap_Standard_Button.setMinimumSize(QtCore.QSize(90, 0))
        self.snap_Standard_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.snap_Standard_Button.setAutoFillBackground(False)
        self.snap_Standard_Button.setObjectName(_fromUtf8("snap_Standard_Button"))
        self.gridLayout_2.addWidget(self.snap_Standard_Button, 1, 0, 1, 1)
        self.video_std_button = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_std_button.sizePolicy().hasHeightForWidth())
        self.video_std_button.setSizePolicy(sizePolicy)
        self.video_std_button.setMinimumSize(QtCore.QSize(90, 0))
        self.video_std_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.video_std_button.setAutoFillBackground(False)
        self.video_std_button.setCheckable(True)
        self.video_std_button.setObjectName(_fromUtf8("video_std_button"))
        self.gridLayout_2.addWidget(self.video_std_button, 1, 1, 1, 1)
        self.snap_High_Button = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snap_High_Button.sizePolicy().hasHeightForWidth())
        self.snap_High_Button.setSizePolicy(sizePolicy)
        self.snap_High_Button.setMinimumSize(QtCore.QSize(90, 0))
        self.snap_High_Button.setObjectName(_fromUtf8("snap_High_Button"))
        self.gridLayout_2.addWidget(self.snap_High_Button, 2, 0, 1, 1)
        self.video_fast_button = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_fast_button.sizePolicy().hasHeightForWidth())
        self.video_fast_button.setSizePolicy(sizePolicy)
        self.video_fast_button.setMinimumSize(QtCore.QSize(90, 0))
        self.video_fast_button.setCheckable(True)
        self.video_fast_button.setObjectName(_fromUtf8("video_fast_button"))
        self.gridLayout_2.addWidget(self.video_fast_button, 2, 1, 1, 1)
        self.record_button = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_button.sizePolicy().hasHeightForWidth())
        self.record_button.setSizePolicy(sizePolicy)
        self.record_button.setMinimumSize(QtCore.QSize(90, 0))
        self.record_button.setCheckable(True)
        self.record_button.setObjectName(_fromUtf8("record_button"))
        self.gridLayout_2.addWidget(self.record_button, 3, 0, 1, 1)
        self.Align_to_Camera = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Align_to_Camera.sizePolicy().hasHeightForWidth())
        self.Align_to_Camera.setSizePolicy(sizePolicy)
        self.Align_to_Camera.setMinimumSize(QtCore.QSize(90, 0))
        self.Align_to_Camera.setObjectName(_fromUtf8("Align_to_Camera"))
        self.gridLayout_2.addWidget(self.Align_to_Camera, 4, 0, 1, 1)
        self.saveROI = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveROI.sizePolicy().hasHeightForWidth())
        self.saveROI.setSizePolicy(sizePolicy)
        self.saveROI.setMinimumSize(QtCore.QSize(90, 0))
        self.saveROI.setObjectName(_fromUtf8("saveROI"))
        self.gridLayout_2.addWidget(self.saveROI, 4, 1, 1, 1)
        self.set_TilesButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_TilesButton.sizePolicy().hasHeightForWidth())
        self.set_TilesButton.setSizePolicy(sizePolicy)
        self.set_TilesButton.setMinimumSize(QtCore.QSize(90, 0))
        self.set_TilesButton.setObjectName(_fromUtf8("set_TilesButton"))
        self.gridLayout_2.addWidget(self.set_TilesButton, 5, 0, 1, 1)
        self.restoreROI = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restoreROI.sizePolicy().hasHeightForWidth())
        self.restoreROI.setSizePolicy(sizePolicy)
        self.restoreROI.setMinimumSize(QtCore.QSize(90, 0))
        self.restoreROI.setObjectName(_fromUtf8("restoreROI"))
        self.gridLayout_2.addWidget(self.restoreROI, 5, 1, 1, 1)
        self.run_button = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_button.sizePolicy().hasHeightForWidth())
        self.run_button.setSizePolicy(sizePolicy)
        self.run_button.setMinimumSize(QtCore.QSize(90, 0))
        self.run_button.setObjectName(_fromUtf8("run_button"))
        self.gridLayout_2.addWidget(self.run_button, 6, 0, 1, 1)
        self.stop_button = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setMinimumSize(QtCore.QSize(90, 0))
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.gridLayout_2.addWidget(self.stop_button, 6, 1, 1, 1)
        self.hide_check = QtGui.QCheckBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hide_check.sizePolicy().hasHeightForWidth())
        self.hide_check.setSizePolicy(sizePolicy)
        self.hide_check.setObjectName(_fromUtf8("hide_check"))
        self.gridLayout_2.addWidget(self.hide_check, 7, 0, 1, 1)
        self.alphaSlider = QtGui.QSlider(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaSlider.sizePolicy().hasHeightForWidth())
        self.alphaSlider.setSizePolicy(sizePolicy)
        self.alphaSlider.setMaximum(100)
        self.alphaSlider.setSingleStep(2)
        self.alphaSlider.setProperty("value", 50)
        self.alphaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.alphaSlider.setInvertedControls(True)
        self.alphaSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.alphaSlider.setObjectName(_fromUtf8("alphaSlider"))
        self.gridLayout_2.addWidget(self.alphaSlider, 7, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 1, 4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_6.setText(_translate("Form", "Xpos (mm)", None))
        self.xpos.setText(_translate("Form", "TextLabel", None))
        self.label.setText(_translate("Form", "Width (um)", None))
        self.width.setText(_translate("Form", "TextLabel", None))
        self.label_8.setText(_translate("Form", "Ypos (mm)", None))
        self.ypos.setText(_translate("Form", "TextLabel", None))
        self.label_4.setText(_translate("Form", "Height (um)", None))
        self.height.setText(_translate("Form", "TextLabel", None))
        self.label_11.setText(_translate("Form", "Pixel (um)", None))
        self.pixelSize.setText(_translate("Form", "TextLabel", None))
        self.label_3.setText(_translate("Form", "Dwell  (us)", None))
        self.dwellTime.setText(_translate("Form", "TextLabel", None))
        self.snap_Button.setText(_translate("Form", "Snap", None))
        self.video_button.setText(_translate("Form", "Video", None))
        self.snap_Standard_Button.setText(_translate("Form", "Snap Std", None))
        self.video_std_button.setText(_translate("Form", "Video Std", None))
        self.snap_High_Button.setText(_translate("Form", "Snap High", None))
        self.video_fast_button.setText(_translate("Form", "Video Fast", None))
        self.record_button.setText(_translate("Form", "Record Stack", None))
        self.Align_to_Camera.setText(_translate("Form", "Align to Camera", None))
        self.saveROI.setText(_translate("Form", "Save ROI", None))
        self.set_TilesButton.setText(_translate("Form", "Set Tile Area", None))
        self.restoreROI.setText(_translate("Form", "Restore ROI", None))
        self.run_button.setText(_translate("Form", "Run", None))
        self.stop_button.setText(_translate("Form", "Stop", None))
        self.hide_check.setText(_translate("Form", "Hide Overlay", None))

