# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acq4/modules/Patch/PatchTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(315, 464)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_3 = QtWidgets.QSplitter(Form)
        self.splitter_3.setOrientation(Qt.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(Qt.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vcPulseCheck = QtWidgets.QCheckBox(self.groupBox_2)
        self.vcPulseCheck.setChecked(True)
        self.vcPulseCheck.setObjectName("vcPulseCheck")
        self.gridLayout_2.addWidget(self.vcPulseCheck, 2, 1, 1, 1)
        self.vcHoldCheck = QtWidgets.QCheckBox(self.groupBox_2)
        self.vcHoldCheck.setObjectName("vcHoldCheck")
        self.gridLayout_2.addWidget(self.vcHoldCheck, 3, 1, 1, 1)
        self.icPulseCheck = QtWidgets.QCheckBox(self.groupBox_2)
        self.icPulseCheck.setChecked(True)
        self.icPulseCheck.setObjectName("icPulseCheck")
        self.gridLayout_2.addWidget(self.icPulseCheck, 4, 1, 1, 1)
        self.icHoldCheck = QtWidgets.QCheckBox(self.groupBox_2)
        self.icHoldCheck.setObjectName("icHoldCheck")
        self.gridLayout_2.addWidget(self.icHoldCheck, 6, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 10, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 9, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 8, 0, 1, 2)
        self.icModeRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.icModeRadio.setObjectName("icModeRadio")
        self.gridLayout_2.addWidget(self.icModeRadio, 4, 0, 1, 1)
        self.vcModeRadio = QtWidgets.QRadioButton(self.groupBox_2)
        self.vcModeRadio.setChecked(True)
        self.vcModeRadio.setObjectName("vcModeRadio")
        self.gridLayout_2.addWidget(self.vcModeRadio, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.startBtn.setCheckable(True)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout.addWidget(self.startBtn)
        self.recordBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.recordBtn.setCheckable(True)
        self.recordBtn.setObjectName("recordBtn")
        self.horizontalLayout.addWidget(self.recordBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.icPulseSpin = SpinBox(self.groupBox_2)
        self.icPulseSpin.setObjectName("icPulseSpin")
        self.gridLayout_2.addWidget(self.icPulseSpin, 4, 2, 1, 1)
        self.pulseTimeSpin = SpinBox(self.groupBox_2)
        self.pulseTimeSpin.setSingleStep(1.0)
        self.pulseTimeSpin.setObjectName("pulseTimeSpin")
        self.gridLayout_2.addWidget(self.pulseTimeSpin, 9, 2, 1, 1)
        self.delayTimeSpin = SpinBox(self.groupBox_2)
        self.delayTimeSpin.setMinimum(1.0)
        self.delayTimeSpin.setMaximum(10000.0)
        self.delayTimeSpin.setSingleStep(1.0)
        self.delayTimeSpin.setObjectName("delayTimeSpin")
        self.gridLayout_2.addWidget(self.delayTimeSpin, 8, 2, 1, 1)
        self.vcPulseSpin = SpinBox(self.groupBox_2)
        self.vcPulseSpin.setObjectName("vcPulseSpin")
        self.gridLayout_2.addWidget(self.vcPulseSpin, 2, 2, 1, 1)
        self.icHoldSpin = SpinBox(self.groupBox_2)
        self.icHoldSpin.setObjectName("icHoldSpin")
        self.gridLayout_2.addWidget(self.icHoldSpin, 5, 2, 2, 1)
        self.cycleTimeSpin = SpinBox(self.groupBox_2)
        self.cycleTimeSpin.setSingleStep(1.0)
        self.cycleTimeSpin.setProperty("value", 0.2)
        self.cycleTimeSpin.setObjectName("cycleTimeSpin")
        self.gridLayout_2.addWidget(self.cycleTimeSpin, 10, 2, 1, 1)
        self.vcHoldSpin = SpinBox(self.groupBox_2)
        self.vcHoldSpin.setObjectName("vcHoldSpin")
        self.gridLayout_2.addWidget(self.vcHoldSpin, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bathModeBtn = QtWidgets.QToolButton(self.groupBox_2)
        self.bathModeBtn.setObjectName("bathModeBtn")
        self.horizontalLayout_2.addWidget(self.bathModeBtn)
        self.patchModeBtn = QtWidgets.QToolButton(self.groupBox_2)
        self.patchModeBtn.setObjectName("patchModeBtn")
        self.horizontalLayout_2.addWidget(self.patchModeBtn)
        self.cellModeBtn = QtWidgets.QToolButton(self.groupBox_2)
        self.cellModeBtn.setObjectName("cellModeBtn")
        self.horizontalLayout_2.addWidget(self.cellModeBtn)
        self.monitorModeBtn = QtWidgets.QToolButton(self.groupBox_2)
        self.monitorModeBtn.setObjectName("monitorModeBtn")
        self.horizontalLayout_2.addWidget(self.monitorModeBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 11, 0, 1, 1)
        self.averageSpin = QtWidgets.QSpinBox(self.groupBox_2)
        self.averageSpin.setMinimum(1)
        self.averageSpin.setMaximum(100)
        self.averageSpin.setProperty("value", 1)
        self.averageSpin.setObjectName("averageSpin")
        self.gridLayout_2.addWidget(self.averageSpin, 11, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.restingPotentialCheck = QtWidgets.QCheckBox(self.groupBox)
        self.restingPotentialCheck.setText("")
        self.restingPotentialCheck.setObjectName("restingPotentialCheck")
        self.gridLayout.addWidget(self.restingPotentialCheck, 3, 0, 1, 1)
        self.restingPotentialLabel = QtWidgets.QLabel(self.groupBox)
        self.restingPotentialLabel.setMinimumSize(Qt.QSize(140, 0))
        font = Qt.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.restingPotentialLabel.setFont(font)
        self.restingPotentialLabel.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.restingPotentialLabel.setObjectName("restingPotentialLabel")
        self.gridLayout.addWidget(self.restingPotentialLabel, 3, 2, 1, 1)
        self.restingCurrentCheck = QtWidgets.QCheckBox(self.groupBox)
        self.restingCurrentCheck.setText("")
        self.restingCurrentCheck.setObjectName("restingCurrentCheck")
        self.gridLayout.addWidget(self.restingCurrentCheck, 4, 0, 1, 1)
        self.fitErrorCheck = QtWidgets.QCheckBox(self.groupBox)
        self.fitErrorCheck.setText("")
        self.fitErrorCheck.setObjectName("fitErrorCheck")
        self.gridLayout.addWidget(self.fitErrorCheck, 6, 0, 1, 1)
        self.fitErrorLabel = QtWidgets.QLabel(self.groupBox)
        font = Qt.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.fitErrorLabel.setFont(font)
        self.fitErrorLabel.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.fitErrorLabel.setObjectName("fitErrorLabel")
        self.gridLayout.addWidget(self.fitErrorLabel, 6, 2, 1, 1)
        self.drawFitCheck = QtWidgets.QCheckBox(self.groupBox)
        self.drawFitCheck.setChecked(True)
        self.drawFitCheck.setObjectName("drawFitCheck")
        self.gridLayout.addWidget(self.drawFitCheck, 0, 2, 1, 1)
        self.accessResistanceLabel = QtWidgets.QLabel(self.groupBox)
        font = Qt.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.accessResistanceLabel.setFont(font)
        self.accessResistanceLabel.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.accessResistanceLabel.setObjectName("accessResistanceLabel")
        self.gridLayout.addWidget(self.accessResistanceLabel, 2, 2, 1, 1)
        self.inputResistanceLabel = QtWidgets.QLabel(self.groupBox)
        font = Qt.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inputResistanceLabel.setFont(font)
        self.inputResistanceLabel.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.inputResistanceLabel.setObjectName("inputResistanceLabel")
        self.gridLayout.addWidget(self.inputResistanceLabel, 1, 2, 1, 1)
        self.accessResistanceCheck = QtWidgets.QCheckBox(self.groupBox)
        self.accessResistanceCheck.setText("")
        self.accessResistanceCheck.setObjectName("accessResistanceCheck")
        self.gridLayout.addWidget(self.accessResistanceCheck, 2, 0, 1, 1)
        self.restingCurrentLabel = QtWidgets.QLabel(self.groupBox)
        self.restingCurrentLabel.setMinimumSize(Qt.QSize(120, 0))
        font = Qt.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.restingCurrentLabel.setFont(font)
        self.restingCurrentLabel.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.restingCurrentLabel.setObjectName("restingCurrentLabel")
        self.gridLayout.addWidget(self.restingCurrentLabel, 4, 2, 1, 1)
        self.inputResistanceCheck = QtWidgets.QCheckBox(self.groupBox)
        self.inputResistanceCheck.setMaximumSize(Qt.QSize(20, 16777215))
        self.inputResistanceCheck.setText("")
        self.inputResistanceCheck.setChecked(True)
        self.inputResistanceCheck.setObjectName("inputResistanceCheck")
        self.gridLayout.addWidget(self.inputResistanceCheck, 1, 0, 1, 1)
        self.capacitanceCheck = QtWidgets.QCheckBox(self.groupBox)
        self.capacitanceCheck.setText("")
        self.capacitanceCheck.setObjectName("capacitanceCheck")
        self.gridLayout.addWidget(self.capacitanceCheck, 5, 0, 1, 1)
        self.capacitanceLabel = QtWidgets.QLabel(self.groupBox)
        font = Qt.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.capacitanceLabel.setFont(font)
        self.capacitanceLabel.setAlignment(Qt.Qt.AlignRight|Qt.Qt.AlignTrailing|Qt.Qt.AlignVCenter)
        self.capacitanceLabel.setObjectName("capacitanceLabel")
        self.gridLayout.addWidget(self.capacitanceLabel, 5, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.resetBtn = QtWidgets.QToolButton(self.groupBox)
        self.resetBtn.setObjectName("resetBtn")
        self.gridLayout.addWidget(self.resetBtn, 0, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(Qt.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.patchPlot = PlotWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patchPlot.sizePolicy().hasHeightForWidth())
        self.patchPlot.setSizePolicy(sizePolicy)
        self.patchPlot.setObjectName("patchPlot")
        self.commandPlot = PlotWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandPlot.sizePolicy().hasHeightForWidth())
        self.commandPlot.setSizePolicy(sizePolicy)
        self.commandPlot.setObjectName("commandPlot")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.plotLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setSpacing(0)
        self.plotLayout.setObjectName("plotLayout")
        self.verticalLayout_2.addWidget(self.splitter_3)

        self.retranslateUi(Form)
        Qt.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = Qt.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Patch"))
        self.vcPulseCheck.setText(_translate("Form", "Pulse"))
        self.vcHoldCheck.setText(_translate("Form", "Hold"))
        self.icPulseCheck.setText(_translate("Form", "Pulse"))
        self.icHoldCheck.setText(_translate("Form", "Hold"))
        self.label.setText(_translate("Form", "Cycle Time"))
        self.label_3.setText(_translate("Form", "Pulse Length"))
        self.label_4.setText(_translate("Form", "Delay Length"))
        self.icModeRadio.setText(_translate("Form", "IC"))
        self.vcModeRadio.setText(_translate("Form", "VC"))
        self.startBtn.setText(_translate("Form", "Start"))
        self.recordBtn.setText(_translate("Form", "Record"))
        self.icPulseSpin.setSuffix(_translate("Form", "A"))
        self.pulseTimeSpin.setSuffix(_translate("Form", "s"))
        self.delayTimeSpin.setSuffix(_translate("Form", "s"))
        self.vcPulseSpin.setSuffix(_translate("Form", "V"))
        self.icHoldSpin.setSuffix(_translate("Form", "A"))
        self.cycleTimeSpin.setSuffix(_translate("Form", "s"))
        self.vcHoldSpin.setSuffix(_translate("Form", "V"))
        self.bathModeBtn.setText(_translate("Form", "Bath"))
        self.patchModeBtn.setText(_translate("Form", "Patch"))
        self.cellModeBtn.setText(_translate("Form", "Cell"))
        self.monitorModeBtn.setText(_translate("Form", "Monitor"))
        self.label_2.setText(_translate("Form", "Average"))
        self.restingPotentialLabel.setText(_translate("Form", "0"))
        self.fitErrorLabel.setText(_translate("Form", "0"))
        self.drawFitCheck.setText(_translate("Form", "Draw Fit"))
        self.accessResistanceLabel.setText(_translate("Form", "0"))
        self.inputResistanceLabel.setText(_translate("Form", "0"))
        self.restingCurrentLabel.setText(_translate("Form", "0"))
        self.capacitanceLabel.setText(_translate("Form", "0"))
        self.label_5.setText(_translate("Form", "Input Res."))
        self.resetBtn.setText(_translate("Form", "Reset History"))
        self.label_6.setText(_translate("Form", "Access Res."))
        self.label_7.setText(_translate("Form", "Rest Potential"))
        self.label_8.setText(_translate("Form", "Rest Current"))
        self.label_9.setText(_translate("Form", "Capacitance"))
        self.label_10.setText(_translate("Form", "Fit Error"))

from acq4.pyqtgraph import PlotWidget, SpinBox
