# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\acq4\modules\Patch\PatchMultiTemplate.ui'
#
# Created: Thu Jan 15 20:16:09 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(307, 609)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_4 = QtGui.QSplitter(Form)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_4)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startBtn = QtGui.QPushButton(self.layoutWidget)
        self.startBtn.setCheckable(True)
        self.startBtn.setObjectName(_fromUtf8("startBtn"))
        self.horizontalLayout.addWidget(self.startBtn)
        self.recordBtn = QtGui.QPushButton(self.layoutWidget)
        self.recordBtn.setCheckable(True)
        self.recordBtn.setObjectName(_fromUtf8("recordBtn"))
        self.horizontalLayout.addWidget(self.recordBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.modeLayout = QtGui.QVBoxLayout()
        self.modeLayout.setObjectName(_fromUtf8("modeLayout"))
        self.verticalLayout.addLayout(self.modeLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.delayTimeSpin = SpinBox(self.layoutWidget)
        self.delayTimeSpin.setMinimum(1.0)
        self.delayTimeSpin.setMaximum(10000.0)
        self.delayTimeSpin.setSingleStep(1.0)
        self.delayTimeSpin.setObjectName(_fromUtf8("delayTimeSpin"))
        self.horizontalLayout_2.addWidget(self.delayTimeSpin)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.pulseTimeSpin = SpinBox(self.layoutWidget)
        self.pulseTimeSpin.setSingleStep(1.0)
        self.pulseTimeSpin.setObjectName(_fromUtf8("pulseTimeSpin"))
        self.horizontalLayout_3.addWidget(self.pulseTimeSpin)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.cycleTimeSpin = SpinBox(self.layoutWidget)
        self.cycleTimeSpin.setSingleStep(1.0)
        self.cycleTimeSpin.setProperty("value", 0.2)
        self.cycleTimeSpin.setObjectName(_fromUtf8("cycleTimeSpin"))
        self.horizontalLayout_5.addWidget(self.cycleTimeSpin)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.averageSpin = QtGui.QSpinBox(self.layoutWidget)
        self.averageSpin.setMinimum(1)
        self.averageSpin.setMaximum(100)
        self.averageSpin.setProperty("value", 1)
        self.averageSpin.setObjectName(_fromUtf8("averageSpin"))
        self.horizontalLayout_4.addWidget(self.averageSpin)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.verticalLayout.addWidget(self.tabWidget)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.patchPlot = PlotWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patchPlot.sizePolicy().hasHeightForWidth())
        self.patchPlot.setSizePolicy(sizePolicy)
        self.patchPlot.setObjectName(_fromUtf8("patchPlot"))
        self.commandPlot = PlotWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandPlot.sizePolicy().hasHeightForWidth())
        self.commandPlot.setSizePolicy(sizePolicy)
        self.commandPlot.setObjectName(_fromUtf8("commandPlot"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.widget = QtGui.QWidget(self.splitter_3)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.restingPotentialLabel = QtGui.QLabel(self.widget)
        self.restingPotentialLabel.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.restingPotentialLabel.setFont(font)
        self.restingPotentialLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.restingPotentialLabel.setObjectName(_fromUtf8("restingPotentialLabel"))
        self.gridLayout.addWidget(self.restingPotentialLabel, 3, 1, 1, 1)
        self.fitErrorCheck = QtGui.QCheckBox(self.widget)
        self.fitErrorCheck.setObjectName(_fromUtf8("fitErrorCheck"))
        self.gridLayout.addWidget(self.fitErrorCheck, 6, 0, 1, 1)
        self.drawFitCheck = QtGui.QCheckBox(self.widget)
        self.drawFitCheck.setChecked(True)
        self.drawFitCheck.setObjectName(_fromUtf8("drawFitCheck"))
        self.gridLayout.addWidget(self.drawFitCheck, 0, 1, 1, 1)
        self.inputResistanceCheck = QtGui.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.inputResistanceCheck.setFont(font)
        self.inputResistanceCheck.setChecked(True)
        self.inputResistanceCheck.setObjectName(_fromUtf8("inputResistanceCheck"))
        self.gridLayout.addWidget(self.inputResistanceCheck, 1, 0, 1, 1)
        self.accessResistanceLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.accessResistanceLabel.setFont(font)
        self.accessResistanceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.accessResistanceLabel.setObjectName(_fromUtf8("accessResistanceLabel"))
        self.gridLayout.addWidget(self.accessResistanceLabel, 2, 1, 1, 1)
        self.inputResistanceLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.inputResistanceLabel.setFont(font)
        self.inputResistanceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputResistanceLabel.setObjectName(_fromUtf8("inputResistanceLabel"))
        self.gridLayout.addWidget(self.inputResistanceLabel, 1, 1, 1, 1)
        self.accessResistanceCheck = QtGui.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.accessResistanceCheck.setFont(font)
        self.accessResistanceCheck.setObjectName(_fromUtf8("accessResistanceCheck"))
        self.gridLayout.addWidget(self.accessResistanceCheck, 2, 0, 1, 1)
        self.restingCurrentLabel = QtGui.QLabel(self.widget)
        self.restingCurrentLabel.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.restingCurrentLabel.setFont(font)
        self.restingCurrentLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.restingCurrentLabel.setObjectName(_fromUtf8("restingCurrentLabel"))
        self.gridLayout.addWidget(self.restingCurrentLabel, 4, 1, 1, 1)
        self.capacitanceCheck = QtGui.QCheckBox(self.widget)
        self.capacitanceCheck.setObjectName(_fromUtf8("capacitanceCheck"))
        self.gridLayout.addWidget(self.capacitanceCheck, 5, 0, 1, 1)
        self.restingPotentialCheck = QtGui.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.restingPotentialCheck.setFont(font)
        self.restingPotentialCheck.setObjectName(_fromUtf8("restingPotentialCheck"))
        self.gridLayout.addWidget(self.restingPotentialCheck, 3, 0, 1, 1)
        self.restingCurrentCheck = QtGui.QCheckBox(self.widget)
        self.restingCurrentCheck.setObjectName(_fromUtf8("restingCurrentCheck"))
        self.gridLayout.addWidget(self.restingCurrentCheck, 4, 0, 1, 1)
        self.capacitanceLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.capacitanceLabel.setFont(font)
        self.capacitanceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.capacitanceLabel.setObjectName(_fromUtf8("capacitanceLabel"))
        self.gridLayout.addWidget(self.capacitanceLabel, 5, 1, 1, 1)
        self.fitErrorLabel = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fitErrorLabel.setFont(font)
        self.fitErrorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fitErrorLabel.setObjectName(_fromUtf8("fitErrorLabel"))
        self.gridLayout.addWidget(self.fitErrorLabel, 6, 1, 1, 1)
        self.resetBtn = QtGui.QToolButton(self.widget)
        self.resetBtn.setObjectName(_fromUtf8("resetBtn"))
        self.gridLayout.addWidget(self.resetBtn, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.plotLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.plotLayout.setSpacing(0)
        self.plotLayout.setMargin(0)
        self.plotLayout.setObjectName(_fromUtf8("plotLayout"))
        self.verticalLayout_2.addWidget(self.splitter_4)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.startBtn.setText(_translate("Form", "Start", None))
        self.recordBtn.setText(_translate("Form", "Record", None))
        self.label_4.setText(_translate("Form", "Delay Length", None))
        self.delayTimeSpin.setSuffix(_translate("Form", "s", None))
        self.label_3.setText(_translate("Form", "Pulse Length", None))
        self.pulseTimeSpin.setSuffix(_translate("Form", "s", None))
        self.label.setText(_translate("Form", "Cycle Time", None))
        self.cycleTimeSpin.setSuffix(_translate("Form", "s", None))
        self.label_2.setText(_translate("Form", "Average", None))
        self.restingPotentialLabel.setText(_translate("Form", "0", None))
        self.fitErrorCheck.setText(_translate("Form", "Fit Error", None))
        self.drawFitCheck.setText(_translate("Form", "Draw Fit", None))
        self.inputResistanceCheck.setText(_translate("Form", "Input Res.", None))
        self.accessResistanceLabel.setText(_translate("Form", "0", None))
        self.inputResistanceLabel.setText(_translate("Form", "0", None))
        self.accessResistanceCheck.setText(_translate("Form", "Access Res.", None))
        self.restingCurrentLabel.setText(_translate("Form", "0", None))
        self.capacitanceCheck.setText(_translate("Form", "Capacitance", None))
        self.restingPotentialCheck.setText(_translate("Form", "Rest Potential", None))
        self.restingCurrentCheck.setText(_translate("Form", "Rest Current", None))
        self.capacitanceLabel.setText(_translate("Form", "0", None))
        self.fitErrorLabel.setText(_translate("Form", "0", None))
        self.resetBtn.setText(_translate("Form", "Reset History", None))

from acq4.pyqtgraph import SpinBox, PlotWidget
