# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './acq4/modules/Patch/PatchTemplate.ui'
#
# Created: Tue Dec 24 01:49:11 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(267, 343)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_3 = QtGui.QSplitter(Form)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.vcPulseCheck = QtGui.QCheckBox(self.groupBox_2)
        self.vcPulseCheck.setChecked(True)
        self.vcPulseCheck.setObjectName(_fromUtf8("vcPulseCheck"))
        self.gridLayout_2.addWidget(self.vcPulseCheck, 2, 1, 1, 1)
        self.vcHoldCheck = QtGui.QCheckBox(self.groupBox_2)
        self.vcHoldCheck.setObjectName(_fromUtf8("vcHoldCheck"))
        self.gridLayout_2.addWidget(self.vcHoldCheck, 3, 1, 1, 1)
        self.icPulseCheck = QtGui.QCheckBox(self.groupBox_2)
        self.icPulseCheck.setChecked(True)
        self.icPulseCheck.setObjectName(_fromUtf8("icPulseCheck"))
        self.gridLayout_2.addWidget(self.icPulseCheck, 4, 1, 1, 1)
        self.icHoldCheck = QtGui.QCheckBox(self.groupBox_2)
        self.icHoldCheck.setObjectName(_fromUtf8("icHoldCheck"))
        self.gridLayout_2.addWidget(self.icHoldCheck, 6, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 10, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 9, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 8, 0, 1, 2)
        self.icModeRadio = QtGui.QRadioButton(self.groupBox_2)
        self.icModeRadio.setObjectName(_fromUtf8("icModeRadio"))
        self.gridLayout_2.addWidget(self.icModeRadio, 4, 0, 1, 1)
        self.vcModeRadio = QtGui.QRadioButton(self.groupBox_2)
        self.vcModeRadio.setChecked(True)
        self.vcModeRadio.setObjectName(_fromUtf8("vcModeRadio"))
        self.gridLayout_2.addWidget(self.vcModeRadio, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.startBtn = QtGui.QPushButton(self.groupBox_2)
        self.startBtn.setCheckable(True)
        self.startBtn.setObjectName(_fromUtf8("startBtn"))
        self.horizontalLayout.addWidget(self.startBtn)
        self.recordBtn = QtGui.QPushButton(self.groupBox_2)
        self.recordBtn.setCheckable(True)
        self.recordBtn.setObjectName(_fromUtf8("recordBtn"))
        self.horizontalLayout.addWidget(self.recordBtn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.icPulseSpin = SpinBox(self.groupBox_2)
        self.icPulseSpin.setMaximumSize(QtCore.QSize(70, 16777215))
        self.icPulseSpin.setObjectName(_fromUtf8("icPulseSpin"))
        self.gridLayout_2.addWidget(self.icPulseSpin, 4, 2, 1, 1)
        self.pulseTimeSpin = SpinBox(self.groupBox_2)
        self.pulseTimeSpin.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pulseTimeSpin.setSingleStep(1.0)
        self.pulseTimeSpin.setObjectName(_fromUtf8("pulseTimeSpin"))
        self.gridLayout_2.addWidget(self.pulseTimeSpin, 9, 2, 1, 1)
        self.delayTimeSpin = SpinBox(self.groupBox_2)
        self.delayTimeSpin.setMaximumSize(QtCore.QSize(70, 16777215))
        self.delayTimeSpin.setMinimum(1.0)
        self.delayTimeSpin.setMaximum(10000.0)
        self.delayTimeSpin.setSingleStep(1.0)
        self.delayTimeSpin.setObjectName(_fromUtf8("delayTimeSpin"))
        self.gridLayout_2.addWidget(self.delayTimeSpin, 8, 2, 1, 1)
        self.vcPulseSpin = SpinBox(self.groupBox_2)
        self.vcPulseSpin.setMaximumSize(QtCore.QSize(70, 16777215))
        self.vcPulseSpin.setObjectName(_fromUtf8("vcPulseSpin"))
        self.gridLayout_2.addWidget(self.vcPulseSpin, 2, 2, 1, 1)
        self.icHoldSpin = SpinBox(self.groupBox_2)
        self.icHoldSpin.setMaximumSize(QtCore.QSize(70, 16777215))
        self.icHoldSpin.setObjectName(_fromUtf8("icHoldSpin"))
        self.gridLayout_2.addWidget(self.icHoldSpin, 5, 2, 2, 1)
        self.cycleTimeSpin = SpinBox(self.groupBox_2)
        self.cycleTimeSpin.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cycleTimeSpin.setSingleStep(1.0)
        self.cycleTimeSpin.setProperty("value", 0.2)
        self.cycleTimeSpin.setObjectName(_fromUtf8("cycleTimeSpin"))
        self.gridLayout_2.addWidget(self.cycleTimeSpin, 10, 2, 1, 1)
        self.vcHoldSpin = SpinBox(self.groupBox_2)
        self.vcHoldSpin.setMaximumSize(QtCore.QSize(70, 16777215))
        self.vcHoldSpin.setObjectName(_fromUtf8("vcHoldSpin"))
        self.gridLayout_2.addWidget(self.vcHoldSpin, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.bathModeBtn = QtGui.QToolButton(self.groupBox_2)
        self.bathModeBtn.setObjectName(_fromUtf8("bathModeBtn"))
        self.horizontalLayout_2.addWidget(self.bathModeBtn)
        self.patchModeBtn = QtGui.QToolButton(self.groupBox_2)
        self.patchModeBtn.setObjectName(_fromUtf8("patchModeBtn"))
        self.horizontalLayout_2.addWidget(self.patchModeBtn)
        self.cellModeBtn = QtGui.QToolButton(self.groupBox_2)
        self.cellModeBtn.setObjectName(_fromUtf8("cellModeBtn"))
        self.horizontalLayout_2.addWidget(self.cellModeBtn)
        self.monitorModeBtn = QtGui.QToolButton(self.groupBox_2)
        self.monitorModeBtn.setObjectName(_fromUtf8("monitorModeBtn"))
        self.horizontalLayout_2.addWidget(self.monitorModeBtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 3)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 11, 0, 1, 1)
        self.averageSpin = QtGui.QSpinBox(self.groupBox_2)
        self.averageSpin.setMinimum(1)
        self.averageSpin.setMaximum(100)
        self.averageSpin.setProperty("value", 1)
        self.averageSpin.setObjectName(_fromUtf8("averageSpin"))
        self.gridLayout_2.addWidget(self.averageSpin, 11, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setMargin(0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.resetBtn = QtGui.QToolButton(self.groupBox)
        self.resetBtn.setObjectName(_fromUtf8("resetBtn"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.resetBtn)
        self.inputResistanceCheck = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.inputResistanceCheck.setFont(font)
        self.inputResistanceCheck.setChecked(True)
        self.inputResistanceCheck.setObjectName(_fromUtf8("inputResistanceCheck"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.inputResistanceCheck)
        self.inputResistanceLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.inputResistanceLabel.setFont(font)
        self.inputResistanceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.inputResistanceLabel.setObjectName(_fromUtf8("inputResistanceLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.inputResistanceLabel)
        self.accessResistanceCheck = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.accessResistanceCheck.setFont(font)
        self.accessResistanceCheck.setObjectName(_fromUtf8("accessResistanceCheck"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.accessResistanceCheck)
        self.accessResistanceLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.accessResistanceLabel.setFont(font)
        self.accessResistanceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.accessResistanceLabel.setObjectName(_fromUtf8("accessResistanceLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.accessResistanceLabel)
        self.restingPotentialCheck = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.restingPotentialCheck.setFont(font)
        self.restingPotentialCheck.setObjectName(_fromUtf8("restingPotentialCheck"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.restingPotentialCheck)
        self.restingPotentialLabel = QtGui.QLabel(self.groupBox)
        self.restingPotentialLabel.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.restingPotentialLabel.setFont(font)
        self.restingPotentialLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.restingPotentialLabel.setObjectName(_fromUtf8("restingPotentialLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.restingPotentialLabel)
        self.restingCurrentCheck = QtGui.QCheckBox(self.groupBox)
        self.restingCurrentCheck.setObjectName(_fromUtf8("restingCurrentCheck"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.restingCurrentCheck)
        self.restingCurrentLabel = QtGui.QLabel(self.groupBox)
        self.restingCurrentLabel.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.restingCurrentLabel.setFont(font)
        self.restingCurrentLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.restingCurrentLabel.setObjectName(_fromUtf8("restingCurrentLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.restingCurrentLabel)
        self.capacitanceCheck = QtGui.QCheckBox(self.groupBox)
        self.capacitanceCheck.setObjectName(_fromUtf8("capacitanceCheck"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.capacitanceCheck)
        self.capacitanceLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.capacitanceLabel.setFont(font)
        self.capacitanceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.capacitanceLabel.setObjectName(_fromUtf8("capacitanceLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.capacitanceLabel)
        self.fitErrorCheck = QtGui.QCheckBox(self.groupBox)
        self.fitErrorCheck.setObjectName(_fromUtf8("fitErrorCheck"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.fitErrorCheck)
        self.fitErrorLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fitErrorLabel.setFont(font)
        self.fitErrorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fitErrorLabel.setObjectName(_fromUtf8("fitErrorLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.fitErrorLabel)
        self.drawFitCheck = QtGui.QCheckBox(self.groupBox)
        self.drawFitCheck.setChecked(True)
        self.drawFitCheck.setObjectName(_fromUtf8("drawFitCheck"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.drawFitCheck)
        self.verticalLayout.addWidget(self.groupBox)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.patchPlot = PlotWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patchPlot.sizePolicy().hasHeightForWidth())
        self.patchPlot.setSizePolicy(sizePolicy)
        self.patchPlot.setObjectName(_fromUtf8("patchPlot"))
        self.commandPlot = PlotWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandPlot.sizePolicy().hasHeightForWidth())
        self.commandPlot.setSizePolicy(sizePolicy)
        self.commandPlot.setObjectName(_fromUtf8("commandPlot"))
        self.layoutWidget1 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.plotLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.plotLayout.setSpacing(0)
        self.plotLayout.setMargin(0)
        self.plotLayout.setObjectName(_fromUtf8("plotLayout"))
        self.verticalLayout_2.addWidget(self.splitter_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Patch", None))
        self.vcPulseCheck.setText(_translate("Form", "Pulse", None))
        self.vcHoldCheck.setText(_translate("Form", "Hold", None))
        self.icPulseCheck.setText(_translate("Form", "Pulse", None))
        self.icHoldCheck.setText(_translate("Form", "Hold", None))
        self.label.setText(_translate("Form", "Cycle Time", None))
        self.label_3.setText(_translate("Form", "Pulse Length", None))
        self.label_4.setText(_translate("Form", "Delay Length", None))
        self.icModeRadio.setText(_translate("Form", "IC", None))
        self.vcModeRadio.setText(_translate("Form", "VC", None))
        self.startBtn.setText(_translate("Form", "Start", None))
        self.recordBtn.setText(_translate("Form", "Record", None))
        self.icPulseSpin.setSuffix(_translate("Form", "A", None))
        self.pulseTimeSpin.setSuffix(_translate("Form", "s", None))
        self.delayTimeSpin.setSuffix(_translate("Form", "s", None))
        self.vcPulseSpin.setSuffix(_translate("Form", "V", None))
        self.icHoldSpin.setSuffix(_translate("Form", "A", None))
        self.cycleTimeSpin.setSuffix(_translate("Form", "s", None))
        self.vcHoldSpin.setSuffix(_translate("Form", "V", None))
        self.bathModeBtn.setText(_translate("Form", "Bath", None))
        self.patchModeBtn.setText(_translate("Form", "Patch", None))
        self.cellModeBtn.setText(_translate("Form", "Cell", None))
        self.monitorModeBtn.setText(_translate("Form", "Monitor", None))
        self.label_2.setText(_translate("Form", "Average", None))
        self.resetBtn.setText(_translate("Form", "Reset History", None))
        self.inputResistanceCheck.setText(_translate("Form", "Input Res.", None))
        self.inputResistanceLabel.setText(_translate("Form", "0", None))
        self.accessResistanceCheck.setText(_translate("Form", "Access Res.", None))
        self.accessResistanceLabel.setText(_translate("Form", "0", None))
        self.restingPotentialCheck.setText(_translate("Form", "Rest Potential", None))
        self.restingPotentialLabel.setText(_translate("Form", "0", None))
        self.restingCurrentCheck.setText(_translate("Form", "Rest Current", None))
        self.restingCurrentLabel.setText(_translate("Form", "0", None))
        self.capacitanceCheck.setText(_translate("Form", "Capacitance", None))
        self.capacitanceLabel.setText(_translate("Form", "0", None))
        self.fitErrorCheck.setText(_translate("Form", "Fit Error", None))
        self.fitErrorLabel.setText(_translate("Form", "0", None))
        self.drawFitCheck.setText(_translate("Form", "Draw Fit", None))

from acq4.pyqtgraph import SpinBox, PlotWidget
