# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './lib/devices/SutterMP285/devTemplate.ui'
#
# Created: Wed Aug 17 13:49:53 2011
#      by: pyside-uic 0.2.11 running on PySide 1.0.5
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(276, 237)
        self.gridLayout_3 = QtGui.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.posLabel = QtGui.QLabel(self.groupBox_2)
        self.posLabel.setObjectName("posLabel")
        self.horizontalLayout.addWidget(self.posLabel)
        self.monitorPosBtn = QtGui.QPushButton(self.groupBox_2)
        self.monitorPosBtn.setCheckable(True)
        self.monitorPosBtn.setChecked(True)
        self.monitorPosBtn.setObjectName("monitorPosBtn")
        self.horizontalLayout.addWidget(self.monitorPosBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.joyBtn = JoystickButton(self.groupBox_2)
        self.joyBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.joyBtn.setText("")
        self.joyBtn.setObjectName("joyBtn")
        self.gridLayout.addWidget(self.joyBtn, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fineStepRadio = QtGui.QRadioButton(self.groupBox_2)
        self.fineStepRadio.setChecked(True)
        self.fineStepRadio.setObjectName("fineStepRadio")
        self.horizontalLayout_2.addWidget(self.fineStepRadio)
        self.coarseStepRadio = QtGui.QRadioButton(self.groupBox_2)
        self.coarseStepRadio.setObjectName("coarseStepRadio")
        self.horizontalLayout_2.addWidget(self.coarseStepRadio)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 3)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.xMinBtn = QtGui.QPushButton(self.groupBox)
        self.xMinBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.xMinBtn.setObjectName("xMinBtn")
        self.gridLayout_2.addWidget(self.xMinBtn, 0, 1, 1, 1)
        self.xMaxBtn = QtGui.QPushButton(self.groupBox)
        self.xMaxBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.xMaxBtn.setObjectName("xMaxBtn")
        self.gridLayout_2.addWidget(self.xMaxBtn, 0, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.yMinBtn = QtGui.QPushButton(self.groupBox)
        self.yMinBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.yMinBtn.setObjectName("yMinBtn")
        self.gridLayout_2.addWidget(self.yMinBtn, 1, 1, 1, 1)
        self.yMaxBtn = QtGui.QPushButton(self.groupBox)
        self.yMaxBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.yMaxBtn.setObjectName("yMaxBtn")
        self.gridLayout_2.addWidget(self.yMaxBtn, 1, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 2)
        self.maxSpeedSpin = SpinBox(self.groupBox)
        self.maxSpeedSpin.setObjectName("maxSpeedSpin")
        self.gridLayout_2.addWidget(self.maxSpeedSpin, 3, 3, 1, 3)
        self.xMinLabel = QtGui.QLabel(self.groupBox)
        self.xMinLabel.setObjectName("xMinLabel")
        self.gridLayout_2.addWidget(self.xMinLabel, 0, 3, 1, 1)
        self.yMinLabel = QtGui.QLabel(self.groupBox)
        self.yMinLabel.setObjectName("yMinLabel")
        self.gridLayout_2.addWidget(self.yMinLabel, 1, 3, 1, 1)
        self.xMaxLabel = QtGui.QLabel(self.groupBox)
        self.xMaxLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xMaxLabel.setObjectName("xMaxLabel")
        self.gridLayout_2.addWidget(self.xMaxLabel, 0, 4, 1, 1)
        self.yMaxLabel = QtGui.QLabel(self.groupBox)
        self.yMaxLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yMaxLabel.setObjectName("yMaxLabel")
        self.gridLayout_2.addWidget(self.yMaxLabel, 1, 4, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.zMinBtn = QtGui.QPushButton(self.groupBox)
        self.zMinBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.zMinBtn.setObjectName("zMinBtn")
        self.gridLayout_2.addWidget(self.zMinBtn, 2, 1, 1, 1)
        self.zMaxBtn = QtGui.QPushButton(self.groupBox)
        self.zMaxBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.zMaxBtn.setObjectName("zMaxBtn")
        self.gridLayout_2.addWidget(self.zMaxBtn, 2, 5, 1, 1)
        self.zMinLabel = QtGui.QLabel(self.groupBox)
        self.zMinLabel.setObjectName("zMinLabel")
        self.gridLayout_2.addWidget(self.zMinLabel, 2, 3, 1, 1)
        self.zMaxLabel = QtGui.QLabel(self.groupBox)
        self.zMaxLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zMaxLabel.setObjectName("zMaxLabel")
        self.gridLayout_2.addWidget(self.zMaxLabel, 2, 4, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.posLabel.setText(QtGui.QApplication.translate("Form", "0,0", None, QtGui.QApplication.UnicodeUTF8))
        self.monitorPosBtn.setText(QtGui.QApplication.translate("Form", "Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.fineStepRadio.setText(QtGui.QApplication.translate("Form", "Fine step", None, QtGui.QApplication.UnicodeUTF8))
        self.coarseStepRadio.setText(QtGui.QApplication.translate("Form", "Coarse step", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Limits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.xMinBtn.setText(QtGui.QApplication.translate("Form", "set", None, QtGui.QApplication.UnicodeUTF8))
        self.xMaxBtn.setText(QtGui.QApplication.translate("Form", "set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.yMinBtn.setText(QtGui.QApplication.translate("Form", "set", None, QtGui.QApplication.UnicodeUTF8))
        self.yMaxBtn.setText(QtGui.QApplication.translate("Form", "set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Max Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.xMinLabel.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.yMinLabel.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.xMaxLabel.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.yMaxLabel.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.zMinBtn.setText(QtGui.QApplication.translate("Form", "set", None, QtGui.QApplication.UnicodeUTF8))
        self.zMaxBtn.setText(QtGui.QApplication.translate("Form", "set", None, QtGui.QApplication.UnicodeUTF8))
        self.zMinLabel.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.zMaxLabel.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))

from JoystickButton import JoystickButton
from SpinBox import SpinBox
