# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './lib/analysis/modules/IVCurve/ctrlTemplate.ui'
#
# Created: Fri Nov  9 17:17:14 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(281, 352)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 105, 36, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.IVCurve_pkTStart = QtGui.QDoubleSpinBox(self.groupBox)
        self.IVCurve_pkTStart.setGeometry(QtCore.QRect(55, 95, 77, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_pkTStart.setFont(font)
        self.IVCurve_pkTStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IVCurve_pkTStart.setMinimum(-5000.0)
        self.IVCurve_pkTStart.setMaximum(50000.0)
        self.IVCurve_pkTStart.setObjectName(_fromUtf8("IVCurve_pkTStart"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(145, 95, 36, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.IVCurve_pkTStop = QtGui.QDoubleSpinBox(self.groupBox)
        self.IVCurve_pkTStop.setGeometry(QtCore.QRect(190, 90, 77, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_pkTStop.setFont(font)
        self.IVCurve_pkTStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IVCurve_pkTStop.setMinimum(-5000.0)
        self.IVCurve_pkTStop.setMaximum(50000.0)
        self.IVCurve_pkTStop.setObjectName(_fromUtf8("IVCurve_pkTStop"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(3, 193, 81, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_6 = QtGui.QFrame(self.groupBox)
        self.line_6.setGeometry(QtCore.QRect(84, 193, 186, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(40, 210, 52, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.IVCurve_SpikeThreshold = QtGui.QDoubleSpinBox(self.groupBox)
        self.IVCurve_SpikeThreshold.setGeometry(QtCore.QRect(105, 210, 83, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_SpikeThreshold.setFont(font)
        self.IVCurve_SpikeThreshold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IVCurve_SpikeThreshold.setDecimals(1)
        self.IVCurve_SpikeThreshold.setMinimum(-100.0)
        self.IVCurve_SpikeThreshold.setObjectName(_fromUtf8("IVCurve_SpikeThreshold"))
        self.line_5 = QtGui.QFrame(self.groupBox)
        self.line_5.setGeometry(QtCore.QRect(5, 230, 151, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_3 = QtGui.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(160, 230, 111, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 240, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 265, 18, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.IVCurve_Rin = QtGui.QLineEdit(self.groupBox)
        self.IVCurve_Rin.setGeometry(QtCore.QRect(60, 260, 66, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_Rin.setFont(font)
        self.IVCurve_Rin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IVCurve_Rin.setObjectName(_fromUtf8("IVCurve_Rin"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 285, 47, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.IVCurve_Tau = QtGui.QLineEdit(self.groupBox)
        self.IVCurve_Tau.setGeometry(QtCore.QRect(60, 285, 66, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_Tau.setFont(font)
        self.IVCurve_Tau.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IVCurve_Tau.setObjectName(_fromUtf8("IVCurve_Tau"))
        self.IVCurve_Update = QtGui.QPushButton(self.groupBox)
        self.IVCurve_Update.setGeometry(QtCore.QRect(185, 205, 87, 32))
        self.IVCurve_Update.setObjectName(_fromUtf8("IVCurve_Update"))
        self.IVCurve_AR = QtGui.QLineEdit(self.groupBox)
        self.IVCurve_AR.setGeometry(QtCore.QRect(60, 310, 66, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_AR.setFont(font)
        self.IVCurve_AR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IVCurve_AR.setObjectName(_fromUtf8("IVCurve_AR"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 300, 31, 36))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.IVCurve_PrintResults = QtGui.QPushButton(self.groupBox)
        self.IVCurve_PrintResults.setGeometry(QtCore.QRect(155, 320, 121, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IVCurve_PrintResults.sizePolicy().hasHeightForWidth())
        self.IVCurve_PrintResults.setSizePolicy(sizePolicy)
        self.IVCurve_PrintResults.setObjectName(_fromUtf8("IVCurve_PrintResults"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(140, 45, 36, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.IVCurve_ssTStop = QtGui.QDoubleSpinBox(self.groupBox)
        self.IVCurve_ssTStop.setGeometry(QtCore.QRect(55, 40, 77, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_ssTStop.setFont(font)
        self.IVCurve_ssTStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IVCurve_ssTStop.setMinimum(-5000.0)
        self.IVCurve_ssTStop.setMaximum(50000.0)
        self.IVCurve_ssTStop.setObjectName(_fromUtf8("IVCurve_ssTStop"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 45, 36, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.IVCurve_ssTStart = QtGui.QDoubleSpinBox(self.groupBox)
        self.IVCurve_ssTStart.setGeometry(QtCore.QRect(185, 40, 77, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_ssTStart.setFont(font)
        self.IVCurve_ssTStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IVCurve_ssTStart.setMinimum(-5000.0)
        self.IVCurve_ssTStart.setMaximum(50000.0)
        self.IVCurve_ssTStart.setObjectName(_fromUtf8("IVCurve_ssTStart"))
        self.IVCurve_tau2TStart = QtGui.QDoubleSpinBox(self.groupBox)
        self.IVCurve_tau2TStart.setGeometry(QtCore.QRect(55, 140, 76, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_tau2TStart.setFont(font)
        self.IVCurve_tau2TStart.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IVCurve_tau2TStart.setDecimals(1)
        self.IVCurve_tau2TStart.setMaximum(1000.0)
        self.IVCurve_tau2TStart.setObjectName(_fromUtf8("IVCurve_tau2TStart"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(140, 145, 36, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 145, 36, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.IVCurve_tau2TStop = QtGui.QDoubleSpinBox(self.groupBox)
        self.IVCurve_tau2TStop.setGeometry(QtCore.QRect(190, 140, 71, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_tau2TStop.setFont(font)
        self.IVCurve_tau2TStop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IVCurve_tau2TStop.setObjectName(_fromUtf8("IVCurve_tau2TStop"))
        self.IVCurve_Tauh = QtGui.QLineEdit(self.groupBox)
        self.IVCurve_Tauh.setGeometry(QtCore.QRect(205, 240, 66, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_Tauh.setFont(font)
        self.IVCurve_Tauh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IVCurve_Tauh.setObjectName(_fromUtf8("IVCurve_Tauh"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(140, 245, 66, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.IVCurve_showHide_lrss = QtGui.QCheckBox(self.groupBox)
        self.IVCurve_showHide_lrss.setGeometry(QtCore.QRect(5, 20, 56, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.IVCurve_showHide_lrss.setFont(font)
        self.IVCurve_showHide_lrss.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.IVCurve_showHide_lrss.setChecked(True)
        self.IVCurve_showHide_lrss.setObjectName(_fromUtf8("IVCurve_showHide_lrss"))
        self.IVCurve_showHide_lrpk = QtGui.QCheckBox(self.groupBox)
        self.IVCurve_showHide_lrpk.setGeometry(QtCore.QRect(0, 75, 71, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.IVCurve_showHide_lrpk.setFont(font)
        self.IVCurve_showHide_lrpk.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.IVCurve_showHide_lrpk.setChecked(True)
        self.IVCurve_showHide_lrpk.setObjectName(_fromUtf8("IVCurve_showHide_lrpk"))
        self.IVCurve_showHide_lrtau = QtGui.QCheckBox(self.groupBox)
        self.IVCurve_showHide_lrtau.setGeometry(QtCore.QRect(10, 125, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.IVCurve_showHide_lrtau.setFont(font)
        self.IVCurve_showHide_lrtau.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.IVCurve_showHide_lrtau.setObjectName(_fromUtf8("IVCurve_showHide_lrtau"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(160, 270, 51, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.IVCurve_Ih_ba = QtGui.QLineEdit(self.groupBox)
        self.IVCurve_Ih_ba.setGeometry(QtCore.QRect(205, 265, 66, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_Ih_ba.setFont(font)
        self.IVCurve_Ih_ba.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IVCurve_Ih_ba.setObjectName(_fromUtf8("IVCurve_Ih_ba"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(15, 175, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(140, 295, 62, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.IVCurve_FOType = QtGui.QLineEdit(self.groupBox)
        self.IVCurve_FOType.setGeometry(QtCore.QRect(205, 290, 71, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.IVCurve_FOType.setFont(font)
        self.IVCurve_FOType.setObjectName(_fromUtf8("IVCurve_FOType"))
        self.IVCurve_tauh_Commands = QtGui.QComboBox(self.groupBox)
        self.IVCurve_tauh_Commands.setGeometry(QtCore.QRect(85, 170, 86, 26))
        self.IVCurve_tauh_Commands.setObjectName(_fromUtf8("IVCurve_tauh_Commands"))
        self.IVCurve_tauh_Commands.addItem(_fromUtf8(""))
        self.IVCurve_dataMode = QtGui.QLabel(self.groupBox)
        self.IVCurve_dataMode.setGeometry(QtCore.QRect(175, 5, 106, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.IVCurve_dataMode.setFont(font)
        self.IVCurve_dataMode.setObjectName(_fromUtf8("IVCurve_dataMode"))
        self.IVCurve_dataUnits = QtGui.QLabel(self.groupBox)
        self.IVCurve_dataUnits.setGeometry(QtCore.QRect(180, 175, 46, 16))
        self.IVCurve_dataUnits.setObjectName(_fromUtf8("IVCurve_dataUnits"))
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "IV Analysis-V1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "T Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "T Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Spike Thr", None, QtGui.QApplication.UnicodeUTF8))
        self.IVCurve_SpikeThreshold.setSuffix(QtGui.QApplication.translate("Form", " mV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Rin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Tau (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.IVCurve_Update.setText(QtGui.QApplication.translate("Form", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Adapt \n"
"Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.IVCurve_PrintResults.setText(QtGui.QApplication.translate("Form", "Print Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "T Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "T Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "T Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "T Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Tau_h (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.IVCurve_showHide_lrss.setText(QtGui.QApplication.translate("Form", "IV:SS", None, QtGui.QApplication.UnicodeUTF8))
        self.IVCurve_showHide_lrpk.setText(QtGui.QApplication.translate("Form", "IV:Peak", None, QtGui.QApplication.UnicodeUTF8))
        self.IVCurve_showHide_lrtau.setText(QtGui.QApplication.translate("Form", "Ih tool", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "b/a (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Command", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "F&O Type", None, QtGui.QApplication.UnicodeUTF8))
        self.IVCurve_tauh_Commands.setItemText(0, QtGui.QApplication.translate("Form", "-0.6", None, QtGui.QApplication.UnicodeUTF8))
        self.IVCurve_dataMode.setText(QtGui.QApplication.translate("Form", "IVCurve_dataMode", None, QtGui.QApplication.UnicodeUTF8))
        self.IVCurve_dataUnits.setText(QtGui.QApplication.translate("Form", "nA", None, QtGui.QApplication.UnicodeUTF8))

