name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1 libglx-mesa0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pytest numpy scipy pyqtgraph pyqt5 metaarray neuroanalysis numba pyyaml pillow trimesh pyopengl coorx teleprox click tifffile vispy

    - name: Run tests
      run: |
        python -m pytest tests/
